/*
 * An oracle rather than a layout measurement: what `file` string does the authority pass to an
 * application-installed allocator, per provider row?
 *
 * `CRYPTO_set_mem_functions` is part of the published contract, and its callbacks take
 * `(size_t num, const char *file, int line)`. The crate's cipher rows record the *size* they pass
 * (`measure-provider-ctxs.c` and friends) but every one of them passes a single shared `FILE`
 * constant naming `ciphercommon.c`. That constant is only right for the bodies `ciphercommon.c.in`
 * actually contains: the rows' `newctx`/`freenewctx` are generated by the `IMPLEMENT_generic_cipher`
 * macro, which `providers/implementations/include/prov/ciphercommon.h:194-225` defines and
 * `cipher_aes.c`, `cipher_camellia.c`, `cipher_seed.c`, `cipher_sm4.c`, `cipher_aria.c` and
 * `cipher_idea.c` each *invoke*, so their `__FILE__` is the invoking file and not the header's.
 *
 * `.c.in`-generated units also differ from source-tree ones: the build compiles
 * `providers/implementations/ciphers/ciphercommon.c` from the build directory, so its `__FILE__`
 * carries no `../../src/openssl-3.6.4/` prefix, while `cipher_aes.c`'s does. Both spellings were
 * confirmed with `strings` on the objects; this program confirms the *binding*, which is what an
 * application actually receives.
 *
 * Output: one line per distinct `file` string seen, `count file`, in first-seen order, then the
 * rows this program created. Compare against `src/provider/cipher.rs`'s per-row constants.
 *
 * Build (see `courts/layout/README.md` for the include set; this one needs the built library):
 *   P=forensics/authorities/prefix/openssl-3.6.4-production
 *   clang -std=c11 -o /tmp/oracle courts/layout/oracle-mem-file.c \
 *       -I $P/include -L $P/lib -lcrypto -Wl,-rpath,$P/lib
 */
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_FILES 256
#define MAX_NAME 320

static char seen[MAX_FILES][MAX_NAME];
static unsigned long seen_count[MAX_FILES];
static int nseen;

static void note(const char *file)
{
    int i;

    if (file == NULL)
        file = "(null)";
    if (strlen(file) >= MAX_NAME)
        return;
    for (i = 0; i < nseen; i++) {
        if (strcmp(seen[i], file) == 0) {
            seen_count[i]++;
            return;
        }
    }
    if (nseen < MAX_FILES) {
        strcpy(seen[nseen], file);
        seen_count[nseen] = 1;
        nseen++;
    }
}

static void *my_malloc(size_t n, const char *file, int line)
{
    (void)line;
    note(file);
    return malloc(n);
}

static void *my_realloc(void *p, size_t n, const char *file, int line)
{
    (void)line;
    note(file);
    return realloc(p, n);
}

static void my_free(void *p, const char *file, int line)
{
    (void)line;
    note(file);
    free(p);
}

/* Every row the crate's default provider currently publishes, plus the two the cipher half has
 * yet to land, so a missing row is visible as a missing line rather than as silence. */
static const char *const ROWS[] = {
    "AES-128-CBC", "AES-256-ECB", "AES-128-CTR", "AES-128-XTS", "AES-128-OCB",
    "AES-128-CCM", "AES-128-SIV", "AES-128-GCM-SIV", "AES-128-WRAP",
    "AES-128-CBC-HMAC-SHA1",
    "CAMELLIA-128-CBC", "CAMELLIA-192-ECB",
    "DES-EDE3-CBC", "DES-EDE-CBC",
    "SM4-CBC", "SM4-ECB", "SM4-XTS", "SM4-CCM",
    "ARIA-128-CBC", "ARIA-128-ECB", "ARIA-128-CCM",
    "ChaCha20", "ChaCha20-Poly1305",
    "IDEA-CBC", "SEED-CBC", "RC4", "RC2-CBC", "BF-CBC", "CAST5-CBC",
    "NULL",
    NULL
};

int main(void)
{
    int i, j;

    if (CRYPTO_set_mem_functions(my_malloc, my_realloc, my_free) != 1) {
        printf("CRYPTO_set_mem_functions=0\n");
        return 1;
    }

    for (i = 0; ROWS[i] != NULL; i++) {
        EVP_CIPHER *c = EVP_CIPHER_fetch(NULL, ROWS[i], NULL);
        EVP_CIPHER_CTX *ctx;
        unsigned char key[64] = { 0 };
        unsigned char iv[16] = { 0 };
        unsigned char in[32] = { 0 };
        unsigned char out[64];
        int outl = 0;

        if (c == NULL) {
            printf("row %s = absent\n", ROWS[i]);
            continue;
        }
        printf("row %s = present\n", ROWS[i]);
        ctx = EVP_CIPHER_CTX_new();
        if (ctx != NULL) {
            if (EVP_EncryptInit_ex2(ctx, c, key, iv, NULL) == 1) {
                EVP_EncryptUpdate(ctx, out, &outl, in, sizeof(in));
                EVP_EncryptFinal_ex(ctx, out, &outl);
            }
            EVP_CIPHER_CTX_free(ctx);
        }
        EVP_CIPHER_free(c);
    }

    printf("---\n");
    for (j = 0; j < nseen; j++)
        printf("%8lu %s\n", seen_count[j], seen[j]);
    return 0;
}
