//! Phase 8 — `crypto/dsa/dsa_key.c`: `DSA_generate_key`, the public-key derivation and the static
//! generator behind them.
//!
//! Three definitions in authority order: [`DSA_generate_key`] (`:24-33`),
//! [`ossl_dsa_generate_public_key`] (`:35-54`) and `dsa_keygen` (`:143-197`). The file also holds
//! the FIPS-only pairwise and known-answer tests (`:60-141`), none of which is compiled on this
//! profile: the whole block is `#ifdef FIPS_MODULE`, and every reader of it is inside
//! `dsa_keygen`'s own `#ifdef`.
//!
//! ## The dispatch is a fall-through, not a call
//!
//! `DSA_generate_key` answers `dsa->meth->dsa_keygen(dsa)` **when that member is non-NULL** and
//! calls the static `dsa_keygen` otherwise. The authority's own table leaves `dsa_keygen` NULL
//! (`dsa_ossl.c:66`), so on every object this crate can build the answer is the static — which is
//! why key generation needed neither `dsa_ossl.c`'s signing path to be reachable nor a second
//! table. It is also why the member test is transcribed rather than dropped: a caller that
//! installs its own table with a `dsa_keygen` gets that one called, and `RT-DSA`'s
//! method-table arm observes the member is `None` on the default table.
//!
//! ## What `dsa_keygen` validates, and the two widths it is parametrised by
//!
//! `ossl_ffc_params_simple_validate` is a **partial** check — the authority's own comment says so
//! — and on this profile's non-FIPS arm it requires `L >= 1024 && N >= 160` for DSA. So a
//! 512/160 group can be *constructed* and can *sign*, but `DSA_generate_key` refuses it with no
//! error raised at all: `dsa_key.c` has no `ERR_raise` in its whole body. That asymmetry is
//! observable and `RT-DSA` has an arm for it.
//!
//! The exponent is `BN_num_bits(q)` bits at `MIN_STRENGTH` (80 here; the FIPS arm's 112 is not
//! compiled), generated by [`crate::ffc::key_generate::ossl_ffc_generate_private_key`], which is
//! the FFC primitive D330 landed. The public key is `g^x mod p` through
//! [`ossl_dsa_generate_public_key`], which is `ossl_dh_generate_public_key`'s shape: a
//! `BN_FLG_CONSTTIME` scratch copy of the private exponent, then one `BN_mod_exp`.
//!
//! ## The `err:` label's two pointer comparisons
//!
//! `pub_key != dsa->pub_key` and `priv_key != dsa->priv_key` are what distinguish a *reused* key
//! from a fresh one: a caller who passed its own `pub_key` keeps it on failure, and a caller who
//! did not has this call's released. Releasing unconditionally would free an object the caller
//! still owns, which is why the two tests are transcribed rather than simplified away.
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::c_int;

use crate::bn::arith::BN_mod_exp;
use crate::bn::bignum::{
    BN_clear_free, BN_free, BN_new, BN_num_bits, BN_secure_new, BN_with_flags, BigNum,
    BN_FLG_CONSTTIME,
};
use crate::bn::ctx::{BN_CTX_free, BN_CTX_new_ex, BnCtx};
use crate::ffc::key_generate::ossl_ffc_generate_private_key;
use crate::ffc::params_validate::ossl_ffc_params_simple_validate;
use crate::ffc::FFC_PARAM_TYPE_DSA;

use super::Dsa;

/// `MIN_STRENGTH` — `dsa_key.c:19-23`. `112` under `FIPS_MODULE` and **80** otherwise, which is
/// this profile: the strength `ossl_ffc_generate_private_key` is handed beside `len(q)`.
const MIN_STRENGTH: c_int = 80;

/// `int DSA_generate_key(DSA *dsa)` — `dsa_key.c:24-33`.
///
/// The method dispatch when a table supplies `dsa_keygen`, the static `dsa_keygen` otherwise. See
/// the module documentation: the authority's default table leaves the member NULL, so the second
/// arm is what every object this crate builds takes.
///
/// # Safety
///
/// `dsa` is a live object whose parameters the caller has set.
#[no_mangle]
pub unsafe extern "C" fn DSA_generate_key(dsa: *mut Dsa) -> c_int {
    // SAFETY: `dsa` is live per the contract.
    let meth = unsafe { (*dsa).meth };
    if !meth.is_null() {
        // SAFETY: `meth` is the object's own table, alive for the call.
        if let Some(keygen) = unsafe { (*meth).dsa_keygen } {
            // SAFETY: `keygen` is that table's entry point, handed this object.
            return unsafe { keygen(dsa) };
        }
    }
    // SAFETY: `dsa` is live per the contract.
    unsafe { dsa_keygen(dsa) }
}

/// `int ossl_dsa_generate_public_key(BN_CTX *ctx, const DSA *dsa, const BIGNUM *priv_key,`
/// `BIGNUM *pub_key)` — `dsa_key.c:35-54`. Internal.
///
/// "pub_key = g ^ priv_key mod p", with the private exponent copied into a `BN_FLG_CONSTTIME`
/// scratch so the exponentiation is constant-time and the caller's value is not modified. The
/// scratch is **cleared** on both exits, because it holds key material.
///
/// # Safety
///
/// `ctx` is live; `dsa` is a live object with live parameters; `priv_key` is live; `pub_key` is a
/// live, writable `BIGNUM`.
pub(crate) unsafe fn ossl_dsa_generate_public_key(
    ctx: *mut BnCtx,
    dsa: *const Dsa,
    priv_key: *const BigNum,
    pub_key: *mut BigNum,
) -> c_int {
    let mut ret: c_int = 0;

    // SAFETY: `BN_new` allocates without touching a caller pointer.
    let prk = unsafe { BN_new() };
    if prk.is_null() {
        return 0;
    }

    // SAFETY: `dsa` is live per the contract; `prk` and `priv_key` are live.
    unsafe {
        BN_with_flags(prk, priv_key, BN_FLG_CONSTTIME);

        /* pub_key = g ^ priv_key mod p */
        if BN_mod_exp(pub_key, (*dsa).params.g, prk, (*dsa).params.p, ctx) == 0 {
            BN_clear_free(prk);
            return ret;
        }
        ret = 1;
        BN_clear_free(prk);
    }
    ret
}

/// `static int dsa_keygen(DSA *dsa)` — `dsa_key.c:143-197`.
///
/// The whole key pair: validate the parameters partially, draw the exponent at `len(q)` bits and
/// `MIN_STRENGTH`, derive the public key, and store both. **Nothing raises** — measured, not
/// assumed: `crypto/dsa/dsa_key.c` contains no `ERR_raise` outside its `#ifdef FIPS_MODULE`
/// block — so a caller that sees 0 reads the reason from the parameter validator's own site or
/// from nothing at all.
///
/// The FIPS-only pairwise and known-answer tests that follow the store are not compiled here, and
/// the `dirty_cnt` bump is: it is outside the `#ifdef`.
///
/// # Safety
///
/// `dsa` is a live object whose parameters the caller has set.
unsafe fn dsa_keygen(dsa: *mut Dsa) -> c_int {
    let mut ok: c_int = 0;
    let mut pub_key: *mut BigNum = core::ptr::null_mut();
    let mut priv_key: *mut BigNum = core::ptr::null_mut();

    // SAFETY: `dsa` is live per the contract; `BN_CTX_new_ex` reads no other pointer.
    let ctx: *mut BnCtx = unsafe { BN_CTX_new_ex((*dsa).libctx) };
    if ctx.is_null() {
        // SAFETY: `ctx` is NULL, both keys are NULL, and `dsa` is live.
        return unsafe { keygen_err(ok, pub_key, priv_key, ctx, dsa) };
    }

    // SAFETY: `dsa` is live per the contract.
    unsafe {
        if (*dsa).priv_key.is_null() {
            /* `BN_secure_new` is the allocating arm; a failure answers NULL and reaches `err`. */
            priv_key = BN_secure_new();
            if priv_key.is_null() {
                return keygen_err(ok, pub_key, priv_key, ctx, dsa);
            }
        } else {
            priv_key = (*dsa).priv_key;
        }

        /* Do a partial check for invalid p, q, g */
        if ossl_ffc_params_simple_validate(
            (*dsa).libctx,
            core::ptr::addr_of!((*dsa).params),
            FFC_PARAM_TYPE_DSA,
            core::ptr::null_mut(),
        ) == 0
        {
            return keygen_err(ok, pub_key, priv_key, ctx, dsa);
        }

        /*
         * For FFC FIPS 186-4 keygen
         * security strength s = 112,
         * Max Private key size N = len(q)
         */
        if ossl_ffc_generate_private_key(
            ctx,
            core::ptr::addr_of!((*dsa).params),
            BN_num_bits((*dsa).params.q),
            MIN_STRENGTH,
            priv_key,
        ) == 0
        {
            return keygen_err(ok, pub_key, priv_key, ctx, dsa);
        }

        if (*dsa).pub_key.is_null() {
            pub_key = BN_new();
            if pub_key.is_null() {
                return keygen_err(ok, pub_key, priv_key, ctx, dsa);
            }
        } else {
            pub_key = (*dsa).pub_key;
        }

        if ossl_dsa_generate_public_key(ctx, dsa, priv_key, pub_key) == 0 {
            return keygen_err(ok, pub_key, priv_key, ctx, dsa);
        }

        (*dsa).priv_key = priv_key;
        (*dsa).pub_key = pub_key;

        ok = 1;
        /* The FIPS-only pairwise and known-answer tests sit here; `#ifdef FIPS_MODULE` does not
         * hold on this profile. */
        (*dsa).dirty_cnt += 1;
    }

    // SAFETY: `dsa` is live; `ctx` is NULL or this call's own; the two keys are NULL, this call's
    // own, or the object's own.
    unsafe { keygen_err(ok, pub_key, priv_key, ctx, dsa) }
}

/// `dsa_keygen`'s `err:` label (`dsa_key.c:191-196`): the two **comparisons** decide what is
/// released, so a key the object already held is not freed under it.
///
/// # Safety
///
/// `dsa` is live; `ctx` is NULL or this call's own; `pub_key` and `priv_key` are each NULL, this
/// call's own, or the object's own.
unsafe fn keygen_err(
    ok: c_int,
    pub_key: *mut BigNum,
    priv_key: *mut BigNum,
    ctx: *mut BnCtx,
    dsa: *mut Dsa,
) -> c_int {
    // SAFETY: `dsa` is live per the contract; each comparison reads the object's own member.
    unsafe {
        if pub_key != (*dsa).pub_key {
            BN_free(pub_key);
        }
        if priv_key != (*dsa).priv_key {
            BN_free(priv_key);
        }
    }
    // SAFETY: `ctx` is NULL or this call's own; `BN_CTX_free` accepts NULL.
    unsafe { BN_CTX_free(ctx) };
    ok
}
