//! GENERATED by forensics/tools/gen_err_strings.py — do not edit by hand.
//!
//! The `ERR_load_<LIB>_strings` entry points libcrypto exports. Each loads the
//! generic tables plus one library, which is observable through
//! `ERR_reason_error_string`; see the generator docstring.

use core::ffi::c_int;

use super::{load_generic, load_lib};

/// `int ERR_load_ASN1_strings(void)` — loads the generic tables and library 13.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_ASN1_strings() -> c_int {
    load_lib(13);
    1
}

/// `int ERR_load_ASYNC_strings(void)` — loads the generic tables and library 51.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_ASYNC_strings() -> c_int {
    load_lib(51);
    1
}

/// `int ERR_load_BIO_strings(void)` — loads the generic tables and library 32.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_BIO_strings() -> c_int {
    load_lib(32);
    1
}

/// `int ERR_load_BN_strings(void)` — loads the generic tables and library 3.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_BN_strings() -> c_int {
    load_lib(3);
    1
}

/// `int ERR_load_BUF_strings(void)` — loads the generic tables and library 7.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_BUF_strings() -> c_int {
    load_lib(7);
    1
}

/// `int ERR_load_CMS_strings(void)` — loads the generic tables and library 46.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_CMS_strings() -> c_int {
    load_lib(46);
    1
}

/// `int ERR_load_COMP_strings(void)` — loads the generic tables and library 41.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_COMP_strings() -> c_int {
    load_lib(41);
    1
}

/// `int ERR_load_CONF_strings(void)` — loads the generic tables and library 14.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_CONF_strings() -> c_int {
    load_lib(14);
    1
}

/// `int ERR_load_CRYPTO_strings(void)` — loads the generic tables and library 15.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_CRYPTO_strings() -> c_int {
    load_lib(15);
    1
}

/// `int ERR_load_CRYPTOlib_strings(void)` — loads the generic tables and library 15.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_CRYPTOlib_strings() -> c_int {
    load_lib(15);
    1
}

/// `int ERR_load_CT_strings(void)` — loads the generic tables and library 50.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_CT_strings() -> c_int {
    load_lib(50);
    1
}

/// `int ERR_load_DH_strings(void)` — loads the generic tables and library 5.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_DH_strings() -> c_int {
    load_lib(5);
    1
}

/// `int ERR_load_DSA_strings(void)` — loads the generic tables and library 10.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_DSA_strings() -> c_int {
    load_lib(10);
    1
}

/// `int ERR_load_DSO_strings(void)` — loads the generic tables and library 37.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_DSO_strings() -> c_int {
    load_lib(37);
    1
}

/// `int ERR_load_EC_strings(void)` — loads the generic tables and library 16.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_EC_strings() -> c_int {
    load_lib(16);
    1
}

/// `int ERR_load_ENGINE_strings(void)` — loads the generic tables and library 38.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_ENGINE_strings() -> c_int {
    load_lib(38);
    1
}

/// `int ERR_load_ERR_strings(void)` — loads the generic tables only.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_ERR_strings() -> c_int {
    load_generic();
    1
}

/// `int ERR_load_EVP_strings(void)` — loads the generic tables and library 6.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_EVP_strings() -> c_int {
    load_lib(6);
    1
}

/// `int ERR_load_KDF_strings(void)` — loads the generic tables; this library has no compiled reason table.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_KDF_strings() -> c_int {
    load_generic();
    1
}

/// `int ERR_load_OBJ_strings(void)` — loads the generic tables and library 8.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_OBJ_strings() -> c_int {
    load_lib(8);
    1
}

/// `int ERR_load_OCSP_strings(void)` — loads the generic tables and library 39.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_OCSP_strings() -> c_int {
    load_lib(39);
    1
}

/// `int ERR_load_OSSL_STORE_strings(void)` — loads the generic tables and library 44.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_OSSL_STORE_strings() -> c_int {
    load_lib(44);
    1
}

/// `int ERR_load_PEM_strings(void)` — loads the generic tables and library 9.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_PEM_strings() -> c_int {
    load_lib(9);
    1
}

/// `int ERR_load_PKCS12_strings(void)` — loads the generic tables and library 35.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_PKCS12_strings() -> c_int {
    load_lib(35);
    1
}

/// `int ERR_load_PKCS7_strings(void)` — loads the generic tables and library 33.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_PKCS7_strings() -> c_int {
    load_lib(33);
    1
}

/// `int ERR_load_RAND_strings(void)` — loads the generic tables and library 36.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_RAND_strings() -> c_int {
    load_lib(36);
    1
}

/// `int ERR_load_RSA_strings(void)` — loads the generic tables and library 4.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_RSA_strings() -> c_int {
    load_lib(4);
    1
}

/// `int ERR_load_TS_strings(void)` — loads the generic tables and library 47.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_TS_strings() -> c_int {
    load_lib(47);
    1
}

/// `int ERR_load_UI_strings(void)` — loads the generic tables and library 40.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_UI_strings() -> c_int {
    load_lib(40);
    1
}

/// `int ERR_load_X509V3_strings(void)` — loads the generic tables and library 34.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_X509V3_strings() -> c_int {
    load_lib(34);
    1
}

/// `int ERR_load_X509_strings(void)` — loads the generic tables and library 11.
#[no_mangle]
pub(crate) extern "C" fn ERR_load_X509_strings() -> c_int {
    load_lib(11);
    1
}
