/* Generated by forensics/tools/phase2_courts.py — layout probe against the header shell. */
#include <stddef.h>
#include <stdio.h>
#include <openssl/aes.h>
#include <openssl/asn1.h>
#include <openssl/asn1err.h>
#include <openssl/asn1t.h>
#include <openssl/async.h>
#include <openssl/asyncerr.h>
#include <openssl/bio.h>
#include <openssl/bioerr.h>
#include <openssl/blowfish.h>
#include <openssl/bn.h>
#include <openssl/bnerr.h>
#include <openssl/buffer.h>
#include <openssl/buffererr.h>
#include <openssl/byteorder.h>
#include <openssl/camellia.h>
#include <openssl/cast.h>
#include <openssl/cmac.h>
#include <openssl/cmp.h>
#include <openssl/cmp_util.h>
#include <openssl/cmperr.h>
#include <openssl/cms.h>
#include <openssl/cmserr.h>
#include <openssl/comp.h>
#include <openssl/comperr.h>
#include <openssl/conf.h>
#include <openssl/conf_api.h>
#include <openssl/conferr.h>
#include <openssl/configuration.h>
#include <openssl/conftypes.h>
#include <openssl/core.h>
#include <openssl/core_dispatch.h>
#include <openssl/core_names.h>
#include <openssl/core_object.h>
#include <openssl/crmf.h>
#include <openssl/crmferr.h>
#include <openssl/crypto.h>
#include <openssl/cryptoerr.h>
#include <openssl/cryptoerr_legacy.h>
#include <openssl/ct.h>
#include <openssl/cterr.h>
#include <openssl/decoder.h>
#include <openssl/decodererr.h>
#include <openssl/des.h>
#include <openssl/dh.h>
#include <openssl/dherr.h>
#include <openssl/dsa.h>
#include <openssl/dsaerr.h>
#include <openssl/dtls1.h>
#include <openssl/e_os2.h>
#include <openssl/e_ostime.h>
#include <openssl/ebcdic.h>
#include <openssl/ec.h>
#include <openssl/ecdh.h>
#include <openssl/ecdsa.h>
#include <openssl/ecerr.h>
#include <openssl/encoder.h>
#include <openssl/encodererr.h>
#include <openssl/engine.h>
#include <openssl/engineerr.h>
#include <openssl/err.h>
#include <openssl/ess.h>
#include <openssl/esserr.h>
#include <openssl/evp.h>
#include <openssl/evperr.h>
#include <openssl/fips_names.h>
#include <openssl/fipskey.h>
#include <openssl/hmac.h>
#include <openssl/hpke.h>
#include <openssl/http.h>
#include <openssl/httperr.h>
#include <openssl/idea.h>
#include <openssl/indicator.h>
#include <openssl/kdf.h>
#include <openssl/kdferr.h>
#include <openssl/lhash.h>
#include <openssl/macros.h>
#include <openssl/md2.h>
#include <openssl/md4.h>
#include <openssl/md5.h>
#include <openssl/mdc2.h>
#include <openssl/ml_kem.h>
#include <openssl/modes.h>
#include <openssl/obj_mac.h>
#include <openssl/objects.h>
#include <openssl/objectserr.h>
#include <openssl/ocsp.h>
#include <openssl/ocsperr.h>
#include <openssl/opensslconf.h>
#include <openssl/opensslv.h>
#include <openssl/ossl_typ.h>
#include <openssl/param_build.h>
#include <openssl/params.h>
#include <openssl/pem.h>
#include <openssl/pem2.h>
#include <openssl/pemerr.h>
#include <openssl/pkcs12.h>
#include <openssl/pkcs12err.h>
#include <openssl/pkcs7.h>
#include <openssl/pkcs7err.h>
#include <openssl/prov_ssl.h>
#include <openssl/proverr.h>
#include <openssl/provider.h>
#include <openssl/quic.h>
#include <openssl/rand.h>
#include <openssl/randerr.h>
#include <openssl/rc2.h>
#include <openssl/rc4.h>
#include <openssl/rc5.h>
#include <openssl/ripemd.h>
#include <openssl/rsa.h>
#include <openssl/rsaerr.h>
#include <openssl/safestack.h>
#include <openssl/seed.h>
#include <openssl/self_test.h>
#include <openssl/sha.h>
#include <openssl/srp.h>
#include <openssl/srtp.h>
#include <openssl/ssl.h>
#include <openssl/ssl2.h>
#include <openssl/ssl3.h>
#include <openssl/sslerr.h>
#include <openssl/sslerr_legacy.h>
#include <openssl/stack.h>
#include <openssl/store.h>
#include <openssl/storeerr.h>
#include <openssl/symhacks.h>
#include <openssl/thread.h>
#include <openssl/tls1.h>
#include <openssl/trace.h>
#include <openssl/ts.h>
#include <openssl/tserr.h>
#include <openssl/txt_db.h>
#include <openssl/types.h>
#include <openssl/ui.h>
#include <openssl/uierr.h>
#include <openssl/whrlpool.h>
#include <openssl/x509.h>
#include <openssl/x509_acert.h>
#include <openssl/x509_vfy.h>
#include <openssl/x509err.h>
#include <openssl/x509v3.h>
#include <openssl/x509v3err.h>

int main(void) {
    printf("sizeof\t%s\t%zu\n", "struct AA_DIST_POINT_st", sizeof(struct AA_DIST_POINT_st));
    printf("alignof\t%s\t%zu\n", "struct AA_DIST_POINT_st", _Alignof(struct AA_DIST_POINT_st));
    printf("sizeof\t%s\t%zu\n", "struct ACCESS_DESCRIPTION_st", sizeof(struct ACCESS_DESCRIPTION_st));
    printf("alignof\t%s\t%zu\n", "struct ACCESS_DESCRIPTION_st", _Alignof(struct ACCESS_DESCRIPTION_st));
    printf("sizeof\t%s\t%zu\n", "struct ALLOWED_ATTRIBUTES_CHOICE_st", sizeof(struct ALLOWED_ATTRIBUTES_CHOICE_st));
    printf("alignof\t%s\t%zu\n", "struct ALLOWED_ATTRIBUTES_CHOICE_st", _Alignof(struct ALLOWED_ATTRIBUTES_CHOICE_st));
    printf("sizeof\t%s\t%zu\n", "struct ALLOWED_ATTRIBUTES_ITEM_st", sizeof(struct ALLOWED_ATTRIBUTES_ITEM_st));
    printf("alignof\t%s\t%zu\n", "struct ALLOWED_ATTRIBUTES_ITEM_st", _Alignof(struct ALLOWED_ATTRIBUTES_ITEM_st));
    printf("sizeof\t%s\t%zu\n", "struct ASIdOrRange_st", sizeof(struct ASIdOrRange_st));
    printf("alignof\t%s\t%zu\n", "struct ASIdOrRange_st", _Alignof(struct ASIdOrRange_st));
    printf("sizeof\t%s\t%zu\n", "struct ASIdentifierChoice_st", sizeof(struct ASIdentifierChoice_st));
    printf("alignof\t%s\t%zu\n", "struct ASIdentifierChoice_st", _Alignof(struct ASIdentifierChoice_st));
    printf("sizeof\t%s\t%zu\n", "struct ASIdentifiers_st", sizeof(struct ASIdentifiers_st));
    printf("alignof\t%s\t%zu\n", "struct ASIdentifiers_st", _Alignof(struct ASIdentifiers_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_ADB_TABLE_st", sizeof(struct ASN1_ADB_TABLE_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_ADB_TABLE_st", _Alignof(struct ASN1_ADB_TABLE_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_ADB_st", sizeof(struct ASN1_ADB_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_ADB_st", _Alignof(struct ASN1_ADB_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_AUX_st", sizeof(struct ASN1_AUX_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_AUX_st", _Alignof(struct ASN1_AUX_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_ENCODING_st", sizeof(struct ASN1_ENCODING_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_ENCODING_st", _Alignof(struct ASN1_ENCODING_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st", sizeof(struct ASN1_EXTERN_FUNCS_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st", _Alignof(struct ASN1_EXTERN_FUNCS_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_ITEM_st", sizeof(struct ASN1_ITEM_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_ITEM_st", _Alignof(struct ASN1_ITEM_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_PRIMITIVE_FUNCS_st", sizeof(struct ASN1_PRIMITIVE_FUNCS_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_PRIMITIVE_FUNCS_st", _Alignof(struct ASN1_PRIMITIVE_FUNCS_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_PRINT_ARG_st", sizeof(struct ASN1_PRINT_ARG_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_PRINT_ARG_st", _Alignof(struct ASN1_PRINT_ARG_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_STREAM_ARG_st", sizeof(struct ASN1_STREAM_ARG_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_STREAM_ARG_st", _Alignof(struct ASN1_STREAM_ARG_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_TEMPLATE_st", sizeof(struct ASN1_TEMPLATE_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_TEMPLATE_st", _Alignof(struct ASN1_TEMPLATE_st));
    printf("sizeof\t%s\t%zu\n", "struct ASN1_TLC_st", sizeof(struct ASN1_TLC_st));
    printf("alignof\t%s\t%zu\n", "struct ASN1_TLC_st", _Alignof(struct ASN1_TLC_st));
    printf("sizeof\t%s\t%zu\n", "struct ASRange_st", sizeof(struct ASRange_st));
    printf("alignof\t%s\t%zu\n", "struct ASRange_st", _Alignof(struct ASRange_st));
    printf("sizeof\t%s\t%zu\n", "struct ATTRIBUTE_MAPPING_st", sizeof(struct ATTRIBUTE_MAPPING_st));
    printf("alignof\t%s\t%zu\n", "struct ATTRIBUTE_MAPPING_st", _Alignof(struct ATTRIBUTE_MAPPING_st));
    printf("sizeof\t%s\t%zu\n", "struct ATTRIBUTE_TYPE_MAPPING_st", sizeof(struct ATTRIBUTE_TYPE_MAPPING_st));
    printf("alignof\t%s\t%zu\n", "struct ATTRIBUTE_TYPE_MAPPING_st", _Alignof(struct ATTRIBUTE_TYPE_MAPPING_st));
    printf("sizeof\t%s\t%zu\n", "struct ATTRIBUTE_VALUE_MAPPING_st", sizeof(struct ATTRIBUTE_VALUE_MAPPING_st));
    printf("alignof\t%s\t%zu\n", "struct ATTRIBUTE_VALUE_MAPPING_st", _Alignof(struct ATTRIBUTE_VALUE_MAPPING_st));
    printf("sizeof\t%s\t%zu\n", "struct AUTHORITY_KEYID_st", sizeof(struct AUTHORITY_KEYID_st));
    printf("alignof\t%s\t%zu\n", "struct AUTHORITY_KEYID_st", _Alignof(struct AUTHORITY_KEYID_st));
    printf("sizeof\t%s\t%zu\n", "struct BASIC_CONSTRAINTS_st", sizeof(struct BASIC_CONSTRAINTS_st));
    printf("alignof\t%s\t%zu\n", "struct BASIC_CONSTRAINTS_st", _Alignof(struct BASIC_CONSTRAINTS_st));
    printf("sizeof\t%s\t%zu\n", "struct BIT_STRING_BITNAME_st", sizeof(struct BIT_STRING_BITNAME_st));
    printf("alignof\t%s\t%zu\n", "struct BIT_STRING_BITNAME_st", _Alignof(struct BIT_STRING_BITNAME_st));
    printf("sizeof\t%s\t%zu\n", "struct DES_ks", sizeof(struct DES_ks));
    printf("alignof\t%s\t%zu\n", "struct DES_ks", _Alignof(struct DES_ks));
    printf("sizeof\t%s\t%zu\n", "struct DIST_POINT_NAME_st", sizeof(struct DIST_POINT_NAME_st));
    printf("alignof\t%s\t%zu\n", "struct DIST_POINT_NAME_st", _Alignof(struct DIST_POINT_NAME_st));
    printf("sizeof\t%s\t%zu\n", "struct DIST_POINT_st", sizeof(struct DIST_POINT_st));
    printf("alignof\t%s\t%zu\n", "struct DIST_POINT_st", _Alignof(struct DIST_POINT_st));
    printf("sizeof\t%s\t%zu\n", "struct EDIPartyName_st", sizeof(struct EDIPartyName_st));
    printf("alignof\t%s\t%zu\n", "struct EDIPartyName_st", _Alignof(struct EDIPartyName_st));
    printf("sizeof\t%s\t%zu\n", "struct ENGINE_CMD_DEFN_st", sizeof(struct ENGINE_CMD_DEFN_st));
    printf("alignof\t%s\t%zu\n", "struct ENGINE_CMD_DEFN_st", _Alignof(struct ENGINE_CMD_DEFN_st));
    printf("sizeof\t%s\t%zu\n", "struct ERR_string_data_st", sizeof(struct ERR_string_data_st));
    printf("alignof\t%s\t%zu\n", "struct ERR_string_data_st", _Alignof(struct ERR_string_data_st));
    printf("sizeof\t%s\t%zu\n", "struct GENERAL_NAME_st", sizeof(struct GENERAL_NAME_st));
    printf("alignof\t%s\t%zu\n", "struct GENERAL_NAME_st", _Alignof(struct GENERAL_NAME_st));
    printf("sizeof\t%s\t%zu\n", "struct GENERAL_SUBTREE_st", sizeof(struct GENERAL_SUBTREE_st));
    printf("alignof\t%s\t%zu\n", "struct GENERAL_SUBTREE_st", _Alignof(struct GENERAL_SUBTREE_st));
    printf("sizeof\t%s\t%zu\n", "struct IPAddressChoice_st", sizeof(struct IPAddressChoice_st));
    printf("alignof\t%s\t%zu\n", "struct IPAddressChoice_st", _Alignof(struct IPAddressChoice_st));
    printf("sizeof\t%s\t%zu\n", "struct IPAddressFamily_st", sizeof(struct IPAddressFamily_st));
    printf("alignof\t%s\t%zu\n", "struct IPAddressFamily_st", _Alignof(struct IPAddressFamily_st));
    printf("sizeof\t%s\t%zu\n", "struct IPAddressOrRange_st", sizeof(struct IPAddressOrRange_st));
    printf("alignof\t%s\t%zu\n", "struct IPAddressOrRange_st", _Alignof(struct IPAddressOrRange_st));
    printf("sizeof\t%s\t%zu\n", "struct IPAddressRange_st", sizeof(struct IPAddressRange_st));
    printf("alignof\t%s\t%zu\n", "struct IPAddressRange_st", _Alignof(struct IPAddressRange_st));
    printf("sizeof\t%s\t%zu\n", "struct ISSUER_SIGN_TOOL_st", sizeof(struct ISSUER_SIGN_TOOL_st));
    printf("alignof\t%s\t%zu\n", "struct ISSUER_SIGN_TOOL_st", _Alignof(struct ISSUER_SIGN_TOOL_st));
    printf("sizeof\t%s\t%zu\n", "struct ISSUING_DIST_POINT_st", sizeof(struct ISSUING_DIST_POINT_st));
    printf("alignof\t%s\t%zu\n", "struct ISSUING_DIST_POINT_st", _Alignof(struct ISSUING_DIST_POINT_st));
    printf("sizeof\t%s\t%zu\n", "struct MD4state_st", sizeof(struct MD4state_st));
    printf("alignof\t%s\t%zu\n", "struct MD4state_st", _Alignof(struct MD4state_st));
    printf("sizeof\t%s\t%zu\n", "struct MD5state_st", sizeof(struct MD5state_st));
    printf("alignof\t%s\t%zu\n", "struct MD5state_st", _Alignof(struct MD5state_st));
    printf("sizeof\t%s\t%zu\n", "struct NAME_CONSTRAINTS_st", sizeof(struct NAME_CONSTRAINTS_st));
    printf("alignof\t%s\t%zu\n", "struct NAME_CONSTRAINTS_st", _Alignof(struct NAME_CONSTRAINTS_st));
    printf("sizeof\t%s\t%zu\n", "struct NOTICEREF_st", sizeof(struct NOTICEREF_st));
    printf("alignof\t%s\t%zu\n", "struct NOTICEREF_st", _Alignof(struct NOTICEREF_st));
    printf("sizeof\t%s\t%zu\n", "struct Netscape_certificate_sequence", sizeof(struct Netscape_certificate_sequence));
    printf("alignof\t%s\t%zu\n", "struct Netscape_certificate_sequence", _Alignof(struct Netscape_certificate_sequence));
    printf("sizeof\t%s\t%zu\n", "struct Netscape_spkac_st", sizeof(struct Netscape_spkac_st));
    printf("alignof\t%s\t%zu\n", "struct Netscape_spkac_st", _Alignof(struct Netscape_spkac_st));
    printf("sizeof\t%s\t%zu\n", "struct Netscape_spki_st", sizeof(struct Netscape_spki_st));
    printf("alignof\t%s\t%zu\n", "struct Netscape_spki_st", _Alignof(struct Netscape_spki_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_ATTRIBUTE_DESCRIPTOR_st", sizeof(struct OSSL_ATTRIBUTE_DESCRIPTOR_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_ATTRIBUTE_DESCRIPTOR_st", _Alignof(struct OSSL_ATTRIBUTE_DESCRIPTOR_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_BASIC_ATTR_CONSTRAINTS_st", sizeof(struct OSSL_BASIC_ATTR_CONSTRAINTS_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_BASIC_ATTR_CONSTRAINTS_st", _Alignof(struct OSSL_BASIC_ATTR_CONSTRAINTS_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_DAY_TIME_BAND_st", sizeof(struct OSSL_DAY_TIME_BAND_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_DAY_TIME_BAND_st", _Alignof(struct OSSL_DAY_TIME_BAND_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_DAY_TIME_st", sizeof(struct OSSL_DAY_TIME_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_DAY_TIME_st", _Alignof(struct OSSL_DAY_TIME_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_HASH_st", sizeof(struct OSSL_HASH_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_HASH_st", _Alignof(struct OSSL_HASH_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_INFO_SYNTAX_POINTER_st", sizeof(struct OSSL_INFO_SYNTAX_POINTER_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_INFO_SYNTAX_POINTER_st", _Alignof(struct OSSL_INFO_SYNTAX_POINTER_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_INFO_SYNTAX_st", sizeof(struct OSSL_INFO_SYNTAX_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_INFO_SYNTAX_st", _Alignof(struct OSSL_INFO_SYNTAX_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_NAMED_DAY_st", sizeof(struct OSSL_NAMED_DAY_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_NAMED_DAY_st", _Alignof(struct OSSL_NAMED_DAY_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_PRIVILEGE_POLICY_ID_st", sizeof(struct OSSL_PRIVILEGE_POLICY_ID_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_PRIVILEGE_POLICY_ID_st", _Alignof(struct OSSL_PRIVILEGE_POLICY_ID_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_ROLE_SPEC_CERT_ID_st", sizeof(struct OSSL_ROLE_SPEC_CERT_ID_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_ROLE_SPEC_CERT_ID_st", _Alignof(struct OSSL_ROLE_SPEC_CERT_ID_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_TIME_PERIOD_st", sizeof(struct OSSL_TIME_PERIOD_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_TIME_PERIOD_st", _Alignof(struct OSSL_TIME_PERIOD_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_ABSOLUTE_st", sizeof(struct OSSL_TIME_SPEC_ABSOLUTE_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_ABSOLUTE_st", _Alignof(struct OSSL_TIME_SPEC_ABSOLUTE_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_DAY_st", sizeof(struct OSSL_TIME_SPEC_DAY_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_DAY_st", _Alignof(struct OSSL_TIME_SPEC_DAY_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_MONTH_st", sizeof(struct OSSL_TIME_SPEC_MONTH_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_MONTH_st", _Alignof(struct OSSL_TIME_SPEC_MONTH_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_TIME_st", sizeof(struct OSSL_TIME_SPEC_TIME_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_TIME_st", _Alignof(struct OSSL_TIME_SPEC_TIME_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_WEEKS_st", sizeof(struct OSSL_TIME_SPEC_WEEKS_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_WEEKS_st", _Alignof(struct OSSL_TIME_SPEC_WEEKS_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_X_DAY_OF_st", sizeof(struct OSSL_TIME_SPEC_X_DAY_OF_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_X_DAY_OF_st", _Alignof(struct OSSL_TIME_SPEC_X_DAY_OF_st));
    printf("sizeof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_st", sizeof(struct OSSL_TIME_SPEC_st));
    printf("alignof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_st", _Alignof(struct OSSL_TIME_SPEC_st));
    printf("sizeof\t%s\t%zu\n", "struct PBE2PARAM_st", sizeof(struct PBE2PARAM_st));
    printf("alignof\t%s\t%zu\n", "struct PBE2PARAM_st", _Alignof(struct PBE2PARAM_st));
    printf("sizeof\t%s\t%zu\n", "struct PBEPARAM_st", sizeof(struct PBEPARAM_st));
    printf("alignof\t%s\t%zu\n", "struct PBEPARAM_st", _Alignof(struct PBEPARAM_st));
    printf("sizeof\t%s\t%zu\n", "struct PBKDF2PARAM_st", sizeof(struct PBKDF2PARAM_st));
    printf("alignof\t%s\t%zu\n", "struct PBKDF2PARAM_st", _Alignof(struct PBKDF2PARAM_st));
    printf("sizeof\t%s\t%zu\n", "struct PKCS7_CTX_st", sizeof(struct PKCS7_CTX_st));
    printf("alignof\t%s\t%zu\n", "struct PKCS7_CTX_st", _Alignof(struct PKCS7_CTX_st));
    printf("sizeof\t%s\t%zu\n", "struct PKEY_USAGE_PERIOD_st", sizeof(struct PKEY_USAGE_PERIOD_st));
    printf("alignof\t%s\t%zu\n", "struct PKEY_USAGE_PERIOD_st", _Alignof(struct PKEY_USAGE_PERIOD_st));
    printf("sizeof\t%s\t%zu\n", "struct POLICYINFO_st", sizeof(struct POLICYINFO_st));
    printf("alignof\t%s\t%zu\n", "struct POLICYINFO_st", _Alignof(struct POLICYINFO_st));
    printf("sizeof\t%s\t%zu\n", "struct POLICYQUALINFO_st", sizeof(struct POLICYQUALINFO_st));
    printf("alignof\t%s\t%zu\n", "struct POLICYQUALINFO_st", _Alignof(struct POLICYQUALINFO_st));
    printf("sizeof\t%s\t%zu\n", "struct POLICY_CONSTRAINTS_st", sizeof(struct POLICY_CONSTRAINTS_st));
    printf("alignof\t%s\t%zu\n", "struct POLICY_CONSTRAINTS_st", _Alignof(struct POLICY_CONSTRAINTS_st));
    printf("sizeof\t%s\t%zu\n", "struct POLICY_MAPPING_st", sizeof(struct POLICY_MAPPING_st));
    printf("alignof\t%s\t%zu\n", "struct POLICY_MAPPING_st", _Alignof(struct POLICY_MAPPING_st));
    printf("sizeof\t%s\t%zu\n", "struct PROXY_CERT_INFO_EXTENSION_st", sizeof(struct PROXY_CERT_INFO_EXTENSION_st));
    printf("alignof\t%s\t%zu\n", "struct PROXY_CERT_INFO_EXTENSION_st", _Alignof(struct PROXY_CERT_INFO_EXTENSION_st));
    printf("sizeof\t%s\t%zu\n", "struct PROXY_POLICY_st", sizeof(struct PROXY_POLICY_st));
    printf("alignof\t%s\t%zu\n", "struct PROXY_POLICY_st", _Alignof(struct PROXY_POLICY_st));
    printf("sizeof\t%s\t%zu\n", "struct RIPEMD160state_st", sizeof(struct RIPEMD160state_st));
    printf("alignof\t%s\t%zu\n", "struct RIPEMD160state_st", _Alignof(struct RIPEMD160state_st));
    printf("sizeof\t%s\t%zu\n", "struct SCRYPT_PARAMS_st", sizeof(struct SCRYPT_PARAMS_st));
    printf("alignof\t%s\t%zu\n", "struct SCRYPT_PARAMS_st", _Alignof(struct SCRYPT_PARAMS_st));
    printf("sizeof\t%s\t%zu\n", "struct SHA256state_st", sizeof(struct SHA256state_st));
    printf("alignof\t%s\t%zu\n", "struct SHA256state_st", _Alignof(struct SHA256state_st));
    printf("sizeof\t%s\t%zu\n", "struct SHA512state_st", sizeof(struct SHA512state_st));
    printf("alignof\t%s\t%zu\n", "struct SHA512state_st", _Alignof(struct SHA512state_st));
    printf("sizeof\t%s\t%zu\n", "struct SHAstate_st", sizeof(struct SHAstate_st));
    printf("alignof\t%s\t%zu\n", "struct SHAstate_st", _Alignof(struct SHAstate_st));
    printf("sizeof\t%s\t%zu\n", "struct SRP_VBASE_st", sizeof(struct SRP_VBASE_st));
    printf("alignof\t%s\t%zu\n", "struct SRP_VBASE_st", _Alignof(struct SRP_VBASE_st));
    printf("sizeof\t%s\t%zu\n", "struct SRP_gN_cache_st", sizeof(struct SRP_gN_cache_st));
    printf("alignof\t%s\t%zu\n", "struct SRP_gN_cache_st", _Alignof(struct SRP_gN_cache_st));
    printf("sizeof\t%s\t%zu\n", "struct SRP_gN_st", sizeof(struct SRP_gN_st));
    printf("alignof\t%s\t%zu\n", "struct SRP_gN_st", _Alignof(struct SRP_gN_st));
    printf("sizeof\t%s\t%zu\n", "struct SRP_user_pwd_st", sizeof(struct SRP_user_pwd_st));
    printf("alignof\t%s\t%zu\n", "struct SRP_user_pwd_st", _Alignof(struct SRP_user_pwd_st));
    printf("sizeof\t%s\t%zu\n", "struct SXNET_ID_st", sizeof(struct SXNET_ID_st));
    printf("alignof\t%s\t%zu\n", "struct SXNET_ID_st", _Alignof(struct SXNET_ID_st));
    printf("sizeof\t%s\t%zu\n", "struct SXNET_st", sizeof(struct SXNET_st));
    printf("alignof\t%s\t%zu\n", "struct SXNET_st", _Alignof(struct SXNET_st));
    printf("sizeof\t%s\t%zu\n", "struct TARGET_CERT_st", sizeof(struct TARGET_CERT_st));
    printf("alignof\t%s\t%zu\n", "struct TARGET_CERT_st", _Alignof(struct TARGET_CERT_st));
    printf("sizeof\t%s\t%zu\n", "struct TARGET_st", sizeof(struct TARGET_st));
    printf("alignof\t%s\t%zu\n", "struct TARGET_st", _Alignof(struct TARGET_st));
    printf("sizeof\t%s\t%zu\n", "struct USERNOTICE_st", sizeof(struct USERNOTICE_st));
    printf("alignof\t%s\t%zu\n", "struct USERNOTICE_st", _Alignof(struct USERNOTICE_st));
    printf("sizeof\t%s\t%zu\n", "struct X509V3_CONF_METHOD_st", sizeof(struct X509V3_CONF_METHOD_st));
    printf("alignof\t%s\t%zu\n", "struct X509V3_CONF_METHOD_st", _Alignof(struct X509V3_CONF_METHOD_st));
    printf("sizeof\t%s\t%zu\n", "struct X509_algor_st", sizeof(struct X509_algor_st));
    printf("alignof\t%s\t%zu\n", "struct X509_algor_st", _Alignof(struct X509_algor_st));
    printf("sizeof\t%s\t%zu\n", "struct X509_info_st", sizeof(struct X509_info_st));
    printf("alignof\t%s\t%zu\n", "struct X509_info_st", _Alignof(struct X509_info_st));
    printf("sizeof\t%s\t%zu\n", "struct X509_val_st", sizeof(struct X509_val_st));
    printf("alignof\t%s\t%zu\n", "struct X509_val_st", _Alignof(struct X509_val_st));
    printf("sizeof\t%s\t%zu\n", "struct aes_key_st", sizeof(struct aes_key_st));
    printf("alignof\t%s\t%zu\n", "struct aes_key_st", _Alignof(struct aes_key_st));
    printf("sizeof\t%s\t%zu\n", "struct asn1_string_st", sizeof(struct asn1_string_st));
    printf("alignof\t%s\t%zu\n", "struct asn1_string_st", _Alignof(struct asn1_string_st));
    printf("sizeof\t%s\t%zu\n", "struct asn1_string_table_st", sizeof(struct asn1_string_table_st));
    printf("alignof\t%s\t%zu\n", "struct asn1_string_table_st", _Alignof(struct asn1_string_table_st));
    printf("sizeof\t%s\t%zu\n", "struct asn1_type_st", sizeof(struct asn1_type_st));
    printf("alignof\t%s\t%zu\n", "struct asn1_type_st", _Alignof(struct asn1_type_st));
    printf("sizeof\t%s\t%zu\n", "struct atav_st", sizeof(struct atav_st));
    printf("alignof\t%s\t%zu\n", "struct atav_st", _Alignof(struct atav_st));
    printf("sizeof\t%s\t%zu\n", "struct bf_key_st", sizeof(struct bf_key_st));
    printf("alignof\t%s\t%zu\n", "struct bf_key_st", _Alignof(struct bf_key_st));
    printf("sizeof\t%s\t%zu\n", "struct bio_mmsg_cb_args_st", sizeof(struct bio_mmsg_cb_args_st));
    printf("alignof\t%s\t%zu\n", "struct bio_mmsg_cb_args_st", _Alignof(struct bio_mmsg_cb_args_st));
    printf("sizeof\t%s\t%zu\n", "struct bio_msg_st", sizeof(struct bio_msg_st));
    printf("alignof\t%s\t%zu\n", "struct bio_msg_st", _Alignof(struct bio_msg_st));
    printf("sizeof\t%s\t%zu\n", "struct bio_poll_descriptor_st", sizeof(struct bio_poll_descriptor_st));
    printf("alignof\t%s\t%zu\n", "struct bio_poll_descriptor_st", _Alignof(struct bio_poll_descriptor_st));
    printf("sizeof\t%s\t%zu\n", "struct buf_mem_st", sizeof(struct buf_mem_st));
    printf("alignof\t%s\t%zu\n", "struct buf_mem_st", _Alignof(struct buf_mem_st));
    printf("sizeof\t%s\t%zu\n", "struct camellia_key_st", sizeof(struct camellia_key_st));
    printf("alignof\t%s\t%zu\n", "struct camellia_key_st", _Alignof(struct camellia_key_st));
    printf("sizeof\t%s\t%zu\n", "struct cast_key_st", sizeof(struct cast_key_st));
    printf("alignof\t%s\t%zu\n", "struct cast_key_st", _Alignof(struct cast_key_st));
    printf("sizeof\t%s\t%zu\n", "struct conf_method_st", sizeof(struct conf_method_st));
    printf("alignof\t%s\t%zu\n", "struct conf_method_st", _Alignof(struct conf_method_st));
    printf("sizeof\t%s\t%zu\n", "struct conf_st", sizeof(struct conf_st));
    printf("alignof\t%s\t%zu\n", "struct conf_st", _Alignof(struct conf_st));
    printf("sizeof\t%s\t%zu\n", "struct crypto_ex_data_st", sizeof(struct crypto_ex_data_st));
    printf("alignof\t%s\t%zu\n", "struct crypto_ex_data_st", _Alignof(struct crypto_ex_data_st));
    printf("sizeof\t%s\t%zu\n", "struct crypto_threadid_st", sizeof(struct crypto_threadid_st));
    printf("alignof\t%s\t%zu\n", "struct crypto_threadid_st", _Alignof(struct crypto_threadid_st));
    printf("sizeof\t%s\t%zu\n", "struct err_state_st", sizeof(struct err_state_st));
    printf("alignof\t%s\t%zu\n", "struct err_state_st", _Alignof(struct err_state_st));
    printf("sizeof\t%s\t%zu\n", "struct evp_cipher_info_st", sizeof(struct evp_cipher_info_st));
    printf("alignof\t%s\t%zu\n", "struct evp_cipher_info_st", _Alignof(struct evp_cipher_info_st));
    printf("sizeof\t%s\t%zu\n", "struct idea_key_st", sizeof(struct idea_key_st));
    printf("alignof\t%s\t%zu\n", "struct idea_key_st", _Alignof(struct idea_key_st));
    printf("sizeof\t%s\t%zu\n", "struct lhash_st_CONF_VALUE", sizeof(struct lhash_st_CONF_VALUE));
    printf("alignof\t%s\t%zu\n", "struct lhash_st_CONF_VALUE", _Alignof(struct lhash_st_CONF_VALUE));
    printf("sizeof\t%s\t%zu\n", "struct lhash_st_ERR_STRING_DATA", sizeof(struct lhash_st_ERR_STRING_DATA));
    printf("alignof\t%s\t%zu\n", "struct lhash_st_ERR_STRING_DATA", _Alignof(struct lhash_st_ERR_STRING_DATA));
    printf("sizeof\t%s\t%zu\n", "struct lhash_st_OPENSSL_CSTRING", sizeof(struct lhash_st_OPENSSL_CSTRING));
    printf("alignof\t%s\t%zu\n", "struct lhash_st_OPENSSL_CSTRING", _Alignof(struct lhash_st_OPENSSL_CSTRING));
    printf("sizeof\t%s\t%zu\n", "struct lhash_st_OPENSSL_STRING", sizeof(struct lhash_st_OPENSSL_STRING));
    printf("alignof\t%s\t%zu\n", "struct lhash_st_OPENSSL_STRING", _Alignof(struct lhash_st_OPENSSL_STRING));
    printf("sizeof\t%s\t%zu\n", "struct mdc2_ctx_st", sizeof(struct mdc2_ctx_st));
    printf("alignof\t%s\t%zu\n", "struct mdc2_ctx_st", _Alignof(struct mdc2_ctx_st));
    printf("sizeof\t%s\t%zu\n", "struct obj_name_st", sizeof(struct obj_name_st));
    printf("alignof\t%s\t%zu\n", "struct obj_name_st", _Alignof(struct obj_name_st));
    printf("sizeof\t%s\t%zu\n", "struct ossl_algorithm_st", sizeof(struct ossl_algorithm_st));
    printf("alignof\t%s\t%zu\n", "struct ossl_algorithm_st", _Alignof(struct ossl_algorithm_st));
    printf("sizeof\t%s\t%zu\n", "struct ossl_dispatch_st", sizeof(struct ossl_dispatch_st));
    printf("alignof\t%s\t%zu\n", "struct ossl_dispatch_st", _Alignof(struct ossl_dispatch_st));
    printf("sizeof\t%s\t%zu\n", "struct ossl_item_st", sizeof(struct ossl_item_st));
    printf("alignof\t%s\t%zu\n", "struct ossl_item_st", _Alignof(struct ossl_item_st));
    printf("sizeof\t%s\t%zu\n", "struct ossl_param_st", sizeof(struct ossl_param_st));
    printf("alignof\t%s\t%zu\n", "struct ossl_param_st", _Alignof(struct ossl_param_st));
    printf("sizeof\t%s\t%zu\n", "struct otherName_st", sizeof(struct otherName_st));
    printf("alignof\t%s\t%zu\n", "struct otherName_st", _Alignof(struct otherName_st));
    printf("sizeof\t%s\t%zu\n", "struct pkcs7_digest_st", sizeof(struct pkcs7_digest_st));
    printf("alignof\t%s\t%zu\n", "struct pkcs7_digest_st", _Alignof(struct pkcs7_digest_st));
    printf("sizeof\t%s\t%zu\n", "struct pkcs7_enc_content_st", sizeof(struct pkcs7_enc_content_st));
    printf("alignof\t%s\t%zu\n", "struct pkcs7_enc_content_st", _Alignof(struct pkcs7_enc_content_st));
    printf("sizeof\t%s\t%zu\n", "struct pkcs7_encrypted_st", sizeof(struct pkcs7_encrypted_st));
    printf("alignof\t%s\t%zu\n", "struct pkcs7_encrypted_st", _Alignof(struct pkcs7_encrypted_st));
    printf("sizeof\t%s\t%zu\n", "struct pkcs7_enveloped_st", sizeof(struct pkcs7_enveloped_st));
    printf("alignof\t%s\t%zu\n", "struct pkcs7_enveloped_st", _Alignof(struct pkcs7_enveloped_st));
    printf("sizeof\t%s\t%zu\n", "struct pkcs7_issuer_and_serial_st", sizeof(struct pkcs7_issuer_and_serial_st));
    printf("alignof\t%s\t%zu\n", "struct pkcs7_issuer_and_serial_st", _Alignof(struct pkcs7_issuer_and_serial_st));
    printf("sizeof\t%s\t%zu\n", "struct pkcs7_recip_info_st", sizeof(struct pkcs7_recip_info_st));
    printf("alignof\t%s\t%zu\n", "struct pkcs7_recip_info_st", _Alignof(struct pkcs7_recip_info_st));
    printf("sizeof\t%s\t%zu\n", "struct pkcs7_signed_st", sizeof(struct pkcs7_signed_st));
    printf("alignof\t%s\t%zu\n", "struct pkcs7_signed_st", _Alignof(struct pkcs7_signed_st));
    printf("sizeof\t%s\t%zu\n", "struct pkcs7_signedandenveloped_st", sizeof(struct pkcs7_signedandenveloped_st));
    printf("alignof\t%s\t%zu\n", "struct pkcs7_signedandenveloped_st", _Alignof(struct pkcs7_signedandenveloped_st));
    printf("sizeof\t%s\t%zu\n", "struct pkcs7_signer_info_st", sizeof(struct pkcs7_signer_info_st));
    printf("alignof\t%s\t%zu\n", "struct pkcs7_signer_info_st", _Alignof(struct pkcs7_signer_info_st));
    printf("sizeof\t%s\t%zu\n", "struct pkcs7_st", sizeof(struct pkcs7_st));
    printf("alignof\t%s\t%zu\n", "struct pkcs7_st", _Alignof(struct pkcs7_st));
    printf("sizeof\t%s\t%zu\n", "struct private_key_st", sizeof(struct private_key_st));
    printf("alignof\t%s\t%zu\n", "struct private_key_st", _Alignof(struct private_key_st));
    printf("sizeof\t%s\t%zu\n", "struct rand_meth_st", sizeof(struct rand_meth_st));
    printf("alignof\t%s\t%zu\n", "struct rand_meth_st", _Alignof(struct rand_meth_st));
    printf("sizeof\t%s\t%zu\n", "struct rc2_key_st", sizeof(struct rc2_key_st));
    printf("alignof\t%s\t%zu\n", "struct rc2_key_st", _Alignof(struct rc2_key_st));
    printf("sizeof\t%s\t%zu\n", "struct rc4_key_st", sizeof(struct rc4_key_st));
    printf("alignof\t%s\t%zu\n", "struct rc4_key_st", _Alignof(struct rc4_key_st));
    printf("sizeof\t%s\t%zu\n", "struct rsa_oaep_params_st", sizeof(struct rsa_oaep_params_st));
    printf("alignof\t%s\t%zu\n", "struct rsa_oaep_params_st", _Alignof(struct rsa_oaep_params_st));
    printf("sizeof\t%s\t%zu\n", "struct rsa_pss_params_st", sizeof(struct rsa_pss_params_st));
    printf("alignof\t%s\t%zu\n", "struct rsa_pss_params_st", _Alignof(struct rsa_pss_params_st));
    printf("sizeof\t%s\t%zu\n", "struct seed_key_st", sizeof(struct seed_key_st));
    printf("alignof\t%s\t%zu\n", "struct seed_key_st", _Alignof(struct seed_key_st));
    printf("sizeof\t%s\t%zu\n", "struct srtp_protection_profile_st", sizeof(struct srtp_protection_profile_st));
    printf("alignof\t%s\t%zu\n", "struct srtp_protection_profile_st", _Alignof(struct srtp_protection_profile_st));
    printf("sizeof\t%s\t%zu\n", "struct ssl_conn_close_info_st", sizeof(struct ssl_conn_close_info_st));
    printf("alignof\t%s\t%zu\n", "struct ssl_conn_close_info_st", _Alignof(struct ssl_conn_close_info_st));
    printf("sizeof\t%s\t%zu\n", "struct ssl_poll_item_st", sizeof(struct ssl_poll_item_st));
    printf("alignof\t%s\t%zu\n", "struct ssl_poll_item_st", _Alignof(struct ssl_poll_item_st));
    printf("sizeof\t%s\t%zu\n", "struct ssl_shutdown_ex_args_st", sizeof(struct ssl_shutdown_ex_args_st));
    printf("alignof\t%s\t%zu\n", "struct ssl_shutdown_ex_args_st", _Alignof(struct ssl_shutdown_ex_args_st));
    printf("sizeof\t%s\t%zu\n", "struct ssl_stream_reset_args_st", sizeof(struct ssl_stream_reset_args_st));
    printf("alignof\t%s\t%zu\n", "struct ssl_stream_reset_args_st", _Alignof(struct ssl_stream_reset_args_st));
    printf("sizeof\t%s\t%zu\n", "struct st_dynamic_MEM_fns", sizeof(struct st_dynamic_MEM_fns));
    printf("alignof\t%s\t%zu\n", "struct st_dynamic_MEM_fns", _Alignof(struct st_dynamic_MEM_fns));
    printf("sizeof\t%s\t%zu\n", "struct st_dynamic_fns", sizeof(struct st_dynamic_fns));
    printf("alignof\t%s\t%zu\n", "struct st_dynamic_fns", _Alignof(struct st_dynamic_fns));
    printf("sizeof\t%s\t%zu\n", "struct tls_session_ticket_ext_st", sizeof(struct tls_session_ticket_ext_st));
    printf("alignof\t%s\t%zu\n", "struct tls_session_ticket_ext_st", _Alignof(struct tls_session_ticket_ext_st));
    printf("sizeof\t%s\t%zu\n", "struct txt_db_st", sizeof(struct txt_db_st));
    printf("alignof\t%s\t%zu\n", "struct txt_db_st", _Alignof(struct txt_db_st));
    printf("sizeof\t%s\t%zu\n", "struct v3_ext_ctx", sizeof(struct v3_ext_ctx));
    printf("alignof\t%s\t%zu\n", "struct v3_ext_ctx", _Alignof(struct v3_ext_ctx));
    printf("sizeof\t%s\t%zu\n", "struct v3_ext_method", sizeof(struct v3_ext_method));
    printf("alignof\t%s\t%zu\n", "struct v3_ext_method", _Alignof(struct v3_ext_method));
    printf("sizeof\t%s\t%zu\n", "struct x509_purpose_st", sizeof(struct x509_purpose_st));
    printf("alignof\t%s\t%zu\n", "struct x509_purpose_st", _Alignof(struct x509_purpose_st));
    printf("sizeof\t%s\t%zu\n", "struct x509_trust_st", sizeof(struct x509_trust_st));
    printf("alignof\t%s\t%zu\n", "struct x509_trust_st", _Alignof(struct x509_trust_st));
    printf("sizeof\t%s\t%zu\n", "union BIO_sock_info_u", sizeof(union BIO_sock_info_u));
    printf("alignof\t%s\t%zu\n", "union BIO_sock_info_u", _Alignof(union BIO_sock_info_u));
    printf("sizeof\t%s\t%zu\n", "union lh_CONF_VALUE_dummy", sizeof(union lh_CONF_VALUE_dummy));
    printf("alignof\t%s\t%zu\n", "union lh_CONF_VALUE_dummy", _Alignof(union lh_CONF_VALUE_dummy));
    printf("sizeof\t%s\t%zu\n", "union lh_ERR_STRING_DATA_dummy", sizeof(union lh_ERR_STRING_DATA_dummy));
    printf("alignof\t%s\t%zu\n", "union lh_ERR_STRING_DATA_dummy", _Alignof(union lh_ERR_STRING_DATA_dummy));
    printf("sizeof\t%s\t%zu\n", "union lh_OPENSSL_CSTRING_dummy", sizeof(union lh_OPENSSL_CSTRING_dummy));
    printf("alignof\t%s\t%zu\n", "union lh_OPENSSL_CSTRING_dummy", _Alignof(union lh_OPENSSL_CSTRING_dummy));
    printf("sizeof\t%s\t%zu\n", "union lh_OPENSSL_STRING_dummy", sizeof(union lh_OPENSSL_STRING_dummy));
    printf("alignof\t%s\t%zu\n", "union lh_OPENSSL_STRING_dummy", _Alignof(union lh_OPENSSL_STRING_dummy));
    printf("offsetof\t%s\t%zu\n", "struct AA_DIST_POINT_st.containsAACerts", offsetof(struct AA_DIST_POINT_st, containsAACerts));
    printf("offsetof\t%s\t%zu\n", "struct AA_DIST_POINT_st.containsSOAPublicKeyCerts", offsetof(struct AA_DIST_POINT_st, containsSOAPublicKeyCerts));
    printf("offsetof\t%s\t%zu\n", "struct AA_DIST_POINT_st.containsUserAttributeCerts", offsetof(struct AA_DIST_POINT_st, containsUserAttributeCerts));
    printf("offsetof\t%s\t%zu\n", "struct AA_DIST_POINT_st.distpoint", offsetof(struct AA_DIST_POINT_st, distpoint));
    printf("offsetof\t%s\t%zu\n", "struct AA_DIST_POINT_st.dp_reasons", offsetof(struct AA_DIST_POINT_st, dp_reasons));
    printf("offsetof\t%s\t%zu\n", "struct AA_DIST_POINT_st.indirectCRL", offsetof(struct AA_DIST_POINT_st, indirectCRL));
    printf("offsetof\t%s\t%zu\n", "struct AA_DIST_POINT_st.reasons", offsetof(struct AA_DIST_POINT_st, reasons));
    printf("offsetof\t%s\t%zu\n", "struct ACCESS_DESCRIPTION_st.location", offsetof(struct ACCESS_DESCRIPTION_st, location));
    printf("offsetof\t%s\t%zu\n", "struct ACCESS_DESCRIPTION_st.method", offsetof(struct ACCESS_DESCRIPTION_st, method));
    printf("offsetof\t%s\t%zu\n", "struct ALLOWED_ATTRIBUTES_CHOICE_st.choice", offsetof(struct ALLOWED_ATTRIBUTES_CHOICE_st, choice));
    printf("offsetof\t%s\t%zu\n", "struct ALLOWED_ATTRIBUTES_CHOICE_st.type", offsetof(struct ALLOWED_ATTRIBUTES_CHOICE_st, type));
    printf("offsetof\t%s\t%zu\n", "struct ALLOWED_ATTRIBUTES_ITEM_st.attributes", offsetof(struct ALLOWED_ATTRIBUTES_ITEM_st, attributes));
    printf("offsetof\t%s\t%zu\n", "struct ALLOWED_ATTRIBUTES_ITEM_st.holderDomain", offsetof(struct ALLOWED_ATTRIBUTES_ITEM_st, holderDomain));
    printf("offsetof\t%s\t%zu\n", "struct ASIdOrRange_st.type", offsetof(struct ASIdOrRange_st, type));
    printf("offsetof\t%s\t%zu\n", "struct ASIdOrRange_st.u", offsetof(struct ASIdOrRange_st, u));
    printf("offsetof\t%s\t%zu\n", "struct ASIdentifierChoice_st.type", offsetof(struct ASIdentifierChoice_st, type));
    printf("offsetof\t%s\t%zu\n", "struct ASIdentifierChoice_st.u", offsetof(struct ASIdentifierChoice_st, u));
    printf("offsetof\t%s\t%zu\n", "struct ASIdentifiers_st.asnum", offsetof(struct ASIdentifiers_st, asnum));
    printf("offsetof\t%s\t%zu\n", "struct ASIdentifiers_st.rdi", offsetof(struct ASIdentifiers_st, rdi));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ADB_TABLE_st.tt", offsetof(struct ASN1_ADB_TABLE_st, tt));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ADB_TABLE_st.value", offsetof(struct ASN1_ADB_TABLE_st, value));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ADB_st.adb_cb", offsetof(struct ASN1_ADB_st, adb_cb));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ADB_st.default_tt", offsetof(struct ASN1_ADB_st, default_tt));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ADB_st.flags", offsetof(struct ASN1_ADB_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ADB_st.null_tt", offsetof(struct ASN1_ADB_st, null_tt));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ADB_st.offset", offsetof(struct ASN1_ADB_st, offset));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ADB_st.tbl", offsetof(struct ASN1_ADB_st, tbl));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ADB_st.tblcount", offsetof(struct ASN1_ADB_st, tblcount));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_AUX_st.app_data", offsetof(struct ASN1_AUX_st, app_data));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_AUX_st.asn1_cb", offsetof(struct ASN1_AUX_st, asn1_cb));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_AUX_st.asn1_const_cb", offsetof(struct ASN1_AUX_st, asn1_const_cb));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_AUX_st.enc_offset", offsetof(struct ASN1_AUX_st, enc_offset));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_AUX_st.flags", offsetof(struct ASN1_AUX_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_AUX_st.ref_lock", offsetof(struct ASN1_AUX_st, ref_lock));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_AUX_st.ref_offset", offsetof(struct ASN1_AUX_st, ref_offset));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ENCODING_st.enc", offsetof(struct ASN1_ENCODING_st, enc));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ENCODING_st.len", offsetof(struct ASN1_ENCODING_st, len));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ENCODING_st.modified", offsetof(struct ASN1_ENCODING_st, modified));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st.app_data", offsetof(struct ASN1_EXTERN_FUNCS_st, app_data));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st.asn1_ex_clear", offsetof(struct ASN1_EXTERN_FUNCS_st, asn1_ex_clear));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st.asn1_ex_d2i", offsetof(struct ASN1_EXTERN_FUNCS_st, asn1_ex_d2i));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st.asn1_ex_d2i_ex", offsetof(struct ASN1_EXTERN_FUNCS_st, asn1_ex_d2i_ex));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st.asn1_ex_free", offsetof(struct ASN1_EXTERN_FUNCS_st, asn1_ex_free));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st.asn1_ex_i2d", offsetof(struct ASN1_EXTERN_FUNCS_st, asn1_ex_i2d));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st.asn1_ex_new", offsetof(struct ASN1_EXTERN_FUNCS_st, asn1_ex_new));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st.asn1_ex_new_ex", offsetof(struct ASN1_EXTERN_FUNCS_st, asn1_ex_new_ex));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_EXTERN_FUNCS_st.asn1_ex_print", offsetof(struct ASN1_EXTERN_FUNCS_st, asn1_ex_print));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ITEM_st.funcs", offsetof(struct ASN1_ITEM_st, funcs));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ITEM_st.itype", offsetof(struct ASN1_ITEM_st, itype));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ITEM_st.size", offsetof(struct ASN1_ITEM_st, size));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ITEM_st.sname", offsetof(struct ASN1_ITEM_st, sname));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ITEM_st.tcount", offsetof(struct ASN1_ITEM_st, tcount));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ITEM_st.templates", offsetof(struct ASN1_ITEM_st, templates));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_ITEM_st.utype", offsetof(struct ASN1_ITEM_st, utype));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRIMITIVE_FUNCS_st.app_data", offsetof(struct ASN1_PRIMITIVE_FUNCS_st, app_data));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRIMITIVE_FUNCS_st.flags", offsetof(struct ASN1_PRIMITIVE_FUNCS_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRIMITIVE_FUNCS_st.prim_c2i", offsetof(struct ASN1_PRIMITIVE_FUNCS_st, prim_c2i));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRIMITIVE_FUNCS_st.prim_clear", offsetof(struct ASN1_PRIMITIVE_FUNCS_st, prim_clear));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRIMITIVE_FUNCS_st.prim_free", offsetof(struct ASN1_PRIMITIVE_FUNCS_st, prim_free));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRIMITIVE_FUNCS_st.prim_i2c", offsetof(struct ASN1_PRIMITIVE_FUNCS_st, prim_i2c));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRIMITIVE_FUNCS_st.prim_new", offsetof(struct ASN1_PRIMITIVE_FUNCS_st, prim_new));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRIMITIVE_FUNCS_st.prim_print", offsetof(struct ASN1_PRIMITIVE_FUNCS_st, prim_print));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRINT_ARG_st.indent", offsetof(struct ASN1_PRINT_ARG_st, indent));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRINT_ARG_st.out", offsetof(struct ASN1_PRINT_ARG_st, out));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_PRINT_ARG_st.pctx", offsetof(struct ASN1_PRINT_ARG_st, pctx));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_STREAM_ARG_st.boundary", offsetof(struct ASN1_STREAM_ARG_st, boundary));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_STREAM_ARG_st.ndef_bio", offsetof(struct ASN1_STREAM_ARG_st, ndef_bio));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_STREAM_ARG_st.out", offsetof(struct ASN1_STREAM_ARG_st, out));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TEMPLATE_st.field_name", offsetof(struct ASN1_TEMPLATE_st, field_name));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TEMPLATE_st.flags", offsetof(struct ASN1_TEMPLATE_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TEMPLATE_st.item", offsetof(struct ASN1_TEMPLATE_st, item));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TEMPLATE_st.offset", offsetof(struct ASN1_TEMPLATE_st, offset));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TEMPLATE_st.tag", offsetof(struct ASN1_TEMPLATE_st, tag));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TLC_st.hdrlen", offsetof(struct ASN1_TLC_st, hdrlen));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TLC_st.pclass", offsetof(struct ASN1_TLC_st, pclass));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TLC_st.plen", offsetof(struct ASN1_TLC_st, plen));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TLC_st.ptag", offsetof(struct ASN1_TLC_st, ptag));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TLC_st.ret", offsetof(struct ASN1_TLC_st, ret));
    printf("offsetof\t%s\t%zu\n", "struct ASN1_TLC_st.valid", offsetof(struct ASN1_TLC_st, valid));
    printf("offsetof\t%s\t%zu\n", "struct ASRange_st.max", offsetof(struct ASRange_st, max));
    printf("offsetof\t%s\t%zu\n", "struct ASRange_st.min", offsetof(struct ASRange_st, min));
    printf("offsetof\t%s\t%zu\n", "struct ATTRIBUTE_MAPPING_st.choice", offsetof(struct ATTRIBUTE_MAPPING_st, choice));
    printf("offsetof\t%s\t%zu\n", "struct ATTRIBUTE_MAPPING_st.type", offsetof(struct ATTRIBUTE_MAPPING_st, type));
    printf("offsetof\t%s\t%zu\n", "struct ATTRIBUTE_TYPE_MAPPING_st.local", offsetof(struct ATTRIBUTE_TYPE_MAPPING_st, local));
    printf("offsetof\t%s\t%zu\n", "struct ATTRIBUTE_TYPE_MAPPING_st.remote", offsetof(struct ATTRIBUTE_TYPE_MAPPING_st, remote));
    printf("offsetof\t%s\t%zu\n", "struct ATTRIBUTE_VALUE_MAPPING_st.local", offsetof(struct ATTRIBUTE_VALUE_MAPPING_st, local));
    printf("offsetof\t%s\t%zu\n", "struct ATTRIBUTE_VALUE_MAPPING_st.remote", offsetof(struct ATTRIBUTE_VALUE_MAPPING_st, remote));
    printf("offsetof\t%s\t%zu\n", "struct AUTHORITY_KEYID_st.issuer", offsetof(struct AUTHORITY_KEYID_st, issuer));
    printf("offsetof\t%s\t%zu\n", "struct AUTHORITY_KEYID_st.keyid", offsetof(struct AUTHORITY_KEYID_st, keyid));
    printf("offsetof\t%s\t%zu\n", "struct AUTHORITY_KEYID_st.serial", offsetof(struct AUTHORITY_KEYID_st, serial));
    printf("offsetof\t%s\t%zu\n", "struct BASIC_CONSTRAINTS_st.ca", offsetof(struct BASIC_CONSTRAINTS_st, ca));
    printf("offsetof\t%s\t%zu\n", "struct BASIC_CONSTRAINTS_st.pathlen", offsetof(struct BASIC_CONSTRAINTS_st, pathlen));
    printf("offsetof\t%s\t%zu\n", "struct BIT_STRING_BITNAME_st.bitnum", offsetof(struct BIT_STRING_BITNAME_st, bitnum));
    printf("offsetof\t%s\t%zu\n", "struct BIT_STRING_BITNAME_st.lname", offsetof(struct BIT_STRING_BITNAME_st, lname));
    printf("offsetof\t%s\t%zu\n", "struct BIT_STRING_BITNAME_st.sname", offsetof(struct BIT_STRING_BITNAME_st, sname));
    printf("offsetof\t%s\t%zu\n", "struct DES_ks.ks", offsetof(struct DES_ks, ks));
    printf("offsetof\t%s\t%zu\n", "struct DIST_POINT_NAME_st.dpname", offsetof(struct DIST_POINT_NAME_st, dpname));
    printf("offsetof\t%s\t%zu\n", "struct DIST_POINT_NAME_st.name", offsetof(struct DIST_POINT_NAME_st, name));
    printf("offsetof\t%s\t%zu\n", "struct DIST_POINT_NAME_st.type", offsetof(struct DIST_POINT_NAME_st, type));
    printf("offsetof\t%s\t%zu\n", "struct DIST_POINT_st.CRLissuer", offsetof(struct DIST_POINT_st, CRLissuer));
    printf("offsetof\t%s\t%zu\n", "struct DIST_POINT_st.distpoint", offsetof(struct DIST_POINT_st, distpoint));
    printf("offsetof\t%s\t%zu\n", "struct DIST_POINT_st.dp_reasons", offsetof(struct DIST_POINT_st, dp_reasons));
    printf("offsetof\t%s\t%zu\n", "struct DIST_POINT_st.reasons", offsetof(struct DIST_POINT_st, reasons));
    printf("offsetof\t%s\t%zu\n", "struct EDIPartyName_st.nameAssigner", offsetof(struct EDIPartyName_st, nameAssigner));
    printf("offsetof\t%s\t%zu\n", "struct EDIPartyName_st.partyName", offsetof(struct EDIPartyName_st, partyName));
    printf("offsetof\t%s\t%zu\n", "struct ENGINE_CMD_DEFN_st.cmd_desc", offsetof(struct ENGINE_CMD_DEFN_st, cmd_desc));
    printf("offsetof\t%s\t%zu\n", "struct ENGINE_CMD_DEFN_st.cmd_flags", offsetof(struct ENGINE_CMD_DEFN_st, cmd_flags));
    printf("offsetof\t%s\t%zu\n", "struct ENGINE_CMD_DEFN_st.cmd_name", offsetof(struct ENGINE_CMD_DEFN_st, cmd_name));
    printf("offsetof\t%s\t%zu\n", "struct ENGINE_CMD_DEFN_st.cmd_num", offsetof(struct ENGINE_CMD_DEFN_st, cmd_num));
    printf("offsetof\t%s\t%zu\n", "struct ERR_string_data_st.error", offsetof(struct ERR_string_data_st, error));
    printf("offsetof\t%s\t%zu\n", "struct ERR_string_data_st.string", offsetof(struct ERR_string_data_st, string));
    printf("offsetof\t%s\t%zu\n", "struct GENERAL_NAME_st.d", offsetof(struct GENERAL_NAME_st, d));
    printf("offsetof\t%s\t%zu\n", "struct GENERAL_NAME_st.type", offsetof(struct GENERAL_NAME_st, type));
    printf("offsetof\t%s\t%zu\n", "struct GENERAL_SUBTREE_st.base", offsetof(struct GENERAL_SUBTREE_st, base));
    printf("offsetof\t%s\t%zu\n", "struct GENERAL_SUBTREE_st.maximum", offsetof(struct GENERAL_SUBTREE_st, maximum));
    printf("offsetof\t%s\t%zu\n", "struct GENERAL_SUBTREE_st.minimum", offsetof(struct GENERAL_SUBTREE_st, minimum));
    printf("offsetof\t%s\t%zu\n", "struct IPAddressChoice_st.type", offsetof(struct IPAddressChoice_st, type));
    printf("offsetof\t%s\t%zu\n", "struct IPAddressChoice_st.u", offsetof(struct IPAddressChoice_st, u));
    printf("offsetof\t%s\t%zu\n", "struct IPAddressFamily_st.addressFamily", offsetof(struct IPAddressFamily_st, addressFamily));
    printf("offsetof\t%s\t%zu\n", "struct IPAddressFamily_st.ipAddressChoice", offsetof(struct IPAddressFamily_st, ipAddressChoice));
    printf("offsetof\t%s\t%zu\n", "struct IPAddressOrRange_st.type", offsetof(struct IPAddressOrRange_st, type));
    printf("offsetof\t%s\t%zu\n", "struct IPAddressOrRange_st.u", offsetof(struct IPAddressOrRange_st, u));
    printf("offsetof\t%s\t%zu\n", "struct IPAddressRange_st.max", offsetof(struct IPAddressRange_st, max));
    printf("offsetof\t%s\t%zu\n", "struct IPAddressRange_st.min", offsetof(struct IPAddressRange_st, min));
    printf("offsetof\t%s\t%zu\n", "struct ISSUER_SIGN_TOOL_st.cATool", offsetof(struct ISSUER_SIGN_TOOL_st, cATool));
    printf("offsetof\t%s\t%zu\n", "struct ISSUER_SIGN_TOOL_st.cAToolCert", offsetof(struct ISSUER_SIGN_TOOL_st, cAToolCert));
    printf("offsetof\t%s\t%zu\n", "struct ISSUER_SIGN_TOOL_st.signTool", offsetof(struct ISSUER_SIGN_TOOL_st, signTool));
    printf("offsetof\t%s\t%zu\n", "struct ISSUER_SIGN_TOOL_st.signToolCert", offsetof(struct ISSUER_SIGN_TOOL_st, signToolCert));
    printf("offsetof\t%s\t%zu\n", "struct ISSUING_DIST_POINT_st.distpoint", offsetof(struct ISSUING_DIST_POINT_st, distpoint));
    printf("offsetof\t%s\t%zu\n", "struct ISSUING_DIST_POINT_st.indirectCRL", offsetof(struct ISSUING_DIST_POINT_st, indirectCRL));
    printf("offsetof\t%s\t%zu\n", "struct ISSUING_DIST_POINT_st.onlyCA", offsetof(struct ISSUING_DIST_POINT_st, onlyCA));
    printf("offsetof\t%s\t%zu\n", "struct ISSUING_DIST_POINT_st.onlyattr", offsetof(struct ISSUING_DIST_POINT_st, onlyattr));
    printf("offsetof\t%s\t%zu\n", "struct ISSUING_DIST_POINT_st.onlysomereasons", offsetof(struct ISSUING_DIST_POINT_st, onlysomereasons));
    printf("offsetof\t%s\t%zu\n", "struct ISSUING_DIST_POINT_st.onlyuser", offsetof(struct ISSUING_DIST_POINT_st, onlyuser));
    printf("offsetof\t%s\t%zu\n", "struct MD4state_st.A", offsetof(struct MD4state_st, A));
    printf("offsetof\t%s\t%zu\n", "struct MD4state_st.B", offsetof(struct MD4state_st, B));
    printf("offsetof\t%s\t%zu\n", "struct MD4state_st.C", offsetof(struct MD4state_st, C));
    printf("offsetof\t%s\t%zu\n", "struct MD4state_st.D", offsetof(struct MD4state_st, D));
    printf("offsetof\t%s\t%zu\n", "struct MD4state_st.Nh", offsetof(struct MD4state_st, Nh));
    printf("offsetof\t%s\t%zu\n", "struct MD4state_st.Nl", offsetof(struct MD4state_st, Nl));
    printf("offsetof\t%s\t%zu\n", "struct MD4state_st.data", offsetof(struct MD4state_st, data));
    printf("offsetof\t%s\t%zu\n", "struct MD4state_st.num", offsetof(struct MD4state_st, num));
    printf("offsetof\t%s\t%zu\n", "struct MD5state_st.A", offsetof(struct MD5state_st, A));
    printf("offsetof\t%s\t%zu\n", "struct MD5state_st.B", offsetof(struct MD5state_st, B));
    printf("offsetof\t%s\t%zu\n", "struct MD5state_st.C", offsetof(struct MD5state_st, C));
    printf("offsetof\t%s\t%zu\n", "struct MD5state_st.D", offsetof(struct MD5state_st, D));
    printf("offsetof\t%s\t%zu\n", "struct MD5state_st.Nh", offsetof(struct MD5state_st, Nh));
    printf("offsetof\t%s\t%zu\n", "struct MD5state_st.Nl", offsetof(struct MD5state_st, Nl));
    printf("offsetof\t%s\t%zu\n", "struct MD5state_st.data", offsetof(struct MD5state_st, data));
    printf("offsetof\t%s\t%zu\n", "struct MD5state_st.num", offsetof(struct MD5state_st, num));
    printf("offsetof\t%s\t%zu\n", "struct NAME_CONSTRAINTS_st.excludedSubtrees", offsetof(struct NAME_CONSTRAINTS_st, excludedSubtrees));
    printf("offsetof\t%s\t%zu\n", "struct NAME_CONSTRAINTS_st.permittedSubtrees", offsetof(struct NAME_CONSTRAINTS_st, permittedSubtrees));
    printf("offsetof\t%s\t%zu\n", "struct NOTICEREF_st.noticenos", offsetof(struct NOTICEREF_st, noticenos));
    printf("offsetof\t%s\t%zu\n", "struct NOTICEREF_st.organization", offsetof(struct NOTICEREF_st, organization));
    printf("offsetof\t%s\t%zu\n", "struct Netscape_certificate_sequence.certs", offsetof(struct Netscape_certificate_sequence, certs));
    printf("offsetof\t%s\t%zu\n", "struct Netscape_certificate_sequence.type", offsetof(struct Netscape_certificate_sequence, type));
    printf("offsetof\t%s\t%zu\n", "struct Netscape_spkac_st.challenge", offsetof(struct Netscape_spkac_st, challenge));
    printf("offsetof\t%s\t%zu\n", "struct Netscape_spkac_st.pubkey", offsetof(struct Netscape_spkac_st, pubkey));
    printf("offsetof\t%s\t%zu\n", "struct Netscape_spki_st.sig_algor", offsetof(struct Netscape_spki_st, sig_algor));
    printf("offsetof\t%s\t%zu\n", "struct Netscape_spki_st.signature", offsetof(struct Netscape_spki_st, signature));
    printf("offsetof\t%s\t%zu\n", "struct Netscape_spki_st.spkac", offsetof(struct Netscape_spki_st, spkac));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_ATTRIBUTE_DESCRIPTOR_st.attributeSyntax", offsetof(struct OSSL_ATTRIBUTE_DESCRIPTOR_st, attributeSyntax));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_ATTRIBUTE_DESCRIPTOR_st.description", offsetof(struct OSSL_ATTRIBUTE_DESCRIPTOR_st, description));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_ATTRIBUTE_DESCRIPTOR_st.dominationRule", offsetof(struct OSSL_ATTRIBUTE_DESCRIPTOR_st, dominationRule));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_ATTRIBUTE_DESCRIPTOR_st.identifier", offsetof(struct OSSL_ATTRIBUTE_DESCRIPTOR_st, identifier));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_ATTRIBUTE_DESCRIPTOR_st.name", offsetof(struct OSSL_ATTRIBUTE_DESCRIPTOR_st, name));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_BASIC_ATTR_CONSTRAINTS_st.authority", offsetof(struct OSSL_BASIC_ATTR_CONSTRAINTS_st, authority));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_BASIC_ATTR_CONSTRAINTS_st.pathlen", offsetof(struct OSSL_BASIC_ATTR_CONSTRAINTS_st, pathlen));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_DAY_TIME_BAND_st.endDayTime", offsetof(struct OSSL_DAY_TIME_BAND_st, endDayTime));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_DAY_TIME_BAND_st.startDayTime", offsetof(struct OSSL_DAY_TIME_BAND_st, startDayTime));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_DAY_TIME_st.hour", offsetof(struct OSSL_DAY_TIME_st, hour));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_DAY_TIME_st.minute", offsetof(struct OSSL_DAY_TIME_st, minute));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_DAY_TIME_st.second", offsetof(struct OSSL_DAY_TIME_st, second));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_HASH_st.algorithmIdentifier", offsetof(struct OSSL_HASH_st, algorithmIdentifier));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_HASH_st.hashValue", offsetof(struct OSSL_HASH_st, hashValue));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_INFO_SYNTAX_POINTER_st.hash", offsetof(struct OSSL_INFO_SYNTAX_POINTER_st, hash));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_INFO_SYNTAX_POINTER_st.name", offsetof(struct OSSL_INFO_SYNTAX_POINTER_st, name));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_INFO_SYNTAX_st.choice", offsetof(struct OSSL_INFO_SYNTAX_st, choice));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_INFO_SYNTAX_st.type", offsetof(struct OSSL_INFO_SYNTAX_st, type));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_NAMED_DAY_st.choice", offsetof(struct OSSL_NAMED_DAY_st, choice));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_NAMED_DAY_st.type", offsetof(struct OSSL_NAMED_DAY_st, type));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_PRIVILEGE_POLICY_ID_st.privPolSyntax", offsetof(struct OSSL_PRIVILEGE_POLICY_ID_st, privPolSyntax));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_PRIVILEGE_POLICY_ID_st.privilegePolicy", offsetof(struct OSSL_PRIVILEGE_POLICY_ID_st, privilegePolicy));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_ROLE_SPEC_CERT_ID_st.roleCertIssuer", offsetof(struct OSSL_ROLE_SPEC_CERT_ID_st, roleCertIssuer));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_ROLE_SPEC_CERT_ID_st.roleCertLocator", offsetof(struct OSSL_ROLE_SPEC_CERT_ID_st, roleCertLocator));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_ROLE_SPEC_CERT_ID_st.roleCertSerialNumber", offsetof(struct OSSL_ROLE_SPEC_CERT_ID_st, roleCertSerialNumber));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_ROLE_SPEC_CERT_ID_st.roleName", offsetof(struct OSSL_ROLE_SPEC_CERT_ID_st, roleName));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_PERIOD_st.days", offsetof(struct OSSL_TIME_PERIOD_st, days));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_PERIOD_st.months", offsetof(struct OSSL_TIME_PERIOD_st, months));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_PERIOD_st.timesOfDay", offsetof(struct OSSL_TIME_PERIOD_st, timesOfDay));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_PERIOD_st.weeks", offsetof(struct OSSL_TIME_PERIOD_st, weeks));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_PERIOD_st.years", offsetof(struct OSSL_TIME_PERIOD_st, years));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_ABSOLUTE_st.endTime", offsetof(struct OSSL_TIME_SPEC_ABSOLUTE_st, endTime));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_ABSOLUTE_st.startTime", offsetof(struct OSSL_TIME_SPEC_ABSOLUTE_st, startTime));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_DAY_st.choice", offsetof(struct OSSL_TIME_SPEC_DAY_st, choice));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_DAY_st.type", offsetof(struct OSSL_TIME_SPEC_DAY_st, type));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_MONTH_st.choice", offsetof(struct OSSL_TIME_SPEC_MONTH_st, choice));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_MONTH_st.type", offsetof(struct OSSL_TIME_SPEC_MONTH_st, type));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_TIME_st.choice", offsetof(struct OSSL_TIME_SPEC_TIME_st, choice));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_TIME_st.type", offsetof(struct OSSL_TIME_SPEC_TIME_st, type));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_WEEKS_st.choice", offsetof(struct OSSL_TIME_SPEC_WEEKS_st, choice));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_WEEKS_st.type", offsetof(struct OSSL_TIME_SPEC_WEEKS_st, type));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_X_DAY_OF_st.choice", offsetof(struct OSSL_TIME_SPEC_X_DAY_OF_st, choice));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_X_DAY_OF_st.type", offsetof(struct OSSL_TIME_SPEC_X_DAY_OF_st, type));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_st.notThisTime", offsetof(struct OSSL_TIME_SPEC_st, notThisTime));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_st.time", offsetof(struct OSSL_TIME_SPEC_st, time));
    printf("offsetof\t%s\t%zu\n", "struct OSSL_TIME_SPEC_st.timeZone", offsetof(struct OSSL_TIME_SPEC_st, timeZone));
    printf("offsetof\t%s\t%zu\n", "struct PBE2PARAM_st.encryption", offsetof(struct PBE2PARAM_st, encryption));
    printf("offsetof\t%s\t%zu\n", "struct PBE2PARAM_st.keyfunc", offsetof(struct PBE2PARAM_st, keyfunc));
    printf("offsetof\t%s\t%zu\n", "struct PBEPARAM_st.iter", offsetof(struct PBEPARAM_st, iter));
    printf("offsetof\t%s\t%zu\n", "struct PBEPARAM_st.salt", offsetof(struct PBEPARAM_st, salt));
    printf("offsetof\t%s\t%zu\n", "struct PBKDF2PARAM_st.iter", offsetof(struct PBKDF2PARAM_st, iter));
    printf("offsetof\t%s\t%zu\n", "struct PBKDF2PARAM_st.keylength", offsetof(struct PBKDF2PARAM_st, keylength));
    printf("offsetof\t%s\t%zu\n", "struct PBKDF2PARAM_st.prf", offsetof(struct PBKDF2PARAM_st, prf));
    printf("offsetof\t%s\t%zu\n", "struct PBKDF2PARAM_st.salt", offsetof(struct PBKDF2PARAM_st, salt));
    printf("offsetof\t%s\t%zu\n", "struct PKCS7_CTX_st.libctx", offsetof(struct PKCS7_CTX_st, libctx));
    printf("offsetof\t%s\t%zu\n", "struct PKCS7_CTX_st.propq", offsetof(struct PKCS7_CTX_st, propq));
    printf("offsetof\t%s\t%zu\n", "struct PKEY_USAGE_PERIOD_st.notAfter", offsetof(struct PKEY_USAGE_PERIOD_st, notAfter));
    printf("offsetof\t%s\t%zu\n", "struct PKEY_USAGE_PERIOD_st.notBefore", offsetof(struct PKEY_USAGE_PERIOD_st, notBefore));
    printf("offsetof\t%s\t%zu\n", "struct POLICYINFO_st.policyid", offsetof(struct POLICYINFO_st, policyid));
    printf("offsetof\t%s\t%zu\n", "struct POLICYINFO_st.qualifiers", offsetof(struct POLICYINFO_st, qualifiers));
    printf("offsetof\t%s\t%zu\n", "struct POLICYQUALINFO_st.d", offsetof(struct POLICYQUALINFO_st, d));
    printf("offsetof\t%s\t%zu\n", "struct POLICYQUALINFO_st.pqualid", offsetof(struct POLICYQUALINFO_st, pqualid));
    printf("offsetof\t%s\t%zu\n", "struct POLICY_CONSTRAINTS_st.inhibitPolicyMapping", offsetof(struct POLICY_CONSTRAINTS_st, inhibitPolicyMapping));
    printf("offsetof\t%s\t%zu\n", "struct POLICY_CONSTRAINTS_st.requireExplicitPolicy", offsetof(struct POLICY_CONSTRAINTS_st, requireExplicitPolicy));
    printf("offsetof\t%s\t%zu\n", "struct POLICY_MAPPING_st.issuerDomainPolicy", offsetof(struct POLICY_MAPPING_st, issuerDomainPolicy));
    printf("offsetof\t%s\t%zu\n", "struct POLICY_MAPPING_st.subjectDomainPolicy", offsetof(struct POLICY_MAPPING_st, subjectDomainPolicy));
    printf("offsetof\t%s\t%zu\n", "struct PROXY_CERT_INFO_EXTENSION_st.pcPathLengthConstraint", offsetof(struct PROXY_CERT_INFO_EXTENSION_st, pcPathLengthConstraint));
    printf("offsetof\t%s\t%zu\n", "struct PROXY_CERT_INFO_EXTENSION_st.proxyPolicy", offsetof(struct PROXY_CERT_INFO_EXTENSION_st, proxyPolicy));
    printf("offsetof\t%s\t%zu\n", "struct PROXY_POLICY_st.policy", offsetof(struct PROXY_POLICY_st, policy));
    printf("offsetof\t%s\t%zu\n", "struct PROXY_POLICY_st.policyLanguage", offsetof(struct PROXY_POLICY_st, policyLanguage));
    printf("offsetof\t%s\t%zu\n", "struct RIPEMD160state_st.A", offsetof(struct RIPEMD160state_st, A));
    printf("offsetof\t%s\t%zu\n", "struct RIPEMD160state_st.B", offsetof(struct RIPEMD160state_st, B));
    printf("offsetof\t%s\t%zu\n", "struct RIPEMD160state_st.C", offsetof(struct RIPEMD160state_st, C));
    printf("offsetof\t%s\t%zu\n", "struct RIPEMD160state_st.D", offsetof(struct RIPEMD160state_st, D));
    printf("offsetof\t%s\t%zu\n", "struct RIPEMD160state_st.E", offsetof(struct RIPEMD160state_st, E));
    printf("offsetof\t%s\t%zu\n", "struct RIPEMD160state_st.Nh", offsetof(struct RIPEMD160state_st, Nh));
    printf("offsetof\t%s\t%zu\n", "struct RIPEMD160state_st.Nl", offsetof(struct RIPEMD160state_st, Nl));
    printf("offsetof\t%s\t%zu\n", "struct RIPEMD160state_st.data", offsetof(struct RIPEMD160state_st, data));
    printf("offsetof\t%s\t%zu\n", "struct RIPEMD160state_st.num", offsetof(struct RIPEMD160state_st, num));
    printf("offsetof\t%s\t%zu\n", "struct SCRYPT_PARAMS_st.blockSize", offsetof(struct SCRYPT_PARAMS_st, blockSize));
    printf("offsetof\t%s\t%zu\n", "struct SCRYPT_PARAMS_st.costParameter", offsetof(struct SCRYPT_PARAMS_st, costParameter));
    printf("offsetof\t%s\t%zu\n", "struct SCRYPT_PARAMS_st.keyLength", offsetof(struct SCRYPT_PARAMS_st, keyLength));
    printf("offsetof\t%s\t%zu\n", "struct SCRYPT_PARAMS_st.parallelizationParameter", offsetof(struct SCRYPT_PARAMS_st, parallelizationParameter));
    printf("offsetof\t%s\t%zu\n", "struct SCRYPT_PARAMS_st.salt", offsetof(struct SCRYPT_PARAMS_st, salt));
    printf("offsetof\t%s\t%zu\n", "struct SHA256state_st.Nh", offsetof(struct SHA256state_st, Nh));
    printf("offsetof\t%s\t%zu\n", "struct SHA256state_st.Nl", offsetof(struct SHA256state_st, Nl));
    printf("offsetof\t%s\t%zu\n", "struct SHA256state_st.data", offsetof(struct SHA256state_st, data));
    printf("offsetof\t%s\t%zu\n", "struct SHA256state_st.h", offsetof(struct SHA256state_st, h));
    printf("offsetof\t%s\t%zu\n", "struct SHA256state_st.md_len", offsetof(struct SHA256state_st, md_len));
    printf("offsetof\t%s\t%zu\n", "struct SHA256state_st.num", offsetof(struct SHA256state_st, num));
    printf("offsetof\t%s\t%zu\n", "struct SHA512state_st.Nh", offsetof(struct SHA512state_st, Nh));
    printf("offsetof\t%s\t%zu\n", "struct SHA512state_st.Nl", offsetof(struct SHA512state_st, Nl));
    printf("offsetof\t%s\t%zu\n", "struct SHA512state_st.h", offsetof(struct SHA512state_st, h));
    printf("offsetof\t%s\t%zu\n", "struct SHA512state_st.md_len", offsetof(struct SHA512state_st, md_len));
    printf("offsetof\t%s\t%zu\n", "struct SHA512state_st.num", offsetof(struct SHA512state_st, num));
    printf("offsetof\t%s\t%zu\n", "struct SHA512state_st.u", offsetof(struct SHA512state_st, u));
    printf("offsetof\t%s\t%zu\n", "struct SHAstate_st.Nh", offsetof(struct SHAstate_st, Nh));
    printf("offsetof\t%s\t%zu\n", "struct SHAstate_st.Nl", offsetof(struct SHAstate_st, Nl));
    printf("offsetof\t%s\t%zu\n", "struct SHAstate_st.data", offsetof(struct SHAstate_st, data));
    printf("offsetof\t%s\t%zu\n", "struct SHAstate_st.h0", offsetof(struct SHAstate_st, h0));
    printf("offsetof\t%s\t%zu\n", "struct SHAstate_st.h1", offsetof(struct SHAstate_st, h1));
    printf("offsetof\t%s\t%zu\n", "struct SHAstate_st.h2", offsetof(struct SHAstate_st, h2));
    printf("offsetof\t%s\t%zu\n", "struct SHAstate_st.h3", offsetof(struct SHAstate_st, h3));
    printf("offsetof\t%s\t%zu\n", "struct SHAstate_st.h4", offsetof(struct SHAstate_st, h4));
    printf("offsetof\t%s\t%zu\n", "struct SHAstate_st.num", offsetof(struct SHAstate_st, num));
    printf("offsetof\t%s\t%zu\n", "struct SRP_VBASE_st.default_N", offsetof(struct SRP_VBASE_st, default_N));
    printf("offsetof\t%s\t%zu\n", "struct SRP_VBASE_st.default_g", offsetof(struct SRP_VBASE_st, default_g));
    printf("offsetof\t%s\t%zu\n", "struct SRP_VBASE_st.gN_cache", offsetof(struct SRP_VBASE_st, gN_cache));
    printf("offsetof\t%s\t%zu\n", "struct SRP_VBASE_st.seed_key", offsetof(struct SRP_VBASE_st, seed_key));
    printf("offsetof\t%s\t%zu\n", "struct SRP_VBASE_st.users_pwd", offsetof(struct SRP_VBASE_st, users_pwd));
    printf("offsetof\t%s\t%zu\n", "struct SRP_gN_cache_st.b64_bn", offsetof(struct SRP_gN_cache_st, b64_bn));
    printf("offsetof\t%s\t%zu\n", "struct SRP_gN_cache_st.bn", offsetof(struct SRP_gN_cache_st, bn));
    printf("offsetof\t%s\t%zu\n", "struct SRP_gN_st.N", offsetof(struct SRP_gN_st, N));
    printf("offsetof\t%s\t%zu\n", "struct SRP_gN_st.g", offsetof(struct SRP_gN_st, g));
    printf("offsetof\t%s\t%zu\n", "struct SRP_gN_st.id", offsetof(struct SRP_gN_st, id));
    printf("offsetof\t%s\t%zu\n", "struct SRP_user_pwd_st.N", offsetof(struct SRP_user_pwd_st, N));
    printf("offsetof\t%s\t%zu\n", "struct SRP_user_pwd_st.g", offsetof(struct SRP_user_pwd_st, g));
    printf("offsetof\t%s\t%zu\n", "struct SRP_user_pwd_st.id", offsetof(struct SRP_user_pwd_st, id));
    printf("offsetof\t%s\t%zu\n", "struct SRP_user_pwd_st.info", offsetof(struct SRP_user_pwd_st, info));
    printf("offsetof\t%s\t%zu\n", "struct SRP_user_pwd_st.s", offsetof(struct SRP_user_pwd_st, s));
    printf("offsetof\t%s\t%zu\n", "struct SRP_user_pwd_st.v", offsetof(struct SRP_user_pwd_st, v));
    printf("offsetof\t%s\t%zu\n", "struct SXNET_ID_st.user", offsetof(struct SXNET_ID_st, user));
    printf("offsetof\t%s\t%zu\n", "struct SXNET_ID_st.zone", offsetof(struct SXNET_ID_st, zone));
    printf("offsetof\t%s\t%zu\n", "struct SXNET_st.ids", offsetof(struct SXNET_st, ids));
    printf("offsetof\t%s\t%zu\n", "struct SXNET_st.version", offsetof(struct SXNET_st, version));
    printf("offsetof\t%s\t%zu\n", "struct TARGET_CERT_st.certDigestInfo", offsetof(struct TARGET_CERT_st, certDigestInfo));
    printf("offsetof\t%s\t%zu\n", "struct TARGET_CERT_st.targetCertificate", offsetof(struct TARGET_CERT_st, targetCertificate));
    printf("offsetof\t%s\t%zu\n", "struct TARGET_CERT_st.targetName", offsetof(struct TARGET_CERT_st, targetName));
    printf("offsetof\t%s\t%zu\n", "struct TARGET_st.choice", offsetof(struct TARGET_st, choice));
    printf("offsetof\t%s\t%zu\n", "struct TARGET_st.type", offsetof(struct TARGET_st, type));
    printf("offsetof\t%s\t%zu\n", "struct USERNOTICE_st.exptext", offsetof(struct USERNOTICE_st, exptext));
    printf("offsetof\t%s\t%zu\n", "struct USERNOTICE_st.noticeref", offsetof(struct USERNOTICE_st, noticeref));
    printf("offsetof\t%s\t%zu\n", "struct X509V3_CONF_METHOD_st.free_section", offsetof(struct X509V3_CONF_METHOD_st, free_section));
    printf("offsetof\t%s\t%zu\n", "struct X509V3_CONF_METHOD_st.free_string", offsetof(struct X509V3_CONF_METHOD_st, free_string));
    printf("offsetof\t%s\t%zu\n", "struct X509V3_CONF_METHOD_st.get_section", offsetof(struct X509V3_CONF_METHOD_st, get_section));
    printf("offsetof\t%s\t%zu\n", "struct X509V3_CONF_METHOD_st.get_string", offsetof(struct X509V3_CONF_METHOD_st, get_string));
    printf("offsetof\t%s\t%zu\n", "struct X509_algor_st.algorithm", offsetof(struct X509_algor_st, algorithm));
    printf("offsetof\t%s\t%zu\n", "struct X509_algor_st.parameter", offsetof(struct X509_algor_st, parameter));
    printf("offsetof\t%s\t%zu\n", "struct X509_info_st.crl", offsetof(struct X509_info_st, crl));
    printf("offsetof\t%s\t%zu\n", "struct X509_info_st.enc_cipher", offsetof(struct X509_info_st, enc_cipher));
    printf("offsetof\t%s\t%zu\n", "struct X509_info_st.enc_data", offsetof(struct X509_info_st, enc_data));
    printf("offsetof\t%s\t%zu\n", "struct X509_info_st.enc_len", offsetof(struct X509_info_st, enc_len));
    printf("offsetof\t%s\t%zu\n", "struct X509_info_st.x509", offsetof(struct X509_info_st, x509));
    printf("offsetof\t%s\t%zu\n", "struct X509_info_st.x_pkey", offsetof(struct X509_info_st, x_pkey));
    printf("offsetof\t%s\t%zu\n", "struct X509_val_st.notAfter", offsetof(struct X509_val_st, notAfter));
    printf("offsetof\t%s\t%zu\n", "struct X509_val_st.notBefore", offsetof(struct X509_val_st, notBefore));
    printf("offsetof\t%s\t%zu\n", "struct aes_key_st.rd_key", offsetof(struct aes_key_st, rd_key));
    printf("offsetof\t%s\t%zu\n", "struct aes_key_st.rounds", offsetof(struct aes_key_st, rounds));
    printf("offsetof\t%s\t%zu\n", "struct asn1_string_st.data", offsetof(struct asn1_string_st, data));
    printf("offsetof\t%s\t%zu\n", "struct asn1_string_st.flags", offsetof(struct asn1_string_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct asn1_string_st.length", offsetof(struct asn1_string_st, length));
    printf("offsetof\t%s\t%zu\n", "struct asn1_string_st.type", offsetof(struct asn1_string_st, type));
    printf("offsetof\t%s\t%zu\n", "struct asn1_string_table_st.flags", offsetof(struct asn1_string_table_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct asn1_string_table_st.mask", offsetof(struct asn1_string_table_st, mask));
    printf("offsetof\t%s\t%zu\n", "struct asn1_string_table_st.maxsize", offsetof(struct asn1_string_table_st, maxsize));
    printf("offsetof\t%s\t%zu\n", "struct asn1_string_table_st.minsize", offsetof(struct asn1_string_table_st, minsize));
    printf("offsetof\t%s\t%zu\n", "struct asn1_string_table_st.nid", offsetof(struct asn1_string_table_st, nid));
    printf("offsetof\t%s\t%zu\n", "struct asn1_type_st.type", offsetof(struct asn1_type_st, type));
    printf("offsetof\t%s\t%zu\n", "struct asn1_type_st.value", offsetof(struct asn1_type_st, value));
    printf("offsetof\t%s\t%zu\n", "struct atav_st.type", offsetof(struct atav_st, type));
    printf("offsetof\t%s\t%zu\n", "struct atav_st.value", offsetof(struct atav_st, value));
    printf("offsetof\t%s\t%zu\n", "struct bf_key_st.P", offsetof(struct bf_key_st, P));
    printf("offsetof\t%s\t%zu\n", "struct bf_key_st.S", offsetof(struct bf_key_st, S));
    printf("offsetof\t%s\t%zu\n", "struct bio_mmsg_cb_args_st.flags", offsetof(struct bio_mmsg_cb_args_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct bio_mmsg_cb_args_st.msg", offsetof(struct bio_mmsg_cb_args_st, msg));
    printf("offsetof\t%s\t%zu\n", "struct bio_mmsg_cb_args_st.msgs_processed", offsetof(struct bio_mmsg_cb_args_st, msgs_processed));
    printf("offsetof\t%s\t%zu\n", "struct bio_mmsg_cb_args_st.num_msg", offsetof(struct bio_mmsg_cb_args_st, num_msg));
    printf("offsetof\t%s\t%zu\n", "struct bio_mmsg_cb_args_st.stride", offsetof(struct bio_mmsg_cb_args_st, stride));
    printf("offsetof\t%s\t%zu\n", "struct bio_msg_st.data", offsetof(struct bio_msg_st, data));
    printf("offsetof\t%s\t%zu\n", "struct bio_msg_st.data_len", offsetof(struct bio_msg_st, data_len));
    printf("offsetof\t%s\t%zu\n", "struct bio_msg_st.flags", offsetof(struct bio_msg_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct bio_msg_st.local", offsetof(struct bio_msg_st, local));
    printf("offsetof\t%s\t%zu\n", "struct bio_msg_st.peer", offsetof(struct bio_msg_st, peer));
    printf("offsetof\t%s\t%zu\n", "struct bio_poll_descriptor_st.type", offsetof(struct bio_poll_descriptor_st, type));
    printf("offsetof\t%s\t%zu\n", "struct bio_poll_descriptor_st.value", offsetof(struct bio_poll_descriptor_st, value));
    printf("offsetof\t%s\t%zu\n", "struct buf_mem_st.data", offsetof(struct buf_mem_st, data));
    printf("offsetof\t%s\t%zu\n", "struct buf_mem_st.flags", offsetof(struct buf_mem_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct buf_mem_st.length", offsetof(struct buf_mem_st, length));
    printf("offsetof\t%s\t%zu\n", "struct buf_mem_st.max", offsetof(struct buf_mem_st, max));
    printf("offsetof\t%s\t%zu\n", "struct camellia_key_st.grand_rounds", offsetof(struct camellia_key_st, grand_rounds));
    printf("offsetof\t%s\t%zu\n", "struct camellia_key_st.u", offsetof(struct camellia_key_st, u));
    printf("offsetof\t%s\t%zu\n", "struct cast_key_st.data", offsetof(struct cast_key_st, data));
    printf("offsetof\t%s\t%zu\n", "struct cast_key_st.short_key", offsetof(struct cast_key_st, short_key));
    printf("offsetof\t%s\t%zu\n", "struct conf_method_st.create", offsetof(struct conf_method_st, create));
    printf("offsetof\t%s\t%zu\n", "struct conf_method_st.destroy", offsetof(struct conf_method_st, destroy));
    printf("offsetof\t%s\t%zu\n", "struct conf_method_st.destroy_data", offsetof(struct conf_method_st, destroy_data));
    printf("offsetof\t%s\t%zu\n", "struct conf_method_st.dump", offsetof(struct conf_method_st, dump));
    printf("offsetof\t%s\t%zu\n", "struct conf_method_st.init", offsetof(struct conf_method_st, init));
    printf("offsetof\t%s\t%zu\n", "struct conf_method_st.is_number", offsetof(struct conf_method_st, is_number));
    printf("offsetof\t%s\t%zu\n", "struct conf_method_st.load", offsetof(struct conf_method_st, load));
    printf("offsetof\t%s\t%zu\n", "struct conf_method_st.load_bio", offsetof(struct conf_method_st, load_bio));
    printf("offsetof\t%s\t%zu\n", "struct conf_method_st.name", offsetof(struct conf_method_st, name));
    printf("offsetof\t%s\t%zu\n", "struct conf_method_st.to_int", offsetof(struct conf_method_st, to_int));
    printf("offsetof\t%s\t%zu\n", "struct conf_st.data", offsetof(struct conf_st, data));
    printf("offsetof\t%s\t%zu\n", "struct conf_st.flag_abspath", offsetof(struct conf_st, flag_abspath));
    printf("offsetof\t%s\t%zu\n", "struct conf_st.flag_dollarid", offsetof(struct conf_st, flag_dollarid));
    printf("offsetof\t%s\t%zu\n", "struct conf_st.includedir", offsetof(struct conf_st, includedir));
    printf("offsetof\t%s\t%zu\n", "struct conf_st.libctx", offsetof(struct conf_st, libctx));
    printf("offsetof\t%s\t%zu\n", "struct conf_st.meth", offsetof(struct conf_st, meth));
    printf("offsetof\t%s\t%zu\n", "struct conf_st.meth_data", offsetof(struct conf_st, meth_data));
    printf("offsetof\t%s\t%zu\n", "struct crypto_ex_data_st.ctx", offsetof(struct crypto_ex_data_st, ctx));
    printf("offsetof\t%s\t%zu\n", "struct crypto_ex_data_st.sk", offsetof(struct crypto_ex_data_st, sk));
    printf("offsetof\t%s\t%zu\n", "struct crypto_threadid_st.dummy", offsetof(struct crypto_threadid_st, dummy));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.bottom", offsetof(struct err_state_st, bottom));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.err_buffer", offsetof(struct err_state_st, err_buffer));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.err_data", offsetof(struct err_state_st, err_data));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.err_data_flags", offsetof(struct err_state_st, err_data_flags));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.err_data_size", offsetof(struct err_state_st, err_data_size));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.err_file", offsetof(struct err_state_st, err_file));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.err_flags", offsetof(struct err_state_st, err_flags));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.err_func", offsetof(struct err_state_st, err_func));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.err_line", offsetof(struct err_state_st, err_line));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.err_marks", offsetof(struct err_state_st, err_marks));
    printf("offsetof\t%s\t%zu\n", "struct err_state_st.top", offsetof(struct err_state_st, top));
    printf("offsetof\t%s\t%zu\n", "struct evp_cipher_info_st.cipher", offsetof(struct evp_cipher_info_st, cipher));
    printf("offsetof\t%s\t%zu\n", "struct evp_cipher_info_st.iv", offsetof(struct evp_cipher_info_st, iv));
    printf("offsetof\t%s\t%zu\n", "struct idea_key_st.data", offsetof(struct idea_key_st, data));
    printf("offsetof\t%s\t%zu\n", "struct lhash_st_CONF_VALUE.dummy", offsetof(struct lhash_st_CONF_VALUE, dummy));
    printf("offsetof\t%s\t%zu\n", "struct lhash_st_ERR_STRING_DATA.dummy", offsetof(struct lhash_st_ERR_STRING_DATA, dummy));
    printf("offsetof\t%s\t%zu\n", "struct lhash_st_OPENSSL_CSTRING.dummy", offsetof(struct lhash_st_OPENSSL_CSTRING, dummy));
    printf("offsetof\t%s\t%zu\n", "struct lhash_st_OPENSSL_STRING.dummy", offsetof(struct lhash_st_OPENSSL_STRING, dummy));
    printf("offsetof\t%s\t%zu\n", "struct mdc2_ctx_st.data", offsetof(struct mdc2_ctx_st, data));
    printf("offsetof\t%s\t%zu\n", "struct mdc2_ctx_st.h", offsetof(struct mdc2_ctx_st, h));
    printf("offsetof\t%s\t%zu\n", "struct mdc2_ctx_st.hh", offsetof(struct mdc2_ctx_st, hh));
    printf("offsetof\t%s\t%zu\n", "struct mdc2_ctx_st.num", offsetof(struct mdc2_ctx_st, num));
    printf("offsetof\t%s\t%zu\n", "struct mdc2_ctx_st.pad_type", offsetof(struct mdc2_ctx_st, pad_type));
    printf("offsetof\t%s\t%zu\n", "struct obj_name_st.alias", offsetof(struct obj_name_st, alias));
    printf("offsetof\t%s\t%zu\n", "struct obj_name_st.data", offsetof(struct obj_name_st, data));
    printf("offsetof\t%s\t%zu\n", "struct obj_name_st.name", offsetof(struct obj_name_st, name));
    printf("offsetof\t%s\t%zu\n", "struct obj_name_st.type", offsetof(struct obj_name_st, type));
    printf("offsetof\t%s\t%zu\n", "struct ossl_algorithm_st.algorithm_description", offsetof(struct ossl_algorithm_st, algorithm_description));
    printf("offsetof\t%s\t%zu\n", "struct ossl_algorithm_st.algorithm_names", offsetof(struct ossl_algorithm_st, algorithm_names));
    printf("offsetof\t%s\t%zu\n", "struct ossl_algorithm_st.implementation", offsetof(struct ossl_algorithm_st, implementation));
    printf("offsetof\t%s\t%zu\n", "struct ossl_algorithm_st.property_definition", offsetof(struct ossl_algorithm_st, property_definition));
    printf("offsetof\t%s\t%zu\n", "struct ossl_dispatch_st.function", offsetof(struct ossl_dispatch_st, function));
    printf("offsetof\t%s\t%zu\n", "struct ossl_dispatch_st.function_id", offsetof(struct ossl_dispatch_st, function_id));
    printf("offsetof\t%s\t%zu\n", "struct ossl_item_st.id", offsetof(struct ossl_item_st, id));
    printf("offsetof\t%s\t%zu\n", "struct ossl_item_st.ptr", offsetof(struct ossl_item_st, ptr));
    printf("offsetof\t%s\t%zu\n", "struct ossl_param_st.data", offsetof(struct ossl_param_st, data));
    printf("offsetof\t%s\t%zu\n", "struct ossl_param_st.data_size", offsetof(struct ossl_param_st, data_size));
    printf("offsetof\t%s\t%zu\n", "struct ossl_param_st.data_type", offsetof(struct ossl_param_st, data_type));
    printf("offsetof\t%s\t%zu\n", "struct ossl_param_st.key", offsetof(struct ossl_param_st, key));
    printf("offsetof\t%s\t%zu\n", "struct ossl_param_st.return_size", offsetof(struct ossl_param_st, return_size));
    printf("offsetof\t%s\t%zu\n", "struct otherName_st.type_id", offsetof(struct otherName_st, type_id));
    printf("offsetof\t%s\t%zu\n", "struct otherName_st.value", offsetof(struct otherName_st, value));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_digest_st.contents", offsetof(struct pkcs7_digest_st, contents));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_digest_st.digest", offsetof(struct pkcs7_digest_st, digest));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_digest_st.md", offsetof(struct pkcs7_digest_st, md));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_digest_st.version", offsetof(struct pkcs7_digest_st, version));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_enc_content_st.algorithm", offsetof(struct pkcs7_enc_content_st, algorithm));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_enc_content_st.cipher", offsetof(struct pkcs7_enc_content_st, cipher));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_enc_content_st.content_type", offsetof(struct pkcs7_enc_content_st, content_type));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_enc_content_st.ctx", offsetof(struct pkcs7_enc_content_st, ctx));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_enc_content_st.enc_data", offsetof(struct pkcs7_enc_content_st, enc_data));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_encrypted_st.enc_data", offsetof(struct pkcs7_encrypted_st, enc_data));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_encrypted_st.version", offsetof(struct pkcs7_encrypted_st, version));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_enveloped_st.enc_data", offsetof(struct pkcs7_enveloped_st, enc_data));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_enveloped_st.recipientinfo", offsetof(struct pkcs7_enveloped_st, recipientinfo));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_enveloped_st.version", offsetof(struct pkcs7_enveloped_st, version));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_issuer_and_serial_st.issuer", offsetof(struct pkcs7_issuer_and_serial_st, issuer));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_issuer_and_serial_st.serial", offsetof(struct pkcs7_issuer_and_serial_st, serial));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_recip_info_st.cert", offsetof(struct pkcs7_recip_info_st, cert));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_recip_info_st.ctx", offsetof(struct pkcs7_recip_info_st, ctx));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_recip_info_st.enc_key", offsetof(struct pkcs7_recip_info_st, enc_key));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_recip_info_st.issuer_and_serial", offsetof(struct pkcs7_recip_info_st, issuer_and_serial));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_recip_info_st.key_enc_algor", offsetof(struct pkcs7_recip_info_st, key_enc_algor));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_recip_info_st.version", offsetof(struct pkcs7_recip_info_st, version));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signed_st.cert", offsetof(struct pkcs7_signed_st, cert));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signed_st.contents", offsetof(struct pkcs7_signed_st, contents));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signed_st.crl", offsetof(struct pkcs7_signed_st, crl));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signed_st.md_algs", offsetof(struct pkcs7_signed_st, md_algs));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signed_st.signer_info", offsetof(struct pkcs7_signed_st, signer_info));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signed_st.version", offsetof(struct pkcs7_signed_st, version));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signedandenveloped_st.cert", offsetof(struct pkcs7_signedandenveloped_st, cert));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signedandenveloped_st.crl", offsetof(struct pkcs7_signedandenveloped_st, crl));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signedandenveloped_st.enc_data", offsetof(struct pkcs7_signedandenveloped_st, enc_data));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signedandenveloped_st.md_algs", offsetof(struct pkcs7_signedandenveloped_st, md_algs));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signedandenveloped_st.recipientinfo", offsetof(struct pkcs7_signedandenveloped_st, recipientinfo));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signedandenveloped_st.signer_info", offsetof(struct pkcs7_signedandenveloped_st, signer_info));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signedandenveloped_st.version", offsetof(struct pkcs7_signedandenveloped_st, version));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signer_info_st.auth_attr", offsetof(struct pkcs7_signer_info_st, auth_attr));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signer_info_st.ctx", offsetof(struct pkcs7_signer_info_st, ctx));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signer_info_st.digest_alg", offsetof(struct pkcs7_signer_info_st, digest_alg));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signer_info_st.digest_enc_alg", offsetof(struct pkcs7_signer_info_st, digest_enc_alg));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signer_info_st.enc_digest", offsetof(struct pkcs7_signer_info_st, enc_digest));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signer_info_st.issuer_and_serial", offsetof(struct pkcs7_signer_info_st, issuer_and_serial));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signer_info_st.pkey", offsetof(struct pkcs7_signer_info_st, pkey));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signer_info_st.unauth_attr", offsetof(struct pkcs7_signer_info_st, unauth_attr));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_signer_info_st.version", offsetof(struct pkcs7_signer_info_st, version));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_st.asn1", offsetof(struct pkcs7_st, asn1));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_st.ctx", offsetof(struct pkcs7_st, ctx));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_st.d", offsetof(struct pkcs7_st, d));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_st.detached", offsetof(struct pkcs7_st, detached));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_st.length", offsetof(struct pkcs7_st, length));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_st.state", offsetof(struct pkcs7_st, state));
    printf("offsetof\t%s\t%zu\n", "struct pkcs7_st.type", offsetof(struct pkcs7_st, type));
    printf("offsetof\t%s\t%zu\n", "struct private_key_st.cipher", offsetof(struct private_key_st, cipher));
    printf("offsetof\t%s\t%zu\n", "struct private_key_st.dec_pkey", offsetof(struct private_key_st, dec_pkey));
    printf("offsetof\t%s\t%zu\n", "struct private_key_st.enc_algor", offsetof(struct private_key_st, enc_algor));
    printf("offsetof\t%s\t%zu\n", "struct private_key_st.enc_pkey", offsetof(struct private_key_st, enc_pkey));
    printf("offsetof\t%s\t%zu\n", "struct private_key_st.key_data", offsetof(struct private_key_st, key_data));
    printf("offsetof\t%s\t%zu\n", "struct private_key_st.key_free", offsetof(struct private_key_st, key_free));
    printf("offsetof\t%s\t%zu\n", "struct private_key_st.key_length", offsetof(struct private_key_st, key_length));
    printf("offsetof\t%s\t%zu\n", "struct private_key_st.version", offsetof(struct private_key_st, version));
    printf("offsetof\t%s\t%zu\n", "struct rand_meth_st.add", offsetof(struct rand_meth_st, add));
    printf("offsetof\t%s\t%zu\n", "struct rand_meth_st.bytes", offsetof(struct rand_meth_st, bytes));
    printf("offsetof\t%s\t%zu\n", "struct rand_meth_st.cleanup", offsetof(struct rand_meth_st, cleanup));
    printf("offsetof\t%s\t%zu\n", "struct rand_meth_st.pseudorand", offsetof(struct rand_meth_st, pseudorand));
    printf("offsetof\t%s\t%zu\n", "struct rand_meth_st.seed", offsetof(struct rand_meth_st, seed));
    printf("offsetof\t%s\t%zu\n", "struct rand_meth_st.status", offsetof(struct rand_meth_st, status));
    printf("offsetof\t%s\t%zu\n", "struct rc2_key_st.data", offsetof(struct rc2_key_st, data));
    printf("offsetof\t%s\t%zu\n", "struct rc4_key_st.data", offsetof(struct rc4_key_st, data));
    printf("offsetof\t%s\t%zu\n", "struct rc4_key_st.x", offsetof(struct rc4_key_st, x));
    printf("offsetof\t%s\t%zu\n", "struct rc4_key_st.y", offsetof(struct rc4_key_st, y));
    printf("offsetof\t%s\t%zu\n", "struct rsa_oaep_params_st.hashFunc", offsetof(struct rsa_oaep_params_st, hashFunc));
    printf("offsetof\t%s\t%zu\n", "struct rsa_oaep_params_st.maskGenFunc", offsetof(struct rsa_oaep_params_st, maskGenFunc));
    printf("offsetof\t%s\t%zu\n", "struct rsa_oaep_params_st.maskHash", offsetof(struct rsa_oaep_params_st, maskHash));
    printf("offsetof\t%s\t%zu\n", "struct rsa_oaep_params_st.pSourceFunc", offsetof(struct rsa_oaep_params_st, pSourceFunc));
    printf("offsetof\t%s\t%zu\n", "struct rsa_pss_params_st.hashAlgorithm", offsetof(struct rsa_pss_params_st, hashAlgorithm));
    printf("offsetof\t%s\t%zu\n", "struct rsa_pss_params_st.maskGenAlgorithm", offsetof(struct rsa_pss_params_st, maskGenAlgorithm));
    printf("offsetof\t%s\t%zu\n", "struct rsa_pss_params_st.maskHash", offsetof(struct rsa_pss_params_st, maskHash));
    printf("offsetof\t%s\t%zu\n", "struct rsa_pss_params_st.saltLength", offsetof(struct rsa_pss_params_st, saltLength));
    printf("offsetof\t%s\t%zu\n", "struct rsa_pss_params_st.trailerField", offsetof(struct rsa_pss_params_st, trailerField));
    printf("offsetof\t%s\t%zu\n", "struct seed_key_st.data", offsetof(struct seed_key_st, data));
    printf("offsetof\t%s\t%zu\n", "struct srtp_protection_profile_st.id", offsetof(struct srtp_protection_profile_st, id));
    printf("offsetof\t%s\t%zu\n", "struct srtp_protection_profile_st.name", offsetof(struct srtp_protection_profile_st, name));
    printf("offsetof\t%s\t%zu\n", "struct ssl_conn_close_info_st.error_code", offsetof(struct ssl_conn_close_info_st, error_code));
    printf("offsetof\t%s\t%zu\n", "struct ssl_conn_close_info_st.flags", offsetof(struct ssl_conn_close_info_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct ssl_conn_close_info_st.frame_type", offsetof(struct ssl_conn_close_info_st, frame_type));
    printf("offsetof\t%s\t%zu\n", "struct ssl_conn_close_info_st.reason", offsetof(struct ssl_conn_close_info_st, reason));
    printf("offsetof\t%s\t%zu\n", "struct ssl_conn_close_info_st.reason_len", offsetof(struct ssl_conn_close_info_st, reason_len));
    printf("offsetof\t%s\t%zu\n", "struct ssl_poll_item_st.desc", offsetof(struct ssl_poll_item_st, desc));
    printf("offsetof\t%s\t%zu\n", "struct ssl_poll_item_st.events", offsetof(struct ssl_poll_item_st, events));
    printf("offsetof\t%s\t%zu\n", "struct ssl_poll_item_st.revents", offsetof(struct ssl_poll_item_st, revents));
    printf("offsetof\t%s\t%zu\n", "struct ssl_shutdown_ex_args_st.quic_error_code", offsetof(struct ssl_shutdown_ex_args_st, quic_error_code));
    printf("offsetof\t%s\t%zu\n", "struct ssl_shutdown_ex_args_st.quic_reason", offsetof(struct ssl_shutdown_ex_args_st, quic_reason));
    printf("offsetof\t%s\t%zu\n", "struct ssl_stream_reset_args_st.quic_error_code", offsetof(struct ssl_stream_reset_args_st, quic_error_code));
    printf("offsetof\t%s\t%zu\n", "struct st_dynamic_MEM_fns.free_fn", offsetof(struct st_dynamic_MEM_fns, free_fn));
    printf("offsetof\t%s\t%zu\n", "struct st_dynamic_MEM_fns.malloc_fn", offsetof(struct st_dynamic_MEM_fns, malloc_fn));
    printf("offsetof\t%s\t%zu\n", "struct st_dynamic_MEM_fns.realloc_fn", offsetof(struct st_dynamic_MEM_fns, realloc_fn));
    printf("offsetof\t%s\t%zu\n", "struct st_dynamic_fns.mem_fns", offsetof(struct st_dynamic_fns, mem_fns));
    printf("offsetof\t%s\t%zu\n", "struct st_dynamic_fns.static_state", offsetof(struct st_dynamic_fns, static_state));
    printf("offsetof\t%s\t%zu\n", "struct tls_session_ticket_ext_st.data", offsetof(struct tls_session_ticket_ext_st, data));
    printf("offsetof\t%s\t%zu\n", "struct tls_session_ticket_ext_st.length", offsetof(struct tls_session_ticket_ext_st, length));
    printf("offsetof\t%s\t%zu\n", "struct txt_db_st.arg1", offsetof(struct txt_db_st, arg1));
    printf("offsetof\t%s\t%zu\n", "struct txt_db_st.arg2", offsetof(struct txt_db_st, arg2));
    printf("offsetof\t%s\t%zu\n", "struct txt_db_st.arg_row", offsetof(struct txt_db_st, arg_row));
    printf("offsetof\t%s\t%zu\n", "struct txt_db_st.data", offsetof(struct txt_db_st, data));
    printf("offsetof\t%s\t%zu\n", "struct txt_db_st.error", offsetof(struct txt_db_st, error));
    printf("offsetof\t%s\t%zu\n", "struct txt_db_st.index", offsetof(struct txt_db_st, index));
    printf("offsetof\t%s\t%zu\n", "struct txt_db_st.num_fields", offsetof(struct txt_db_st, num_fields));
    printf("offsetof\t%s\t%zu\n", "struct txt_db_st.qual", offsetof(struct txt_db_st, qual));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_ctx.crl", offsetof(struct v3_ext_ctx, crl));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_ctx.db", offsetof(struct v3_ext_ctx, db));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_ctx.db_meth", offsetof(struct v3_ext_ctx, db_meth));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_ctx.flags", offsetof(struct v3_ext_ctx, flags));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_ctx.issuer_cert", offsetof(struct v3_ext_ctx, issuer_cert));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_ctx.issuer_pkey", offsetof(struct v3_ext_ctx, issuer_pkey));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_ctx.subject_cert", offsetof(struct v3_ext_ctx, subject_cert));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_ctx.subject_req", offsetof(struct v3_ext_ctx, subject_req));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.d2i", offsetof(struct v3_ext_method, d2i));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.ext_flags", offsetof(struct v3_ext_method, ext_flags));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.ext_free", offsetof(struct v3_ext_method, ext_free));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.ext_new", offsetof(struct v3_ext_method, ext_new));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.ext_nid", offsetof(struct v3_ext_method, ext_nid));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.i2d", offsetof(struct v3_ext_method, i2d));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.i2r", offsetof(struct v3_ext_method, i2r));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.i2s", offsetof(struct v3_ext_method, i2s));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.i2v", offsetof(struct v3_ext_method, i2v));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.it", offsetof(struct v3_ext_method, it));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.r2i", offsetof(struct v3_ext_method, r2i));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.s2i", offsetof(struct v3_ext_method, s2i));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.usr_data", offsetof(struct v3_ext_method, usr_data));
    printf("offsetof\t%s\t%zu\n", "struct v3_ext_method.v2i", offsetof(struct v3_ext_method, v2i));
    printf("offsetof\t%s\t%zu\n", "struct x509_purpose_st.check_purpose", offsetof(struct x509_purpose_st, check_purpose));
    printf("offsetof\t%s\t%zu\n", "struct x509_purpose_st.flags", offsetof(struct x509_purpose_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct x509_purpose_st.name", offsetof(struct x509_purpose_st, name));
    printf("offsetof\t%s\t%zu\n", "struct x509_purpose_st.purpose", offsetof(struct x509_purpose_st, purpose));
    printf("offsetof\t%s\t%zu\n", "struct x509_purpose_st.sname", offsetof(struct x509_purpose_st, sname));
    printf("offsetof\t%s\t%zu\n", "struct x509_purpose_st.trust", offsetof(struct x509_purpose_st, trust));
    printf("offsetof\t%s\t%zu\n", "struct x509_purpose_st.usr_data", offsetof(struct x509_purpose_st, usr_data));
    printf("offsetof\t%s\t%zu\n", "struct x509_trust_st.arg1", offsetof(struct x509_trust_st, arg1));
    printf("offsetof\t%s\t%zu\n", "struct x509_trust_st.arg2", offsetof(struct x509_trust_st, arg2));
    printf("offsetof\t%s\t%zu\n", "struct x509_trust_st.check_trust", offsetof(struct x509_trust_st, check_trust));
    printf("offsetof\t%s\t%zu\n", "struct x509_trust_st.flags", offsetof(struct x509_trust_st, flags));
    printf("offsetof\t%s\t%zu\n", "struct x509_trust_st.name", offsetof(struct x509_trust_st, name));
    printf("offsetof\t%s\t%zu\n", "struct x509_trust_st.trust", offsetof(struct x509_trust_st, trust));
    printf("offsetof\t%s\t%zu\n", "union BIO_sock_info_u.addr", offsetof(union BIO_sock_info_u, addr));
    printf("offsetof\t%s\t%zu\n", "union lh_CONF_VALUE_dummy.d1", offsetof(union lh_CONF_VALUE_dummy, d1));
    printf("offsetof\t%s\t%zu\n", "union lh_CONF_VALUE_dummy.d2", offsetof(union lh_CONF_VALUE_dummy, d2));
    printf("offsetof\t%s\t%zu\n", "union lh_CONF_VALUE_dummy.d3", offsetof(union lh_CONF_VALUE_dummy, d3));
    printf("offsetof\t%s\t%zu\n", "union lh_ERR_STRING_DATA_dummy.d1", offsetof(union lh_ERR_STRING_DATA_dummy, d1));
    printf("offsetof\t%s\t%zu\n", "union lh_ERR_STRING_DATA_dummy.d2", offsetof(union lh_ERR_STRING_DATA_dummy, d2));
    printf("offsetof\t%s\t%zu\n", "union lh_ERR_STRING_DATA_dummy.d3", offsetof(union lh_ERR_STRING_DATA_dummy, d3));
    printf("offsetof\t%s\t%zu\n", "union lh_OPENSSL_CSTRING_dummy.d1", offsetof(union lh_OPENSSL_CSTRING_dummy, d1));
    printf("offsetof\t%s\t%zu\n", "union lh_OPENSSL_CSTRING_dummy.d2", offsetof(union lh_OPENSSL_CSTRING_dummy, d2));
    printf("offsetof\t%s\t%zu\n", "union lh_OPENSSL_CSTRING_dummy.d3", offsetof(union lh_OPENSSL_CSTRING_dummy, d3));
    printf("offsetof\t%s\t%zu\n", "union lh_OPENSSL_STRING_dummy.d1", offsetof(union lh_OPENSSL_STRING_dummy, d1));
    printf("offsetof\t%s\t%zu\n", "union lh_OPENSSL_STRING_dummy.d2", offsetof(union lh_OPENSSL_STRING_dummy, d2));
    printf("offsetof\t%s\t%zu\n", "union lh_OPENSSL_STRING_dummy.d3", offsetof(union lh_OPENSSL_STRING_dummy, d3));
    return 0;
}
