//! Generated by forensics/tools/gen_abi_facades.py -- do not edit.
//!
//! The pre-1.1.0 public layouts of the 0.9.8zh compatibility generation. Each struct
//! is `#[repr(C)]` with the authority's own field order, and the `const _: ()`
//! assertions pin its size, alignment, every field offset and every field width to the
//! measurement in `forensics/multitrack/abi-facades.json`. A field reorder, width change
//! or padding change therefore fails to compile rather than silently reinterpreting a
//! historical object as a modern one.
//!
//! SPDX-License-Identifier: Apache-2.0
#![allow(dead_code)]

use core::ffi::{c_uchar, c_uint, c_ulong, c_void};

/// `struct env_md_ctx_st` — `EVP_MD_CTX`, `crypto/evp/evp.h`, at the
/// 0.9.8zh layout (transparent; opaque in `openssl-3.6.4-production`).
#[repr(C)]
pub struct FacadeEvpMdCtx {
    /// `const EVP_MD *` at offset 0.
    pub(crate) digest: *const crate::evp::digest::EvpMd,
    /// `ENGINE *` at offset 8.
    pub(crate) engine: *mut c_void,
    /// `unsigned long` at offset 16.
    pub(crate) flags: c_ulong,
    /// `void *` at offset 24.
    pub(crate) md_data: *mut c_void,
}

const _: () = {
    assert!(core::mem::size_of::<FacadeEvpMdCtx>() == 32);
    assert!(core::mem::align_of::<FacadeEvpMdCtx>() == 8);
    assert!(core::mem::offset_of!(FacadeEvpMdCtx, digest) == 0);
    assert!(core::mem::size_of::<*const crate::evp::digest::EvpMd>() == 8);
    assert!(core::mem::offset_of!(FacadeEvpMdCtx, engine) == 8);
    assert!(core::mem::size_of::<*mut c_void>() == 8);
    assert!(core::mem::offset_of!(FacadeEvpMdCtx, flags) == 16);
    assert!(core::mem::size_of::<c_ulong>() == 8);
    assert!(core::mem::offset_of!(FacadeEvpMdCtx, md_data) == 24);
    assert!(core::mem::size_of::<*mut c_void>() == 8);
};

/// `struct hmac_ctx_st` — `HMAC_CTX`, `crypto/hmac/hmac.h`, at the
/// 0.9.8zh layout (transparent; opaque in `openssl-3.6.4-production`).
#[repr(C)]
pub struct FacadeHmacCtx {
    /// `const EVP_MD *` at offset 0.
    pub(crate) md: *const crate::evp::digest::EvpMd,
    /// `EVP_MD_CTX` at offset 8.
    pub(crate) md_ctx: FacadeEvpMdCtx,
    /// `EVP_MD_CTX` at offset 40.
    pub(crate) i_ctx: FacadeEvpMdCtx,
    /// `EVP_MD_CTX` at offset 72.
    pub(crate) o_ctx: FacadeEvpMdCtx,
    /// `unsigned int` at offset 104.
    pub(crate) key_length: c_uint,
    /// `unsigned char []` at offset 108.
    pub(crate) key: [c_uchar; 128],
}

const _: () = {
    assert!(core::mem::size_of::<FacadeHmacCtx>() == 240);
    assert!(core::mem::align_of::<FacadeHmacCtx>() == 8);
    assert!(core::mem::offset_of!(FacadeHmacCtx, md) == 0);
    assert!(core::mem::size_of::<*const crate::evp::digest::EvpMd>() == 8);
    assert!(core::mem::offset_of!(FacadeHmacCtx, md_ctx) == 8);
    assert!(core::mem::size_of::<FacadeEvpMdCtx>() == 32);
    assert!(core::mem::offset_of!(FacadeHmacCtx, i_ctx) == 40);
    assert!(core::mem::size_of::<FacadeEvpMdCtx>() == 32);
    assert!(core::mem::offset_of!(FacadeHmacCtx, o_ctx) == 72);
    assert!(core::mem::size_of::<FacadeEvpMdCtx>() == 32);
    assert!(core::mem::offset_of!(FacadeHmacCtx, key_length) == 104);
    assert!(core::mem::size_of::<c_uint>() == 4);
    assert!(core::mem::offset_of!(FacadeHmacCtx, key) == 108);
    assert!(core::mem::size_of::<[c_uchar; 128]>() == 128);
};
