/*
 * RT-CIPHER-MEM -- which authority translation unit does each default-provider cipher row pass as
 * the `file` argument to a caller-installed allocator?
 *
 * Why this is a court of its own
 * ------------------------------
 * `CRYPTO_set_mem_functions`'s callbacks take `(size_t num, const char *file, int line)`, and all
 * three are part of the published contract: an embedder that installs an allocator receives them.
 * The crate had recorded `num` for every cipher context (`courts/layout/measure-*.c` and the size
 * test in `src/provider/cipher.rs`) but had never asked what `file` is, and the answer was wrong
 * for every row: one shared constant named `providers/implementations/ciphers/ciphercommon.c`,
 * which is a translation unit no row's allocation is in at all. The rows' context constructors are
 * generated by the `IMPLEMENT_generic_cipher` macro, which `prov/ciphercommon.h` *defines* but
 * `cipher_aes.c`, `cipher_camellia.c`, `cipher_tdes_common.c`, `cipher_sm4.c`, `cipher_aria.c` and
 * `cipher_idea.c` each *invoke*, so `__FILE__` inside an expanded body is the invoking file.
 *
 * **This cannot be an arm of `RT-CIPHER`.** `CRYPTO_set_mem_functions` latches: the first non-zero
 * allocation through the default path clears `allow_customize` for the life of the process, and a
 * later install returns 0. `rt_cipher_probe.c` allocates long before any of its cipher arms would
 * run, so the installation has to be the first thing this program does -- which is also why the
 * finding was made by a separate *oracle* program (`courts/layout/oracle-mem-file.c`) before it
 * could be a court.
 *
 * What is compared, and what is deliberately not
 * ----------------------------------------------
 * The transcript is the **set of distinct `file` strings that name a
 * `providers/implementations/ciphers/` translation unit**, in first-seen order, per row, inside a
 * window that starts after the fetch and ends after the context is released. Every other `file` in
 * the window -- `crypto/evp/`, `crypto/property/`, `crypto/lhash/` and the rest -- is excluded by
 * construction, because the crate's *EVP layer* is not what this court is about and comparing it
 * whole would turn one finding into an unbounded one. The exclusion is the claim's scope, and it is
 * stated rather than implied: what this court proves is that the row's own provider allocation is
 * attributed to the authority's own translation unit for that row.
 *
 * **No counts and no sizes are printed.** A count would compare allocation *strategy* rather than
 * allocation *origin*, and the two sides need not allocate the same number of times; the sizes are
 * already `courts/layout/measure-*.c`'s subject and the size test's. `EVP_CipherInit_ex2` is given a
 * key and no IV so that every row reaches its `newctx`, which is the allocation in question, even
 * where an init later refuses.
 */
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include <openssl/crypto.h>
#include <openssl/err.h>
#include <openssl/evp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MEM_MAX 32
#define MEM_NAME 400
#define CIPHER_TU "providers/implementations/ciphers/"

static char seen[MEM_MAX][MEM_NAME];
static int nseen;
static int recording;

static void note(const char *file)
{
    int i;

    if (!recording || file == NULL)
        return;
    for (i = 0; i < nseen; i++) {
        if (strcmp(seen[i], file) == 0)
            return;
    }
    if (nseen < MEM_MAX && strlen(file) < MEM_NAME) {
        strcpy(seen[nseen], file);
        nseen++;
    }
}

static void *my_malloc(size_t n, const char *file, int line)
{
    (void)line;
    note(file);
    return malloc(n);
}

static void *my_realloc(void *p, size_t n, const char *file, int line)
{
    (void)line;
    note(file);
    return realloc(p, n);
}

static void my_free(void *p, const char *file, int line)
{
    (void)line;
    note(file);
    free(p);
}

static void begin(void)
{
    nseen = 0;
    recording = 1;
}

/* Only the provider cipher translation units, in first-seen order. */
static void end(const char *row)
{
    int i, n = 0;

    recording = 0;
    for (i = 0; i < nseen; i++) {
        if (strstr(seen[i], CIPHER_TU) != NULL) {
            printf("mem.%s.%d=%s\n", row, n, seen[i]);
            n++;
        }
    }
    printf("mem.%s.count=%d\n", row, n);
}

/* The default provider's cipher census, in `defltprov.c` order. It mirrors
 * `rt_cipher_probe.c`'s list deliberately: a probe is a standalone translation unit
 * (`probe_hygiene.py` permits no shared header), so a row added to one and forgotten in
 * the other would silently stop being observed by this court. */
static const char *const rows[] = {
    "NULL",
    "AES-256-ECB",
    "AES-192-ECB",
    "AES-128-ECB",
    "AES-256-CBC",
    "AES-192-CBC",
    "AES-128-CBC",
    "AES-128-CBC-CTS",
    "AES-192-CBC-CTS",
    "AES-256-CBC-CTS",
    "AES-256-OFB",
    "AES-192-OFB",
    "AES-128-OFB",
    "AES-256-CFB",
    "AES-192-CFB",
    "AES-128-CFB",
    "AES-256-CFB1",
    "AES-192-CFB1",
    "AES-128-CFB1",
    "AES-256-CFB8",
    "AES-192-CFB8",
    "AES-128-CFB8",
    "AES-256-CTR",
    "AES-192-CTR",
    "AES-128-CTR",
    "AES-256-XTS",
    "AES-128-XTS",
    "AES-256-OCB",
    "AES-192-OCB",
    "AES-128-OCB",
    "AES-128-SIV",
    "AES-192-SIV",
    "AES-256-SIV",
    "AES-128-GCM-SIV",
    "AES-192-GCM-SIV",
    "AES-256-GCM-SIV",
    "AES-256-CCM",
    "AES-192-CCM",
    "AES-128-CCM",
    "AES-256-WRAP",
    "AES-192-WRAP",
    "AES-128-WRAP",
    "AES-256-WRAP-PAD",
    "AES-192-WRAP-PAD",
    "AES-128-WRAP-PAD",
    "AES-256-WRAP-INV",
    "AES-192-WRAP-INV",
    "AES-128-WRAP-INV",
    "AES-256-WRAP-PAD-INV",
    "AES-192-WRAP-PAD-INV",
    "AES-128-WRAP-PAD-INV",
    "AES-128-CBC-HMAC-SHA1",
    "AES-256-CBC-HMAC-SHA1",
    "AES-128-CBC-HMAC-SHA256",
    "AES-256-CBC-HMAC-SHA256",
    "AES-128-CBC-HMAC-SHA1-ETM",
    "AES-192-CBC-HMAC-SHA1-ETM",
    "AES-256-CBC-HMAC-SHA1-ETM",
    "AES-128-CBC-HMAC-SHA256-ETM",
    "AES-192-CBC-HMAC-SHA256-ETM",
    "AES-256-CBC-HMAC-SHA256-ETM",
    "AES-128-CBC-HMAC-SHA512-ETM",
    "AES-192-CBC-HMAC-SHA512-ETM",
    "AES-256-CBC-HMAC-SHA512-ETM",
    "ARIA-256-CCM",
    "ARIA-192-CCM",
    "ARIA-128-CCM",
    "ARIA-256-ECB",
    "ARIA-192-ECB",
    "ARIA-128-ECB",
    "ARIA-256-CBC",
    "ARIA-192-CBC",
    "ARIA-128-CBC",
    "ARIA-256-OFB",
    "ARIA-192-OFB",
    "ARIA-128-OFB",
    "ARIA-256-CFB",
    "ARIA-192-CFB",
    "ARIA-128-CFB",
    "ARIA-256-CFB1",
    "ARIA-192-CFB1",
    "ARIA-128-CFB1",
    "ARIA-256-CFB8",
    "ARIA-192-CFB8",
    "ARIA-128-CFB8",
    "ARIA-256-CTR",
    "ARIA-192-CTR",
    "ARIA-128-CTR",
    "CAMELLIA-256-ECB",
    "CAMELLIA-192-ECB",
    "CAMELLIA-128-ECB",
    "CAMELLIA-256-CBC",
    "CAMELLIA-192-CBC",
    "CAMELLIA-128-CBC",
    "CAMELLIA-128-CBC-CTS",
    "CAMELLIA-192-CBC-CTS",
    "CAMELLIA-256-CBC-CTS",
    "CAMELLIA-256-OFB",
    "CAMELLIA-192-OFB",
    "CAMELLIA-128-OFB",
    "CAMELLIA-256-CFB",
    "CAMELLIA-192-CFB",
    "CAMELLIA-128-CFB",
    "CAMELLIA-256-CFB1",
    "CAMELLIA-192-CFB1",
    "CAMELLIA-128-CFB1",
    "CAMELLIA-256-CFB8",
    "CAMELLIA-192-CFB8",
    "CAMELLIA-128-CFB8",
    "CAMELLIA-256-CTR",
    "CAMELLIA-192-CTR",
    "CAMELLIA-128-CTR",
    "DES-EDE3-ECB",
    "DES-EDE3-CBC",
    "DES-EDE3-OFB",
    "DES-EDE3-CFB",
    "DES-EDE3-CFB8",
    "DES-EDE3-CFB1",
    "DES-EDE-ECB",
    "DES-EDE-CBC",
    "DES-EDE-OFB",
    "DES-EDE-CFB",
    "SM4-CCM",
    "SM4-ECB",
    "SM4-CBC",
    "SM4-CTR",
    "SM4-OFB",
    "SM4-CFB",
    "SM4-XTS",
    "ChaCha20",
    "ChaCha20-Poly1305",
};

int main(void)
{
    static const unsigned char key[32] = { 0 };
    unsigned char out[64];
    int i, outl = 0;

    setvbuf(stdout, NULL, _IOLBF, 0);
    if (CRYPTO_set_mem_functions(my_malloc, my_realloc, my_free) != 1) {
        printf("mem.install=0\n");
        return 1;
    }
    printf("mem.install=1\n");

    for (i = 0; i < (int)(sizeof(rows) / sizeof(rows[0])); i++) {
        EVP_CIPHER *c = EVP_CIPHER_fetch(NULL, rows[i], NULL);
        EVP_CIPHER_CTX *ctx;

        printf("mem.%s.fetched=%d\n", rows[i], c != NULL);
        if (c == NULL)
            continue;

        begin();
        ctx = EVP_CIPHER_CTX_new();
        if (ctx != NULL) {
            ERR_clear_error();
            EVP_CipherInit_ex2(ctx, c, key, NULL, 1, NULL);
            ERR_clear_error();
            EVP_CipherUpdate(ctx, out, &outl, out, 0);
            ERR_clear_error();
            EVP_CIPHER_CTX_free(ctx);
        }
        EVP_CIPHER_free(c);
        end(rows[i]);
    }
    return 0;
}
