#!/bin/sh
exec /bin/sh /work/courts/phase17/rt_cli_bodies_probe.sh /work/forensics/authorities/prefix/openssl-3.6.4-production/bin/openssl /work/forensics/authorities/prefix/openssl-3.6.4-production/lib/ossl-modules
