/*
 * openssl-rs — the differential DRBG probe (RT-DRBG).
 *
 * This program is compiled **twice**, once against the admitted authority and once against the
 * candidate distribution shell, and the two `key=value` transcripts are diffed. It decides
 * nothing: a residual is a difference between two executions, so the expectation cannot drift
 * with the crate. `forensics/tools/phase9_courts.py` owns the comparison.
 *
 * What this probe establishes
 * ---------------------------
 * It is the evidence that the three DRBG rows the default provider publishes — `CTR-DRBG`,
 * `HASH-DRBG` and `HMAC-DRBG` — are **fetched, named, introspected, parameterised, instantiated,
 * driven and torn down the same way** on both sides. A fetch that resolves to a row whose
 * callbacks are wrong is worse than no fetch, so the fetch is only the first observation: the
 * settable/gettable parameter surface, the state machine and every refusal arm are observed too.
 *
 * Why the rows must be parameterised first
 * ----------------------------------------
 * None of the three rows carries a default algorithm: `drbg_ctr_new` allocates a context and
 * `drbg_ctr_init` refuses without a cipher (`PROV_R_MISSING_CIPHER`), `drbg_hash_new` refuses
 * without a digest (`EVP_R_NO_DIGEST_SET` from the front) and `drbg_hmac_new` refuses without a
 * MAC (`PROV_R_MISSING_MAC`). A probe that skipped `EVP_RAND_CTX_set_params` would therefore
 * measure the *refusal* path for all three and never touch the machine it exists to court -- and
 * it would look identical on both sides, which is exactly the kind of agreement that proves
 * nothing. So each row names its own algorithm set, and both the set and its refusal are observed.
 *
 * What it deliberately does not observe
 * -------------------------------------
 * **The generated bytes.** Entropy reaches a DRBG through the provider's own
 * `get_entropy`/`get_nonce` up-calls, not through `EVP_RAND_instantiate`'s arguments, so the
 * authority and the candidate seed from different pools and their outputs differ by
 * construction. Comparing them would compare two machines, which is why
 * `docs/PHASE-9-SUBPHASES.md` section 3.3 records output unpredictability as not courted. The
 * bytes are compared by `CT-DRBG`, against the pinned CAVP vectors, rather than here.
 *
 * What a difference here means
 * ----------------------------
 * Every observation is a return code, a state, a name, a parameter key/type pair, or an
 * `ERR_GET_LIB`/`ERR_GET_REASON` pair drained from the error queue. No address is ever printed
 * and no NULL-dereferencing entry point is called, so a probe that aborts the harness compares
 * nothing rather than comparing noise.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <stdio.h>
#include <string.h>

#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/params.h>
#include <openssl/provider.h>

/*
 * The three rows `deflt_rands[]` publishes for the DRBGs, in the authority's own table order, each
 * with the algorithm set its own `_initialize`/`_new` path requires.
 */
struct rowdef {
    const char *name;
    const char *cipher;
    const char *digest;
    const char *mac;
};

static const struct rowdef ROWS[] = {
    { "CTR-DRBG", "AES-256-CTR", NULL, NULL },
    { "HASH-DRBG", NULL, "SHA-256", NULL },
    { "HMAC-DRBG", NULL, "SHA-256", "HMAC" },
};
#define N_ROWS (sizeof(ROWS) / sizeof(ROWS[0]))

/* A strength no row can satisfy, for the refusal arm. */
#define TOO_STRONG 4096u

/*
 * The error queue, normalised to the two fields `docs/PARITY_MODEL.md`'s `ERROR_PASS` names as
 * portable: the library and the reason. The file/line/function coordinates are deliberately not
 * printed -- they are transcription-unit properties the error-site courts cover, and printing
 * them here would turn one behavioural residual into a coordinate diff.
 */
static void errs(const char *key)
{
    unsigned long e;
    int i = 0;

    while ((e = ERR_get_error()) != 0) {
        printf("%s.%d=lib=%d,reason=%d\n", key, i++, ERR_GET_LIB(e), ERR_GET_REASON(e));
    }
    printf("%s.count=%d\n", key, i);
}

/* An `OSSL_PARAM` list's keys and types, in order. A NULL list is itself an observation. */
static void params(const char *key, const OSSL_PARAM *p)
{
    int i = 0;

    if (p == NULL) {
        printf("%s=null\n", key);
        return;
    }
    for (; p->key != NULL; p++, i++)
        printf("%s.%d=%s:%d\n", key, i, p->key, p->data_type);
    printf("%s.count=%d\n", key, i);
}

/* The unsigned-integer entries of a name list, read back through the ctx's own get. */
static void uints(const char *key, EVP_RAND_CTX *ctx, const OSSL_PARAM *names)
{
    OSSL_PARAM params[16];
    unsigned int v[15];
    int i = 0, n = 0, rc;

    if (names == NULL) {
        printf("%s=null\n", key);
        return;
    }
    for (; names->key != NULL && i < 15; names++, i++) {
        if (names->data_type != OSSL_PARAM_UNSIGNED_INTEGER)
            continue;
        params[n] = OSSL_PARAM_construct_uint(names->key, &v[n]);
        n++;
    }
    params[n] = OSSL_PARAM_construct_end();
    rc = EVP_RAND_CTX_get_params(ctx, params);
    printf("%s.rc=%d\n", key, rc);
    for (i = 0; i < n; i++) {
        if (params[i].return_size != (size_t)-1)
            printf("%s.v.%s=%u\n", key, params[i].key, *(unsigned int *)params[i].data);
    }
}

/* One UTF-8 ctx parameter, which is how a row reports the algorithm it was given. */
static void utf8(const char *key, EVP_RAND_CTX *ctx, const char *param)
{
    char buf[64];
    OSSL_PARAM p[2];
    int rc;

    buf[0] = '\0';
    p[0] = OSSL_PARAM_construct_utf8_string(param, buf, sizeof(buf));
    p[1] = OSSL_PARAM_construct_end();
    rc = EVP_RAND_CTX_get_params(ctx, p);
    printf("%s.rc=%d\n", key, rc);
    printf("%s.v=%s\n", key, buf);
}

/* The row's own algorithm set, as the settable-params call it expects. */
static int set_algorithms(EVP_RAND_CTX *ctx, const struct rowdef *d)
{
    OSSL_PARAM p[4];
    int n = 0;

    if (d->cipher != NULL)
        p[n++] = OSSL_PARAM_construct_utf8_string("cipher", (char *)d->cipher, 0);
    if (d->digest != NULL)
        p[n++] = OSSL_PARAM_construct_utf8_string("digest", (char *)d->digest, 0);
    if (d->mac != NULL)
        p[n++] = OSSL_PARAM_construct_utf8_string("mac", (char *)d->mac, 0);
    p[n] = OSSL_PARAM_construct_end();
    return EVP_RAND_CTX_set_params(ctx, p);
}

/*
 * The two remaining `OSSL_OP_RAND` rows the **default** provider publishes: `SEED-SRC` (which the
 * base provider publishes too) and `TEST-RAND`. Neither is a DRBG, so neither needs an algorithm
 * set before it will instantiate; they differ from each other in one way that matters here.
 *
 * `SEED-SRC`'s generate polls the platform pool, so its **bytes are not observable** -- two
 * machines would disagree. Its return code, its states and its parameter surface are.
 *
 * `TEST-RAND` is the opposite and is the reason this stratum can court construction at all: once
 * `test_entropy` and `test_nonce` are set it is a pure function of them, so its 32 generated
 * bytes are compared **byte for byte**. That is the only place in this probe where an output is
 * an observation rather than a comparison of two entropy pools.
 */
static void non_drbg_row(const char *name, int is_test_rand)
{
    char k[200];
    EVP_RAND *r;
    EVP_RAND_CTX *ctx;
    unsigned char out[64];
    unsigned char ent[64];
    unsigned char nonce[16];
    size_t i;

    r = EVP_RAND_fetch(NULL, name, NULL);
    snprintf(k, sizeof(k), "fetch.%s", name);
    printf("%s=%d\n", k, r != NULL);
    if (r == NULL) {
        snprintf(k, sizeof(k), "fetch.err.%s", name);
        errs(k);
        return;
    }

    snprintf(k, sizeof(k), "name.%s", name);
    printf("%s=%s\n", k, EVP_RAND_get0_name(r));
    snprintf(k, sizeof(k), "is_a.%s.self", name);
    printf("%s=%d\n", k, EVP_RAND_is_a(r, name));
    snprintf(k, sizeof(k), "gettable.%s", name);
    params(k, EVP_RAND_gettable_params(r));

    ctx = EVP_RAND_CTX_new(r, NULL);
    snprintf(k, sizeof(k), "ctx.%s", name);
    printf("%s=%d\n", k, ctx != NULL);
    if (ctx == NULL) {
        EVP_RAND_free(r);
        return;
    }

    snprintf(k, sizeof(k), "state.new.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "ctxtable.%s", name);
    params(k, EVP_RAND_CTX_gettable_params(ctx));
    snprintf(k, sizeof(k), "settable.%s", name);
    params(k, EVP_RAND_CTX_settable_params(ctx));

    if (is_test_rand) {
        OSSL_PARAM p[3];

        for (i = 0; i < sizeof(ent); i++)
            ent[i] = (unsigned char)i;
        for (i = 0; i < sizeof(nonce); i++)
            nonce[i] = (unsigned char)(0xa0 + i);
        p[0] = OSSL_PARAM_construct_octet_string("test_entropy", ent, sizeof(ent));
        p[1] = OSSL_PARAM_construct_octet_string("test_nonce", nonce, sizeof(nonce));
        p[2] = OSSL_PARAM_construct_end();
        snprintf(k, sizeof(k), "set.%s", name);
        printf("%s=%d\n", k, EVP_RAND_CTX_set_params(ctx, p));
        snprintf(k, sizeof(k), "err.set.%s", name);
        errs(k);
    }

    snprintf(k, sizeof(k), "instantiate.%s", name);
    printf("%s=%d\n", k, EVP_RAND_instantiate(ctx, 0, 0, NULL, 0, NULL));
    snprintf(k, sizeof(k), "state.ready.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "strength.ready.%s", name);
    printf("%s=%u\n", k, EVP_RAND_get_strength(ctx));
    snprintf(k, sizeof(k), "err.instantiate.%s", name);
    errs(k);
    snprintf(k, sizeof(k), "uints.%s", name);
    uints(k, ctx, EVP_RAND_CTX_gettable_params(ctx));

    snprintf(k, sizeof(k), "generate.%s", name);
    printf("%s=%d\n", k, EVP_RAND_generate(ctx, out, sizeof(out), 0, 0, NULL, 0));
    snprintf(k, sizeof(k), "state.after.generate.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "err.generate.%s", name);
    errs(k);

    if (is_test_rand) {
        /* The one place an output is an observation: TEST-RAND is a function of its seed. */
        printf("bytes.%s=", name);
        for (i = 0; i < sizeof(out); i++)
            printf("%02x", out[i]);
        printf("\n");
    }

    snprintf(k, sizeof(k), "uninstantiate.%s", name);
    printf("%s=%d\n", k, EVP_RAND_uninstantiate(ctx));
    snprintf(k, sizeof(k), "state.uninstantiated.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "err.uninstantiate.%s", name);
    errs(k);

    EVP_RAND_CTX_free(ctx);
    EVP_RAND_free(r);
}

static void row(const struct rowdef *d)
{
    const char *name = d->name;
    char k[160];
    EVP_RAND *r;
    EVP_RAND_CTX *ctx, *strong;
    unsigned char out[64];
    size_t i;

    r = EVP_RAND_fetch(NULL, name, NULL);
    snprintf(k, sizeof(k), "fetch.%s", name);
    printf("%s=%d\n", k, r != NULL);
    if (r == NULL) {
        snprintf(k, sizeof(k), "fetch.err.%s", name);
        errs(k);
        return;
    }

    snprintf(k, sizeof(k), "name.%s", name);
    printf("%s=%s\n", k, EVP_RAND_get0_name(r) ? EVP_RAND_get0_name(r) : "<null>");
    snprintf(k, sizeof(k), "is_a.%s.self", name);
    printf("%s=%d\n", k, EVP_RAND_is_a(r, name));
    snprintf(k, sizeof(k), "gettable.%s", name);
    params(k, EVP_RAND_gettable_params(r));

    /*
     * Context A: the refusal arms. A DRBG that has been asked to generate before it was
     * instantiated is left in `ERROR`, so it is discarded here rather than reused -- reusing it
     * would make every later observation a measurement of the error state instead of the row.
     */
    ctx = EVP_RAND_CTX_new(r, NULL);
    snprintf(k, sizeof(k), "ctx.%s", name);
    printf("%s=%d\n", k, ctx != NULL);
    if (ctx == NULL) {
        EVP_RAND_free(r);
        return;
    }

    snprintf(k, sizeof(k), "state.new.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "strength.new.%s", name);
    printf("%s=%u\n", k, EVP_RAND_get_strength(ctx));
    snprintf(k, sizeof(k), "ctxtable.%s", name);
    params(k, EVP_RAND_CTX_gettable_params(ctx));
    snprintf(k, sizeof(k), "settable.%s", name);
    params(k, EVP_RAND_CTX_settable_params(ctx));

    snprintf(k, sizeof(k), "generate.uninit.%s", name);
    printf("%s=%d\n", k, EVP_RAND_generate(ctx, out, sizeof(out), 0, 0, NULL, 0));
    snprintf(k, sizeof(k), "state.after.uninit.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "err.uninit.%s", name);
    errs(k);
    for (i = 0; i < sizeof(out); i++)
        out[i] = 0;

    /* The context above is now in `ERROR`; instantiating it is its own refusal arm. */
    snprintf(k, sizeof(k), "instantiate.in_error.%s", name);
    printf("%s=%d\n", k, EVP_RAND_instantiate(ctx, 0, 0, NULL, 0, NULL));
    snprintf(k, sizeof(k), "state.in_error.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "err.in_error.%s", name);
    errs(k);
    EVP_RAND_CTX_free(ctx);

    /*
     * Context B: the working arm. The algorithms are set first -- see the header -- and
     * `strength == 0` on instantiate is the authority's own "use the row's strength".
     */
    ctx = EVP_RAND_CTX_new(r, NULL);
    snprintf(k, sizeof(k), "set.%s", name);
    printf("%s=%d\n", k, set_algorithms(ctx, d));
    snprintf(k, sizeof(k), "err.set.%s", name);
    errs(k);
    snprintf(k, sizeof(k), "state.after_set.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "strength.after_set.%s", name);
    printf("%s=%u\n", k, EVP_RAND_get_strength(ctx));

    snprintf(k, sizeof(k), "instantiate.%s", name);
    printf("%s=%d\n", k, EVP_RAND_instantiate(ctx, 0, 0, NULL, 0, NULL));
    snprintf(k, sizeof(k), "state.ready.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "strength.ready.%s", name);
    printf("%s=%u\n", k, EVP_RAND_get_strength(ctx));
    snprintf(k, sizeof(k), "err.instantiate.%s", name);
    errs(k);

    /* The parameter surface, read back through the ctx. */
    snprintf(k, sizeof(k), "uints.%s", name);
    uints(k, ctx, EVP_RAND_CTX_gettable_params(ctx));
    if (d->cipher != NULL) {
        snprintf(k, sizeof(k), "cipher.%s", name);
        utf8(k, ctx, "cipher");
    }
    if (d->digest != NULL) {
        snprintf(k, sizeof(k), "digest.%s", name);
        utf8(k, ctx, "digest");
    }
    if (d->mac != NULL) {
        snprintf(k, sizeof(k), "mac.%s", name);
        utf8(k, ctx, "mac");
    }

    /*
     * A generate with a caller-supplied strength of 0 and a fixed output length. The **return
     * code and the state** are observed; the bytes are not (see the header). The output is
     * cleared so nothing derived from the pool can leak through a later comparison.
     */
    snprintf(k, sizeof(k), "generate.%s", name);
    printf("%s=%d\n", k, EVP_RAND_generate(ctx, out, sizeof(out), 0, 0, NULL, 0));
    snprintf(k, sizeof(k), "state.after.generate.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "err.generate.%s", name);
    errs(k);
    for (i = 0; i < sizeof(out); i++)
        out[i] = 0;

    /* A second, smaller generate, so the counter/state update path is exercised twice. */
    snprintf(k, sizeof(k), "generate.short.%s", name);
    printf("%s=%d\n", k, EVP_RAND_generate(ctx, out, 1, 0, 0, NULL, 0));
    snprintf(k, sizeof(k), "state.after.short.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "err.short.%s", name);
    errs(k);
    out[0] = 0;

    /* The parameter surface after a generate, so a value that moves is a residual. */
    snprintf(k, sizeof(k), "uints.after.%s", name);
    uints(k, ctx, EVP_RAND_CTX_gettable_params(ctx));

    /* Instantiating an already-instantiated ctx is a refusal arm, not a re-seed. */
    snprintf(k, sizeof(k), "reinstantiate.%s", name);
    printf("%s=%d\n", k, EVP_RAND_instantiate(ctx, 0, 0, NULL, 0, NULL));
    snprintf(k, sizeof(k), "state.after.reinstantiate.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "err.reinstantiate.%s", name);
    errs(k);

    snprintf(k, sizeof(k), "verify_zeroization.%s", name);
    printf("%s=%d\n", k, EVP_RAND_verify_zeroization(ctx));
    snprintf(k, sizeof(k), "err.verify_zeroization.%s", name);
    errs(k);

    snprintf(k, sizeof(k), "uninstantiate.%s", name);
    printf("%s=%d\n", k, EVP_RAND_uninstantiate(ctx));
    snprintf(k, sizeof(k), "state.uninstantiated.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(ctx));
    snprintf(k, sizeof(k), "err.uninstantiate.%s", name);
    errs(k);

    /* Generate after uninstantiate returns to the uninitialised refusal. */
    snprintf(k, sizeof(k), "generate.post.%s", name);
    printf("%s=%d\n", k, EVP_RAND_generate(ctx, out, sizeof(out), 0, 0, NULL, 0));
    snprintf(k, sizeof(k), "err.post.%s", name);
    errs(k);
    out[0] = 0;
    EVP_RAND_CTX_free(ctx);

    /* The over-strong request, on a fresh context so the arms above are unaffected. */
    strong = EVP_RAND_CTX_new(r, NULL);
    printf("set.too_strong.%s=%d\n", name, set_algorithms(strong, d));
    (void)ERR_get_error();
    snprintf(k, sizeof(k), "instantiate.too_strong.%s", name);
    printf("%s=%d\n", k, EVP_RAND_instantiate(strong, TOO_STRONG, 0, NULL, 0, NULL));
    snprintf(k, sizeof(k), "state.too_strong.%s", name);
    printf("%s=%d\n", k, EVP_RAND_get_state(strong));
    snprintf(k, sizeof(k), "err.too_strong.%s", name);
    errs(k);
    EVP_RAND_CTX_free(strong);

    /* An algorithm name no provider answers is a refusal on the set call. */
    ctx = EVP_RAND_CTX_new(r, NULL);
    {
        OSSL_PARAM p[2];
        char bad[32];
        strcpy(bad, "NO-SUCH-ALG");
        p[0] = OSSL_PARAM_construct_utf8_string(d->cipher != NULL ? "cipher"
                                                : d->digest != NULL ? "digest" : "mac",
                                                bad, 0);
        p[1] = OSSL_PARAM_construct_end();
        snprintf(k, sizeof(k), "set.bad.%s", name);
        printf("%s=%d\n", k, EVP_RAND_CTX_set_params(ctx, p));
        snprintf(k, sizeof(k), "err.set.bad.%s", name);
        errs(k);
    }
    EVP_RAND_CTX_free(ctx);

    EVP_RAND_free(r);
}

int main(void)
{
    size_t i;

    setvbuf(stdout, NULL, _IOLBF, 0);
    (void)OSSL_PROVIDER_load(NULL, "default");

    for (i = 0; i < N_ROWS; i++)
        row(&ROWS[i]);

    /* The default provider's two non-DRBG RAND rows. */
    non_drbg_row("SEED-SRC", 0);
    non_drbg_row("TEST-RAND", 1);

    /* The walk's own edges: a name no row answers, and the provider's availability. */
    printf("fetch.RSA=%d\n", EVP_RAND_fetch(NULL, "RSA", NULL) != NULL);
    errs("fetch.RSA.err");

    printf("provider.available=%d\n", OSSL_PROVIDER_available(NULL, "default"));
    return 0;
}
