#!/bin/sh
#
# openssl-rs — Phase 17 downstream (HAProxy): capture the crash backtrace.
#
# proxy_probe.sh shows the candidate-linked HAProxy dying with exit 139 (SIGSEGV) on the first TLS
# handshake. This script re-runs that single event under an LD_PRELOAD fatal-signal handler
# (segv_trace.c) to print the crashing stack, so the defect is attributable rather than merely
# observed. The image ships no gdb, and core dumps are piped to a systemd-coredump that is not
# present in the container, so a backtrace handler is the available route.
#
# It reuses the cert/config generated by a prior `proxy_probe.sh` run under the same $WORK.
#
# Run:  bash docker/openssl-rs-court.sh exec \
#         sh /work/courts/phase17/downstream/haproxy/crash_trace.sh
#
set -eu

WORK=${WORK:-/court/haproxy}
HAPROXY_BIN=${HAPROXY:-$WORK/haproxy-3.0.29/haproxy}
CURL=${CURL:-/court/curl/curl-8.22.0/src/curl}
PORT=${PORT:-18445}
BACKEND_PORT=${BACKEND_PORT:-18081}
P=$WORK/probe

if [ ! -f "$P/haproxy.cfg" ] || [ ! -f "$P/ca.crt" ]; then
    echo "crash_trace.sh: no probe config in $P; run proxy_probe.sh first" >&2
    exit 2
fi

cc -O2 -fPIC -shared -o "$WORK/segv_trace.so" \
    /work/courts/phase17/downstream/haproxy/segv_trace.c

kill_ours() {
    for p in /proc/[0-9]*; do
        c=$(cat "$p/comm" 2>/dev/null || true)
        case "$c" in haproxy|python3) kill -9 "${p#/proc/}" 2>/dev/null || true ;; esac
    done
}
kill_ours
sleep 0.3

python3 -m http.server "$BACKEND_PORT" --bind 127.0.0.1 --directory "$P/docroot" \
    > "$P/trace_backend.log" 2>&1 &
BE=$!
sleep 0.5

echo "=== haproxy -vv (linked against candidate) ==="
"$HAPROXY_BIN" -vv | grep -E 'HAProxy version|Built with OpenSSL|Running on OpenSSL'

echo "=== start haproxy under LD_PRELOAD backtrace handler ==="
LD_PRELOAD="$WORK/segv_trace.so" "$HAPROXY_BIN" -db -f "$P/haproxy.cfg" \
    -p "$P/run/haproxy.pid" > "$P/trace_haproxy.out" 2> "$P/trace_haproxy.err" &
HP=$!
sleep 1
if ! kill -0 "$HP" 2>/dev/null; then
    echo "crash_trace.sh: haproxy was already dead before any client" >&2
    sed -n '1,20p' "$P/trace_haproxy.err" >&2
    kill -9 "$BE" 2>/dev/null || true
    exit 3
fi

echo "=== one candidate-curl TLS handshake ==="
set +e
"$CURL" -s --max-time 10 --cacert "$P/ca.crt" -o /dev/null \
    -w 'curl_http=%{http_code} verify=%{ssl_verify_result} exit=%{exitcode}\n' \
    "https://127.0.0.1:$PORT/index.html" 2> "$P/trace_curl.err"
set -e
cat "$P/trace_curl.err" 2>/dev/null || true

i=0
while [ "$i" -lt 25 ] && kill -0 "$HP" 2>/dev/null; do i=$((i + 1)); sleep 0.2; done
if kill -0 "$HP" 2>/dev/null; then
    echo "haproxy survived the handshake (no crash this run)"
else
    HRC=0; wait "$HP" 2>/dev/null || HRC=$?
    echo "haproxy exit=$HRC (139 = SIGSEGV)"
fi

echo "=== backtrace (stderr) ==="
sed -n '1,60p' "$P/trace_haproxy.err"

kill -9 "$HP" "$BE" 2>/dev/null || true
kill_ours
echo "crash_trace.sh: done"
