//! The `EVP_sha3_224()` … `EVP_shake256()` static `EVP_MD` objects.
//!
//! # There is no `crypto/evp/legacy_sha3.c`
//!
//! The task that produced this file looked for `crypto/evp/legacy_sha3.c` and it does **not** exist
//! in the 3.6.4 authority. A `grep -rn "EVP_sha3_256"` over `crypto/` and
//! `providers/implementations/digests/` finds no definition either: the six entry points are
//! generated by two macros inside **`crypto/evp/legacy_sha.c`** — `EVP_MD_SHA3(bitlen)` at
//! `legacy_sha.c:195-209` and `EVP_MD_SHAKE(bitlen)` at `:210-223`, invoked at `:225-231`. Their
//! callbacks come from `IMPLEMENT_LEGACY_EVP_MD_METH_SHA3(sha3_int, ossl_sha3, '\x06')`
//! (`legacy_sha.c:29-42`, `:64`) and `IMPLEMENT_LEGACY_EVP_MD_METH_SHAKE(shake, ossl_sha3, '\x1f')`
//! (`:43-47`, `:65`), plus `shake_ctrl` (`:73-88`).
//!
//! The SHA-1/SHA-2 objects that share that authority file are transcribed in
//! [`crate::evp::legacy_sha`]; the SHA-3/SHAKE six live here so that file stays readable.
//!
//! # The internals this file needed are present in the crate — nothing is invented
//!
//! The task's rule is to omit rather than invent an internal that the crate lacks. Every internal
//! the macros reach **exists**, and each was checked before the callbacks below were written:
//!
//! - `ossl_sha3_init` — `src/digest/sha3.rs:290`, signature `(*mut KeccakCtx, u8, usize) -> c_int`.
//! - `ossl_sha3_update` — `src/digest/sha3.rs:330`, `(*mut KeccakCtx, *const u8, usize) -> c_int`.
//! - `ossl_sha3_final` — `src/digest/sha3.rs:413`, `(*mut KeccakCtx, *mut u8, usize) -> c_int`.
//! - `KeccakCtx` — `src/digest/sha3.rs:81`, the crate's `KECCAK1600_CTX`, whose `md_size` is
//!   `usize`.
//!
//! So this file is complete: all six entry points and all five callbacks are transcribed.
//!
//! # Two things the macros do that are easy to miss
//!
//! **The rate is the object's, not a literal.** `IMPLEMENT_LEGACY_EVP_MD_METH_SHA3`'s init is
//! `fn##_init(md_data(ctx), tag, ctx->digest->md_size * 8)` — the bit length handed to
//! `ossl_sha3_init` is computed from the *method's* `md_size`, which is why the callbacks below
//! dereference `(*ctx).digest` rather than carrying a per-object constant. The `tag` argument is
//! the domain-separation pad byte: `'\x06'` for SHA-3 and `'\x1f'` for SHAKE.
//!
//! **SHAKE defines only an init.** `IMPLEMENT_LEGACY_EVP_MD_METH_SHAKE` emits one function
//! (`legacy_sha.c:43-47`), so both SHAKE objects reuse `sha3_int_update` and `sha3_int_final` and
//! differ from SHA-3 only in the pad, the `flags`, the pkey NID and `shake_ctrl`.
//!
//! # `flags` differs between the two families
//!
//! The four SHA-3 objects carry `EVP_MD_FLAG_DIGALGID_ABSENT` alone (`legacy_sha.c:202`); the two
//! SHAKE objects carry `EVP_MD_FLAG_XOF | EVP_MD_FLAG_DIGALGID_ABSENT` (`:217`), i.e. `0x0002 |
//! 0x0008`. The helper below therefore takes `flags` as an argument and each initialiser states the
//! authority's own expression.
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::{c_int, c_uchar, c_ulong, c_void};
use core::sync::atomic::AtomicI32;

use crate::digest::sha3::{ossl_sha3_final, ossl_sha3_init, ossl_sha3_update, KeccakCtx};
use crate::evp::digest::{
    EvpMd, EvpMdCtx, MdLegacyCtrlFn, MdLegacyFinalFn, MdLegacyInitFn, MdLegacyUpdateFn,
};
use crate::runtime::obj::{
    NID_sha3_224, NID_sha3_256, NID_sha3_384, NID_sha3_512, NID_shake128, NID_shake256,
    NID_RSA_SHA3_224, NID_RSA_SHA3_256, NID_RSA_SHA3_384, NID_RSA_SHA3_512,
};

/// `KECCAK1600_WIDTH` — `include/internal/sha3.h:18`. The state is 1600 bits, and the rate of each
/// spelling is `(KECCAK1600_WIDTH - bitlen * 2) / 8`, which is the block-size expression the two
/// object macros write.
const KECCAK1600_WIDTH: c_int = 1600;

/// `(KECCAK1600_WIDTH - 224 * 2) / 8` — the SHA3-224 rate, `legacy_sha.c:206`.
const SHA3_224_CBLOCK: c_int = (KECCAK1600_WIDTH - 224 * 2) / 8;
/// `(KECCAK1600_WIDTH - 256 * 2) / 8` — the SHA3-256 rate.
const SHA3_256_CBLOCK: c_int = (KECCAK1600_WIDTH - 256 * 2) / 8;
/// `(KECCAK1600_WIDTH - 384 * 2) / 8` — the SHA3-384 rate.
const SHA3_384_CBLOCK: c_int = (KECCAK1600_WIDTH - 384 * 2) / 8;
/// `(KECCAK1600_WIDTH - 512 * 2) / 8` — the SHA3-512 rate.
const SHA3_512_CBLOCK: c_int = (KECCAK1600_WIDTH - 512 * 2) / 8;
/// `(KECCAK1600_WIDTH - 128 * 2) / 8` — the SHAKE128 rate, `legacy_sha.c:220`.
const SHAKE128_CBLOCK: c_int = (KECCAK1600_WIDTH - 128 * 2) / 8;
/// `(KECCAK1600_WIDTH - 256 * 2) / 8` — the SHAKE256 rate.
const SHAKE256_CBLOCK: c_int = (KECCAK1600_WIDTH - 256 * 2) / 8;

/// `bitlen / 8` for SHA3-224 — the `md_size` field `EVP_MD_SHA3(224)` writes.
const SHA3_224_DIGEST_LENGTH: c_int = 224 / 8;
/// `bitlen / 8` for SHA3-256.
const SHA3_256_DIGEST_LENGTH: c_int = 256 / 8;
/// `bitlen / 8` for SHA3-384.
const SHA3_384_DIGEST_LENGTH: c_int = 384 / 8;
/// `bitlen / 8` for SHA3-512.
const SHA3_512_DIGEST_LENGTH: c_int = 512 / 8;
/// `bitlen / 8` for SHAKE128 — **16**, the default output length, not the rate.
const SHAKE128_DIGEST_LENGTH: c_int = 128 / 8;
/// `bitlen / 8` for SHAKE256.
const SHAKE256_DIGEST_LENGTH: c_int = 256 / 8;

/// The SHA-3 domain-separation byte, `'\x06'` — `legacy_sha.c:64`.
const SHA3_PAD: u8 = 0x06;
/// The SHAKE domain-separation byte, `'\x1f'` — `legacy_sha.c:65`.
const SHAKE_PAD: u8 = 0x1f;

/// `EVP_MD_CTRL_XOF_LEN` — `include/openssl/evp.h:204`. The one command `shake_ctrl` answers; it
/// sets the output length `EVP_DigestSqueeze` will read.
const EVP_MD_CTRL_XOF_LEN: c_int = 0x3;

/// `EVP_MD_FLAG_XOF` — `include/openssl/evp.h:179`.
const EVP_MD_FLAG_XOF: c_ulong = 0x0002;
/// `EVP_MD_FLAG_DIGALGID_ABSENT` — `include/openssl/evp.h:191`.
const EVP_MD_FLAG_DIGALGID_ABSENT: c_ulong = 0x0008;

/// `EVP_ORIG_GLOBAL` — `include/crypto/evp.h:255`. A global method is not reference counted and not
/// freed, which is why the mutating arms of `EVP_MD_up_ref`/`EVP_MD_free` both refuse it.
const EVP_ORIG_GLOBAL: c_int = 1;

/// `EVP_MD_CTX_get0_md_data(ctx)` — `crypto/evp/evp_lib.c:1087`, which the authority's legacy macros
/// call. A bare `return ctx->md_data;`, factored out because every callback below opens with it.
///
/// # Safety
/// `ctx` must be a live `EVP_MD_CTX`.
unsafe fn md_data(ctx: *mut EvpMdCtx) -> *mut c_void {
    // SAFETY: the caller's contract.
    unsafe { (*ctx).md_data }
}

/// A `static` `EVP_MD`. The wrapper claims `Sync` for a value that is only ever read: a heap
/// `EvpMd` is mutable and synchronised by its reference count, while a compile-time constant one is
/// neither.
///
/// **A private copy per file, not an import**, chosen to keep each legacy file independent; see the
/// identical note in `court/legacy_md5.rs`.
struct StaticMd(EvpMd);

// SAFETY: the inner value is fully initialised at compile time and is never written. Every mutating
// arm in the digest module is guarded by `origin`, and `EVP_ORIG_GLOBAL` is not `EVP_ORIG_DYNAMIC`,
// so `EVP_MD_up_ref` and `EVP_MD_free` both refuse these objects.
unsafe impl Sync for StaticMd {}

/// `LEGACY_EVP_MD_METH_TABLE`'s shape, as a `const fn`. `flags` is an argument because the SHA-3
/// objects carry `EVP_MD_FLAG_DIGALGID_ABSENT` and the SHAKE objects carry additionally
/// `EVP_MD_FLAG_XOF`; the rest of the legacy half is the macro's six values and the provider half
/// stays zero.
#[allow(clippy::too_many_arguments)]
const fn legacy_md(
    type_: c_int,
    pkey_type: c_int,
    md_size: c_int,
    flags: c_ulong,
    block_size: c_int,
    init: Option<MdLegacyInitFn>,
    update: Option<MdLegacyUpdateFn>,
    final_: Option<MdLegacyFinalFn>,
    md_ctrl: Option<MdLegacyCtrlFn>,
) -> StaticMd {
    StaticMd(EvpMd {
        type_,
        pkey_type,
        md_size,
        flags,
        origin: EVP_ORIG_GLOBAL,
        init,
        update,
        final_,
        // The authority's table writes `NULL, NULL` for `copy` and `cleanup`.
        copy: None,
        cleanup: None,
        block_size,
        // **Zero, and that is the authority's value rather than an omission**; the fetch-replacement
        // arm replaces this method before any callback would read `md_data`.
        ctx_size: 0,
        md_ctrl,
        name_id: 0,
        type_name: core::ptr::null_mut(),
        description: core::ptr::null(),
        prov: core::ptr::null_mut(),
        refcnt: AtomicI32::new(0),
        newctx: None,
        dinit: None,
        dupdate: None,
        dfinal: None,
        dsqueeze: None,
        digest: None,
        freectx: None,
        copyctx: None,
        dupctx: None,
        get_params: None,
        set_ctx_params: None,
        get_ctx_params: None,
        gettable_params: None,
        settable_ctx_params: None,
        gettable_ctx_params: None,
    })
}

// ---------------------------------------------------------------------------------------------
// `IMPLEMENT_LEGACY_EVP_MD_METH_SHA3(sha3_int, ossl_sha3, '\x06')` — `legacy_sha.c:29-42`, written
// out. All three are shared by the four SHA-3 objects.
// ---------------------------------------------------------------------------------------------

/// `sha3_int_init` — `legacy_sha.c:30-33`. The bit length is `ctx->digest->md_size * 8`, so the
/// rate `ossl_sha3_init` selects follows the object rather than a literal.
unsafe extern "C" fn sha3_int_init(ctx: *mut EvpMdCtx) -> c_int {
    // SAFETY: the caller's contract; `(*ctx).digest` is the live method the context holds, and
    // `md_data(ctx)` is its block. `md_size` is always one of the four small positive lengths here,
    // so the wrapping multiply is the authority's `* 8` and never actually wraps.
    unsafe {
        let bitlen = (*(*ctx).digest).md_size.wrapping_mul(8) as usize;
        ossl_sha3_init(md_data(ctx).cast::<KeccakCtx>(), SHA3_PAD, bitlen)
    }
}

/// `sha3_int_update` — `legacy_sha.c:34-37`.
unsafe extern "C" fn sha3_int_update(
    ctx: *mut EvpMdCtx,
    data: *const c_void,
    count: usize,
) -> c_int {
    // SAFETY: as above, and `data`/`count` are forwarded unchanged.
    unsafe { ossl_sha3_update(md_data(ctx).cast::<KeccakCtx>(), data.cast::<u8>(), count) }
}

/// `sha3_int_final` — `legacy_sha.c:38-42`. The authority names the local `kctx` and passes
/// `kctx->md_size` as the output length, **not** the digest size the caller asked for, which is why
/// a `shake_ctrl`-set length is what `EVP_DigestFinal_ex` returns.
unsafe extern "C" fn sha3_int_final(ctx: *mut EvpMdCtx, md: *mut c_uchar) -> c_int {
    // SAFETY: the caller's contract; the block is a live `KECCAK1600_CTX` and `md` is writable for
    // its `md_size` bytes.
    unsafe {
        let kctx = md_data(ctx).cast::<KeccakCtx>();
        ossl_sha3_final(kctx, md, (*kctx).md_size)
    }
}

// ---------------------------------------------------------------------------------------------
// `IMPLEMENT_LEGACY_EVP_MD_METH_SHAKE(shake, ossl_sha3, '\x1f')` — `legacy_sha.c:43-47`, which
// emits only `shake_init`, plus `shake_ctrl` at `:73-88`.
// ---------------------------------------------------------------------------------------------

/// `shake_init` — `legacy_sha.c:44-47`. The same body as `sha3_int_init` with the SHAKE pad byte;
/// the two SHAKE objects reuse [`sha3_int_update`] and [`sha3_int_final`] for the other two thirds.
unsafe extern "C" fn shake_init(ctx: *mut EvpMdCtx) -> c_int {
    // SAFETY: as `sha3_int_init`.
    unsafe {
        let bitlen = (*(*ctx).digest).md_size.wrapping_mul(8) as usize;
        ossl_sha3_init(md_data(ctx).cast::<KeccakCtx>(), SHAKE_PAD, bitlen)
    }
}

/// `shake_ctrl` — `legacy_sha.c:73-88`. `EVP_MD_CTRL_XOF_LEN` writes the requested output length
/// into the sponge's `md_size` and answers `1`; every other command answers `0`, and a NULL context
/// answers `0` before the command is even looked at. The authority writes `ctx = evp_ctx->md_data`
/// directly rather than through `EVP_MD_CTX_get0_md_data`, which is why [`md_data`] is not used.
unsafe extern "C" fn shake_ctrl(
    evp_ctx: *mut EvpMdCtx,
    cmd: c_int,
    p1: c_int,
    _p2: *mut c_void,
) -> c_int {
    if evp_ctx.is_null() {
        return 0;
    }
    // SAFETY: `evp_ctx` is non-NULL per the check above and is the live context.
    let raw = unsafe { (*evp_ctx).md_data };
    let kctx = raw.cast::<KeccakCtx>();

    match cmd {
        EVP_MD_CTRL_XOF_LEN => {
            // SAFETY: `kctx` is the live context's block, a `KECCAK1600_CTX`. The `int`-to-`usize`
            // cast is the authority's `int`-to-`size_t` assignment; the length is non-negative in
            // every call `EVP_DigestSqueeze` makes.
            unsafe { (*kctx).md_size = p1 as usize };
            1
        }
        _ => 0,
    }
}

// ---------------------------------------------------------------------------------------------
// The six objects, in `legacy_sha.c`'s own order: the four SHA-3 spellings from
// `EVP_MD_SHA3(224)`, `(256)`, `(384)`, `(512)` at `:225-228`, then the two SHAKE spellings from
// `EVP_MD_SHAKE(128)`, `(256)` at `:230-231`.
// ---------------------------------------------------------------------------------------------

/// `sha3_224_md` — `legacy_sha.c:198-207` as `EVP_MD_SHA3(224)`. `pkey_type` is
/// `NID_RSA_SHA3_224`, `flags` is `EVP_MD_FLAG_DIGALGID_ABSENT` alone, and `md_ctrl` is NULL.
static SHA3_224_MD: StaticMd = legacy_md(
    NID_sha3_224,
    NID_RSA_SHA3_224,
    SHA3_224_DIGEST_LENGTH,
    EVP_MD_FLAG_DIGALGID_ABSENT,
    SHA3_224_CBLOCK,
    Some(sha3_int_init),
    Some(sha3_int_update),
    Some(sha3_int_final),
    None,
);

/// `sha3_256_md` — `EVP_MD_SHA3(256)`.
static SHA3_256_MD: StaticMd = legacy_md(
    NID_sha3_256,
    NID_RSA_SHA3_256,
    SHA3_256_DIGEST_LENGTH,
    EVP_MD_FLAG_DIGALGID_ABSENT,
    SHA3_256_CBLOCK,
    Some(sha3_int_init),
    Some(sha3_int_update),
    Some(sha3_int_final),
    None,
);

/// `sha3_384_md` — `EVP_MD_SHA3(384)`.
static SHA3_384_MD: StaticMd = legacy_md(
    NID_sha3_384,
    NID_RSA_SHA3_384,
    SHA3_384_DIGEST_LENGTH,
    EVP_MD_FLAG_DIGALGID_ABSENT,
    SHA3_384_CBLOCK,
    Some(sha3_int_init),
    Some(sha3_int_update),
    Some(sha3_int_final),
    None,
);

/// `sha3_512_md` — `EVP_MD_SHA3(512)`.
static SHA3_512_MD: StaticMd = legacy_md(
    NID_sha3_512,
    NID_RSA_SHA3_512,
    SHA3_512_DIGEST_LENGTH,
    EVP_MD_FLAG_DIGALGID_ABSENT,
    SHA3_512_CBLOCK,
    Some(sha3_int_init),
    Some(sha3_int_update),
    Some(sha3_int_final),
    None,
);

/// `shake128_md` — `legacy_sha.c:213-222` as `EVP_MD_SHAKE(128)`. The **pkey NID is the literal
/// `0`** the macro writes, not a named NID; `flags` adds `EVP_MD_FLAG_XOF`; and `shake_ctrl` is the
/// one control function in this family. `md_size` is 16 — the default output length, which
/// `shake_ctrl` may change — while the rate is 168.
static SHAKE128_MD: StaticMd = legacy_md(
    NID_shake128,
    0,
    SHAKE128_DIGEST_LENGTH,
    EVP_MD_FLAG_XOF | EVP_MD_FLAG_DIGALGID_ABSENT,
    SHAKE128_CBLOCK,
    Some(shake_init),
    Some(sha3_int_update),
    Some(sha3_int_final),
    Some(shake_ctrl),
);

/// `shake256_md` — `EVP_MD_SHAKE(256)`. The same shape with a 32-octet default output and the
/// SHAKE256 rate of 136.
static SHAKE256_MD: StaticMd = legacy_md(
    NID_shake256,
    0,
    SHAKE256_DIGEST_LENGTH,
    EVP_MD_FLAG_XOF | EVP_MD_FLAG_DIGALGID_ABSENT,
    SHAKE256_CBLOCK,
    Some(shake_init),
    Some(sha3_int_update),
    Some(sha3_int_final),
    Some(shake_ctrl),
);

// ---------------------------------------------------------------------------------------------
// The six entry points, in the authority's own order.
// ---------------------------------------------------------------------------------------------

/// `const EVP_MD *EVP_sha3_224(void)` — `legacy_sha.c:196` (the `EVP_MD_SHA3(224)` expansion).
///
/// The answer is a constant, so this is not an `unsafe` function: the authority's own body reads
/// nothing. Handing the pointer to `EVP_DigestInit_ex` still digests, because the library fetches
/// the provider implementation by NID and replaces this object before any of its callbacks would
/// run (`src/evp/digest.rs:124-145`).
#[no_mangle]
pub extern "C" fn EVP_sha3_224() -> *const EvpMd {
    core::ptr::addr_of!(SHA3_224_MD.0)
}

/// `const EVP_MD *EVP_sha3_256(void)` — `EVP_MD_SHA3(256)`.
#[no_mangle]
pub extern "C" fn EVP_sha3_256() -> *const EvpMd {
    core::ptr::addr_of!(SHA3_256_MD.0)
}

/// `const EVP_MD *EVP_sha3_384(void)` — `EVP_MD_SHA3(384)`.
#[no_mangle]
pub extern "C" fn EVP_sha3_384() -> *const EvpMd {
    core::ptr::addr_of!(SHA3_384_MD.0)
}

/// `const EVP_MD *EVP_sha3_512(void)` — `EVP_MD_SHA3(512)`.
#[no_mangle]
pub extern "C" fn EVP_sha3_512() -> *const EvpMd {
    core::ptr::addr_of!(SHA3_512_MD.0)
}

/// `const EVP_MD *EVP_shake128(void)` — `EVP_MD_SHAKE(128)`.
#[no_mangle]
pub extern "C" fn EVP_shake128() -> *const EvpMd {
    core::ptr::addr_of!(SHAKE128_MD.0)
}

/// `const EVP_MD *EVP_shake256(void)` — `EVP_MD_SHAKE(256)`.
#[no_mangle]
pub extern "C" fn EVP_shake256() -> *const EvpMd {
    core::ptr::addr_of!(SHAKE256_MD.0)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The six objects against the authority's own fields, read from the `EVP_MD_SHA3`/
    /// `EVP_MD_SHAKE` macros at `legacy_sha.c:195-223` and their invocations at `:225-231`.
    ///
    /// The things this catches that a name-and-size test would not: the four SHA-3 objects carry
    /// `EVP_MD_FLAG_DIGALGID_ABSENT` **alone** while the two SHAKE objects add `EVP_MD_FLAG_XOF`;
    /// the SHAKE pkey NID is `0`; and each rate is `(1600 - bitlen * 2) / 8` rather than the digest
    /// length or a rounded value.
    #[test]
    fn the_six_objects_are_the_authoritys_fields() {
        let cases: [(&EvpMd, c_int, c_int, c_int, c_int, c_ulong); 6] = [
            (
                &SHA3_224_MD.0,
                NID_sha3_224,
                NID_RSA_SHA3_224,
                28,
                144,
                EVP_MD_FLAG_DIGALGID_ABSENT,
            ),
            (
                &SHA3_256_MD.0,
                NID_sha3_256,
                NID_RSA_SHA3_256,
                32,
                136,
                EVP_MD_FLAG_DIGALGID_ABSENT,
            ),
            (
                &SHA3_384_MD.0,
                NID_sha3_384,
                NID_RSA_SHA3_384,
                48,
                104,
                EVP_MD_FLAG_DIGALGID_ABSENT,
            ),
            (
                &SHA3_512_MD.0,
                NID_sha3_512,
                NID_RSA_SHA3_512,
                64,
                72,
                EVP_MD_FLAG_DIGALGID_ABSENT,
            ),
            (
                &SHAKE128_MD.0,
                NID_shake128,
                0,
                16,
                168,
                EVP_MD_FLAG_XOF | EVP_MD_FLAG_DIGALGID_ABSENT,
            ),
            (
                &SHAKE256_MD.0,
                NID_shake256,
                0,
                32,
                136,
                EVP_MD_FLAG_XOF | EVP_MD_FLAG_DIGALGID_ABSENT,
            ),
        ];

        for (md, type_, pkey_type, md_size, block_size, flags) in cases {
            assert_eq!(md.type_, type_);
            assert_eq!(md.pkey_type, pkey_type);
            assert_eq!(md.md_size, md_size);
            assert_eq!(md.block_size, block_size);
            assert_eq!(md.flags, flags);
            assert_eq!(md.origin, EVP_ORIG_GLOBAL);
            assert_eq!(md.ctx_size, 0);
            assert_eq!(md.name_id, 0);
            assert!(md.type_name.is_null());
            assert!(md.prov.is_null());
            assert!(md.copy.is_none());
            assert!(md.cleanup.is_none());
            assert!(md.init.is_some());
            assert!(md.update.is_some());
            assert!(md.final_.is_some());
        }
    }

    /// Only the two SHAKE objects carry a control function, and it is `shake_ctrl`; the four SHA-3
    /// objects write NULL as the macro's fourth table argument spells out. The SHAKE objects are
    /// also the only ones with the `XOF` bit.
    #[test]
    fn only_shake_carries_a_control_function_and_the_xof_flag() {
        for md in [
            &SHA3_224_MD.0,
            &SHA3_256_MD.0,
            &SHA3_384_MD.0,
            &SHA3_512_MD.0,
        ] {
            assert!(md.md_ctrl.is_none());
            assert_eq!(md.flags & EVP_MD_FLAG_XOF, 0);
        }
        for md in [&SHAKE128_MD.0, &SHAKE256_MD.0] {
            assert!(md.md_ctrl.is_some());
            assert_ne!(md.flags & EVP_MD_FLAG_XOF, 0);
        }
    }

    /// The entry points answer the addresses of their own objects, and the six are distinct. A
    /// transcription that returned one object for two names would satisfy every field test above.
    #[test]
    fn each_entry_point_answers_its_own_object() {
        let pointers = [
            EVP_sha3_224() as usize,
            EVP_sha3_256() as usize,
            EVP_sha3_384() as usize,
            EVP_sha3_512() as usize,
            EVP_shake128() as usize,
            EVP_shake256() as usize,
        ];

        for (i, a) in pointers.iter().enumerate() {
            assert!(*a != 0, "entry point {i} answered NULL");
            for b in pointers.iter().skip(i + 1) {
                assert_ne!(a, b, "two entry points answered the same object");
            }
        }
        assert_eq!(EVP_sha3_256(), core::ptr::addr_of!(SHA3_256_MD.0));
        assert_eq!(EVP_shake128(), core::ptr::addr_of!(SHAKE128_MD.0));
    }
}
