#!/usr/bin/env python3
"""openssl-rs — atlas generator: the public API surface.

Mines the admitted authority's **installed public headers** through Clang and
produces, per authority:

    functions.json      typedefs.json       structs.json
    enums.json          variables.json      macros.json
    header-graph.json

Why Clang rather than regexes
-----------------------------
The Phase 1 requirement is to cross-check *headers vs Clang AST vs built DSO
exports vs `.num` inventories*. Regexes over headers cannot resolve typedefs,
macro-expanded declarations, attribute placement or nested records. Clang's AST
is the compiler's own view of the declarations an application would actually see,
so it is the correct plane.

What is captured
----------------
* Every declaration whose *spelling location* lies inside the authority's
  installed `include/openssl/` tree. Declarations from libc/system headers are
  excluded, so the surface is OpenSSL's own.
* Locations are stored **relative to the authority prefix**, never as host
  paths, so evidence is portable and deterministic.
* Deprecation is captured structurally (`DeprecatedAttr`), not guessed from
  names, because `docs/PARITY_MODEL.md` treats deprecation as observable.

Determinism
-----------
The generated translation unit is written to the authority capture area and its
hash recorded. All lists are sorted. No wall-clock, host path or environment
value enters the atlas.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_common import (  # noqa: E402
    Authority,
    InputRef,
    all_authority_ids,
    authority_atlas_dir,
    content_hash,
    envelope,
    must_run,
    rel,
    resolve_authority,
    sha256_bytes,
    sha256_file,
    write_json,
    write_text,
    AUTH_ROOT,
    REPO_ROOT,
)

INCLUDE_SUBDIR = "include/openssl"

# --- header graph -----------------------------------------------------------

_INCLUDE_RE = re.compile(r"^\s*#\s*include\s+[<\"]([^>\"]+)[>\"]", re.MULTILINE)
_DEFINE_RE = re.compile(r"^\s*#\s*define\s+([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE)
_DEFINE_FUNC_RE = re.compile(
    r"^\s*#\s*define\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", re.MULTILINE
)


def build_header_graph(prefix: Path) -> dict:
    inc_root = prefix / INCLUDE_SUBDIR
    headers = sorted(p.name for p in inc_root.glob("*.h"))
    edges: dict[str, list[str]] = {}
    macros_defined: dict[str, list[str]] = defaultdict(list)
    for name in headers:
        text = (inc_root / name).read_text(errors="replace")
        deps = sorted({m for m in _INCLUDE_RE.findall(text)})
        edges[name] = deps
        func_like = set(_DEFINE_FUNC_RE.findall(text))
        for m in _DEFINE_RE.findall(text):
            kind = "function-like" if m in func_like else "object-like"
            macros_defined[m].append(f"{name}:{kind}")
    body = {
        "include_dir": INCLUDE_SUBDIR,
        "header_count": len(headers),
        "headers": headers,
        "edges": edges,
        "macros_defined_in_headers": {k: sorted(v) for k, v in sorted(macros_defined.items())},
    }
    return body


# --- Clang AST --------------------------------------------------------------

def make_tu(prefix: Path) -> str:
    inc_root = prefix / INCLUDE_SUBDIR
    lines = ["/* Generated by forensics/tools/atlas_api.py. Do not edit. */"]
    for name in sorted(p.name for p in inc_root.glob("*.h")):
        lines.append(f"#include <openssl/{name}>")
    return "\n".join(lines) + "\n"


def ast_dump(prefix: Path, tu_path: Path) -> dict:
    res = must_run([
        "clang", "-x", "c", "-fsyntax-only",
        "-I", str(prefix / "include"),
        "-Wno-everything",
        "-Xclang", "-ast-dump=json",
        str(tu_path),
    ])
    if not res.stdout:
        raise SystemExit("FATAL: clang produced no AST")
    return json.loads(res.stdout)


def macro_dump(prefix: Path, tu_path: Path) -> str:
    res = must_run([
        "clang", "-x", "c", "-E", "-dM",
        "-I", str(prefix / "include"),
        "-Wno-everything",
        str(tu_path),
    ])
    return res.stdout


def loc_of(node: dict) -> tuple[str | None, int | None]:
    """Return (file, line) for a node, preferring the spelling location.

    NOTE: this is only correct for a node whose location carries an explicit
    `file`. Clang's JSON omits `file` when it equals the previously printed
    location, so general traversal must use `SourceLocationTracker` below.
    """
    loc = node.get("loc")
    while isinstance(loc, dict):
        if "spellingLoc" in loc:
            loc = loc["spellingLoc"]
            continue
        if "expansionLoc" in loc:
            loc = loc["expansionLoc"]
            continue
        break
    if not isinstance(loc, dict):
        return None, None
    return loc.get("file"), loc.get("line")


class SourceLocationTracker:
    """Reconstruct clang's elided source locations during a pre-order walk.

    `clang -ast-dump=json` prints location objects that include `file` only when
    the file differs from the previously printed location, and `line` only when
    the line changes. A stateless reader therefore sees a location as missing a
    file for almost every declaration, which silently shrinks the inventory.

    Clang emits nodes in pre-order and prints each node's `loc` and then its
    `range` before descending into `inner`, so absorbing locations in that same
    order reconstructs the true (file, line) for every node.
    """

    __slots__ = ("file", "line")

    def __init__(self) -> None:
        self.file: str | None = None
        self.line: int | None = None

    def absorb(self, loc: object) -> None:
        """Advance the elision state through a printed location object.

        Clang prints a macro location as `{spellingLoc, expansionLoc}` in that
        order, and shares one elision state across both. We therefore process
        sub-locations **in key order** (Python preserves JSON key order, which is
        clang's print order) and let the last one win. For a macro-generated
        declaration that lands on `expansionLoc` — the header that invoked the
        macro, i.e. the public header a consumer actually includes — which is the
        correct attribution. `spellingLoc` for such a declaration is
        `<scratch space>` and would wrongly exclude it from the inventory.
        """
        if not isinstance(loc, dict):
            return
        for key, value in loc.items():
            if key in ("spellingLoc", "expansionLoc") and isinstance(value, dict):
                self.absorb(value)
        if isinstance(loc.get("file"), str):
            self.file = loc["file"]
        if isinstance(loc.get("line"), int):
            self.line = loc["line"]

    def absorb_node(self, node: dict) -> tuple[str | None, int | None]:
        """Absorb a node's loc/range in clang's print order; return its location."""
        self.absorb(node.get("loc"))
        here = (self.file, self.line)
        rng = node.get("range")
        if isinstance(rng, dict):
            self.absorb(rng.get("begin"))
            self.absorb(rng.get("end"))
        return here


def attr_kinds(node: dict) -> list[str]:
    out = []
    for child in node.get("inner", []) or []:
        kind = child.get("kind", "")
        if kind.endswith("Attr"):
            out.append(kind)
    return sorted(set(out))


def params_of(node: dict) -> list[dict]:
    out = []
    for child in node.get("inner", []) or []:
        if child.get("kind") == "ParmVarDecl":
            out.append({
                "name": child.get("name", ""),
                "type": (child.get("type") or {}).get("qualType", ""),
            })
    return out


def fields_of(node: dict) -> list[dict]:
    out = []
    for child in node.get("inner", []) or []:
        if child.get("kind") == "FieldDecl":
            out.append({
                "name": child.get("name", ""),
                "type": (child.get("type") or {}).get("qualType", ""),
            })
    return out


def enum_constants(node: dict) -> list[dict]:
    out = []
    for child in node.get("inner", []) or []:
        if child.get("kind") in ("EnumConstantDecl",):
            value = None
            for sub in child.get("inner", []) or []:
                if sub.get("kind") == "ConstantExpr":
                    value = sub.get("value")
            out.append({"name": child.get("name", ""), "value": value})
    return out


def collect_decls(ast: dict, inc_prefix: str) -> dict[str, list]:
    """Walk the AST, keeping only decls spelled inside include/openssl.

    Locations are reconstructed with SourceLocationTracker because clang elides
    repeated filenames; without it almost every declaration appears to have no
    file and the inventory silently collapses.
    """
    found: dict[str, dict[str, dict]] = {
        "functions": {}, "typedefs": {}, "structs": {}, "enums": {}, "variables": {},
    }
    tracker = SourceLocationTracker()

    def visit(node: dict) -> None:
        kind = node.get("kind")
        file, line = tracker.absorb_node(node)
        if kind in ("FunctionDecl", "TypedefDecl", "RecordDecl", "EnumDecl", "VarDecl"):
            if file and file.startswith(inc_prefix):
                header = file[len(inc_prefix):].lstrip("/")
                name = node.get("name", "")
                attrs = attr_kinds(node)
                if kind == "FunctionDecl" and name:
                    found["functions"].setdefault(name, {
                        "name": name,
                        # The full declared function type as clang spells it. This
                        # is the most faithful and most comparable representation
                        # of the declaration for source/ABI parity; the parameter
                        # list is extracted separately for readability.
                        "type": (node.get("type") or {}).get("qualType", ""),
                        "params": params_of(node),
                        "variadic": bool(node.get("variadic", False)),
                        "storage_class": node.get("storageClass", ""),
                        "inline": bool(node.get("inline", False)),
                        "deprecated": any("Deprecated" in a for a in attrs),
                        "attributes": attrs,
                        "header": header,
                        "line": line,
                    })
                elif kind == "TypedefDecl" and name:
                    found["typedefs"].setdefault(name, {
                        "name": name,
                        "underlying_type": (node.get("type") or {}).get("qualType", ""),
                        "header": header,
                        "line": line,
                    })
                elif kind == "RecordDecl" and name:
                    tag = node.get("tagUsed", "struct")
                    key = f"{tag} {name}"
                    existing = found["structs"].get(key)
                    complete = bool(node.get("completeDefinition", False))
                    if existing is None or (complete and not existing["complete"]) \
                            or (complete and not existing["fields"]):
                        found["structs"][key] = {
                            "name": name,
                            "tag": tag,
                            "complete": complete,
                            "fields": fields_of(node),
                            "header": header,
                            "line": line,
                        }
                elif kind == "EnumDecl" and name:
                    found["enums"].setdefault(name, {
                        "name": name,
                        "constants": enum_constants(node),
                        "header": header,
                        "line": line,
                    })
                elif kind == "VarDecl" and name:
                    # Only file-scope declarations with external linkage are part
                    # of the public data surface. VarDecl nodes also appear for
                    # macro-local objects and for function-pointer parameters,
                    # which are not exported symbols and would be noise.
                    if node.get("storageClass", "") == "extern":
                        found["variables"].setdefault(name, {
                            "name": name,
                            "type": (node.get("type") or {}).get("qualType", ""),
                            "storage_class": "extern",
                            "header": header,
                            "line": line,
                        })
        for child in node.get("inner", []) or []:
            if isinstance(child, dict):
                visit(child)

    visit(ast)
    return {k: [v[n] for n in sorted(v)] for k, v in found.items()}


def collect_macros(macro_text: str, header_body: dict) -> list[dict]:
    """Attribute `clang -dM` macros to the headers that define them.

    `-dM` dumps every macro in the translation unit, including libc's. We keep
    only macros whose name is written as a `#define` in an OpenSSL header, which
    is what makes the inventory OpenSSL's own rather than the platform's.
    """
    defined_in = header_body["macros_defined_in_headers"]
    records = []
    for line in macro_text.splitlines():
        if not line.startswith("#define "):
            continue
        rest = line[len("#define "):]
        m = re.match(r"([A-Za-z_][A-Za-z0-9_]*)(\([^)]*\))?\s*(.*)$", rest)
        if not m:
            continue
        name, args, value = m.group(1), m.group(2), m.group(3)
        sites = defined_in.get(name)
        if not sites:
            continue
        kinds = sorted({s.rsplit(":", 1)[1] for s in sites})
        records.append({
            "name": name,
            "params": args if args else None,
            "value": value,
            "kind": kinds[0] if len(kinds) == 1 else "mixed",
            "defined_in": sorted({s.rsplit(":", 1)[0] for s in sites}),
        })
    return sorted(records, key=lambda r: r["name"])


def generate(authority_id: str) -> dict[str, str]:
    auth = resolve_authority(authority_id)
    outdir = authority_atlas_dir(authority_id)
    capture = AUTH_ROOT / "captures" / authority_id
    prefix = auth.prefix
    inc_prefix = str((prefix / INCLUDE_SUBDIR).resolve())

    print(f"[api] {auth.id}")

    header_body = build_header_graph(prefix)
    print(f"  headers: {header_body['header_count']}, "
          f"macros declared: {len(header_body['macros_defined_in_headers'])}")

    tu_text = make_tu(prefix)
    tu_path = capture / "api-tu.c"
    if not tu_path.exists() or tu_path.read_text() != tu_text:
        write_text(tu_path, tu_text)
    print(f"  tu: {rel(tu_path)} ({sha256_file(tu_path)[:12]})")

    ast = ast_dump(prefix, tu_path)
    macro_text = macro_dump(prefix, tu_path)

    decls = collect_decls(ast, inc_prefix)
    macros = collect_macros(macro_text, header_body)

    inputs = [InputRef("translation_unit", tu_path)]

    outputs: dict[str, str] = {}
    counts = {}
    for kind, records in sorted(decls.items()):
        body = {"count": len(records), "records": records}
        doc = envelope(f"api-{kind}", "forensics/tools/atlas_api.py", inputs, body,
                       authority=auth.id)
        doc["body_hash"] = content_hash(body)
        p = outdir / f"{kind}.json"
        outputs[p.name] = write_json(p, doc)
        counts[kind] = len(records)
    print(f"  declarations: {counts}")

    macro_body = {"count": len(macros), "records": macros}
    doc = envelope("api-macros", "forensics/tools/atlas_api.py", inputs, macro_body,
                   authority=auth.id)
    doc["body_hash"] = content_hash(macro_body)
    p = outdir / "macros.json"
    outputs[p.name] = write_json(p, doc)

    hdr_doc = envelope("header-graph", "forensics/tools/atlas_api.py", [],
                       header_body, authority=auth.id)
    hdr_doc["body_hash"] = content_hash(header_body)
    p = outdir / "header-graph.json"
    outputs[p.name] = write_json(p, hdr_doc)
    print(f"  macros: {len(macros)}")
    return outputs


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Generate the API surface atlas.")
    ap.add_argument("--authority", action="append", default=[])
    ap.add_argument("--all", action="store_true")
    args = ap.parse_args(argv)
    ids = all_authority_ids() if args.all else args.authority
    if not ids:
        ap.error("specify --all or --authority")
    for aid in ids:
        generate(aid)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
