#!/usr/bin/env python3
"""openssl-rs — atlas generator: ABI layout and ownership obligations.

Two related planes that the declaration atlas cannot express:

1. `abi-layout.json` — the *layout* facts a declaration does not carry:
   `sizeof`, alignment and per-field `offsetof` for every complete public
   aggregate, plus the integer value of every named enum constant. These are
   the facts a downstream binary compiled against the authority's headers
   depends on, and they are measured by *compiling and running a probe against
   the authority's own installed headers* — never assumed from source text.

2. `ownership-obligations.json` — the ownership contract encoded in the public
   API's naming conventions (`docs/OWNERSHIP_MODEL.md`). Phase 1 can only
   *enumerate* these obligations from declarations; the behavioural probe that
   would discharge one runs in Phase 3 against a real candidate. The status is
   therefore recorded honestly as `DISCOVERED`, never as proved.

Probe policy
------------
One probe program per aggregate, compiled and executed inside the court. A
probe that fails to compile is a *residual*, not a silent omission: the record
keeps the failure and the compiler diagnostic. Aggregates that are not complete
(opaque) are recorded as opaque rather than skipped, because opacity is itself
an ABI fact.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_common import (  # noqa: E402
    Authority,
    InputRef,
    all_authority_ids,
    authority_atlas_dir,
    content_hash,
    envelope,
    rel,
    resolve_authority,
    run,
    sha256_bytes,
    write_json,
)

INCLUDE_SUBDIR = "include/openssl"

# Ownership conventions, longest/most-specific first. `docs/OWNERSHIP_MODEL.md`
# defines the meanings; this table only recognises the names.
OWNERSHIP_PATTERNS = [
    (re.compile(r"_get0(_|$)"), "get0", "borrowed reference; caller must not free"),
    (re.compile(r"_get1(_|$)"), "get1", "owned reference; refcount incremented; caller must free"),
    (re.compile(r"_get0_"), "get0", "borrowed reference (infix form)"),
    (re.compile(r"_set0(_|$)"), "set0", "takes ownership; callee frees"),
    (re.compile(r"_set1(_|$)"), "set1", "copies/increments; caller keeps its reference"),
    (re.compile(r"_up_ref$"), "up_ref", "increments the refcount; caller takes a new reference"),
    (re.compile(r"_free$"), "free", "decrements; frees at zero; idempotent on NULL"),
    (re.compile(r"_dup$"), "dup", "copy; ownership of the result transfers to the caller"),
    (re.compile(r"_new$|_create$|_new_ex$"), "constructor", "creates a new owned object"),
]

PROBE_TEMPLATE = r"""
/* Generated by forensics/tools/atlas_abi.py — do not edit. */
#include <stddef.h>
#include <stdio.h>
{includes}

int main(void) {{
{probes}
    return 0;
}}
"""


def all_includes(prefix: Path) -> str:
    inc = prefix / INCLUDE_SUBDIR
    return "\n".join(
        f"#include <openssl/{p.name}>" for p in sorted(inc.glob("*.h"))
    )


def probe_aggregate(prefix: Path, inc_text: str, workdir: Path,
                    tag: str, name: str, fields: list[dict]) -> dict:
    """Compile and run one layout probe for a single aggregate."""
    type_name = f"{tag} {name}"
    probes = [
        f'    printf("sizeof\\t%zu\\n", sizeof({type_name}));',
        f'    printf("alignof\\t%zu\\n", _Alignof({type_name}));',
    ]
    for f in fields:
        fname = f.get("name")
        if not fname:
            continue
        probes.append(
            f'    printf("offsetof\\t{fname}\\t%zu\\n", offsetof({type_name}, {fname}));'
        )
    src = PROBE_TEMPLATE.format(includes=inc_text, probes="\n".join(probes))
    src_path = workdir / "probe.c"
    bin_path = workdir / "probe"
    src_path.write_text(src)
    compile_res = run(["clang", "-std=c11", "-I", str(prefix / "include"),
                       "-o", str(bin_path), str(src_path)])
    if not compile_res.ok:
        return {
            "aggregate": f"{tag} {name}",
            "probe_status": "compile_failed",
            "diagnostic": compile_res.stderr.strip().splitlines()[:4],
        }
    exec_res = run([str(bin_path)])
    if not exec_res.ok:
        return {
            "aggregate": f"{tag} {name}",
            "probe_status": "run_failed",
            "diagnostic": exec_res.stderr.strip().splitlines()[:4],
        }
    size = align = None
    offsets = {}
    for line in exec_res.stdout.splitlines():
        parts = line.split("\t")
        if len(parts) == 2 and parts[0] == "sizeof":
            size = int(parts[1])
        elif len(parts) == 2 and parts[0] == "alignof":
            align = int(parts[1])
        elif len(parts) == 3 and parts[0] == "offsetof":
            offsets[parts[1]] = int(parts[2])
    return {
        "aggregate": f"{tag} {name}",
        "probe_status": "ok",
        "sizeof": size,
        "alignof": align,
        "field_offsetof": dict(sorted(offsets.items())),
    }


def build_abi_layout(auth: Authority, work: Path) -> dict:
    structs = json.loads((authority_atlas_dir(auth.id) / "structs.json").read_text())
    records = structs["body"]["records"]
    inc_text = all_includes(auth.prefix)

    probes = []
    opaque = []
    for rec in sorted(records, key=lambda r: (r["tag"], r["name"])):
        if not rec["complete"]:
            opaque.append({"aggregate": f"{rec['tag']} {rec['name']}",
                           "header": rec["header"], "note": "incomplete/opaque type"})
            continue
        probes.append(probe_aggregate(auth.prefix, inc_text, work,
                                      rec["tag"], rec["name"], rec["fields"]))

    ok = [p for p in probes if p["probe_status"] == "ok"]
    failed = [p for p in probes if p["probe_status"] != "ok"]
    return {
        "aggregates_probed": len(probes),
        "aggregates_ok": len(ok),
        "aggregates_failed": len(failed),
        "opaque_aggregates": len(opaque),
        "records": probes,
        "opaque": opaque,
        "overflow_check": {
            "note": "sizeof/alignof/offsetof are recorded as measured, not "
                    "inferred; a probe failure is preserved with its diagnostic",
        },
    }


def build_ownership(functions: dict) -> dict:
    records = []
    by_kind: dict[str, int] = {}
    for rec in functions["body"]["records"]:
        name = rec["name"]
        for pattern, kind, meaning in OWNERSHIP_PATTERNS:
            if pattern.search(name):
                records.append({
                    "symbol": name,
                    "kind": kind,
                    "meaning": meaning,
                    "header": rec["header"],
                    "line": rec["line"],
                    "deprecated": rec["deprecated"],
                    "status": "DISCOVERED",
                    "discharge_court": "MEM-OWNERSHIP",
                    "note": "declaration-derived obligation; the behavioural probe "
                            "that discharges it runs in Phase 3 against a candidate",
                })
                by_kind[kind] = by_kind.get(kind, 0) + 1
                break
    records.sort(key=lambda r: (r["kind"], r["symbol"]))
    return {
        "obligation_count": len(records),
        "by_kind": {k: by_kind[k] for k in sorted(by_kind)},
        "records": records,
    }


def generate(authority_id: str) -> None:
    auth = resolve_authority(authority_id)
    outdir = authority_atlas_dir(authority_id)
    work = Path("/court/abi-probe")
    work.mkdir(parents=True, exist_ok=True)
    print(f"[abi] {auth.id}")

    layout = build_abi_layout(auth, work)
    doc = envelope("abi-layout", "forensics/tools/atlas_abi.py",
                   [InputRef("headers",
                             note="authority installed public headers under include/openssl; "
                                  "the probe is compiled against exactly these bytes")],
                   layout, authority=auth.id)
    doc["body_hash"] = content_hash(layout)
    write_json(outdir / "abi-layout.json", doc)
    print(f"  aggregates: probed={layout['aggregates_probed']} ok={layout['aggregates_ok']} "
          f"failed={layout['aggregates_failed']} opaque={layout['opaque_aggregates']}")
    if layout["aggregates_failed"]:
        print(f"  WARNING: {layout['aggregates_failed']} probe(s) failed (preserved as residuals)")

    functions = json.loads((outdir / "functions.json").read_text())
    own = build_ownership(functions)
    odoc = envelope("ownership-obligations", "forensics/tools/atlas_abi.py",
                    [InputRef("functions", outdir / "functions.json")],
                    own, authority=auth.id)
    odoc["body_hash"] = content_hash(own)
    write_json(outdir / "ownership-obligations.json", odoc)
    print(f"  ownership obligations: {own['obligation_count']} {own['by_kind']}")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Generate ABI layout and ownership atlas.")
    ap.add_argument("--authority", action="append", default=[])
    ap.add_argument("--all", action="store_true")
    args = ap.parse_args(argv)
    ids = all_authority_ids() if args.all else args.authority
    if not ids:
        ap.error("specify --all or --authority")
    for aid in ids:
        generate(aid)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
