#!/usr/bin/env python3
"""openssl-rs — Phase 2: generate the distribution / ABI shell.

Phase 2 proves that a *trivial external consumer can build and load* against the
candidate, before any complex semantics exist. It reconstructs the parts of an
OpenSSL distribution that are structural rather than behavioural:

    artifacts/phase2/
      libcrypto.ld, libssl.ld          generated ELF version scripts (export maps)
      pkgconfig/libcrypto.pc, libssl.pc  pkg-config metadata
      shell/libcrypto.shell.rs         SCAFFOLDED symbol definitions (libcrypto)
      shell/libssl.shell.rs            SCAFFOLDED symbol definitions (libssl)
      include/openssl/...              public header shell, with provenance
      SHELL_MANIFEST.json              content-addressed record of all of it

SCAFFOLDED, by construction and by rule
---------------------------------------
The generated symbol definitions are **scaffolds**. They are required so that the
distribution artifacts exist and can be linked and loaded, and they are governed
by `docs/CUSTODIAN_CONTRACT.md` §5:

  * classified `SCAFFOLDED` — `SHELL_MANIFEST.json` says so for every symbol;
  * they **cannot** count as parity: a scaffolded symbol is not an implemented
    obligation, and the parity ledger keeps it at `SCAFFOLDED`;
  * they must never return a plausible value. Each scaffold aborts with a
    diagnostic naming the symbol, so a consumer that *calls* one fails loudly
    instead of silently receiving invented output. That is the honest failure
    mode for an unimplemented obligation.

The header shell
----------------
`docs/ABI_POLICY.md` §4 and the contract's provenance rule allow interface
material to be carried from the authority with attribution. The header shell is
therefore *constructed from the authority's installed public headers*, with any
OpenSSL-derived interface material carrying its licence notice, and every file
recorded by hash. This is a deliberate, documented choice: hand-regenerating 142
headers from the AST would be a large source of silent divergence for no gain,
whereas a byte-identical shell is the strongest source-compatibility statement
available and is trivially verifiable.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_common import (  # noqa: E402
    PRODUCTION_AUTHORITY,
    authority_atlas_dir,
    content_hash,
    envelope,
    rel,
    resolve_authority,
    sha256_bytes,
    sha256_file,
    write_json,
    write_text,
    REPO_ROOT,
)

OUT = REPO_ROOT / "artifacts" / "phase2"
LIBRARIES = {"libcrypto": "libcrypto.so.3", "libssl": "libssl.so.3"}

HEADER_SHELL_NOTICE = """/* SPDX-License-Identifier: Apache-2.0
 *
 * openssl-rs — public header shell (Phase 2).
 *
 * PROVENANCE: this directory is constructed from the installed public headers of
 * the admitted OpenSSL authority `openssl-3.6.4-production`, which is licensed
 * under the Apache License 2.0. It is carried here so that unmodified consumers
 * can compile against a byte-faithful interface, and it is recorded by hash in
 * artifacts/phase2/SHELL_MANIFEST.json.
 *
 * This is interface material, not implementation. The implementation is native
 * Rust and lives in src/. See docs/CUSTODIAN_CONTRACT.md §3 (provenance rule).
 */
"""


def generate_version_script(doc: dict, soname: str) -> str:
    """Emit a GNU ld version script from the authority's measured DSO bindings.

    The binding of each symbol to a version node is taken from what the *built
    authority DSO* actually did (plane C), not from the source `.num` inventory,
    because that is what a downstream binary resolves against.
    """
    by_node: dict[str, list[str]] = {}
    for rec in doc["body"]["records"]:
        dso = rec.get("dso") or {}
        if not dso.get("present"):
            continue
        node = dso.get("version") or soname
        by_node.setdefault(node, []).append(rec["symbol"])
    lines = [
        f"# Generated by forensics/tools/phase2_shell.py — do not edit.",
        f"# Export map for {soname}, derived from the built authority DSO.",
        f"#",
        f"# Every symbol the authority actually exports, bound to the same ELF",
        f"# version node. Nothing is added and nothing is dropped: the ABI-SYMBOL",
        f"# court compares this script's effect against the authority exactly.",
        "",
    ]
    nodes = [n for n in sorted(by_node) if n != soname]
    for idx, node in enumerate(nodes):
        lines.append(f"{node} {{")
        lines.append("    global:")
        for sym in sorted(by_node[node]):
            lines.append(f"        {sym};")
        if idx == len(nodes) - 1:
            # The authority's own script carries `local: *;` in its final node,
            # which is what hides every symbol not explicitly listed. Omitting
            # it leaks whatever else ends up in the object graph (in particular
            # the Rust runtime's symbols, since a whole-archive link pulls them
            # in). Matching the authority here is not cosmetic: it is the
            # difference between a 5896-symbol ABI and an exported runtime.
            lines.append("    local: *;")
        lines.append("};")
        lines.append("")
    return "\n".join(lines) + "\n"


def generate_shell_rs(doc: dict, lib: str) -> str:
    """Emit SCAFFOLDED Rust symbol definitions for one library."""
    symbols = sorted(
        rec["symbol"] for rec in doc["body"]["records"]
        if (rec.get("dso") or {}).get("present")
    )
    out = [
        "// GENERATED by forensics/tools/phase2_shell.py — do not edit by hand.",
        f"//",
        f"// openssl-rs — Phase 2 ABI shell for {lib} ({LIBRARIES[lib]}).",
        "//",
        "// STATUS: SCAFFOLDED. Every symbol below is a scaffold, not an",
        "// implementation. It exists so the distribution artifact can be linked",
        "// and loaded; it is governed by docs/CUSTODIAN_CONTRACT.md §5 and",
        "// *cannot* count as parity.",
        "//",
        "// A scaffold never returns a plausible value. Calling one aborts with a",
        "// diagnostic naming the symbol, so an unimplemented obligation fails",
        "// loudly rather than silently inventing output.",
        "#![allow(non_snake_case)]",
        "",
        "use std::io::Write;",
        "",
        "#[cold]",
        "#[inline(never)]",
        "fn openssl_rs_scaffolded(name: &str) -> ! {",
        "    let _ = writeln!(",
        "        std::io::stderr(),",
        '        "openssl-rs: SCAFFOLDED symbol {name} was called. This symbol is not"',
        "    );",
        "    let _ = writeln!(",
        "        std::io::stderr(),",
        '        "openssl-rs: implemented; the ABI shell exists only so distribution"',
        "    );",
        "    let _ = writeln!(",
        "        std::io::stderr(),",
        '        "openssl-rs: artifacts can be linked and loaded. See docs/RELEASE_GATES.md."',
        "    );",
        "    std::process::abort();",
        "}",
        "",
        "/// Report that `name` is scaffolded. Never returns.",
        "macro_rules! scaffolded {",
        "    ($name:literal) => {",
        "        openssl_rs_scaffolded($name)",
        "    };",
        "}",
        "",
    ]
    for sym in symbols:
        out.append(f'#[no_mangle]\npub extern "C" fn {sym}() -> core::ffi::c_int {{')
        out.append(f'    scaffolded!("{sym}")')
        out.append("}")
        out.append("")
    return "\n".join(out)


def generate_pkgconfig(lib: str, version: str) -> str:
    soname = LIBRARIES[lib]
    other = "libssl" if lib == "libcrypto" else None
    req = "Requires.private: libcrypto" if lib == "libssl" else "Requires.private:"
    return f"""# Generated by forensics/tools/phase2_shell.py — do not edit.
# pkg-config metadata for the openssl-rs {lib} ABI shell.

prefix=/usr/local
exec_prefix=${{prefix}}
libdir=${{exec_prefix}}/lib
includedir=${{prefix}}/include

Name: {lib}
Description: openssl-rs — custodian reconstruction of OpenSSL {version} ({lib} ABI shell)
Version: {version}
Libs: -L${{libdir}} -l{lib.replace('lib', '', 1)}
Libs.private: -ldl -lpthread
Cflags: -I${{includedir}}
{req}
"""


SCAFFOLD_HEADER = """// GENERATED by forensics/tools/phase2_shell.py — do not edit by hand.
//
// STATUS: SCAFFOLDED. This artefact exists so the distribution shell is
// complete enough to be installed, linked, loaded and substituted; it is
// governed by docs/CUSTODIAN_CONTRACT.md §5 and cannot count as parity.
// It aborts with a diagnostic rather than returning a plausible value.

use std::io::Write;

#[cold]
#[inline(never)]
fn openssl_rs_scaffolded(name: &str) -> ! {{
    let _ = writeln!(std::io::stderr(), "openssl-rs: SCAFFOLDED {name} invoked.");
    let _ = writeln!(std::io::stderr(), "openssl-rs: not implemented; the Phase 2 shell exists so the");
    let _ = writeln!(std::io::stderr(), "openssl-rs: distribution artifacts can be linked and loaded.");
    std::process::abort();
}}
"""


def generate_provider_module_rs() -> str:
    """The legacy provider module.

    The authority's `lib/ossl-modules/legacy.so` exports exactly ONE symbol,
    `OSSL_provider_init`, and declares `NEEDED libcrypto.so.3`. Reproducing that
    shape is what makes the module discoverable at the same path with the same
    loading contract; the build step passes `-Wl,--no-as-needed -lcrypto` so the
    dependency is really declared rather than assumed.
    """
    return (
        SCAFFOLD_HEADER
        + "\n#[no_mangle]\npub extern \"C\" fn OSSL_provider_init() -> core::ffi::c_int {\n"
        + '    openssl_rs_scaffolded("OSSL_provider_init")\n}\n'
    )


def generate_cli_rs(version: str) -> str:
    """The `openssl` executable.

    Phase 2 requires the executable to EXIST with the right name and install
    path so that a consumer's build scripts and `which openssl` behave. Its
    behaviour is Phase 16 work; until then it fails loudly rather than pretending.
    """
    return (
        SCAFFOLD_HEADER
        + "\nfn main() {\n"
        + f'    let _ = writeln!(std::io::stderr(), "openssl-rs: SCAFFOLDED openssl CLI ({version} shell).");\n'
        + '    let _ = writeln!(std::io::stderr(), "openssl-rs: the command surface is Phase 16 work; nothing was executed.");\n'
        + "    std::process::exit(2);\n}\n"
    )


def generate_c_rehash_sh() -> str:
    return (
        "#!/bin/sh\n"
        "# GENERATED by forensics/tools/phase2_shell.py — SCAFFOLDED.\n"
        "# The authority installs bin/c_rehash; Phase 2 ships the name and path so\n"
        "# the install layout is complete. Behaviour is Phase 16 work.\n"
        "echo \"openssl-rs: SCAFFOLDED c_rehash (Phase 2 shell); nothing was executed.\" >&2\n"
        "exit 2\n"
    )


def generate(authority_id: str) -> None:
    auth = resolve_authority(authority_id)
    adir = authority_atlas_dir(authority_id)
    print(f"[phase2] {auth.id}")

    docs = {lib: json.loads((adir / f"symbols-{lib}.json").read_text())
            for lib in LIBRARIES}

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "shell").mkdir(exist_ok=True)
    (OUT / "pkgconfig").mkdir(exist_ok=True)

    produced: list[dict] = []

    for lib, doc in sorted(docs.items()):
        soname = LIBRARIES[lib]
        ld = generate_version_script(doc, soname)
        p = OUT / f"{lib}.ld"
        write_text(p, ld)
        produced.append({"artifact": p.name, "role": "version-script",
                         "sha256": sha256_file(p)})

        rs = generate_shell_rs(doc, lib)
        p = OUT / "shell" / f"{lib}.shell.rs"
        write_text(p, rs)
        produced.append({"artifact": rel(p), "role": "scaffolded-symbols",
                         "sha256": sha256_file(p),
                         "symbol_count": sum(
                             1 for r in doc["body"]["records"]
                             if (r.get("dso") or {}).get("present"))})

        pc = generate_pkgconfig(lib, auth.version)
        p = OUT / "pkgconfig" / f"{lib}.pc"
        write_text(p, pc)
        produced.append({"artifact": rel(p), "role": "pkg-config",
                         "sha256": sha256_file(p)})

    # --- the remaining distribution artefacts ----------------------------
    extra = {
        "shell/legacy.shell.rs": generate_provider_module_rs(),
        "shell/openssl.shell.rs": generate_cli_rs(auth.version),
        "shell/c_rehash.sh": generate_c_rehash_sh(),
    }
    for name, text in extra.items():
        p = OUT / name
        write_text(p, text)
        produced.append({"artifact": rel(p), "role": "scaffold-source",
                         "sha256": sha256_file(p)})

    # --- header shell: constructed from the authority's installed headers -----
    src_inc = auth.prefix / "include"
    dst_inc = OUT / "include"
    if dst_inc.exists():
        shutil.rmtree(dst_inc)
    shutil.copytree(src_inc, dst_inc, symlinks=False)
    header_files = sorted(p for p in dst_inc.rglob("*") if p.is_file())
    write_text(dst_inc / "PROVENANCE-NOTICE.h", HEADER_SHELL_NOTICE)
    header_files = sorted(p for p in dst_inc.rglob("*") if p.is_file())
    lines = [f"{sha256_file(p)}  {p.relative_to(dst_inc).as_posix()}\n"
             for p in header_files]
    produced.append({
        "artifact": rel(dst_inc),
        "role": "header-shell",
        "file_count": len(header_files),
        "root_hash": sha256_bytes("".join(lines).encode("utf-8")),
    })
    print(f"  header shell: {len(header_files)} files")

    # --- development symlinks -------------------------------------------
    # A real OpenSSL install ships `libcrypto.so` -> `libcrypto.so.3` so that
    # `-lcrypto` resolves at link time while the runtime object carries the
    # SONAME. Without these, a consumer cannot link (the linker searches for
    # `libcrypto.so`). Recorded as part of the install-layout contract.
    for lib, soname in LIBRARIES.items():
        link = OUT / f"{lib}.so"
        if link.is_symlink() or link.exists():
            link.unlink()
        link.symlink_to(soname)
        produced.append({"artifact": f"{lib}.so", "role": "development-symlink",
                         "target": soname})

    manifest_body = {
        "authority": auth.id,
        "authority_version": auth.version,
        "sonames": LIBRARIES,
        "scaffold_policy": (
            "every generated symbol definition is SCAFFOLDED; it cannot count as "
            "parity, and it aborts rather than returning a plausible value "
            "(docs/CUSTODIAN_CONTRACT.md §5)"
        ),
        "artifacts": produced,
    }
    doc = envelope("phase2-shell", "forensics/tools/phase2_shell.py", [],
                   manifest_body, authority=auth.id)
    doc["body_hash"] = content_hash(manifest_body)
    write_json(OUT / "SHELL_MANIFEST.json", doc)
    print(f"  manifest: {rel(OUT / 'SHELL_MANIFEST.json')}")
    for a in produced:
        extra = a.get("symbol_count") or a.get("file_count") or ""
        print(f"    {a['role']:<18} {a['artifact']} {extra}")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Generate the Phase 2 ABI shell.")
    ap.add_argument("--authority", default=PRODUCTION_AUTHORITY)
    args = ap.parse_args(argv)
    generate(args.authority)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
