#!/usr/bin/env python3
"""openssl-rs — render STATUS.md from machine-readable evidence.

`docs/NON_CLAIMS.md` §1 forbids prose status: every number in STATUS.md is read
from the atlas and receipts, and the document is regenerated, never edited. If
the atlas is missing, the generator says so instead of inventing a status.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_common import (  # noqa: E402
    ATLAS,
    FORENSICS,
    PRODUCTION_AUTHORITY,
    authority_atlas_dir,
    contract_unit_lines,
    rel,
    write_text,
)

STATUS = FORENSICS / "STATUS.md"
RECEIPTS = FORENSICS / "receipts"


def load(path: Path):
    return json.loads(path.read_text()) if path.exists() else None


def _phase22_figures(p22: Path) -> list[tuple[str, int]]:
    """The Phase-22 plane figures, read from the committed artefacts.

    The Phase-1 census above is the public contract; this is the whole-program archaeology
    around it. The two are separate planes and are rendered separately, because a single
    "atlas census" row of `cli commands | 55` is true of the Phase-1 capture and false of
    the atlas Phase 22 measured. A plane that has not landed is skipped rather than
    rendered as a zero.
    """
    def body(name: str) -> dict:
        return ((load(p22 / name) or {}).get("body") or {})

    def count(name: str, key: str):
        return (body(name).get("counts") or {}).get(key)

    def length(name: str, key: str):
        seq = body(name).get(key)
        return len(seq) if isinstance(seq, list) else None

    rows: list[tuple[str, object]] = [
        ("translation units (captured compiler invocations)",
         count("compile-commands.json", "commands")),
        ("distinct source files", count("compile-commands.json", "distinct_sources")),
        ("Clang AST entities", count("tu-ast.json", "entities")),
        ("direct-call edges", count("tu-ast.json", "call_edges")),
        ("address-taken functions", count("tu-ast.json", "address_taken")),
        ("Doxygen entities", count("doxygen-entities.json", "entities")),
        ("Doxygen reference edges", count("doxygen-entities.json", "reference_edges")),
        ("dispatch/registration tables", count("dispatch-graph.json", "tables")),
        ("indirect typed edges", count("dispatch-graph.json", "edges")),
        ("CLI commands", count("cli-surface.json", "commands")),
        ("CLI structured options", count("cli-surface.json", "options_structured")),
        ("environment variables", count("config-surface.json", "env_vars")),
        ("configuration directives", count("config-surface.json", "directives")),
        ("installed distribution entries", length("install-manifest.json", "entries")),
        ("POD manual pages", count("pod-contract.json", "pages")),
        ("POD claims", count("pod-contract.json", "claims")),
        ("unified entities", count("reconciliation.json", "entities")),
        ("cross-plane residuals", count("reconciliation.json", "residuals")),
        ("`UNKNOWN` residuals", count("reconciliation.json", "unknown")),
        ("compatibility graph edges", count("compatibility-closure.json", "edges")),
        ("root-reachable entities", count("compatibility-closure.json", "reachable_entities")),
    ]
    return [(label, value) for label, value in rows if isinstance(value, int)]


def main() -> int:
    outdir = authority_atlas_dir(PRODUCTION_AUTHORITY)
    coverage = load(outdir / "coverage.json")
    parity = load(outdir / "parity-obligations.json")
    recon = load(outdir / "surface-reconciliation.json")
    index = load(ATLAS / "ATLAS_INDEX.json")
    implemented = load(ATLAS / "implemented-surface.json")
    receipts = sorted(RECEIPTS.glob("EVIDENCE_RECEIPT.*.json")) if RECEIPTS.exists() else []

    L: list[str] = []
    L.append("# openssl-rs — status (generated)")
    L.append("")
    L.append("Generated by `forensics/tools/render_status.py` from the atlas and")
    L.append("receipts. **Do not edit by hand.** Every figure below is derived from")
    L.append("evidence; see `docs/NON_CLAIMS.md`.")
    L.append("")

    if not coverage or not parity or not recon:
        L.append("> **The Phase 1 atlas has not been generated.**")
        L.append(">")
        L.append("> Run, inside the court container:")
        L.append(">")
        L.append("> ```")
        L.append("> bash docker/openssl-rs-court.sh exec bash forensics/tools/build_atlas.sh")
        L.append("> ```")
        write_text(STATUS, "\n".join(L))
        print(f"wrote {rel(STATUS)} (atlas absent)")
        return 0

    c = coverage["body"]["counts"]
    p = parity["body"]
    r = recon["body"]
    fs = r["function_vs_symbol"]

    L.append(f"## Scope of this status")
    L.append("")
    L.append(f"- Authority: **`{coverage['authority']}`** (OpenSSL {coverage['body']['version']})")
    L.append(f"- Build profile: `linux-x86_64-default-shared-legacy-notests`")
    L.append(f"- Platform: `linux-x86_64` (ELF)")
    L.append("")
    L.append("These figures describe **only** that authority, profile and platform.")
    L.append("They say nothing about other profiles, other platforms, or OpenSSL 4.x.")
    L.append("")

    L.append("## Conservation strata")
    L.append("")
    phase_state = load(FORENSICS / "phase-state.json")
    if phase_state:
        L.append("Derived from evidence by `forensics/tools/phase_state.py`; the")
        L.append("renderer does not know any phase status.")
        L.append("")
        L.append("| phase | stratum | state | blocking |")
        L.append("|---|---|---|---|")
        rows = phase_state["body"]["phases"]
        # The table lists every started stratum; the unstarted remainder is
        # summarised below. Both the membership of that remainder and its range are
        # derived -- hardcoding "4-21" made the status text contradict the JSON as
        # soon as Phase 4 started, which is exactly the kind of lie this project
        # exists to avoid.
        unstarted = [row["phase"] for row in rows if row["state"] == "not-started"]
        for row in rows:
            if row["state"] == "not-started":
                continue
            L.append(f"| {row['phase']} | {row['stratum']} | `{row['state']}` | "
                     f"{row['blocking'] or ''} |")
        L.append("")
        if unstarted:
            first, last = min(unstarted), max(unstarted)
            contiguous = unstarted == list(range(first, last + 1))
            scope = (f"strata {first}-{last}" if contiguous else
                     "strata " + ", ".join(str(p) for p in unstarted))
            L.append(f"Not started: {scope} "
                     f"({phase_state['body']['summary']['not_started']} total).")
        else:
            L.append("No stratum is `not-started`.")
    else:
        L.append("`forensics/phase-state.json` is absent; run "
                 "`forensics/tools/phase_state.py`.")
    L.append("")

    L.append("## Phase-1 public API / ABI atlas census")
    L.append("")
    L.append("The **contract**: what the installed public headers, the `.num` inventories and")
    L.append("the distribution shell promise. `cli commands` and `config files` below are the")
    L.append("Phase-1 capture's own; the Phase-22 section after this one is the whole-program")
    L.append("archaeology around them, which is where the CLI and configuration surfaces are")
    L.append("actually enumerated.")
    L.append("")
    L.append("| surface | count |")
    L.append("|---|---|")
    for k in sorted(c):
        L.append(f"| {k.replace('_', ' ')} | {c[k]} |")
    L.append("")

    L.append("## Phase-22 whole-program compatibility atlas")
    L.append("")
    figures = _phase22_figures(ATLAS / "phase22")
    if figures:
        L.append("| surface | count |")
        L.append("|---|---|")
        for label, value in figures:
            L.append(f"| {label} | {value} |")
        L.append("")
        L.append("> These are plane measurements, not contract claims: a `UNKNOWN` residual")
        L.append("> is a name Phase 22 found and did not classify, and ")
        L.append("> `docs/PHASE-22-ATLAS-SEAL.md` records the bound of the claim.")
        L.append("")
    else:
        L.append("Not generated (run the Phase-22 planes).")
        L.append("")

    L.append("## Obligations")
    L.append("")
    L.append(f"Total generated parity obligations: **{p['obligation_count']}**.")
    L.append("")
    L.append("| kind | obligations |")
    L.append("|---|---|")
    for k in sorted(p["by_kind"]):
        L.append(f"| {k} | {p['by_kind'][k]} |")
    L.append("")
    L.append("| state | obligations |")
    L.append("|---|---|")
    for k in sorted(p["by_status"]):
        L.append(f"| {k} | {p['by_status'][k]} |")
    L.append("")
    L.append("> No obligation is `PARITY_VERIFIED`, and no completion percentage here")
    L.append("> is a compatibility percentage. Phase 1 establishes *what must be")
    L.append("> proved*; the obligations above are the inventory, and implementation")
    L.append("> state is counted separately below. `UNKNOWN` is distinct from `FAIL`.")
    L.append("")

    L.append("## Implementation state")
    L.append("")
    if implemented:
        totals = implemented["body"]["totals"]
        L.append("Counted by `forensics/tools/implemented_surface.py` from the crate's")
        L.append("compiled output. **Implemented is not parity**: it means a symbol with")
        L.append("that name is defined, nothing more.")
        L.append("")
        L.append("| library | exports | implemented | scaffolded |")
        L.append("|---|---|---|---|")
        for lib in ("libcrypto", "libssl"):
            row = implemented["body"]["libraries"][lib]
            L.append(f"| {lib} | {row['authority_exports']} | {row['implemented']} "
                     f"| {row['scaffolded']} |")
        L.append(f"| **total** | **{totals['authority_exports']}** "
                 f"| **{totals['implemented']}** | **{totals['scaffolded']}** |")
        L.append("")
    else:
        L.append("`forensics/atlas/implemented-surface.json` is absent; run")
        L.append("`forensics/tools/implemented_surface.py` in the court container.")
        L.append("")

    # One section per stratum that publishes a ledger, **discovered**, rendered the
    # same way, so a reader cannot mistake which stratum a figure belongs to. A
    # stratum's ledger names, on both sides, every symbol it coordinates with another
    # stratum (`implemented_by_owner` on the deferring side, `handoffs_discharged` on
    # the receiving side), because a reader has to be able to see that the obligation
    # sits in exactly one of them. See `docs/DECISIONS.md` D21, D57 and D97.
    #
    # Discovery rather than a list: the previous version named Phases 3 and 4, so
    # Phase 5's ledger was never rendered at all and no reader could tell whether
    # that was a decision. The same reason `run_courts.py` derives its runner list.
    ledgers = []
    for path in sorted(FORENSICS.glob("phase*-obligations.json")):
        m = re.fullmatch(r"phase(\d+)-obligations\.json", path.name)
        if m is None:
            continue
        ledgers.append((int(m.group(1)), load(path),
                        f"forensics/tools/phase{m.group(1)}_obligations.py"))
    for phase, ledger, generator in ledgers:
        if not ledger:
            continue
        counts = ledger["body"]["counts"]
        L.append(f"### Phase {phase} obligation ledger")
        L.append("")
        L.append(f"Generated by `{generator}`, which fails closed: an export the")
        L.append(f"ownership atlas assigns Phase {phase}, or that an earlier stratum")
        L.append("handed it, that is neither implemented, deferred to a named later")
        L.append("phase, nor recorded as open in the stratum is an error, not a warning.")
        L.append("")
        L.append(f"* authority exports in the Phase {phase} working set: "
                 f"{counts['owned']}")
        L.append(f"* implemented: {counts['implemented']}")
        deferred_count = counts.get("deferred", counts.get("deferred_to_later_phase"))
        if deferred_count is not None:
            L.append(f"* deferred to a later phase with a stated reason: {deferred_count}")
        if "open_in_this_stratum" in counts:
            L.append(f"* open in this stratum: {counts['open_in_this_stratum']}")
        L.append("")
        # A stratum whose unit is not an export publishes its working set as contract units;
        # render both axes so a passing court cannot read as a property claim.
        L.extend(contract_unit_lines(ledger["body"]))
        by_phase: dict[int, list[dict]] = {}
        for row in ledger["body"].get("deferred", []):
            by_phase.setdefault(row["owning_phase"], []).append(row)
        for owner in sorted(by_phase):
            rows_here = by_phase[owner]
            L.append(f"Deferred to phase {owner}: "
                     + ", ".join(f"`{r['symbol']}`" for r in rows_here))
            L.append("")
            discharged = [r["symbol"] for r in rows_here if r.get("implemented_by_owner")]
            if discharged:
                L.append(f"Of those, {len(discharged)} have since been implemented by "
                         f"phase {owner}, which is where the obligation sits, so "
                         f"phase {phase} does not count them as its own work: "
                         + ", ".join(f"`{s}`" for s in discharged))
                L.append("")
        for source in sorted(ledger["body"].get("handoffs_discharged") or {}):
            symbols = ledger["body"]["handoffs_discharged"][source]
            L.append(f"Hand-offs from phase {source} discharged by this stratum: "
                     + ", ".join(f"`{s}`" for s in symbols))
            L.append("")

    L.append("## Symbol reconciliation")
    L.append("")
    L.append("| plane | count |")
    L.append("|---|---|")
    L.append(f"| `.num` declared symbols | {r['planes']['num_declared_symbols']} |")
    L.append(f"| generated version-script symbols | {r['planes']['version_script_symbols']} |")
    L.append(f"| DSO exported symbols | {r['planes']['dso_exported_symbols']} |")
    L.append(f"| declared functions | {r['planes']['declared_functions']} |")
    L.append(f"| declared and exported | {fs['declared_and_exported']} |")
    L.append(f"| declared not exported | {fs['declared_not_exported']} |")
    L.append(f"| exported not declared | {fs['exported_not_declared']} |")
    L.append("")
    L.append("### Declared-not-exported, by explanation")
    L.append("")
    L.append("| class | count |")
    L.append("|---|---|")
    for k in sorted(fs["declared_not_exported_by_class"]):
        L.append(f"| {k} | {fs['declared_not_exported_by_class'][k]} |")
    L.append("")
    L.append("### Hard residuals (must be zero)")
    L.append("")
    L.append("| library | residual class | count |")
    L.append("|---|---|---|")
    for lib in sorted(r["symbol_hard_residuals"]):
        for k, v in r["symbol_hard_residuals"][lib].items():
            L.append(f"| {lib} | {k} | {len(v) if isinstance(v, list) else v} |")
    L.append("")

    L.append("## Evidence receipts")
    L.append("")
    if index:
        L.append(f"- Atlas aggregate hash: `{index['aggregate_hash']}` "
                 f"over {index['file_count']} files")
    L.append("")
    L.append("| receipt | kind | deterministic | aggregate hash |")
    L.append("|---|---|---|---|")
    for rp in receipts:
        d = load(rp)
        if not d:
            continue
        L.append(f"| `{rp.name}` | {d['kind']} | {d['deterministic']} | "
                 f"`{d['aggregate_hash'][:16]}…` |")
    L.append("")

    L.append("## Non-claims")
    L.append("")
    for nc in (load(receipts[-1]).get("non_claims", []) if receipts else []):
        L.append(f"- {nc}")
    L.append("- No completion percentage here is a compatibility percentage.")
    L.append("- Behavioural FIPS parity is not FIPS validation.")
    L.append("")

    write_text(STATUS, "\n".join(L))
    print(f"wrote {rel(STATUS)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
