#!/usr/bin/env python3
"""openssl-rs — the seal census, generated so a seal never restates a number.

Why this exists
---------------
Each stratum's seal document (`docs/PHASE-3-CORE-RUNTIME-SEAL.md` and its
successors) carries a census: how many exports the stratum owns, how many are
implemented, how many are handed on, how many courts observed them. Those numbers
were **prose**, typed by hand at seal time, and prose does not regenerate. The
consequence was measured: `docs/PHASE-5-BN-ASN1-PEM-SEAL.md` opened by saying ASN.1
and PEM were "entirely open", that 5,271 libcrypto exports remained scaffolded, and
that the stratum owned 513 exports, while a later section of *the same document*
correctly said 155 open -- and the generated `forensics/STATUS.md` said something
else again. That is precisely the internal record contradiction this project exists
to prevent, and it happened inside the document that is supposed to be the record.

The fix is not to type the numbers more carefully. It is to stop typing them. This
tool renders **one** census for every stratum, from the ledgers and the court
results, and the seals cite it. A seal's prose is then free to be about what was
established; the arithmetic lives where it regenerates.

    forensics/STATUS.md          derived state and per-stratum ledgers
    docs/SEAL-CENSUS.md          the arithmetic a seal cites, in one place

Outputs
-------
  docs/SEAL-CENSUS.md

SPDX-License-Identifier: Apache-2.0
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_common import (  # noqa: E402
    REPO_ROOT,
    court_observations,
    has_transcript,
    rel,
)

OUT = REPO_ROOT / "docs" / "SEAL-CENSUS.md"
GENERATOR = "forensics/tools/render_seal_census.py"

# Which seal document belongs to which stratum, where one exists. A stratum with no
# seal yet is rendered from its ledger and says so, rather than being omitted: an
# omitted stratum reads as a stratum with nothing to say.
SEALS = {
    3: "docs/PHASE-3-CORE-RUNTIME-SEAL.md",
    4: "docs/PHASE-4-BIO-CONF-SEAL.md",
    5: "docs/PHASE-5-BN-ASN1-PEM-SEAL.md",
    6: "docs/PHASE-6-PROVIDER-SEAL.md",
}


def load(relpath: str):
    p = REPO_ROOT / relpath
    return json.loads(p.read_text(encoding="utf-8")) if p.is_file() else None


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.parse_args(argv)

    ownership = load("forensics/atlas/symbol-ownership.json")
    state = load("forensics/phase-state.json")
    audit = load("forensics/atlas/ownership-audit.json")

    if ownership is None or state is None:
        raise SystemExit(
            "[seal-census] forensics/atlas/symbol-ownership.json and "
            "forensics/phase-state.json are both required; run the generators first"
        )

    phases = {int(r["phase"]): r for r in state["body"]["phases"]}
    by_phase = {int(k): v for k, v in ownership["body"]["by_phase"].items()}

    ledgers: dict[int, dict] = {}
    for p in sorted((REPO_ROOT / "forensics").glob("phase*-obligations.json")):
        m = re.fullmatch(r"phase(\d+)-obligations\.json", p.name)
        if m:
            ledgers[int(m.group(1))] = json.loads(p.read_text(encoding="utf-8"))["body"]

    courts: dict[int, dict] = {}
    for p in sorted((REPO_ROOT / "artifacts").glob("phase*/COURTS.json")):
        m = re.fullmatch(r"phase(\d+)", p.parent.name)
        if m:
            courts[int(m.group(1))] = json.loads(p.read_text(encoding="utf-8"))["body"]

    surface = load("forensics/atlas/implemented-surface.json")

    L: list[str] = []
    L.append("# Seal census (generated)")
    L.append("")
    L.append("Generated by `forensics/tools/render_seal_census.py` from")
    L.append("`forensics/atlas/symbol-ownership.json`, `forensics/phase-state.json`,")
    L.append("the `forensics/phase<N>-obligations.json` ledgers and the")
    L.append("`artifacts/phase<N>/COURTS.json` results. **Do not edit by hand, and do")
    L.append("not restate these numbers in a seal.** A seal cites this document; the")
    L.append("arithmetic lives here, where it regenerates")
    L.append("(docs/DECISIONS.md D97).")
    L.append("")
    L.append("Nothing here is a parity claim. `implemented` means a symbol with that")
    L.append("name is defined; `open` means the stratum owns it and has not built it;")
    L.append("`deferred` means a recorded hand-off with the dependency named. See")
    L.append("`docs/PARITY_MODEL.md`.")
    L.append("")

    if surface is not None:
        t = surface["body"]["totals"]
        L.append("## Library totals")
        L.append("")
        L.append("| library | authority exports | implemented | scaffolded |")
        L.append("|---|---|---|---|")
        for lib in ("libcrypto", "libssl"):
            row = surface["body"]["libraries"][lib]
            L.append(f"| {lib} | {row['authority_exports']} | {row['implemented']} | "
                     f"{row['scaffolded']} |")
        L.append(f"| **total** | **{t['authority_exports']}** | "
                 f"**{t['implemented']}** | **{t['scaffolded']}** |")
        L.append("")

    L.append("## Ownership atlas, by stratum")
    L.append("")
    L.append("Every one of the authority's "
             f"{ownership['body']['universe']['exports']} exports has exactly one")
    L.append("declared owner; this is that assignment.")
    L.append("")
    L.append("| phase | stratum | state | atlas-owned | ledger owned | implemented | deferred | open |")
    L.append("|---|---|---|---|---|---|---|---|")
    for phase in sorted(phases):
        if phase < 3:
            continue
        ledger = ledgers.get(phase)
        counts = (ledger or {}).get("counts", {})
        deferred = counts.get("deferred", counts.get("deferred_to_later_phase"))
        L.append(
            f"| {phase} | {phases[phase]['stratum']} | `{phases[phase]['state']}` | "
            f"{by_phase.get(phase, 0)} | {counts.get('owned', '—')} | "
            f"{counts.get('implemented', '—')} | "
            f"{deferred if deferred is not None else '—'} | "
            f"{counts.get('open_in_this_stratum', '—')} |"
        )
    L.append("")

    for phase in sorted(ledgers):
        ledger = ledgers[phase]
        counts = ledger["counts"]
        row = phases.get(phase, {})
        L.append(f"## Phase {phase} — {row.get('stratum', '(unknown stratum)')}")
        L.append("")
        L.append(f"* state: `{row.get('state', 'unknown')}`")
        if row.get("blocking"):
            L.append(f"* blocking: {row['blocking']}")
        seal = SEALS.get(phase)
        if seal and (REPO_ROOT / seal).is_file():
            L.append(f"* seal: `{seal}`")
        else:
            L.append(f"* seal: none written yet (`{seal or 'unnamed'}`)")
        L.append(f"* ledger: `forensics/phase{phase}-obligations.json`")
        L.append(f"* atlas-owned: {counts.get('atlas_owned', counts.get('owned'))}")
        L.append(f"* owned working set: {counts['owned']}")
        L.append(f"* implemented: {counts['implemented']}")
        deferred_count = counts.get("deferred", counts.get("deferred_to_later_phase"))
        if deferred_count is not None:
            L.append(f"* deferred to a later stratum with a stated reason: "
                     f"{deferred_count}")
        if "open_in_this_stratum" in counts:
            L.append(f"* **open in this stratum: {counts['open_in_this_stratum']}**")
        L.append("")

        by_owner: dict[int, list[dict]] = {}
        for r in ledger.get("deferred", []):
            by_owner.setdefault(int(r["owning_phase"]), []).append(r)
        if by_owner:
            L.append("Deferred out, by receiving stratum:")
            L.append("")
            for owner in sorted(by_owner):
                rows = by_owner[owner]
                discharged = sum(1 for r in rows if r.get("implemented_by_owner"))
                L.append(f"* to phase {owner}: {len(rows)} symbol(s)"
                         + (f", {discharged} already discharged by that stratum"
                            if discharged else ""))
                L.append("  " + ", ".join(f"`{r['symbol']}`" for r in rows))
            L.append("")

        discharged_in = ledger.get("handoffs_discharged") or {}
        if discharged_in:
            L.append("Hand-offs received and discharged:")
            L.append("")
            for source in sorted(discharged_in):
                syms = discharged_in[source]
                L.append(f"* from phase {source}: {len(syms)} symbol(s) — "
                         + ", ".join(f"`{s}`" for s in syms))
            L.append("")

        if phase in courts:
            c = courts[phase]
            rows = c.get("courts", [])
            total = sum(court_observations(x) for x in rows)
            transcript = sum(1 for x in rows if has_transcript(x))
            L.append(f"Courts: `{c.get('all_pass') and 'all pass' or 'NOT ALL PASS'}`"
                     f", {len(rows)} court(s), "
                     f"**{total}** authority observation(s) over {transcript} "
                     f"transcript court(s).")
            if transcript != len(rows):
                L.append("")
                L.append(f"The other {len(rows) - transcript} compare ELF structure rather "
                         f"than a transcript and observe nothing line-wise; they are counted "
                         f"as zero for that reason and not by default.")
            L.append("")
            L.append("| court | verdict | observations |")
            L.append("|---|---|---|")
            for x in rows:
                n = court_observations(x)
                L.append(f"| {x['court']} | `{x['verdict']}` | "
                         f"{n if has_transcript(x) else '— (structural)'} |")
            L.append("")

    if audit is not None:
        L.append("## Atlas/ledger reconciliation")
        L.append("")
        L.append("From `forensics/atlas/ownership-audit.json`: every export the atlas")
        L.append("assigns a stratum appears in that stratum's ledger, and every ledger")
        L.append("row for another stratum's export is a hand-off that stratum recorded.")
        L.append("")
        L.append("| phase | atlas-owned | ledger rows | only in atlas | only in ledger |")
        L.append("|---|---|---|---|---|")
        for r in audit["body"]["ledger_agreement"]:
            L.append(f"| {r['phase']} | {r['atlas']} | {r['ledger']} | "
                     f"{r['only_in_atlas']} | {r['only_in_ledger']} |")
        L.append("")
        L.append(f"Problems recorded by the audit: "
                 f"{len(audit['body']['problems'])}.")
        L.append("")

    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"[seal-census] {len(ledgers)} ledger(s), {len(courts)} court result(s)")
    print(f"  -> {rel(OUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
