#!/usr/bin/env python3
"""openssl-rs — render STATUS.md from machine-readable evidence.

`docs/NON_CLAIMS.md` §1 forbids prose status: every number in STATUS.md is read
from the atlas and receipts, and the document is regenerated, never edited. If
the atlas is missing, the generator says so instead of inventing a status.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from atlas_common import (  # noqa: E402
    ATLAS,
    FORENSICS,
    PRODUCTION_AUTHORITY,
    authority_atlas_dir,
    rel,
    write_text,
)

STATUS = FORENSICS / "STATUS.md"
RECEIPTS = FORENSICS / "receipts"


def load(path: Path):
    return json.loads(path.read_text()) if path.exists() else None


def main() -> int:
    outdir = authority_atlas_dir(PRODUCTION_AUTHORITY)
    coverage = load(outdir / "coverage.json")
    parity = load(outdir / "parity-obligations.json")
    recon = load(outdir / "surface-reconciliation.json")
    index = load(ATLAS / "ATLAS_INDEX.json")
    receipts = sorted(RECEIPTS.glob("EVIDENCE_RECEIPT.*.json")) if RECEIPTS.exists() else []

    L: list[str] = []
    L.append("# openssl-rs — status (generated)")
    L.append("")
    L.append("Generated by `forensics/tools/render_status.py` from the atlas and")
    L.append("receipts. **Do not edit by hand.** Every figure below is derived from")
    L.append("evidence; see `docs/NON_CLAIMS.md`.")
    L.append("")

    if not coverage or not parity or not recon:
        L.append("> **The Phase 1 atlas has not been generated.**")
        L.append(">")
        L.append("> Run, inside the court container:")
        L.append(">")
        L.append("> ```")
        L.append("> bash docker/openssl-rs-court.sh exec bash forensics/tools/build_atlas.sh")
        L.append("> ```")
        write_text(STATUS, "\n".join(L))
        print(f"wrote {rel(STATUS)} (atlas absent)")
        return 0

    c = coverage["body"]["counts"]
    p = parity["body"]
    r = recon["body"]
    fs = r["function_vs_symbol"]

    L.append(f"## Scope of this status")
    L.append("")
    L.append(f"- Authority: **`{coverage['authority']}`** (OpenSSL {coverage['body']['version']})")
    L.append(f"- Build profile: `linux-x86_64-default-shared-legacy-notests`")
    L.append(f"- Platform: `linux-x86_64` (ELF)")
    L.append("")
    L.append("These figures describe **only** that authority, profile and platform.")
    L.append("They say nothing about other profiles, other platforms, or OpenSSL 4.x.")
    L.append("")

    L.append("## Conservation strata")
    L.append("")
    L.append("| phase | stratum | state |")
    L.append("|---|---|---|")
    L.append("| 0 | constitution | complete |")
    L.append("| 1 | archaeology / API / ABI atlas | in progress |")
    L.append("| 2–21 | (see docs/RELEASE_GATES.md) | not started |")
    L.append("")

    L.append("## Atlas census")
    L.append("")
    L.append("| surface | count |")
    L.append("|---|---|")
    for k in sorted(c):
        L.append(f"| {k.replace('_', ' ')} | {c[k]} |")
    L.append("")

    L.append("## Obligations")
    L.append("")
    L.append(f"Total generated parity obligations: **{p['obligation_count']}**.")
    L.append("")
    L.append("| kind | obligations |")
    L.append("|---|---|")
    for k in sorted(p["by_kind"]):
        L.append(f"| {k} | {p['by_kind'][k]} |")
    L.append("")
    L.append("| state | obligations |")
    L.append("|---|---|")
    for k in sorted(p["by_status"]):
        L.append(f"| {k} | {p['by_status'][k]} |")
    L.append("")
    L.append("> No obligation is `PARITY_VERIFIED`. Phase 1 establishes *what must")
    L.append("> be proved*; it proves nothing about the candidate, which does not yet")
    L.append("> implement any subsystem. `UNKNOWN` is distinct from `FAIL`.")
    L.append("")

    L.append("## Symbol reconciliation")
    L.append("")
    L.append("| plane | count |")
    L.append("|---|---|")
    L.append(f"| `.num` declared symbols | {r['planes']['num_declared_symbols']} |")
    L.append(f"| generated version-script symbols | {r['planes']['version_script_symbols']} |")
    L.append(f"| DSO exported symbols | {r['planes']['dso_exported_symbols']} |")
    L.append(f"| declared functions | {r['planes']['declared_functions']} |")
    L.append(f"| declared and exported | {fs['declared_and_exported']} |")
    L.append(f"| declared not exported | {fs['declared_not_exported']} |")
    L.append(f"| exported not declared | {fs['exported_not_declared']} |")
    L.append("")
    L.append("### Declared-not-exported, by explanation")
    L.append("")
    L.append("| class | count |")
    L.append("|---|---|")
    for k in sorted(fs["declared_not_exported_by_class"]):
        L.append(f"| {k} | {fs['declared_not_exported_by_class'][k]} |")
    L.append("")
    L.append("### Hard residuals (must be zero)")
    L.append("")
    L.append("| library | residual class | count |")
    L.append("|---|---|---|")
    for lib in sorted(r["symbol_hard_residuals"]):
        for k, v in r["symbol_hard_residuals"][lib].items():
            L.append(f"| {lib} | {k} | {len(v) if isinstance(v, list) else v} |")
    L.append("")

    L.append("## Evidence receipts")
    L.append("")
    if index:
        L.append(f"- Atlas aggregate hash: `{index['aggregate_hash']}` "
                 f"over {index['file_count']} files")
    L.append("")
    L.append("| receipt | kind | deterministic | aggregate hash |")
    L.append("|---|---|---|---|")
    for rp in receipts:
        d = load(rp)
        if not d:
            continue
        L.append(f"| `{rp.name}` | {d['kind']} | {d['deterministic']} | "
                 f"`{d['aggregate_hash'][:16]}…` |")
    L.append("")

    L.append("## Non-claims")
    L.append("")
    for nc in (load(receipts[-1]).get("non_claims", []) if receipts else []):
        L.append(f"- {nc}")
    L.append("- No completion percentage here is a compatibility percentage.")
    L.append("- Behavioural FIPS parity is not FIPS validation.")
    L.append("")

    write_text(STATUS, "\n".join(L))
    print(f"wrote {rel(STATUS)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
