//! Phase 5 — `ASN1_TYPE`: the type/value pair `ANY` is.
//!
//! `ASN1_TYPE` is what an `ANY` item decodes into and what
//! `ASN1_ITEM_TEMPLATE(ASN1_TYPE)` is built from. It is a selector plus a union whose
//! members are all pointers except `ASN1_BOOLEAN`, which occupies the union's first
//! four bytes — so a boolean round-trips through the same storage a pointer would, and
//! two of the functions here depend on that.
//!
//! The file has three groups, and the split matters to what a caller observes:
//!
//! * `ASN1_TYPE_new` and `ASN1_TYPE_free` are the allocator pair the item machinery
//!   generates from `IMPLEMENT_ASN1_FUNCTIONS_fname(ASN1_TYPE, ASN1_ANY, ASN1_TYPE)`.
//!   They are the item layer over `ASN1_ANY_it`, so a new value is a zeroed
//!   `ASN1_TYPE` whose selector is `V_ASN1_UNDEF` and whose union is null.
//! * `ASN1_TYPE_get`, `ASN1_TYPE_set` and `ASN1_TYPE_set1` are the accessors. `get`
//!   answers `0` rather than the stored selector when the union is null and the
//!   selector is neither `BOOLEAN` nor `NULL`, because a selector with no value is not
//!   a value. `set` releases whatever the union held **before** overwriting it, which
//!   is what makes re-typing an existing `ASN1_TYPE` leak-free.
//! * `ASN1_TYPE_cmp`, `ASN1_TYPE_pack_sequence` and `ASN1_TYPE_unpack_sequence` are the
//!   comparison and the pack/unpack pair. `cmp` answers `-1` for a null argument or a
//!   type mismatch, and `0` for two `NULL`s, because a `NULL` has no content to
//!   compare.
//!
//! ## The `set` release is the interesting one
//!
//! `ASN1_TYPE_set(a, type, value)` calls `ossl_asn1_primitive_free((ASN1_VALUE **)&a,
//! NULL, 0)` — with a **null item**, which is the `ASN1_TYPE` arm of the free path. So
//! setting a type on a value that already holds one releases the old one through the
//! same code the item layer uses, and the release is skipped when the old selector was
//! `BOOLEAN` or `NULL`, because neither owns a pointer.
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::{c_int, c_long, c_uchar, c_void};

use crate::asn1::asn_pack::{ASN1_item_pack, ASN1_item_unpack};
use crate::asn1::d2i::item_d2i;
use crate::asn1::fre::primitive_free;
use crate::asn1::i2d::item_i2d;
use crate::asn1::items::ASN1_ANY_it;
use crate::asn1::layout::*;
use crate::asn1::string::{ASN1_STRING_cmp, ASN1_STRING_dup};
use crate::ffi::guard_ffi;
use crate::runtime::obj::{Asn1Object, OBJ_cmp, OBJ_dup};

/// `ASN1_TYPE *ASN1_TYPE_new(void)`
///
/// Generated by `tasn_typ.c`'s `IMPLEMENT_ASN1_FUNCTIONS_fname(ASN1_TYPE, ASN1_ANY,
/// ASN1_TYPE)` over `ASN1_ANY_it`, so it is the item allocator rather than a bespoke
/// one: the value is zeroed, the object's own bytes are owned, and a failure raises
/// from `tasn_new.c`.
///
/// A freshly allocated `ASN1_TYPE` has selector `V_ASN1_UNDEF` and a null union —
/// which is why `ASN1_TYPE_get` answers `0` for one.
#[no_mangle]
pub extern "C" fn ASN1_TYPE_new() -> *mut Asn1Type {
    guard_ffi(core::ptr::null_mut(), || {
        // SAFETY: `ASN1_ANY_it()` answers a static item, so the item layer's contract
        // is satisfied.
        unsafe { crate::asn1::new::ASN1_item_new(ASN1_ANY_it()) }.cast::<Asn1Type>()
    })
}

/// `void ASN1_TYPE_free(ASN1_TYPE *a)`
///
/// The free half of the pair above. A null argument is legal and does nothing, which
/// is what `err:` tails in the decoder rely on.
///
/// # Safety
///
/// `a` must be null or a live `ASN1_TYPE` owned by the caller.
#[no_mangle]
pub unsafe extern "C" fn ASN1_TYPE_free(a: *mut Asn1Type) {
    guard_ffi((), || {
        // SAFETY: the caller's contract; `ASN1_ANY_it()` answers a static item.
        unsafe { crate::asn1::fre::ASN1_item_free(a.cast::<c_void>(), ASN1_ANY_it()) }
    });
}

/// `int ASN1_TYPE_get(const ASN1_TYPE *a)`
///
/// The selector, except that a selector with no value behind it answers `0`. A
/// `BOOLEAN` and a `NULL` are the two cases where the union is not a pointer, so they
/// answer their own selector even when the union reads null.
///
/// # Safety
///
/// `a` must be a live `ASN1_TYPE`.
#[no_mangle]
pub unsafe extern "C" fn ASN1_TYPE_get(a: *const Asn1Type) -> c_int {
    guard_ffi(0, || {
        // SAFETY: `a` is the caller's live value.
        let type_ = unsafe { (*a).type_ };
        if type_ == V_ASN1_BOOLEAN || type_ == V_ASN1_NULL {
            return type_;
        }
        // SAFETY: `a` is live.
        if unsafe { (*a).value.ptr }.is_null() {
            0
        } else {
            type_
        }
    })
}

/// `void ASN1_TYPE_set(ASN1_TYPE *a, int type, void *value)`
///
/// Overwrites the pair, releasing whatever the union held first. The release is
/// skipped when the **old** selector was `BOOLEAN` or `NULL`, because neither owns a
/// pointer — a `BOOLEAN`'s value is in the union's bytes and a `NULL`'s is the
/// sentinel the decoder writes.
///
/// A `BOOLEAN` value is stored through the union's first four bytes as `0xff` for true
/// and `0` for false, so any non-null `value` means true. That is not a normalisation
/// invented here: the union is read back as an `int` by the encoder, so the exact byte
/// pattern is what a caller sees.
///
/// # Safety
///
/// `a` must be a live `ASN1_TYPE`. `value` must be appropriate for `type`: an
/// `ASN1_OBJECT *`, an `ASN1_STRING *`, or null. Ownership of `value` passes to `a`.
#[no_mangle]
pub unsafe extern "C" fn ASN1_TYPE_set(a: *mut Asn1Type, type_: c_int, value: *mut c_void) {
    guard_ffi((), || {
        // SAFETY: `a` is the caller's live value.
        let old = unsafe { (*a).type_ };
        if old != V_ASN1_BOOLEAN && old != V_ASN1_NULL {
            // SAFETY: `a` is live.
            let held = unsafe { (*a).value.ptr };
            if !held.is_null() {
                // The authority passes the address of its *pointer* local, and the
                // null item selects the `ASN1_TYPE` arm of the free path. The redirect
                // inside that arm means only the union is touched, never `a` itself.
                let mut tmp: *mut Asn1Type = a;
                // SAFETY: `tmp` is this frame's slot holding the caller's value.
                unsafe {
                    primitive_free(
                        (&mut tmp as *mut *mut Asn1Type).cast::<*mut c_void>(),
                        core::ptr::null(),
                        0,
                    )
                };
            }
        }
        // SAFETY: `a` is live.
        unsafe { (*a).type_ = type_ };
        // SAFETY: `a` is live and the union is writable.
        unsafe {
            if type_ == V_ASN1_BOOLEAN {
                (*a).value.boolean = if value.is_null() { 0 } else { 0xff };
            } else {
                (*a).value.ptr = value;
            }
        }
    });
}

/// `int ASN1_TYPE_set1(ASN1_TYPE *a, int type, const void *value)`
///
/// `ASN1_TYPE_set` with a **copy** of the value. An `OBJECT` is duplicated with
/// `OBJ_dup` and everything else with `ASN1_STRING_dup`; a null value or a `BOOLEAN`
/// is passed straight through, because neither is a structure to duplicate. A
/// duplication failure leaves the value untouched and answers 0.
///
/// # Safety
///
/// `a` must be a live `ASN1_TYPE`. `value` must be null or a live `ASN1_OBJECT` or
/// `ASN1_STRING`, depending on `type`. The copy, not `value`, becomes `a`'s.
#[no_mangle]
pub unsafe extern "C" fn ASN1_TYPE_set1(
    a: *mut Asn1Type,
    type_: c_int,
    value: *const c_void,
) -> c_int {
    guard_ffi(0, || {
        if value.is_null() || type_ == V_ASN1_BOOLEAN {
            // SAFETY: the caller's contract.
            unsafe { ASN1_TYPE_set(a, type_, value.cast_mut()) };
        } else if type_ == V_ASN1_OBJECT {
            // SAFETY: `type_ == V_ASN1_OBJECT` means `value` is an `ASN1_OBJECT`.
            let odup = unsafe { OBJ_dup(value.cast::<Asn1Object>()) };
            if odup.is_null() {
                return 0;
            }
            // SAFETY: the caller's contract; ownership of the copy passes to `a`.
            unsafe { ASN1_TYPE_set(a, type_, odup.cast::<c_void>()) };
        } else {
            // SAFETY: any other selector means `value` is an `ASN1_STRING`.
            let sdup = unsafe { ASN1_STRING_dup(value.cast::<Asn1String>()) };
            if sdup.is_null() {
                return 0;
            }
            // SAFETY: as above.
            unsafe { ASN1_TYPE_set(a, type_, sdup.cast::<c_void>()) };
        }
        1
    })
}

/// `int ASN1_TYPE_cmp(const ASN1_TYPE *a, const ASN1_TYPE *b)`
///
/// 0 when equal, non-zero otherwise, and `-1` for a null argument or a type mismatch.
/// The type mismatch answer is `-1` rather than "different", so a caller can tell
/// "these are the same kind of thing but differ" from "these are not comparable".
/// Two `NULL`s are equal because a `NULL` has no content.
///
/// # Safety
///
/// `a` and `b` must be null or live `ASN1_TYPE` values.
#[no_mangle]
pub unsafe extern "C" fn ASN1_TYPE_cmp(a: *const Asn1Type, b: *const Asn1Type) -> c_int {
    guard_ffi(-1, || {
        if a.is_null() || b.is_null() {
            return -1;
        }
        // SAFETY: both are live per the check above.
        let (ta, tb) = unsafe { ((*a).type_, (*b).type_) };
        if ta != tb {
            return -1;
        }
        match ta {
            V_ASN1_OBJECT => {
                // SAFETY: both values are `ASN1_OBJECT`s in this arm.
                unsafe {
                    OBJ_cmp(
                        (*a).value.ptr.cast::<Asn1Object>(),
                        (*b).value.ptr.cast::<Asn1Object>(),
                    )
                }
            }
            V_ASN1_BOOLEAN => {
                // SAFETY: the union's first four bytes hold the boolean.
                unsafe { (*a).value.boolean - (*b).value.boolean }
            }
            V_ASN1_NULL => {
                // A `NULL` has no content, so two of them are equal.
                0
            }
            _ => {
                // Everything else is `ASN1_STRING`-based, including
                // `V_ASN1_SEQUENCE`, which holds the original bytes in a string.
                // SAFETY: both values are `ASN1_STRING`s in this arm.
                unsafe {
                    ASN1_STRING_cmp(
                        (*a).value.ptr.cast::<Asn1String>(),
                        (*b).value.ptr.cast::<Asn1String>(),
                    )
                }
            }
        }
    })
}

/// `ASN1_TYPE *ASN1_TYPE_pack_sequence(const ASN1_ITEM *it, void *s, ASN1_TYPE **t)`
///
/// Packs `s` through `it` into an octet string and wraps it as a `V_ASN1_SEQUENCE`
/// value. The optional `t` is an in/out parameter with three cases, and the difference
/// is observable: a null `t` allocates a fresh `ASN1_TYPE` the caller owns, `*t == NULL`
/// allocates one and *writes it back*, and a non-null `*t` reuses the caller's value.
/// The pack's octet string is freed if the fresh `ASN1_TYPE` could not be allocated.
///
/// # Safety
///
/// `it` must be a live item. `s` must be null or a live value of `it`'s type. `t` must
/// be null or point to a slot holding null or a live `ASN1_TYPE`.
#[no_mangle]
pub unsafe extern "C" fn ASN1_TYPE_pack_sequence(
    it: *const Asn1Item,
    s: *mut c_void,
    t: *mut *mut Asn1Type,
) -> *mut Asn1Type {
    guard_ffi(core::ptr::null_mut(), || {
        // SAFETY: the caller's contract; a null octet-string slot asks for a fresh one.
        let oct = unsafe { ASN1_item_pack(s, it, core::ptr::null_mut()) };
        if oct.is_null() {
            return core::ptr::null_mut();
        }
        let rt: *mut Asn1Type;
        if !t.is_null() {
            // SAFETY: `t` is the caller's live slot per the caller's contract.
            if !unsafe { *t }.is_null() {
                // SAFETY: as above.
                rt = unsafe { *t };
            } else {
                rt = ASN1_TYPE_new();
                if rt.is_null() {
                    // SAFETY: `oct` is a fresh octet string this call owns.
                    unsafe { crate::asn1::string::ASN1_STRING_free(oct) };
                    return core::ptr::null_mut();
                }
                // SAFETY: the caller's slot is writable.
                unsafe { *t = rt };
            }
        } else {
            rt = ASN1_TYPE_new();
            if rt.is_null() {
                // SAFETY: `oct` is a fresh octet string this call owns.
                unsafe { crate::asn1::string::ASN1_STRING_free(oct) };
                return core::ptr::null_mut();
            }
        }
        // SAFETY: `rt` is live and takes ownership of `oct`.
        unsafe { ASN1_TYPE_set(rt, V_ASN1_SEQUENCE, oct.cast::<c_void>()) };
        rt
    })
}

/// `void *ASN1_TYPE_unpack_sequence(const ASN1_ITEM *it, const ASN1_TYPE *t)`
///
/// The inverse: unpacks a `V_ASN1_SEQUENCE` value through `it`. A null `t`, a value of
/// another type, and a `SEQUENCE` whose union is null all answer null without raising,
/// because each is a caller mistake the authority treats as "nothing to unpack".
///
/// # Safety
///
/// `it` must be a live item. `t` must be null or a live `ASN1_TYPE`.
#[no_mangle]
pub unsafe extern "C" fn ASN1_TYPE_unpack_sequence(
    it: *const Asn1Item,
    t: *const Asn1Type,
) -> *mut c_void {
    guard_ffi(core::ptr::null_mut(), || {
        if t.is_null() {
            return core::ptr::null_mut();
        }
        // SAFETY: `t` is live per the check above.
        let (type_, seq) = unsafe { ((*t).type_, (*t).value.ptr) };
        if type_ != V_ASN1_SEQUENCE || seq.is_null() {
            return core::ptr::null_mut();
        }
        // SAFETY: the value holds an `ASN1_STRING` of encoded content in this arm.
        unsafe { ASN1_item_unpack(seq.cast::<Asn1String>(), it) }
    })
}

/// `ASN1_TYPE *d2i_ASN1_TYPE(ASN1_TYPE **a, const unsigned char **pp, long len)`
///
/// The same wrapper shape every other generated `d2i_*` has, over `ASN1_ANY_it`. The
/// null-slot redirect belongs to the shared decoder, so `a` is passed through
/// untouched — including when it is null.
///
/// # Safety
///
/// `pp` must point to a slot holding a readable pointer to `len` bytes. `a` must be
/// null or point to a slot holding null or a live `ASN1_TYPE`.
#[no_mangle]
pub unsafe extern "C" fn d2i_ASN1_TYPE(
    a: *mut *mut Asn1Type,
    pp: *mut *const c_uchar,
    len: c_long,
) -> *mut Asn1Type {
    guard_ffi(core::ptr::null_mut(), || {
        // SAFETY: the caller's contract; `ASN1_ANY_it()` answers a static item.
        unsafe { item_d2i(a.cast::<*mut Asn1String>(), pp, len, ASN1_ANY_it()) }.cast::<Asn1Type>()
    })
}

/// `int i2d_ASN1_TYPE(const ASN1_TYPE *a, unsigned char **out)`
///
/// The encode half. A null `a` is legal here — but `ASN1_ANY_it` is not the `BOOLEAN`
/// exception, so an absent value reports `0` rather than encoding a null.
///
/// # Safety
///
/// `a` must be null or a live `ASN1_TYPE`. `out` must be null or point to a slot
/// holding null or a pointer with room for the encoding.
#[no_mangle]
pub unsafe extern "C" fn i2d_ASN1_TYPE(a: *const Asn1Type, out: *mut *mut c_uchar) -> c_int {
    guard_ffi(0, || {
        // SAFETY: as the decode above, read in the other direction.
        unsafe { item_i2d(a.cast::<Asn1String>(), out, ASN1_ANY_it()) }
    })
}
