//! Phase 5 — the `tasn_typ.c` function family: the `d2i_*`/`i2d_*` wrappers for
//! the coded types, and `ASN1_NULL`'s allocator.
//!
//! The authority generates these with three macros, and every one of them is a
//! one-line forward to the shared machinery:
//!
//! ```text
//! IMPLEMENT_ASN1_ENCODE_FUNCTIONS_fname(stname, itname, fname)
//!     stname *d2i_##fname(stname **a, const unsigned char **in, long len)
//!     { return (stname *)ASN1_item_d2i((ASN1_VALUE **)a, in, len, ASN1_ITEM_rptr(itname)); }
//!     int i2d_##fname(const stname *a, unsigned char **out)
//!     { return ASN1_item_i2d((const ASN1_VALUE *)a, out, ASN1_ITEM_rptr(itname)); }
//! ```
//!
//! so there is no per-type behaviour here at all. That is the point: the type's
//! behaviour is its [`crate::asn1::items`] descriptor, and this module is the
//! naming layer that binds a symbol to one.
//!
//! Two families share the file because the authority groups them: the plain types
//! (`ASN1_OCTET_STRING` through `ASN1_BMPSTRING`, `ASN1_NULL`, `ASN1_OBJECT`) and
//! the multi-string types (`ASN1_PRINTABLE`, `DIRECTORYSTRING`, `DISPLAYTEXT`,
//! `ASN1_TIME`), which are declared `DECLARE_ASN1_FUNCTIONS_name(ASN1_STRING, X)`
//! and so take an `ASN1_STRING **` rather than an `X **`. The macro below carries
//! both spellings because the difference is visible in the installed headers.
//!
//! ## Why the null redirect is inside the shared decoder
//!
//! `d2i_*(NULL, pp, len)` is legal, and it is the *item* machinery that
//! accommodates it — `ASN1_item_d2i` redirects a null value slot to a local. The
//! wrappers therefore pass `a` through untouched, including when it is null, and
//! [`crate::asn1::d2i::item_d2i`] is where the redirect happens. Doing it here
//! instead would mean twenty places could get it wrong.
//!
//! ## `ASN1_NULL`
//!
//! `typedef int ASN1_NULL`, so `ASN1_NULL_new` answers an `int *` and its value is
//! the sentinel `1` — an address that is never dereferenced, because a NULL's
//! content is empty and `ASN1_NULL_free` is a no-op. That is not a shortcut
//! invented here: `asn1_primitive_new`'s `V_ASN1_NULL` arm stores
//! `(ASN1_VALUE *)1` and `ossl_asn1_primitive_free`'s is `break`.
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::{c_int, c_long, c_uchar};

use crate::asn1::d2i::item_d2i;
use crate::asn1::i2d::item_i2d;
use crate::asn1::items::*;
use crate::asn1::layout::Asn1String;
use crate::ffi::guard_ffi;

/// Declare one `d2i_*`/`i2d_*` pair over a named item.
///
/// The two identifiers are written out at each use because a macro cannot build a
/// `#[no_mangle]` symbol from another token — the constraint
/// [`crate::asn1::string`]'s `define_new_free` records. The macro exists so the
/// *shape* is stated once: a null-tolerant decode through the shared decoder, and
/// an encode whose three output conventions live in
/// [`crate::asn1::i2d::item_i2d`].
macro_rules! item_functions {
    ($getter:ident, $d2i:ident, $i2d:ident, $ty:literal, $origin:literal) => {
        #[doc = concat!(
                    "`", $ty, " *", stringify!($d2i), "(", $ty,
                    " **a, const unsigned char **pp, long len)`"
                )]
        ///
        #[doc = concat!(
                    "Generated by `tasn_typ.c`'s `IMPLEMENT_ASN1_ENCODE_FUNCTIONS_name(", $origin,
                    ", ", $origin, ")` over the item `", stringify!($getter), "`."
                )]
        ///
        /// # Safety
        ///
        /// `pp` must point to a slot holding a readable pointer to `len` bytes.
        /// `a` must be null or point to a slot holding null or a live value of this
        /// type.
        #[no_mangle]
        pub unsafe extern "C" fn $d2i(
            a: *mut *mut Asn1String,
            pp: *mut *const c_uchar,
            len: c_long,
        ) -> *mut Asn1String {
            guard_ffi(core::ptr::null_mut(), || {
                // SAFETY: the caller's contract; `$getter()` answers a static item.
                unsafe { item_d2i(a, pp, len, $getter()) }
            })
        }

        #[doc = concat!("`int ", stringify!($i2d), "(const ", $ty, " *a, unsigned char **out)`")]
        ///
        #[doc = concat!(
                    "The encode half of the pair above. `out == NULL` answers the length, ",
                    "`*out == NULL` allocates, and otherwise the caller's buffer is written ",
                    "and its pointer advanced."
                )]
        ///
        /// # Safety
        ///
        /// `a` must be null or a live value of this type. `out` must be null or
        /// point to a slot holding null or a pointer with room for the encoding.
        #[no_mangle]
        pub unsafe extern "C" fn $i2d(a: *const Asn1String, out: *mut *mut c_uchar) -> c_int {
            guard_ffi(0, || {
                // SAFETY: the caller's contract; `$getter()` answers a static item.
                unsafe { item_i2d(a, out, $getter()) }
            })
        }
    };
}

// ---------------------------------------------------------------------------
// The plain types — `IMPLEMENT_ASN1_STRING_FUNCTIONS`
// ---------------------------------------------------------------------------

item_functions!(
    ASN1_OCTET_STRING_it,
    d2i_ASN1_OCTET_STRING,
    i2d_ASN1_OCTET_STRING,
    "ASN1_OCTET_STRING",
    "ASN1_OCTET_STRING"
);
item_functions!(
    ASN1_INTEGER_it,
    d2i_ASN1_INTEGER,
    i2d_ASN1_INTEGER,
    "ASN1_INTEGER",
    "ASN1_INTEGER"
);
item_functions!(
    ASN1_ENUMERATED_it,
    d2i_ASN1_ENUMERATED,
    i2d_ASN1_ENUMERATED,
    "ASN1_ENUMERATED",
    "ASN1_ENUMERATED"
);
item_functions!(
    ASN1_BIT_STRING_it,
    d2i_ASN1_BIT_STRING,
    i2d_ASN1_BIT_STRING,
    "ASN1_BIT_STRING",
    "ASN1_BIT_STRING"
);
item_functions!(
    ASN1_UTF8STRING_it,
    d2i_ASN1_UTF8STRING,
    i2d_ASN1_UTF8STRING,
    "ASN1_UTF8STRING",
    "ASN1_UTF8STRING"
);
item_functions!(
    ASN1_PRINTABLESTRING_it,
    d2i_ASN1_PRINTABLESTRING,
    i2d_ASN1_PRINTABLESTRING,
    "ASN1_PRINTABLESTRING",
    "ASN1_PRINTABLESTRING"
);
item_functions!(
    ASN1_T61STRING_it,
    d2i_ASN1_T61STRING,
    i2d_ASN1_T61STRING,
    "ASN1_T61STRING",
    "ASN1_T61STRING"
);
item_functions!(
    ASN1_IA5STRING_it,
    d2i_ASN1_IA5STRING,
    i2d_ASN1_IA5STRING,
    "ASN1_IA5STRING",
    "ASN1_IA5STRING"
);
item_functions!(
    ASN1_GENERALSTRING_it,
    d2i_ASN1_GENERALSTRING,
    i2d_ASN1_GENERALSTRING,
    "ASN1_GENERALSTRING",
    "ASN1_GENERALSTRING"
);
item_functions!(
    ASN1_UTCTIME_it,
    d2i_ASN1_UTCTIME,
    i2d_ASN1_UTCTIME,
    "ASN1_UTCTIME",
    "ASN1_UTCTIME"
);
item_functions!(
    ASN1_GENERALIZEDTIME_it,
    d2i_ASN1_GENERALIZEDTIME,
    i2d_ASN1_GENERALIZEDTIME,
    "ASN1_GENERALIZEDTIME",
    "ASN1_GENERALIZEDTIME"
);
item_functions!(
    ASN1_VISIBLESTRING_it,
    d2i_ASN1_VISIBLESTRING,
    i2d_ASN1_VISIBLESTRING,
    "ASN1_VISIBLESTRING",
    "ASN1_VISIBLESTRING"
);
item_functions!(
    ASN1_UNIVERSALSTRING_it,
    d2i_ASN1_UNIVERSALSTRING,
    i2d_ASN1_UNIVERSALSTRING,
    "ASN1_UNIVERSALSTRING",
    "ASN1_UNIVERSALSTRING"
);
item_functions!(
    ASN1_BMPSTRING_it,
    d2i_ASN1_BMPSTRING,
    i2d_ASN1_BMPSTRING,
    "ASN1_BMPSTRING",
    "ASN1_BMPSTRING"
);

// ---------------------------------------------------------------------------
// The multi-string types — `IMPLEMENT_ASN1_FUNCTIONS_name(ASN1_STRING, X)`
// ---------------------------------------------------------------------------

item_functions!(
    ASN1_PRINTABLE_it,
    d2i_ASN1_PRINTABLE,
    i2d_ASN1_PRINTABLE,
    "ASN1_STRING",
    "ASN1_PRINTABLE"
);
item_functions!(
    DIRECTORYSTRING_it,
    d2i_DIRECTORYSTRING,
    i2d_DIRECTORYSTRING,
    "ASN1_STRING",
    "DIRECTORYSTRING"
);
item_functions!(
    DISPLAYTEXT_it,
    d2i_DISPLAYTEXT,
    i2d_DISPLAYTEXT,
    "ASN1_STRING",
    "DISPLAYTEXT"
);
item_functions!(
    ASN1_TIME_it,
    d2i_ASN1_TIME,
    i2d_ASN1_TIME,
    "ASN1_STRING",
    "ASN1_TIME"
);

// ---------------------------------------------------------------------------
// `ASN1_NULL` — the sentinel the authority stores and never dereferences
// ---------------------------------------------------------------------------

/// `ASN1_NULL *ASN1_NULL_new(void)`
///
/// Answers the sentinel `1`, not an allocation. `asn1_primitive_new`'s
/// `V_ASN1_NULL` arm stores `(ASN1_VALUE *)1` through the value slot, and
/// `ossl_asn1_primitive_free`'s is a bare `break`, so a caller that frees one and a
/// caller that never does are indistinguishable — which is the contract.
///
/// The clippy lint below wants `ptr::dangling_mut`, whose address comes from the
/// type's *alignment* — 4 for an `int`, not 1. The authority's sentinel is
/// literally `(ASN1_VALUE *)1`, and `ASN1_NULL_new()`'s result is a value a caller
/// can compare and print, so the lint's suggestion would change observable
/// behaviour.
#[allow(clippy::manual_dangling_ptr)]
#[no_mangle]
pub extern "C" fn ASN1_NULL_new() -> *mut c_int {
    1 as *mut c_int
}

/// `void ASN1_NULL_free(ASN1_NULL *a)`
///
/// A no-op, for the reason above: there is nothing behind the sentinel to release.
/// It is still an exported symbol because a caller must be able to call it, and
/// still takes its argument because the authority's signature does.
///
/// # Safety
///
/// The argument is never dereferenced, so any `ASN1_NULL *` is acceptable; the
/// contract is stated for the documented signature's sake.
#[no_mangle]
pub unsafe extern "C" fn ASN1_NULL_free(a: *mut c_int) {
    // The authority's `ossl_asn1_primitive_free` reaches a bare `break` for
    // `V_ASN1_NULL`, so nothing is released and nothing is read. The parameter is
    // named and dropped rather than omitted so the symbol's arity matches.
    let _ = a;
}

/// `ASN1_NULL *d2i_ASN1_NULL(ASN1_NULL **a, const unsigned char **pp, long len)`
///
/// `ASN1_NULL` is `int`, so the value slot is an `int **`; the decoder stores the
/// sentinel through it exactly as `ASN1_NULL_new` answers it.
///
/// # Safety
///
/// `pp` must point to a slot holding a readable pointer to `len` bytes. `a` must
/// be null or point to a slot holding null.
#[no_mangle]
pub unsafe extern "C" fn d2i_ASN1_NULL(
    a: *mut *mut c_int,
    pp: *mut *const c_uchar,
    len: c_long,
) -> *mut c_int {
    guard_ffi(core::ptr::null_mut(), || {
        // SAFETY: an `int **` and a value slot have the same representation, and
        // the caller's contract covers both readings.
        let ret = unsafe { item_d2i(a.cast::<*mut Asn1String>(), pp, len, ASN1_NULL_it()) };
        ret.cast::<c_int>()
    })
}

/// `int i2d_ASN1_NULL(const ASN1_NULL *a, unsigned char **out)`
///
/// A NULL's content is empty, so this writes one header of length zero. Note that
/// the value is never read: `asn1_ex_i2c`'s `V_ASN1_NULL` arm sets `cont = NULL,
/// len = 0` without dereferencing it. A **null** `a` is a different case — the
/// item's `utype` is not the `BOOLEAN` exception, so the shared encoder reports the
/// value absent and this answers 0 without writing anything.
///
/// # Safety
///
/// `a` must be null or an `ASN1_NULL *`. `out` must be null or point to a slot
/// holding null or a pointer with room for the encoding.
#[no_mangle]
pub unsafe extern "C" fn i2d_ASN1_NULL(a: *const c_int, out: *mut *mut c_uchar) -> c_int {
    guard_ffi(0, || {
        // SAFETY: as the decode above, read in the other direction.
        unsafe { item_i2d(a.cast::<Asn1String>(), out, ASN1_NULL_it()) }
    })
}
