//! Phase 4 — CONF: `crypto/conf/conf_def.c`, the default configuration method.
//!
//! This is the largest single behavioural surface in the stratum, because
//! `openssl.cnf` is *input that people write*: its grammar is a contract, not an
//! implementation detail. Everything below is reachable from a configuration
//! file an administrator or an application may hand to `NCONF_load`, and every
//! branch here is drivable by a file.
//!
//! ## The grammar, as the authority defines it
//!
//! * Lines are read with `BIO_gets` into a `BUF_MEM` that accumulates. A line
//!   that fills the read buffer without a newline, or that ends in a lone `\`, is
//!   *continued*: the next read appends to the same logical line. The two cases
//!   are the same `again` flag because both mean "do not parse yet".
//! * A UTF-8 BOM is stripped, and only on the first read.
//! * `#` and `;` start comments — but only through the two character-class
//!   tables, and the default table does **not** mark `;` as a comment at all.
//!   `CONF_type_win32` does, which is the entire observable difference between
//!   `NCONF_default()` and `NCONF_WIN32()`.
//! * `[section]` starts a section. A key may be qualified as `section::key`, and
//!   an unqualified key belongs to the section the *last* bracket opened — which
//!   is why the parser carries a `section` string that `str_copy` owns and
//!   reallocates.
//! * `name = value`, with the `=` optional after `.pragma`/`.include`.
//! * Values are bare or quoted with `'`/`"`, with `\r \n \b \t` escapes, and with
//!   `$name`, `${name}`, `$(name)` and `$section::name` expansion capped by
//!   `MAX_CONF_VALUE_LENGTH`.
//! * `.pragma dollarid|abspath|includedir` and `.include` of a file *or a
//!   directory*. Unknown pragmas are ignored; a missing `=` is an error.
//!
//! ## What the court is for
//!
//! Almost every one of those rules has a plausible-but-wrong implementation, and
//! the authority's source contains the traps: the BOM strip only on the first
//! call, the `key > 127` rejection in `is_keytype`, the "second last char is not
//! `\\`" condition on continuation, the trailing-`\r\n`-only trim loop, the
//! `buf->length` rather than content length in the expansion cap, and the fact
//! that `;` is punctuation in the default table. `RT-CONF` drives each one
//! against the authority rather than assuming.

use core::ffi::{c_char, c_int, c_long, c_void};
use core::ptr;

use crate::runtime::bio::bss_file::BIO_new_file;
use crate::runtime::bio::iolib::BIO_gets;
use crate::runtime::bio::print::BIO_printf;
use crate::runtime::bio::sys;
use crate::runtime::bio::{BIO_free, BIO_vfree, Bio};
use crate::runtime::buffer::{BUF_MEM_free, BUF_MEM_grow, BUF_MEM_grow_clean, BUF_MEM_new, BufMem};
use crate::runtime::conf::api::{
    _CONF_add_string, _CONF_free_data, _CONF_get_section, _CONF_get_string, _CONF_new_data,
    _CONF_new_section,
};
use crate::runtime::conf::modparse::OPENSSL_CONF_INCLUDE;
use crate::runtime::conf::types::{Conf, ConfMethod, ConfValue};
use crate::runtime::dir::{
    ossl_ends_with_dirsep, ossl_is_absolute_path, stat_is_dir, OPENSSL_DIR_end, OPENSSL_DIR_read,
    OpenSslDirCtx,
};
use crate::runtime::err::err_sites::{
    CONF_DEF_179, CONF_DEF_181, CONF_DEF_201, CONF_DEF_233, CONF_DEF_242, CONF_DEF_248,
    CONF_DEF_256, CONF_DEF_366, CONF_DEF_375, CONF_DEF_405, CONF_DEF_488, CONF_DEF_509,
    CONF_DEF_515, CONF_DEF_524, CONF_DEF_547, CONF_DEF_554, CONF_DEF_737, CONF_DEF_757,
    CONF_DEF_762, CONF_DEF_766, CONF_DEF_806, CONF_DEF_813,
};
use crate::runtime::err::{
    openssl_rs_err_add_data, raise_site, raise_site_data, raise_site_dynamic_data,
};
use crate::runtime::getenv::ossl_safe_getenv;
use crate::runtime::mem::{CRYPTO_free, CRYPTO_malloc, CRYPTO_strdup, CRYPTO_zalloc};
use crate::runtime::stack::{
    OPENSSL_sk_free, OPENSSL_sk_new_null, OPENSSL_sk_num, OPENSSL_sk_pop, OPENSSL_sk_push,
    OpenSslStack,
};
use crate::runtime::str::{OPENSSL_strcasecmp, OPENSSL_strlcat, OPENSSL_strlcpy};

/* ------------------------------------------------------------------------- */
/* conf_def.h — the two character-class tables.                               */
/*                                                                            */
/* Transcribed from the generated header, itself generated by                 */
/* `crypto/conf/keysets.pl`. They are not "roughly ASCII": the default table  */
/* leaves `;` a plain punctuation character and leaves the double-quote class */
/* entirely unused, and reproducing that is the point.                        */
/* ------------------------------------------------------------------------- */

const CONF_NUMBER: u16 = 1;
const CONF_UPPER: u16 = 2;
const CONF_LOWER: u16 = 4;
const CONF_UNDER: u16 = 256;
const CONF_PUNCT: u16 = 512;
const CONF_WS: u16 = 16;
const CONF_ESC: u16 = 32;
const CONF_QUOTE: u16 = 64;
const CONF_DQUOTE: u16 = 1024;
const CONF_COMMENT: u16 = 128;
const CONF_FCOMMENT: u16 = 2048;
const CONF_DOLLAR: u16 = 4096;
const CONF_EOF: u16 = 8;
const CONF_ALPHA: u16 = CONF_UPPER | CONF_LOWER;
const CONF_ALNUM: u16 = CONF_ALPHA | CONF_NUMBER | CONF_UNDER;
const CONF_ALNUM_PUNCT: u16 = CONF_ALNUM | CONF_PUNCT;

/// `CONF_type_default[128]`.
static CONF_TYPE_DEFAULT: [u16; 128] = [
    0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, //
    0x0000, 0x0010, 0x0010, 0x0000, 0x0000, 0x0010, 0x0000, 0x0000, //
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, //
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, //
    0x0010, 0x0200, 0x0040, 0x0080, 0x1000, 0x0200, 0x0200, 0x0040, //
    0x0000, 0x0000, 0x0200, 0x0200, 0x0200, 0x0200, 0x0200, 0x0200, //
    0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, //
    0x0001, 0x0001, 0x0000, 0x0200, 0x0000, 0x0000, 0x0000, 0x0200, //
    0x0200, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, //
    0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, //
    0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, //
    0x0002, 0x0002, 0x0002, 0x0000, 0x0020, 0x0000, 0x0200, 0x0100, //
    0x0040, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, //
    0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, //
    0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, //
    0x0004, 0x0004, 0x0004, 0x0000, 0x0200, 0x0000, 0x0200, 0x0000, //
];

/// `CONF_type_win32[128]` — reachable only through `NCONF_WIN32()`.
static CONF_TYPE_WIN32: [u16; 128] = [
    0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, //
    0x0000, 0x0010, 0x0010, 0x0000, 0x0000, 0x0010, 0x0000, 0x0000, //
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, //
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, //
    0x0010, 0x0200, 0x0400, 0x0000, 0x1000, 0x0200, 0x0200, 0x0000, //
    0x0000, 0x0000, 0x0200, 0x0200, 0x0200, 0x0200, 0x0200, 0x0200, //
    0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001, //
    0x0001, 0x0001, 0x0000, 0x0A00, 0x0000, 0x0000, 0x0000, 0x0200, //
    0x0200, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, //
    0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, //
    0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, 0x0002, //
    0x0002, 0x0002, 0x0002, 0x0000, 0x0000, 0x0000, 0x0200, 0x0100, //
    0x0000, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, //
    0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, //
    0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, 0x0004, //
    0x0004, 0x0004, 0x0004, 0x0000, 0x0200, 0x0000, 0x0200, 0x0000, //
];

/// `MAX_CONF_VALUE_LENGTH` — the cap `str_copy` applies during expansion.
const MAX_CONF_VALUE_LENGTH: usize = 65536;

/// `CONFBUFSIZE` — the `BIO_gets` chunk.
const CONFBUFSIZE: usize = 512;

/// `BIO_R_NO_SUCH_FILE`, which `def_load` compares the BIO layer's last error
/// against in order to choose between two raises.
const BIO_R_NO_SUCH_FILE: c_int = 128;

/* ------------------------------------------------------------------------- */
/* The character-class predicates.                                            */
/* ------------------------------------------------------------------------- */

/// `static int is_keytype(const CONF *conf, char c, unsigned short type)`
///
/// Bytes at or above `0x80` are rejected outright rather than looked up, so a
/// UTF-8 continuation byte is never whitespace, punctuation or a comment — which
/// is what makes a non-ASCII key a parse error rather than a silently different
/// key.
///
/// # Safety
/// `conf` must be live and its `meth_data` must point at a 128-entry table.
unsafe fn is_keytype(conf: *const Conf, c: c_char, ty: u16) -> bool {
    // SAFETY: `conf` is live per the caller's contract.
    let keytypes = unsafe { (*conf).meth_data } as *const u16;
    let key = c as u8;
    if key > 127 {
        return false;
    }
    // SAFETY: `key <= 127`, so this is inside the table.
    (unsafe { *keytypes.add(key as usize) } & ty) != 0
}

/// `IS_COMMENT(conf, c)`.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_comment(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_COMMENT) }
}
/// `IS_FCOMMENT(conf, c)`.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_fcomment(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_FCOMMENT) }
}
/// `IS_EOF(conf, c)` — true only for the NUL terminator.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_eof(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_EOF) }
}
/// `IS_ESC(conf, c)`.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_esc(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_ESC) }
}
/// `IS_NUMBER(conf, c)`.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_number(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_NUMBER) }
}
/// `IS_WS(conf, c)`.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_ws(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_WS) }
}
/// `IS_ALNUM(conf, c)`.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_alnum(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_ALNUM) }
}
/// `IS_ALNUM_PUNCT(conf, c)`.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_alnum_punct(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_ALNUM_PUNCT) }
}
/// `IS_QUOTE(conf, c)`.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_quote(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_QUOTE) }
}
/// `IS_DQUOTE(conf, c)`.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_dquote(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_DQUOTE) }
}
/// `IS_DOLLAR(conf, c)`.
///
/// # Safety
/// As [`is_keytype`].
unsafe fn is_dollar(conf: *const Conf, c: c_char) -> bool {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per
    // [`is_keytype`]'s contract; the call forwards `conf` unchanged.
    unsafe { is_keytype(conf, c, CONF_DOLLAR) }
}

/* ------------------------------------------------------------------------- */
/* The scanner primitives.                                                    */
/* ------------------------------------------------------------------------- */

/// `scan_esc(conf, p)` — step over an escape sequence.
///
/// # Safety
/// `p` must point at the backslash of a NUL-terminated string.
unsafe fn scan_esc(conf: *const Conf, p: *mut c_char) -> *mut c_char {
    // SAFETY: `p` points inside the string; `p[1]` is the terminator at worst.
    if unsafe { is_eof(conf, *p.add(1)) } {
        // SAFETY: `p` is at the backslash and `p[1]` is the terminator, so
        // `p + 1` is the terminator itself, still inside the string.
        unsafe { p.add(1) }
    } else {
        // SAFETY: `p[1]` is not the terminator, so the escape has a second byte
        // and `p + 2` is at worst one past that byte, i.e. inside the string.
        unsafe { p.add(2) }
    }
}

/// `static char *eat_ws(CONF *conf, char *p)`
///
/// # Safety
/// `p` must point into a NUL-terminated string.
unsafe fn eat_ws(conf: *const Conf, p: *mut c_char) -> *mut c_char {
    let mut p = p;
    // SAFETY: the loop stops at the terminator, which `is_ws` rejects.
    while unsafe { is_ws(conf, *p) } && !unsafe { is_eof(conf, *p) } {
        // SAFETY: the body runs only for a whitespace byte that is not the
        // terminator, so the next byte is still inside the string.
        p = unsafe { p.add(1) };
    }
    p
}

/// `static void trim_ws(CONF *conf, char *start)`
///
/// Note the authority's `p--` before the backward scan: for a string that is
/// entirely whitespace, `p` starts one byte *before* `start`, and the `p >= start`
/// guard is what stops the scan. Reproduced because the write afterwards is what
/// terminates the value.
///
/// # Safety
/// `start` must point into a NUL-terminated string.
unsafe fn trim_ws(conf: *const Conf, start: *mut c_char) {
    let mut p = start;
    // SAFETY: the loop stops at the terminator.
    while !unsafe { is_eof(conf, *p) } {
        // SAFETY: the condition stopped at a non-terminator byte, so advancing
        // stays inside the string.
        p = unsafe { p.add(1) };
    }
    // SAFETY: `start` points into a NUL-terminated string and the scan above
    // stopped at its terminator, so `p - 1` is the last data byte (or, for an
    // empty string, one before `start`, which the guarded loop below never
    // dereferences).
    p = unsafe { p.sub(1) };
    // SAFETY: `p >= start` keeps the scan inside the string, and `is_ws` reads
    // only within it.
    while (p as usize) >= (start as usize) && unsafe { is_ws(conf, *p) } {
        // SAFETY: `is_ws` returned non-zero for `*p` and the `p >= start` guard
        // held, so this byte is inside the string.
        p = unsafe { p.sub(1) };
    }
    // SAFETY: the backward scan stops at or above `start`; if it ended below
    // (the empty case) the single `p + 1` restores it to `start`.
    p = unsafe { p.add(1) };
    // SAFETY: `p` is inside the string: the first `p++` was at most one past the
    // terminator, and the scan walks back at most to `start`.
    unsafe { *p = 0 };
}

/// `static char *eat_alpha_numeric(CONF *conf, char *p)`
///
/// # Safety
/// `p` must point into a NUL-terminated string.
unsafe fn eat_alpha_numeric(conf: *const Conf, p: *mut c_char) -> *mut c_char {
    let mut p = p;
    loop {
        // SAFETY: `p` stays inside the string; the terminator is neither an
        // escape nor alphanumeric, so the loop cannot run past it.
        unsafe {
            if is_esc(conf, *p) {
                p = scan_esc(conf, p);
                continue;
            }
            let dollar_ok = (*conf).flag_dollarid != 0 && is_dollar(conf, *p);
            if !(is_alnum_punct(conf, *p) || dollar_ok) {
                return p;
            }
            p = p.add(1);
        }
    }
}

/// `static char *scan_quote(CONF *conf, char *p)`
///
/// # Safety
/// `p` must point at the opening quote of a NUL-terminated string.
unsafe fn scan_quote(conf: *const Conf, p: *mut c_char) -> *mut c_char {
    // SAFETY: `p` points at the opening quote of a NUL-terminated string per the
    // caller's contract, so this byte is readable.
    let q = unsafe { *p };
    // SAFETY: the opening quote is not the terminator, so `p + 1` is inside the
    // string.
    let mut p = unsafe { p.add(1) };
    // SAFETY: the loop stops at the terminator.
    while !unsafe { is_eof(conf, *p) } && unsafe { *p } != q {
        // SAFETY: `p` is inside the string here.
        if unsafe { is_esc(conf, *p) } {
            // SAFETY: `p` is at a backslash whose escaped byte follows.
            p = unsafe { p.add(1) };
            // SAFETY: `p` is at the escaped byte, which is inside the string.
            if unsafe { is_eof(conf, *p) } {
                return p;
            }
        }
        // SAFETY: `*p` was not the terminator, so the next byte is in bounds.
        p = unsafe { p.add(1) };
    }
    // SAFETY: the loop stopped at the terminator or the closing quote; both are
    // inside the string.
    if unsafe { *p } == q {
        // SAFETY: `p` is at the closing quote, so `p + 1` is at worst the
        // terminator.
        p = unsafe { p.add(1) };
    }
    p
}

/// `static char *scan_dquote(CONF *conf, char *p)`
///
/// Unlike [`scan_quote`], a doubled quote is an escaped quote rather than the
/// end: `"a""b"` is `a"b` here and `ab` under the single-quote rule. Only the
/// `WIN32` table marks the double quote as its own class, so this is reachable
/// only through `NCONF_WIN32()`.
///
/// # Safety
/// `p` must point at the opening quote of a NUL-terminated string.
unsafe fn scan_dquote(conf: *const Conf, p: *mut c_char) -> *mut c_char {
    // SAFETY: `p` points at the opening quote of a NUL-terminated string per the
    // caller's contract, so this byte is readable.
    let q = unsafe { *p };
    // SAFETY: the opening quote is not the terminator, so `p + 1` is inside the
    // string.
    let mut p = unsafe { p.add(1) };
    // SAFETY: the loop stops at the terminator.
    while !unsafe { is_eof(conf, *p) } {
        // SAFETY: `p` is inside the string here.
        if unsafe { *p } == q {
            // SAFETY: `p` is at a quote, so the next byte is at worst the
            // terminator.
            if unsafe { *p.add(1) } == q {
                // SAFETY: the doubled quote is not the terminator, so `p + 1` is
                // the second quote and still inside the string.
                p = unsafe { p.add(1) };
            } else {
                break;
            }
        }
        // SAFETY: `*p` was not the terminator, so the next byte is in bounds.
        p = unsafe { p.add(1) };
    }
    // SAFETY: `p` is at the terminator or the closing quote, both inside the
    // string.
    if unsafe { *p } == q {
        // SAFETY: `p` is at the closing quote, so `p + 1` is at worst the
        // terminator.
        p = unsafe { p.add(1) };
    }
    p
}

/// `static void clear_comments(CONF *conf, char *p)`
///
/// Two phases, and the difference between them is the difference between `;` at
/// the start of a line and inside it: a "full-line comment" character is honoured
/// only before any non-whitespace, while `#` is honoured anywhere outside a
/// quoted region.
///
/// # Safety
/// `p` must point into a NUL-terminated string.
unsafe fn clear_comments(conf: *const Conf, p: *mut c_char) {
    let mut p = p;
    loop {
        // SAFETY: `p` is inside the string.
        if unsafe { is_fcomment(conf, *p) } {
            // SAFETY: `p` was inside the string when read above.
            unsafe { *p = 0 };
            return;
        }
        // SAFETY: `p` is inside the string; the loop returns at the terminator.
        if !unsafe { is_ws(conf, *p) } {
            break;
        }
        // SAFETY: `*p` is whitespace, not the terminator, so the next byte is in
        // bounds.
        p = unsafe { p.add(1) };
    }
    loop {
        // SAFETY: `p` stays inside the string: every branch either advances
        // within it or returns at the terminator.
        unsafe {
            if is_comment(conf, *p) {
                *p = 0;
                return;
            }
            if is_dquote(conf, *p) {
                p = scan_dquote(conf, p);
                continue;
            }
            if is_quote(conf, *p) {
                p = scan_quote(conf, p);
                continue;
            }
            if is_esc(conf, *p) {
                p = scan_esc(conf, p);
                continue;
            }
            if is_eof(conf, *p) {
                return;
            }
            p = p.add(1);
        }
    }
}

/// `CHECK_AND_SKIP_PREFIX(str, pre)` with `HAS_PREFIX`'s comparison.
///
/// Advances `s` past `pre` when it is a prefix. `pre` never contains a NUL, so
/// the scan stops at the first mismatch or at `s`'s own terminator.
///
/// # Safety
/// `s` must point into a NUL-terminated string.
unsafe fn check_and_skip_prefix(s: &mut *mut c_char, pre: &[u8]) -> bool {
    for (i, want) in pre.iter().enumerate() {
        // SAFETY: reading at most up to and including the terminator.
        if unsafe { *s.add(i) } as u8 != *want {
            return false;
        }
    }
    // SAFETY: every `pre` byte matched, so `pre.len()` bytes lie before `s`'s
    // terminator and the advanced pointer is at most the terminator.
    *s = unsafe { s.add(pre.len()) };
    true
}

/// `static int str_copy(CONF *conf, char *section, char **pto, char *from)`
///
/// Copies a value, unquoting and expanding variables. The subtle parts, all
/// reproduced:
///
/// * the destination starts at `strlen(from) + 1` and is grown *from that
///   length*, so the 65536 cap applies to the buffer length rather than to the
///   number of characters written;
/// * `from` itself is temporarily NUL-terminated to isolate the variable name and
///   then restored — twice, once before the NULL check and once after the copy;
/// * a quoted region is copied verbatim, with escapes stepped over but **not**
///   expanded, while `$` outside quotes is;
/// * `*pto` is freed before the new buffer is installed, so a caller may pass the
///   field it is replacing.
///
/// # Safety
/// `conf` live; `pto` writable and its current value NULL or a `CRYPTO_malloc`
/// buffer; `from` NUL-terminated and writable (it is modified in place).
unsafe fn str_copy(
    conf: *mut Conf,
    section: *mut c_char,
    pto: *mut *mut c_char,
    from: *mut c_char,
) -> c_int {
    let buf = BUF_MEM_new();
    if buf.is_null() {
        return 0;
    }
    // SAFETY: `from` is NUL-terminated per the caller's contract.
    let from_len = unsafe { sys::strlen(from) };
    // SAFETY: `buf` is live; a failed grow leaves it empty and reports 0.
    if unsafe { BUF_MEM_grow(buf, from_len + 1) } == 0 {
        // SAFETY: `buf` is a live, still-empty `BUF_MEM`.
        unsafe { BUF_MEM_free(buf) };
        return 0;
    }

    let mut from = from;
    let mut to = 0usize;

    // The `err:` label's only action is to release the working buffer; the
    // caller's `*pto` is left exactly as it was.
    macro_rules! bail {
        () => {{
            // No `unsafe` block here: every call site is already inside one.
            BUF_MEM_free(buf);
            return 0;
        }};
    }

    loop {
        // SAFETY: `from` stays inside the caller's string throughout; no branch
        // advances past its terminator without returning or breaking.
        unsafe {
            if is_quote(conf, *from) {
                let q = *from;
                from = from.add(1);
                while !is_eof(conf, *from) && *from != q {
                    if is_esc(conf, *from) {
                        from = from.add(1);
                        if is_eof(conf, *from) {
                            break;
                        }
                    }
                    (*buf).data.add(to).write(*from);
                    to += 1;
                    from = from.add(1);
                }
                if *from == q {
                    from = from.add(1);
                }
            } else if is_dquote(conf, *from) {
                let q = *from;
                from = from.add(1);
                while !is_eof(conf, *from) {
                    if *from == q {
                        if *from.add(1) == q {
                            from = from.add(1);
                        } else {
                            break;
                        }
                    }
                    (*buf).data.add(to).write(*from);
                    to += 1;
                    from = from.add(1);
                }
                if *from == q {
                    from = from.add(1);
                }
            } else if is_esc(conf, *from) {
                from = from.add(1);
                let mut v = *from;
                from = from.add(1);
                if is_eof(conf, v) {
                    break;
                } else if v == b'r' as c_char {
                    v = b'\r' as c_char;
                } else if v == b'n' as c_char {
                    v = b'\n' as c_char;
                } else if v == b'b' as c_char {
                    v = 0x08;
                } else if v == b't' as c_char {
                    v = b'\t' as c_char;
                }
                (*buf).data.add(to).write(v);
                to += 1;
            } else if is_eof(conf, *from) {
                break;
            } else if *from == b'$' as c_char
                && ((*conf).flag_dollarid == 0
                    || *from.add(1) == b'{' as c_char
                    || *from.add(1) == b'(' as c_char)
            {
                // try to expand it
                let mut rrp: *mut c_char = ptr::null_mut();
                let mut s = from.add(1);
                let mut q: c_char = 0;
                if *s == b'{' as c_char {
                    q = b'}' as c_char;
                } else if *s == b'(' as c_char {
                    q = b')' as c_char;
                }
                if q != 0 {
                    s = s.add(1);
                }
                let mut cp = section;
                let mut np = s;
                let mut e = np;
                while is_alnum(conf, *e) || ((*conf).flag_dollarid != 0 && is_dollar(conf, *e)) {
                    e = e.add(1);
                }
                // `rr`/`rrp` remember the first byte replaced by a terminator,
                // which for a `section::name` reference is the second colon.
                let mut rr: c_char = 0;
                if *e == b':' as c_char && *e.add(1) == b':' as c_char {
                    cp = np;
                    rrp = e;
                    rr = *e;
                    *rrp = 0;
                    e = e.add(2);
                    np = e;
                    while is_alnum(conf, *e) || ((*conf).flag_dollarid != 0 && is_dollar(conf, *e))
                    {
                        e = e.add(1);
                    }
                }
                let r = *e;
                *e = 0;
                let rp = e;
                if q != 0 {
                    if r != q {
                        raise_site(&CONF_DEF_737);
                        bail!();
                    }
                    e = e.add(1);
                }
                let p = _CONF_get_string(conf, cp, np);
                if !rrp.is_null() {
                    *rrp = rr;
                }
                *rp = r;
                if p.is_null() {
                    raise_site(&CONF_DEF_757);
                    bail!();
                }
                let newsize = sys::strlen(p) + (*buf).length - ((e as usize) - (from as usize));
                if newsize > MAX_CONF_VALUE_LENGTH {
                    raise_site(&CONF_DEF_762);
                    bail!();
                }
                if BUF_MEM_grow_clean(buf, newsize) == 0 {
                    raise_site(&CONF_DEF_766);
                    bail!();
                }
                let mut q2 = p;
                while *q2 != 0 {
                    (*buf).data.add(to).write(*q2);
                    to += 1;
                    q2 = q2.add(1);
                }
                from = e;
                *rp = r;
            } else {
                (*buf).data.add(to).write(*from);
                to += 1;
                from = from.add(1);
            }
        }
    }

    // SAFETY: `to` never exceeds the buffer's length, so this write is inside the
    // allocation; and the old `*pto` is released before the new value is
    // installed, which is what lets a caller pass the field it is replacing.
    unsafe {
        (*buf).data.add(to).write(0);
        CRYPTO_free((*pto).cast::<c_void>(), ptr::null(), 0);
        *pto = (*buf).data;
        // Only the `BufMem` header is released: `data` now belongs to `*pto`.
        CRYPTO_free(buf.cast::<c_void>(), ptr::null(), 0);
    }
    1
}

/// `static int parsebool(const char *pval, int *flag)`
///
/// Case-insensitive `on`/`true`/`off`/`false`; anything else is
/// `CONF_R_INVALID_PRAGMA`. The comparison is `OPENSSL_strcasecmp`, whose
/// ASCII-only folding means a high byte can never match.
///
/// # Safety
/// `pval` NUL-terminated; `flag` writable.
unsafe fn parsebool(pval: *const c_char, flag: *mut c_int) -> c_int {
    // SAFETY: `pval` is NUL-terminated per the caller's contract.
    let on = unsafe { OPENSSL_strcasecmp(pval, c"on".as_ptr()) } == 0
        || unsafe { OPENSSL_strcasecmp(pval, c"true".as_ptr()) } == 0;
    // SAFETY: as above.
    let off = unsafe { OPENSSL_strcasecmp(pval, c"off".as_ptr()) } == 0
        || unsafe { OPENSSL_strcasecmp(pval, c"false".as_ptr()) } == 0;
    if on {
        // SAFETY: `flag` is writable per the caller's contract.
        unsafe { *flag = 1 };
    } else if off {
        // SAFETY: as above.
        unsafe { *flag = 0 };
    } else {
        // SAFETY: the site is a compile-time constant, which is `raise_site`'s
        // only precondition.
        unsafe { raise_site(&CONF_DEF_201) };
        return 0;
    }
    1
}

/* ------------------------------------------------------------------------- */
/* The method itself.                                                         */
/* ------------------------------------------------------------------------- */

/// A method table with a stable address.
///
/// `NCONF_default()` hands out a pointer to one of these and callers compare it
/// by identity, so it must be a `static` rather than a `const`. The wrapper
/// exists only to carry the `Sync` assertion; `repr(transparent)` keeps the
/// address and layout identical to the inner table.
#[repr(transparent)]
pub struct ConfMethodCell(pub ConfMethod);

// SAFETY: every field of the table is a function pointer or a pointer to a
// string literal, and nothing writes to it after initialisation. Its address is
// what `NCONF_default` publishes, which is why it must be a `static`.
unsafe impl Sync for ConfMethodCell {}

/// `static CONF_METHOD default_method`.
static DEFAULT_METHOD: ConfMethodCell = ConfMethodCell(ConfMethod {
    name: c"OpenSSL default".as_ptr(),
    create: Some(def_create),
    init: Some(def_init_default),
    destroy: Some(def_destroy),
    destroy_data: Some(def_destroy_data),
    load_bio: Some(def_load_bio),
    dump: Some(def_dump),
    is_number: Some(def_is_number),
    to_int: Some(def_to_int),
    load: Some(def_load),
});

/// `static CONF_METHOD WIN32_method`.
static WIN32_METHOD: ConfMethodCell = ConfMethodCell(ConfMethod {
    name: c"WIN32".as_ptr(),
    create: Some(def_create),
    init: Some(def_init_win32),
    destroy: Some(def_destroy),
    destroy_data: Some(def_destroy_data),
    load_bio: Some(def_load_bio),
    dump: Some(def_dump),
    is_number: Some(def_is_number),
    to_int: Some(def_to_int),
    load: Some(def_load),
});

/// `CONF_METHOD *NCONF_default(void)`
#[no_mangle]
pub extern "C" fn NCONF_default() -> *mut ConfMethod {
    core::ptr::addr_of!(DEFAULT_METHOD.0).cast_mut()
}

/// `CONF_METHOD *NCONF_WIN32(void)`
///
/// Deprecated in the headers but still exported, and it is the *only* way to
/// reach `CONF_type_win32` and the double-quote scanner.
#[no_mangle]
pub extern "C" fn NCONF_WIN32() -> *mut ConfMethod {
    core::ptr::addr_of!(WIN32_METHOD.0).cast_mut()
}

/// `static CONF *def_create(CONF_METHOD *meth)`
///
/// # Safety
/// `meth` must be a live method table whose `init` is set.
unsafe extern "C" fn def_create(meth: *mut ConfMethod) -> *mut Conf {
    let ret = CRYPTO_malloc(core::mem::size_of::<Conf>(), ptr::null(), 0).cast::<Conf>();
    if ret.is_null() {
        return ptr::null_mut();
    }
    // SAFETY: `meth` is live per the caller's contract, and `init` is set for
    // both tables this module publishes.
    let ok = match unsafe { (*meth).init } {
        // SAFETY: `init` is the live method's own initialiser and `ret` is the
        // freshly allocated `CONF` storage it initialises.
        Some(init) => unsafe { init(ret) },
        None => 0,
    };
    if ok == 0 {
        // SAFETY: `ret` came from `CRYPTO_malloc` above.
        unsafe { CRYPTO_free(ret.cast::<c_void>(), ptr::null(), 0) };
        return ptr::null_mut();
    }
    ret
}

/// `static int def_init_default(CONF *conf)`
///
/// # Safety
/// `conf` NULL or writable for `size_of::<Conf>()` bytes.
unsafe extern "C" fn def_init_default(conf: *mut Conf) -> c_int {
    if conf.is_null() {
        return 0;
    }
    // SAFETY: `conf` is writable per the caller's contract.
    unsafe {
        sys::memset(conf.cast::<c_void>(), 0, core::mem::size_of::<Conf>());
        (*conf).meth = core::ptr::addr_of!(DEFAULT_METHOD.0).cast_mut();
        (*conf).meth_data = (&raw const CONF_TYPE_DEFAULT).cast_mut().cast::<c_void>();
    }
    1
}

/// `static int def_init_WIN32(CONF *conf)`
///
/// # Safety
/// As [`def_init_default`].
unsafe extern "C" fn def_init_win32(conf: *mut Conf) -> c_int {
    if conf.is_null() {
        return 0;
    }
    // SAFETY: `conf` is writable per the caller's contract.
    unsafe {
        sys::memset(conf.cast::<c_void>(), 0, core::mem::size_of::<Conf>());
        (*conf).meth = core::ptr::addr_of!(WIN32_METHOD.0).cast_mut();
        (*conf).meth_data = (&raw const CONF_TYPE_WIN32).cast_mut().cast::<c_void>();
    }
    1
}

/// `static int def_destroy_data(CONF *conf)`
///
/// # Safety
/// `conf` NULL or live.
unsafe extern "C" fn def_destroy_data(conf: *mut Conf) -> c_int {
    if conf.is_null() {
        return 0;
    }
    // SAFETY: `conf` is live per the caller's contract.
    unsafe { _CONF_free_data(conf) };
    1
}

/// `static int def_destroy(CONF *conf)`
///
/// # Safety
/// `conf` must be a live configuration that is not used again.
unsafe extern "C" fn def_destroy(conf: *mut Conf) -> c_int {
    // SAFETY: `conf` is live per the caller's contract.
    if unsafe { def_destroy_data(conf) } != 0 {
        // SAFETY: `conf` came from `def_create`'s `CRYPTO_malloc`.
        unsafe { CRYPTO_free(conf.cast::<c_void>(), ptr::null(), 0) };
        return 1;
    }
    0
}

/// `static int def_load(CONF *conf, const char *name, long *line)`
///
/// Two raises for one failure, chosen by the BIO layer's own last error: a
/// missing file is `CONF_R_NO_SUCH_FILE`, anything else `ERR_R_SYS_LIB`. That is
/// why the BIO error must still be on the queue when this decides.
///
/// # Safety
/// `conf` live; `name` NUL-terminated; `line` NULL or writable.
unsafe extern "C" fn def_load(conf: *mut Conf, name: *const c_char, line: *mut c_long) -> c_int {
    // SAFETY: `name` is NUL-terminated per the caller's contract.
    let inbio = unsafe { BIO_new_file(name, c"rb".as_ptr()) };
    if inbio.is_null() {
        // SAFETY: the ERR accessors take no arguments and are thread-safe.
        let last = crate::runtime::err::ERR_peek_last_error();
        // `ERR_GET_REASON(e)` is the low twelve bits of the packed code.
        let reason = (last & 0xfff) as c_int;
        if reason == BIO_R_NO_SUCH_FILE {
            // SAFETY: the site is a compile-time constant, which is `raise_site`'s
            // only precondition.
            unsafe { raise_site(&CONF_DEF_179) };
        } else {
            // SAFETY: the site is a compile-time constant, which is `raise_site`'s
            // only precondition.
            unsafe { raise_site(&CONF_DEF_181) };
        }
        return 0;
    }
    // SAFETY: `conf` and `inbio` are live; `line` is NULL or writable.
    let ret = unsafe { def_load_bio(conf, inbio, line) };
    // SAFETY: `inbio` is a live BIO owned by this call.
    unsafe { BIO_free(inbio) };
    ret
}

/// `static int def_load_bio(CONF *conf, BIO *in, long *line)`
///
/// See the module documentation for the grammar. The control flow mirrors the
/// authority's two labels: `read_retry` (a new BIO to read from without
/// re-growing the buffer) and `err` (the shared failure exit, which is
/// [`finish_with_error`] here so that every early exit performs the same
/// sequence in the same order).
///
/// # Safety
/// `conf` live; `in` NULL or a live BIO; `line` NULL or writable.
unsafe extern "C" fn def_load_bio(conf: *mut Conf, in_: *mut Bio, line: *mut c_long) -> c_int {
    let mut bufnum: usize;
    let mut eline: c_long = 0;
    let mut again: c_int;
    let mut first_call = true;
    let mut section: *mut c_char = ptr::null_mut();
    let mut sv: *mut ConfValue = ptr::null_mut();
    let mut v: *mut ConfValue = ptr::null_mut();
    let mut biosk: *mut OpenSslStack = ptr::null_mut();
    let mut dirpath: *mut c_char = ptr::null_mut();
    let mut dirctx: *mut OpenSslDirCtx = ptr::null_mut();
    let mut in_ = in_;
    let mut btmp = [0 as c_char; 24];
    let mut failed = false;

    // The table the caller handed in: the error path uses it to tell whether
    // this call created the table and must therefore free it.
    // SAFETY: `conf` is live per the caller's contract.
    let h = unsafe { (*conf).data };

    let buff = BUF_MEM_new();
    if buff.is_null() {
        // SAFETY: the site is a compile-time constant, which is `raise_site`'s
        // only precondition.
        unsafe { raise_site(&CONF_DEF_233) };
        failed = true;
    }

    if !failed {
        // SAFETY: a fresh `CRYPTO_strdup`.
        section = unsafe { CRYPTO_strdup(c"default".as_ptr(), ptr::null(), 0) };
        if section.is_null() {
            failed = true;
        }
    }

    if !failed {
        // SAFETY: `conf` is live.
        if unsafe { _CONF_new_data(conf) } == 0 {
            // SAFETY: the site is a compile-time constant, which is `raise_site`'s
            // only precondition.
            unsafe { raise_site(&CONF_DEF_242) };
            failed = true;
        }
    }

    if !failed {
        // SAFETY: `conf` is live and `section` is its "default" name.
        sv = unsafe { _CONF_new_section(conf, section) };
        if sv.is_null() {
            // SAFETY: the site is a compile-time constant, which is `raise_site`'s
            // only precondition.
            unsafe { raise_site(&CONF_DEF_248) };
            failed = true;
        }
    }

    if !failed {
        bufnum = 0;
        again = 0;
        'outer: loop {
            // SAFETY: `buff` is live; a failed grow reports 0.
            if unsafe { BUF_MEM_grow(buff, bufnum + CONFBUFSIZE) } == 0 {
                // SAFETY: the site is a compile-time constant, which is
                // `raise_site`'s only precondition.
                unsafe { raise_site(&CONF_DEF_256) };
                failed = true;
                break 'outer;
            }
            // SAFETY: the grow above made `bufnum + CONFBUFSIZE` bytes available.
            let p = unsafe { (*buff).data.add(bufnum) };
            // SAFETY: `p` points at `bufnum`, which is inside the freshly grown
            // region, so the byte is writable.
            unsafe { *p = 0 };

            let mut i: usize;
            let mut ii: usize;
            'read: loop {
                if !in_.is_null() {
                    // SAFETY: `p` has `CONFBUFSIZE` bytes and `in_` is a live BIO.
                    if unsafe { BIO_gets(in_, p, (CONFBUFSIZE - 1) as c_int) } < 0 {
                        failed = true;
                        break 'outer;
                    }
                }
                // SAFETY: as above; the terminator is inside the region.
                unsafe { *p.add(CONFBUFSIZE - 1) = 0 };
                // SAFETY: `BIO_gets` NUL-terminates at or before the byte just
                // set, so this stays in bounds.
                i = unsafe { sys::strlen(p) };
                ii = i;
                if first_call {
                    // Other BOMs imply an unsupported multibyte encoding, so they
                    // are not stripped and the resulting parse error is allowed to
                    // speak.
                    let bom = [0xEFu8, 0xBB, 0xBF];
                    if i >= 3
                        // SAFETY: `i >= 3`, so `p` has at least three readable bytes
                        // and `bom` is a three-byte array.
                        && unsafe {
                            sys::memcmp(p.cast::<c_void>(), bom.as_ptr().cast::<c_void>(), 3)
                        } == 0
                    {
                        // SAFETY: the region is `i >= 3` bytes and `p` is writable.
                        unsafe {
                            sys::memmove(p.cast::<c_void>(), p.add(3).cast::<c_void>(), i - 3);
                            *p.add(i - 3) = 0;
                        }
                        i -= 3;
                        ii -= 3;
                    }
                    first_call = false;
                }
                if i == 0 && again == 0 {
                    // The current BIO is NULL or at EOF: continue with the next
                    // file of a directory include, else with the parent BIO.
                    if !dirctx.is_null() {
                        // SAFETY: `dirpath` is set whenever `dirctx` is, and both
                        // are live out-parameters.
                        let next = unsafe { get_next_file(dirpath, &mut dirctx) };
                        if !next.is_null() {
                            // SAFETY: `in_` is the live BIO whose ownership the
                            // directory walk took.
                            unsafe { BIO_vfree(in_) };
                            in_ = next;
                            continue 'read;
                        }
                        // SAFETY: `dirpath` was allocated for the include path
                        // and `get_next_file` has closed the context.
                        unsafe { CRYPTO_free(dirpath.cast::<c_void>(), ptr::null(), 0) };
                        dirpath = ptr::null_mut();
                    }
                    // SAFETY: `biosk` is a live stack of BIOs, or NULL.
                    let parent = unsafe { OPENSSL_sk_pop(biosk) } as *mut Bio;
                    if parent.is_null() {
                        // Everything processed: success.
                        break 'outer;
                    }
                    // SAFETY: `in_` is a live BIO whose ownership the stack took.
                    unsafe { BIO_vfree(in_) };
                    in_ = parent;
                    continue 'read;
                }
                break 'read;
            }
            if failed {
                break 'outer;
            }

            again = 0;
            while i > 0 {
                // SAFETY: `i - 1 < i <= strlen(p)`.
                let c = unsafe { *p.add(i - 1) };
                if c != b'\r' as c_char && c != b'\n' as c_char {
                    break;
                }
                i -= 1;
            }
            // The trailing newline that was *not* found is what distinguishes a
            // complete line from a read that filled the buffer.
            if ii != 0 && i == ii {
                again = 1; // long line
            } else {
                // SAFETY: `i <= strlen(p)`.
                unsafe { *p.add(i) = 0 };
                eline += 1;
            }
            bufnum += i;

            v = ptr::null_mut();
            if again == 0 && bufnum >= 1 {
                // A line ending in a lone backslash continues; a doubled one does
                // not.
                // SAFETY: `bufnum - 1` is inside what has been read.
                let q = unsafe { (*buff).data.add(bufnum - 1) };
                // SAFETY: `q` points at the last byte of the accumulated line.
                if unsafe { is_esc(conf, *q) }
                    // SAFETY: `bufnum > 1` whenever this operand is evaluated, and
                    // `q` is inside the line, so `q - 1` is still in bounds.
                    && (bufnum <= 1 || !unsafe { is_esc(conf, *q.sub(1)) })
                {
                    bufnum -= 1;
                    again = 1;
                }
            }
            if again != 0 {
                continue 'outer;
            }

            bufnum = 0;
            // SAFETY: `buff` is live and has at least `CONFBUFSIZE` bytes.
            let buf = unsafe { (*buff).data };
            // SAFETY: `buf` is the live line buffer and `conf` is live.
            unsafe { clear_comments(conf, buf) };
            // SAFETY: `buf` is the live, NUL-terminated line.
            let s = unsafe { eat_ws(conf, buf) };
            // SAFETY: `s` points inside the line (or at its terminator).
            if unsafe { is_eof(conf, *s) } {
                continue 'outer; // blank line
            }

            // SAFETY: `s` points inside the line or at its terminator.
            if unsafe { *s } == b'[' as c_char {
                // SAFETY: `s` points at `[`, so `s + 1` is inside the line.
                let mut ss = unsafe { eat_ws(conf, s.add(1)) };
                let start = ss;
                let mut end;
                loop {
                    // SAFETY: `ss` points inside the line.
                    end = unsafe { eat_alpha_numeric(conf, ss) };
                    // SAFETY: `end` is at or before the terminator.
                    let p = unsafe { eat_ws(conf, end) };
                    // SAFETY: `p` is at or before the terminator.
                    if unsafe { *p } != b']' as c_char {
                        // SAFETY: `p` is at or before the terminator.
                        if unsafe { *p } != 0 && ss != p {
                            ss = p;
                            continue;
                        }
                        // SAFETY: the site is a compile-time constant, which is
                        // `raise_site`'s only precondition.
                        unsafe { raise_site(&CONF_DEF_366) };
                        failed = true;
                        break 'outer;
                    }
                    break;
                }
                // SAFETY: `end` is at the `]` that ended the scan, so it is
                // inside the line and writable.
                unsafe { *end = 0 };
                // SAFETY: `conf` is live; `start` is a NUL-terminated slice of the
                // line and `section` is NULL, which `str_copy` accepts.
                if unsafe { str_copy(conf, ptr::null_mut(), &mut section, start) } == 0 {
                    failed = true;
                    break 'outer;
                }
                // SAFETY: `conf` is live and `section` is now NUL-terminated.
                let mut found = unsafe { _CONF_get_section(conf, section) };
                if found.is_null() {
                    // SAFETY: `conf` is live and `section` is NUL-terminated.
                    found = unsafe { _CONF_new_section(conf, section) };
                }
                if found.is_null() {
                    // SAFETY: the site is a compile-time constant, which is
                    // `raise_site`'s only precondition.
                    unsafe { raise_site(&CONF_DEF_375) };
                    failed = true;
                    break 'outer;
                }
                sv = found;
                continue 'outer;
            }

            // A key, optionally qualified as `section::key`.
            let mut pname = s;
            // SAFETY: `s` points inside the line.
            let mut end = unsafe { eat_alpha_numeric(conf, s) };
            let psection: *mut c_char;
            // SAFETY: `end` is at or before the terminator; `end + 1` is only
            // evaluated when `end` is at a `:`, so both reads are inside the line.
            if unsafe { *end } == b':' as c_char && unsafe { *end.add(1) } == b':' as c_char {
                // SAFETY: `end` is at the first `:`, which is inside the line.
                unsafe { *end = 0 };
                // SAFETY: `end` is at the first `:`, so `end + 2` is at or before
                // the terminator.
                end = unsafe { end.add(2) };
                psection = pname;
                pname = end;
                // SAFETY: `end` points at the start of the key, inside the line.
                end = unsafe { eat_alpha_numeric(conf, end) };
            } else {
                psection = section;
            }
            // SAFETY: `end` is at or before the terminator.
            let p = unsafe { eat_ws(conf, end) };

            let mut skipped = pname;
            // SAFETY: `skipped` points into the line; the prefix test reads at
            // most the literal's length and stops at a mismatch.
            if unsafe { check_and_skip_prefix(&mut skipped, b".pragma") }
                // SAFETY: `p` is the same in-line pointer, at or before the
                // terminator, and is only read after the prefix test matched.
                && (p != skipped || unsafe { *p } == b'=' as c_char)
            {
                let mut p = p;
                // SAFETY: `p` is at or before the terminator.
                if unsafe { *p } == b'=' as c_char {
                    // SAFETY: `p` is at `=`, so `p + 1` is at or before the
                    // terminator.
                    p = unsafe { eat_ws(conf, p.add(1)) };
                }
                // SAFETY: `p` is at or before the terminator.
                unsafe { trim_ws(conf, p) };

                // Pragma values take the form keyword:value.
                // SAFETY: `p` is inside the line and NUL-terminated.
                let colon = unsafe { sys::strchr(p, b':' as c_int) };
                // SAFETY: the preceding tests guarantee `colon` is a non-empty
                // position inside the line, so `colon + 1` is readable.
                if colon.is_null() || colon == p || unsafe { *colon.add(1) } == 0 {
                    // SAFETY: the site is a compile-time constant, which is
                    // `raise_site`'s only precondition.
                    unsafe { raise_site(&CONF_DEF_405) };
                    failed = true;
                    break 'outer;
                }
                // SAFETY: `colon` points at the `:` inside the line.
                unsafe { *colon = 0 };
                // SAFETY: `colon` is at the `:`, so `colon + 1` is inside the line.
                let mut pval = unsafe { colon.add(1) };
                // SAFETY: `p` is a NUL-terminated keyword inside the line.
                unsafe { trim_ws(conf, p) };
                // SAFETY: `pval` is a NUL-terminated value inside the line.
                pval = unsafe { eat_ws(conf, pval) };

                // Known pragmas: dollarid, abspath, includedir. The comparisons
                // are pure and evaluate no pointer that is not already valid, so
                // hoisting them out of the chain preserves the behaviour.
                // SAFETY: `p` is a NUL-terminated keyword inside the line.
                let is_dollarid = unsafe { sys::strcmp(p, c"dollarid".as_ptr()) } == 0;
                // SAFETY: as above.
                let is_abspath = unsafe { sys::strcmp(p, c"abspath".as_ptr()) } == 0;
                // SAFETY: as above.
                let is_includedir = unsafe { sys::strcmp(p, c"includedir".as_ptr()) } == 0;
                if is_dollarid {
                    // SAFETY: `pval` is NUL-terminated and the flag is writable.
                    if unsafe { parsebool(pval, &mut (*conf).flag_dollarid) } == 0 {
                        failed = true;
                        break 'outer;
                    }
                } else if is_abspath {
                    // SAFETY: as above.
                    if unsafe { parsebool(pval, &mut (*conf).flag_abspath) } == 0 {
                        failed = true;
                        break 'outer;
                    }
                } else if is_includedir {
                    // SAFETY: `includedir` is NULL or a previous duplicate.
                    unsafe {
                        CRYPTO_free((*conf).includedir.cast::<c_void>(), ptr::null(), 0);
                        (*conf).includedir = CRYPTO_strdup(pval, ptr::null(), 0);
                    }
                    // SAFETY: `conf` is live.
                    if unsafe { (*conf).includedir }.is_null() {
                        failed = true;
                        break 'outer;
                    }
                }
                // Unknown pragmas are ignored, not errors.
                continue 'outer;
            }

            let mut skipped = pname;
            // SAFETY: `skipped` points into the line; the prefix test reads at
            // most the literal's length and stops at a mismatch.
            if unsafe { check_and_skip_prefix(&mut skipped, b".include") }
                // SAFETY: `p` is the same in-line pointer, at or before the
                // terminator, and is only read after the prefix test matched.
                && (p != skipped || unsafe { *p } == b'=' as c_char)
            {
                let mut include: *mut c_char = ptr::null_mut();
                // SAFETY: reading the environment is always defined.
                let mut include_dir = unsafe { ossl_safe_getenv(OPENSSL_CONF_INCLUDE.as_ptr()) };
                if include_dir.is_null() {
                    // SAFETY: `conf` is live and `includedir` is NULL or a
                    // `CRYPTO_strdup` buffer owned by it.
                    include_dir = unsafe { (*conf).includedir };
                }
                let mut p = p;
                // SAFETY: `p` is at or before the terminator.
                if unsafe { *p } == b'=' as c_char {
                    // SAFETY: `p` is at `=`, so `p + 1` is at or before the
                    // terminator.
                    p = unsafe { eat_ws(conf, p.add(1)) };
                }
                // SAFETY: `p` is at or before the terminator.
                unsafe { trim_ws(conf, p) };
                // SAFETY: `conf` is live; `p` is a NUL-terminated value and
                // `include` is NULL, which `str_copy` accepts.
                if unsafe { str_copy(conf, psection, &mut include, p) } == 0 {
                    failed = true;
                    break 'outer;
                }

                // SAFETY: `include_dir` is NULL or NUL-terminated and `include`
                // is the NUL-terminated value just built.
                let include_path: *mut c_char =
                    if !include_dir.is_null() && unsafe { ossl_is_absolute_path(include) } == 0 {
                        // SAFETY: both are NUL-terminated paths.
                        let newlen = unsafe { sys::strlen(include_dir) + sys::strlen(include) + 2 };
                        let joined = CRYPTO_malloc(newlen, ptr::null(), 0).cast::<c_char>();
                        if joined.is_null() {
                            // SAFETY: `include` is a `str_copy` buffer owned here.
                            unsafe { CRYPTO_free(include.cast::<c_void>(), ptr::null(), 0) };
                            failed = true;
                            break 'outer;
                        }
                        // SAFETY: `joined` has `newlen` bytes, which both copies fit.
                        unsafe {
                            OPENSSL_strlcpy(joined, include_dir, newlen);
                            if ossl_ends_with_dirsep(joined) == 0 {
                                OPENSSL_strlcat(joined, c"/".as_ptr(), newlen);
                            }
                            OPENSSL_strlcat(joined, include, newlen);
                            CRYPTO_free(include.cast::<c_void>(), ptr::null(), 0);
                        }
                        joined
                    } else {
                        include
                    };

                // SAFETY: `conf` is live.
                if unsafe { (*conf).flag_abspath } != 0
                    // SAFETY: `include_path` is NUL-terminated in both branches.
                    && unsafe { ossl_is_absolute_path(include_path) } == 0
                {
                    // SAFETY: the site is a compile-time constant, which is
                    // `raise_site`'s only precondition.
                    unsafe { raise_site(&CONF_DEF_488) };
                    // SAFETY: `include_path` is NUL-terminated and owned here.
                    unsafe { CRYPTO_free(include_path.cast::<c_void>(), ptr::null(), 0) };
                    failed = true;
                    break 'outer;
                }

                // SAFETY: `include_path` is NUL-terminated and owned here.
                let next = unsafe { process_include(include_path, &mut dirctx, &mut dirpath) };
                if include_path != dirpath {
                    // A directory include hands ownership to `dirpath`.
                    // SAFETY: `include_path` is NUL-terminated and owned here.
                    unsafe { CRYPTO_free(include_path.cast::<c_void>(), ptr::null(), 0) };
                }

                if !next.is_null() {
                    if biosk.is_null() {
                        biosk = OPENSSL_sk_new_null();
                        if biosk.is_null() {
                            // SAFETY: the site is a compile-time constant, which is
                            // `raise_site`'s only precondition.
                            unsafe { raise_site(&CONF_DEF_509) };
                            // SAFETY: `next` is the BIO `process_include` opened and
                            // ownership has not been handed on.
                            unsafe { BIO_free(next) };
                            failed = true;
                            break 'outer;
                        }
                    }
                    // SAFETY: `biosk` is a live stack, and `in_` is a live BIO
                    // whose ownership moves to the stack.
                    if unsafe { OPENSSL_sk_push(biosk, in_.cast::<c_void>()) } == 0 {
                        // SAFETY: the site is a compile-time constant, which is
                        // `raise_site`'s only precondition.
                        unsafe { raise_site(&CONF_DEF_515) };
                        // SAFETY: `next` is the BIO `process_include` opened and
                        // ownership has not been handed on.
                        unsafe { BIO_free(next) };
                        failed = true;
                        break 'outer;
                    }
                    in_ = next;
                }
                continue 'outer;
            }

            // SAFETY: `p` points at or before the terminator.
            if unsafe { *p } != b'=' as c_char {
                let mut msg: Vec<u8> = b"HERE-->".to_vec();
                // SAFETY: `p` points into the line and is NUL-terminated.
                msg.extend_from_slice(unsafe { core::ffi::CStr::from_ptr(p) }.to_bytes());
                msg.push(0);
                // `ERR_raise_data(lib, reason, "HERE-->%s", p)`; the one
                // substitution is applied here rather than through a variadic
                // shim.
                // SAFETY: the site is a compile-time constant and `msg` is
                // NUL-terminated.
                unsafe { raise_site_data(&CONF_DEF_524, msg.as_ptr().cast::<c_char>()) };
                failed = true;
                break 'outer;
            }
            // SAFETY: `end` is at the name terminator, inside the line.
            unsafe { *end = 0 };
            // SAFETY: `p` points at `=`, so `p + 1` is inside the line.
            let p = unsafe { p.add(1) };
            // SAFETY: `p` is at or before the terminator.
            let start = unsafe { eat_ws(conf, p) };
            // SAFETY: `start` points into the line.
            unsafe { trim_ws(conf, start) };

            let fresh = CRYPTO_malloc(core::mem::size_of::<ConfValue>(), ptr::null(), 0)
                .cast::<ConfValue>();
            if fresh.is_null() {
                failed = true;
                break 'outer;
            }
            v = fresh;
            // SAFETY: `v` is a fresh entry and `pname` is NUL-terminated.
            unsafe {
                (*v).name = CRYPTO_strdup(pname, ptr::null(), 0);
                (*v).value = ptr::null_mut();
            }
            // SAFETY: `v` is the live entry just allocated.
            if unsafe { (*v).name }.is_null() {
                failed = true;
                break 'outer;
            }
            // SAFETY: `v` is live; `str_copy` installs an owned `value`.
            if unsafe { str_copy(conf, psection, &mut (*v).value, start) } == 0 {
                failed = true;
                break 'outer;
            }

            // SAFETY: `psection` and `section` are NUL-terminated strings.
            let tv = if unsafe { sys::strcmp(psection, section) } != 0 {
                // SAFETY: `conf` is live and `psection` is NUL-terminated.
                let mut found = unsafe { _CONF_get_section(conf, psection) };
                if found.is_null() {
                    // SAFETY: `conf` is live and `psection` is NUL-terminated.
                    found = unsafe { _CONF_new_section(conf, psection) };
                }
                if found.is_null() {
                    // SAFETY: the site is a compile-time constant, which is
                    // `raise_site`'s only precondition.
                    unsafe { raise_site(&CONF_DEF_547) };
                    failed = true;
                    break 'outer;
                }
                found
            } else {
                sv
            };
            // SAFETY: `conf`, `tv` and `v` are live, and `v`'s ownership passes
            // to the model.
            if unsafe { _CONF_add_string(conf, tv, v) } == 0 {
                // SAFETY: the site is a compile-time constant, which is
                // `raise_site`'s only precondition.
                unsafe { raise_site(&CONF_DEF_554) };
                failed = true;
                break 'outer;
            }
            // Ownership transferred: the error path must not free it again.
            v = ptr::null_mut();
        }
    }

    if !failed {
        // SAFETY: `buff` and `section` are live; `biosk` is NULL or an empty
        // stack at this point, since reaching here means the stack was drained.
        unsafe {
            BUF_MEM_free(buff);
            CRYPTO_free(section.cast::<c_void>(), ptr::null(), 0);
            OPENSSL_sk_free(biosk);
        }
        return 1;
    }

    // SAFETY: every pointer here is NULL or live, as at the authority's `err:`
    // label, and `conf` is live.
    unsafe {
        finish_with_error(
            conf,
            buff,
            section,
            biosk,
            dirpath,
            &mut dirctx,
            &mut in_,
            h,
            v,
            line,
            eline,
            &mut btmp,
        )
    }
}

/// The authority's `err:` label, factored out of [`def_load_bio`] so that every
/// early exit performs the same sequence in the same order.
///
/// Two details are contract rather than housekeeping:
///
/// * the include stack is unwound one BIO at a time and the *caller's* BIO — the
///   first element — is deliberately **not** freed, which is why `sk_BIO_pop_free`
///   cannot be used;
/// * the last `ERR_add_error_data(2, "line ", btmp)` appends the line number to
///   whatever error the parse already raised, so a caller sees both.
///
/// # Safety
/// Every pointer must be NULL or live, exactly as at the corresponding `goto
/// err`; `conf` must be live.
#[allow(clippy::too_many_arguments)]
unsafe fn finish_with_error(
    conf: *mut Conf,
    buff: *mut BufMem,
    section: *mut c_char,
    biosk: *mut OpenSslStack,
    dirpath: *mut c_char,
    dirctx: &mut *mut OpenSslDirCtx,
    in_: &mut *mut Bio,
    h: *mut crate::runtime::lhash::OpenSslLhash,
    v: *mut ConfValue,
    line: *mut c_long,
    eline: c_long,
    btmp: &mut [c_char; 24],
) -> c_int {
    // SAFETY: `buff` is a `BUF_MEM` or NULL; `section` is a `CRYPTO_strdup` or
    // NULL. Both are released unconditionally, as the authority does.
    unsafe {
        BUF_MEM_free(buff);
        CRYPTO_free(section.cast::<c_void>(), ptr::null(), 0);
        // The first element of the stack is the caller's BIO, so it is popped and
        // walked past rather than freed.
        while OPENSSL_sk_num(biosk) > 0 {
            let popped = OPENSSL_sk_pop(biosk) as *mut Bio;
            BIO_vfree(*in_);
            *in_ = popped;
        }
        OPENSSL_sk_free(biosk);
        CRYPTO_free(dirpath.cast::<c_void>(), ptr::null(), 0);
        if !(*dirctx).is_null() {
            OPENSSL_DIR_end(dirctx);
        }
        if !line.is_null() {
            *line = eline;
        }
        format_line_number(btmp.as_mut_ptr(), btmp.len(), eline);
        // `ERR_add_error_data(2, "line ", btmp)` joins its arguments with no
        // separator, so the two are concatenated here directly.
        let mut msg: Vec<u8> = b"line ".to_vec();
        msg.extend_from_slice(core::ffi::CStr::from_ptr(btmp.as_ptr()).to_bytes());
        msg.push(0);
        openssl_rs_err_add_data(msg.as_ptr().cast::<c_char>());
        if h != (*conf).data {
            // The table was created during this call, so it must not survive a
            // failed parse; `CONF_free` is the classic API on the same hash.
            super::lib::CONF_free((*conf).data);
            (*conf).data = ptr::null_mut();
        }
        if !v.is_null() {
            CRYPTO_free((*v).name.cast::<c_void>(), ptr::null(), 0);
            CRYPTO_free((*v).value.cast::<c_void>(), ptr::null(), 0);
            CRYPTO_free(v.cast::<c_void>(), ptr::null(), 0);
        }
    }
    0
}

/// `BIO_snprintf(btmp, sizeof(btmp), "%ld", eline)`.
///
/// The authority formats this through its own `_dopr` engine, not through libc
/// (`docs/DECISIONS.md` D41). `%ld` of a `long` is plain decimal, which is the one
/// format where the two engines cannot differ, so the digits are written directly
/// rather than routing a variadic call through a C shim for a single fixed format.
///
/// # Safety
/// `buf` must be writable for `len` bytes, which every caller guarantees is at
/// least 1.
unsafe fn format_line_number(buf: *mut c_char, len: usize, value: c_long) {
    let mut digits = [0u8; 24];
    let mut n = 0usize;
    let negative = value < 0;
    // `i64::MIN` negates to itself, so the magnitude is taken unsigned.
    let mut v = if negative {
        value.unsigned_abs()
    } else {
        value as u64
    };
    if v == 0 {
        digits[0] = b'0';
        n = 1;
    }
    while v != 0 {
        digits[n] = b'0' + (v % 10) as u8;
        n += 1;
        v /= 10;
    }
    let mut out = 0usize;
    if negative && out + 1 < len {
        // SAFETY: `out + 1 < len`, so this index is inside the buffer.
        unsafe { *buf = b'-' as c_char };
    }
    if negative {
        out += 1;
    }
    while n > 0 {
        n -= 1;
        if out + 1 < len {
            // SAFETY: `out + 1 < len`, so this index is inside the buffer.
            unsafe { *buf.add(out) = digits[n] as c_char };
        }
        out += 1;
    }
    let term = if out < len { out } else { len - 1 };
    // SAFETY: `len >= 1`, so `term < len`.
    unsafe { *buf.add(term) = 0 };
}

/// `static BIO *process_include(char *include, OPENSSL_DIR_CTX **dirctx, char **dirpath)`
///
/// A path that cannot be `stat`ed is not fatal: the system error is raised, NULL
/// is returned, and the caller treats "no such include" as an empty include. A
/// *directory* include reached while another directory include is already open is
/// `CONF_R_RECURSIVE_DIRECTORY_INCLUDE`.
///
/// # Safety
/// `include` NUL-terminated and owned by this call in the directory case;
/// `dirctx`/`dirpath` writable.
unsafe fn process_include(
    include: *mut c_char,
    dirctx: *mut *mut OpenSslDirCtx,
    dirpath: *mut *mut c_char,
) -> *mut Bio {
    // SAFETY: `include` is NUL-terminated per the caller's contract.
    match unsafe { stat_is_dir(include) } {
        Err(errno) => {
            // `ERR_raise_data(ERR_LIB_SYS, errno, "calling stat(%s)", include)`:
            // the format has one substitution, applied here.
            let mut msg: Vec<u8> = b"calling stat(".to_vec();
            // SAFETY: `include` is NUL-terminated.
            msg.extend_from_slice(unsafe { core::ffi::CStr::from_ptr(include) }.to_bytes());
            msg.push(b')');
            msg.push(0);
            // SAFETY: `msg` is NUL-terminated and `include` is live.
            unsafe {
                raise_site_dynamic_data(&CONF_DEF_806, errno, msg.as_ptr().cast::<c_char>());
            }
            ptr::null_mut()
        }
        Ok(true) => {
            // SAFETY: `dirctx` is writable per the caller's contract.
            if !unsafe { *dirctx }.is_null() {
                let mut msg: Vec<u8> = Vec::new();
                // SAFETY: `include` is NUL-terminated.
                msg.extend_from_slice(unsafe { core::ffi::CStr::from_ptr(include) }.to_bytes());
                msg.push(0);
                // SAFETY: `msg` is NUL-terminated.
                unsafe { raise_site_data(&CONF_DEF_813, msg.as_ptr().cast::<c_char>()) };
                return ptr::null_mut();
            }
            // SAFETY: both out-parameters are writable; on success `include` is
            // retained by the caller's `dirpath`.
            let next = unsafe { get_next_file(include, dirctx) };
            if next.is_null() {
                ptr::null_mut()
            } else {
                // SAFETY: `dirpath` is writable per the caller's contract.
                unsafe { *dirpath = include };
                next
            }
        }
        Ok(false) => {
            // SAFETY: `include` is NUL-terminated.
            unsafe { BIO_new_file(include, c"r".as_ptr()) }
        }
    }
}

/// `static BIO *get_next_file(const char *path, OPENSSL_DIR_CTX **dirctx)`
///
/// Only names ending in `.conf` or `.cnf` (case-insensitively) are opened, and a
/// file that cannot be opened is skipped. When the directory is exhausted the
/// context is closed and cleared here, so the caller's "still walking" test is the
/// pointer itself.
///
/// # Safety
/// `path` NUL-terminated; `dirctx` writable and pointing at a live-or-NULL
/// context.
unsafe fn get_next_file(path: *const c_char, dirctx: *mut *mut OpenSslDirCtx) -> *mut Bio {
    // SAFETY: `path` is NUL-terminated per the caller's contract.
    let pathlen = unsafe { sys::strlen(path) };
    loop {
        // SAFETY: `dirctx` is writable per the caller's contract.
        let filename = unsafe { OPENSSL_DIR_read(dirctx, path) };
        if filename.is_null() {
            break;
        }
        // SAFETY: `filename` is NUL-terminated.
        let namelen = unsafe { sys::strlen(filename) };
        let is_conf = namelen > 5
            // SAFETY: `namelen > 5`, so `filename + namelen - 5` is the five-byte
            // suffix, inside the NUL-terminated string.
            && unsafe { OPENSSL_strcasecmp(filename.add(namelen - 5), c".conf".as_ptr()) } == 0;
        let is_cnf = namelen > 4
            // SAFETY: `namelen > 4`, so `filename + namelen - 4` is the four-byte
            // suffix, inside the NUL-terminated string.
            && unsafe { OPENSSL_strcasecmp(filename.add(namelen - 4), c".cnf".as_ptr()) } == 0;
        if !(is_conf || is_cnf) {
            continue;
        }
        let newlen = pathlen + namelen + 2;
        // SAFETY: `newlen` zeroed bytes.
        let newpath = CRYPTO_zalloc(newlen, ptr::null(), 0).cast::<c_char>();
        if newpath.is_null() {
            break;
        }
        // SAFETY: `newpath` holds `newlen` bytes and both sources are
        // NUL-terminated, so each copy fits.
        unsafe {
            OPENSSL_strlcpy(newpath, path, newlen);
            OPENSSL_strlcat(newpath, c"/".as_ptr(), newlen);
            OPENSSL_strlcat(newpath, filename, newlen);
        }
        // SAFETY: `newpath` is NUL-terminated.
        let bio = unsafe { BIO_new_file(newpath, c"r".as_ptr()) };
        // SAFETY: `newpath` came from `CRYPTO_zalloc` above.
        unsafe { CRYPTO_free(newpath.cast::<c_void>(), ptr::null(), 0) };
        // Errors when opening files are non-fatal.
        if !bio.is_null() {
            return bio;
        }
    }
    // SAFETY: `dirctx` is a live out-parameter; a NULL context is explicitly
    // handled by `OPENSSL_DIR_end`.
    unsafe { OPENSSL_DIR_end(dirctx) };
    // The context is cleared *here*, by its owner, because `OPENSSL_DIR_end`
    // deliberately does not clear the caller's pointer (the authority's version
    // leaves it dangling, and `dir.rs` reproduces that). Without this assignment
    // the caller's "am I still walking a directory?" test — the pointer itself —
    // stays true, and the next end-of-file calls back in with a `dirpath` that
    // has already been freed. `RT-CONF`'s recursive/directory include cases hit
    // exactly that, and the failure was a segfault rather than a residual.
    // SAFETY: `dirctx` is a writable out-parameter per the caller's contract.
    unsafe { *dirctx = ptr::null_mut() };
    ptr::null_mut()
}

/// `static void dump_value_doall_arg(const CONF_VALUE *a, BIO *out)`
///
/// Sections print as `[[name]]` and pairs as `[section] name=value`, in the
/// hash's own iteration order.
///
/// # Safety
/// `a` must be a live entry; `out` a live BIO.
unsafe extern "C" fn dump_value_doall_arg(a: *mut c_void, out: *mut c_void) {
    let a = a as *mut ConfValue;
    let out = out as *mut Bio;
    // SAFETY: `out` is a live BIO and `a` a live entry per the callback contract.
    // `BIO_printf` is `extern "C"`-variadic, which Rust may call.
    unsafe {
        if !(*a).name.is_null() {
            BIO_printf(
                out,
                c"[%s] %s=%s\n".as_ptr(),
                (*a).section,
                (*a).name,
                (*a).value,
            );
        } else {
            BIO_printf(out, c"[[%s]]\n".as_ptr(), (*a).section);
        }
    }
}

/// `static int def_dump(const CONF *conf, BIO *bp)`
///
/// # Safety
/// `conf` live with a non-NULL `data`; `bp` a live BIO.
unsafe extern "C" fn def_dump(conf: *const Conf, bp: *mut Bio) -> c_int {
    // SAFETY: `conf` is live per the caller's contract.
    unsafe {
        crate::runtime::lhash::OPENSSL_LH_doall_arg(
            (*conf).data,
            Some(dump_value_doall_arg),
            bp.cast::<c_void>(),
        );
    }
    1
}

/// `static int def_is_number(const CONF *conf, char c)`
///
/// # Safety
/// As [`is_keytype`].
unsafe extern "C" fn def_is_number(conf: *const Conf, c: c_char) -> c_int {
    // SAFETY: `conf` is live with a 128-entry `meth_data` table per this
    // function's contract, which is what [`is_keytype`] requires.
    c_int::from(unsafe { is_number(conf, c) })
}

/// `static int def_to_int(const CONF *conf, char c)`
///
/// # Safety
/// `conf` must be live; `c` must be a character `def_is_number` accepted.
unsafe extern "C" fn def_to_int(_conf: *const Conf, c: c_char) -> c_int {
    c_int::from(c) - c_int::from(b'0' as c_char)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime::conf::lib::{NCONF_free, NCONF_load, NCONF_new_ex};

    /// The two tables must differ exactly where the authority's do: `;` is a
    /// full-line comment only under the WIN32 method, and the double quote is its
    /// own class only there.
    #[test]
    fn the_two_tables_differ_only_where_the_authority_says() {
        let mut differences = Vec::new();
        for i in 0..128u8 {
            if CONF_TYPE_DEFAULT[i as usize] != CONF_TYPE_WIN32[i as usize] {
                differences.push((
                    i,
                    CONF_TYPE_DEFAULT[i as usize],
                    CONF_TYPE_WIN32[i as usize],
                ));
            }
        }
        assert_eq!(
            differences,
            vec![
                // '"'  quote -> dquote
                (34, 0x0040, 0x0400),
                // '#'  comment -> nothing at all
                (35, 0x0080, 0x0000),
                // '\'' quote -> plain
                (39, 0x0040, 0x0000),
                // ';'  punct -> fcomment|punct
                (59, 0x0200, 0x0A00),
                // '\\' esc -> plain
                (92, 0x0020, 0x0000),
                // '`'  quote -> plain
                (96, 0x0040, 0x0000),
            ]
        );
        // Spot-check the classes the parser depends on most.
        assert_eq!(CONF_TYPE_DEFAULT[b' ' as usize], CONF_WS);
        assert_eq!(CONF_TYPE_DEFAULT[b'\t' as usize], CONF_WS);
        assert_eq!(CONF_TYPE_DEFAULT[b'\r' as usize], CONF_WS);
        assert_eq!(CONF_TYPE_DEFAULT[0], CONF_EOF);
        assert_eq!(CONF_TYPE_DEFAULT[b'#' as usize], CONF_COMMENT);
        assert_eq!(CONF_TYPE_DEFAULT[b'$' as usize], CONF_DOLLAR);
        assert_eq!(CONF_TYPE_DEFAULT[b'_' as usize], CONF_UNDER);
        assert_eq!(CONF_TYPE_DEFAULT[b'\\' as usize], CONF_ESC);
    }

    #[test]
    fn method_tables_are_reachable_and_stable() -> Result<(), Box<dyn std::error::Error>> {
        let d = NCONF_default();
        let w = NCONF_WIN32();
        assert!(!d.is_null());
        assert!(!w.is_null());
        assert_ne!(d, w);
        assert_eq!(d, NCONF_default(), "the same static is returned each time");
        // SAFETY: both are the module's own statics.
        unsafe {
            assert_eq!(
                core::ffi::CStr::from_ptr((*d).name).to_str()?,
                "OpenSSL default"
            );
            assert_eq!(core::ffi::CStr::from_ptr((*w).name).to_str()?, "WIN32");
            // The default table is the one the initialiser installs.
            let init = (*d).init.ok_or("default method has init")?;
            // SAFETY: `init` is that default method's initialiser; a NULL
            // configuration is documented to return 0.
            assert_eq!(init(core::ptr::null_mut()), 0);
        }
        Ok(())
    }

    /// A tiny configuration exercised end to end through `NCONF_load`, plus the
    /// two error paths a caller sees most: a missing file and a missing `=`.
    #[test]
    fn loads_a_file_and_reports_the_line_of_a_failure() -> Result<(), Box<dyn std::error::Error>> {
        let dir = std::env::temp_dir().join(format!("openssl-rs-conf-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir)?;
        let path = dir.join("good.cnf");
        std::fs::write(
            &path,
            "[default]\nname = value\ntrailing  =  spaced   \n\n[sect]\nqualified::key = 1\n",
        )?;

        let cpath = std::ffi::CString::new(path.to_str().ok_or("path is not utf-8")?)?;
        // SAFETY: the default method's `create` allocates and initialises.
        let conf = unsafe { NCONF_new_ex(ptr::null_mut(), NCONF_default()) };
        let mut eline: c_long = -1;
        // SAFETY: `conf` is live and `cpath` is NUL-terminated.
        assert_eq!(unsafe { NCONF_load(conf, cpath.as_ptr(), &mut eline) }, 1);
        assert_eq!(eline, -1, "no failure, so the out-parameter is untouched");
        // SAFETY: `conf` is live.
        unsafe {
            let v = _CONF_get_string(conf, c"default".as_ptr(), c"name".as_ptr());
            assert_eq!(core::ffi::CStr::from_ptr(v).to_str(), Ok("value"));
            // Trailing whitespace is trimmed; interior runs are not collapsed.
            let v = _CONF_get_string(conf, c"default".as_ptr(), c"trailing".as_ptr());
            assert_eq!(core::ffi::CStr::from_ptr(v).to_str(), Ok("spaced"));
            // `qualified::key = 1` lands in the section it names, not in the
            // bracket section that was open.
            let v = _CONF_get_string(conf, c"qualified".as_ptr(), c"key".as_ptr());
            assert_eq!(core::ffi::CStr::from_ptr(v).to_str(), Ok("1"));
            assert!(_CONF_get_string(conf, c"sect".as_ptr(), c"key".as_ptr()).is_null());
            // A key in a named section is not visible from `default`.
            assert!(_CONF_get_string(conf, c"default".as_ptr(), c"key".as_ptr()).is_null());
            NCONF_free(conf);
        }

        let bad = dir.join("bad.cnf");
        std::fs::write(&bad, "[default]\nthis line has no equals\n")?;
        let cbad = std::ffi::CString::new(bad.to_str().ok_or("bad path is not utf-8")?)?;
        // SAFETY: fresh configuration and a NUL-terminated path.
        let conf = unsafe { NCONF_new_ex(ptr::null_mut(), NCONF_default()) };
        let mut eline: c_long = -1;
        // SAFETY: `conf` is live and `cbad` is NUL-terminated.
        assert_eq!(unsafe { NCONF_load(conf, cbad.as_ptr(), &mut eline) }, 0);
        assert_eq!(eline, 2, "the failing line number is reported");
        // SAFETY: `conf` is live.
        unsafe { NCONF_free(conf) };

        let missing = dir.join("missing.cnf");
        let cmissing =
            std::ffi::CString::new(missing.to_str().ok_or("missing path is not utf-8")?)?;
        // SAFETY: fresh configuration and a NUL-terminated path.
        let conf = unsafe { NCONF_new_ex(ptr::null_mut(), NCONF_default()) };
        // SAFETY: `conf` is live and `cmissing` is NUL-terminated.
        let loaded = unsafe { NCONF_load(conf, cmissing.as_ptr(), ptr::null_mut()) };
        assert_eq!(loaded, 0);
        // SAFETY: `conf` is live.
        unsafe { NCONF_free(conf) };
        let _ = std::fs::remove_dir_all(&dir);
        Ok(())
    }
}
