//! Phase 8 — `providers/common/der/der_rsa_sig.c`: the RSA `WITH MD` AlgorithmIdentifier writer,
//! and the sixteen `*WithRSAEncryption` OIDs it selects from.
//!
//! This unit is one of `rsa_sig.c.in`'s three non-FIPS prerequisites: `rsa_generate_signature_aid`
//! calls `ossl_DER_w_algorithmIdentifier_MDWithRSAEncryption` for the PKCS#1 v1.5 pad mode, and the
//! identifier it writes is part of the signature's *parameter* contract rather than of the
//! operation — which is why the court can observe it through `OSSL_SIGNATURE_PARAM_ALGORITHM_ID`.
//!
//! ## The OIDs are precompiled literals, and they are transcribed rather than computed
//!
//! `providers/common/der/der_rsa_gen.c` is generated by `oids_to_c.pm` from
//! `providers/common/der/RSA.asn1`, and every entry is the DER encoding of one OID with no values
//! to derive. The values below are read back from the authority's own generated headers —
//! `der_rsa.h`'s `DER_OID_V_*` macros for the `pkcs-1` arcs and `der_digests.h`'s for the four
//! `sha3` ones, which `der_rsa_sig.c` reaches through its own `#define` aliases — not typed from
//! the ASN.1 by hand.
//!
//! ## What is here, and what is not
//!
//! `der_rsa_sig.c` defines exactly one function and it is transcribed whole. The other RSA
//! AlgorithmIdentifier writers (`ossl_DER_w_RSASSA_PSS_params` and the two
//! `ossl_DER_w_algorithmIdentifier_RSA*` functions) live in `providers/common/der/der_rsa_key.c`
//! and are a separate unit, transcribed as `src/provider/der_rsa_key.rs`.
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::{c_int, c_uchar};

use crate::der_writer::{
    ossl_DER_w_begin_sequence, ossl_DER_w_end_sequence, ossl_DER_w_null, ossl_DER_w_precompiled,
};
use crate::packet::Wpacket;
use crate::runtime::obj::{
    NID_md2, NID_md4, NID_md5, NID_mdc2, NID_ripemd160, NID_sha1, NID_sha224, NID_sha256,
    NID_sha384, NID_sha3_224, NID_sha3_256, NID_sha3_384, NID_sha3_512, NID_sha512, NID_sha512_224,
    NID_sha512_256,
};

/// `ossl_der_oid_md2WithRSAEncryption` — `der_rsa.h`'s `DER_OID_V_md2WithRSAEncryption DER_P_OBJECT,
/// 9, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x02`. Thirteen bytes, the DER encoding
/// including its `06 09` header.
static OSSL_DER_OID_MD2_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x02,
];

/// `ossl_der_oid_md5WithRSAEncryption`.
static OSSL_DER_OID_MD5_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x04,
];

/// `ossl_der_oid_md4WithRSAEncryption`.
static OSSL_DER_OID_MD4_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x03,
];

/// `ossl_der_oid_ripemd160WithRSAEncryption` — an eight-byte DER object over the `1.3.36.3.3.1.2`
/// arc, so its header is `06 06` rather than `06 09`.
static OSSL_DER_OID_RIPEMD160_WITH_RSA_ENCRYPTION: [u8; 8] =
    [0x06, 0x06, 0x2B, 0x24, 0x03, 0x03, 0x01, 0x02];

/// `ossl_der_oid_mdc2WithRSASignature` — the seven-byte `1.3.14.3.2.14` arc. `der_rsa_sig.c`'s
/// `#define ossl_der_oid_mdc2WithRSAEncryption ossl_der_oid_mdc2WithRSASignature` is the alias that
/// lets `MD_with_RSA_CASE(mdc2, …)` name it by the same spelling as its siblings.
static OSSL_DER_OID_MDC2_WITH_RSA_SIGNATURE: [u8; 7] = [0x06, 0x05, 0x2B, 0x0E, 0x03, 0x02, 0x0E];

/// `ossl_der_oid_sha1WithRSAEncryption`.
static OSSL_DER_OID_SHA1_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x05,
];

/// `ossl_der_oid_sha224WithRSAEncryption`.
static OSSL_DER_OID_SHA224_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0E,
];

/// `ossl_der_oid_sha256WithRSAEncryption`.
static OSSL_DER_OID_SHA256_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0B,
];

/// `ossl_der_oid_sha384WithRSAEncryption`.
static OSSL_DER_OID_SHA384_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0C,
];

/// `ossl_der_oid_sha512WithRSAEncryption`.
static OSSL_DER_OID_SHA512_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0D,
];

/// `ossl_der_oid_sha512_224WithRSAEncryption`.
static OSSL_DER_OID_SHA512_224_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0F,
];

/// `ossl_der_oid_sha512_256WithRSAEncryption`.
static OSSL_DER_OID_SHA512_256_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x10,
];

/// `ossl_der_oid_sha3_224WithRSAEncryption` — the `#define` alias of
/// `ossl_der_oid_id_rsassa_pkcs1_v1_5_with_sha3_224` (`der_rsa.h`'s `DER_OID_V_*`).
static OSSL_DER_OID_SHA3_224_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0D,
];

/// `ossl_der_oid_sha3_256WithRSAEncryption`.
static OSSL_DER_OID_SHA3_256_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0E,
];

/// `ossl_der_oid_sha3_384WithRSAEncryption`.
static OSSL_DER_OID_SHA3_384_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0F,
];

/// `ossl_der_oid_sha3_512WithRSAEncryption`.
static OSSL_DER_OID_SHA3_512_WITH_RSA_ENCRYPTION: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x10,
];

/// `int ossl_DER_w_algorithmIdentifier_MDWithRSAEncryption(WPACKET *pkt, int tag, int mdnid)` —
/// `der_rsa_sig.c:33-73`.
///
/// Sixteen cases, all compiled on this profile: the `#ifndef FIPS_MODULE` block at `:40-46` guards
/// the five legacy digests (`md2`, `md5`, `md4`, `ripemd160`, `mdc2`), and `FIPS_MODULE` is not
/// defined here. The shape differs from the DSA/ECDSA/EdDSA writers in two ways: the identifier
/// carries an explicit `NULL` PARAMETERS field (`:69`), and an unlisted `mdnid` answers **-1**
/// rather than 0 (`:64`) — the caller distinguishes "no such OID" from "the write failed".
///
/// # Safety
/// `pkt` live.
#[allow(non_snake_case)] // the authority's name is the contract
#[allow(non_upper_case_globals)] // the `NID_*` constants are the authority's own spellings
pub(crate) unsafe fn ossl_DER_w_algorithmIdentifier_MDWithRSAEncryption(
    pkt: *mut Wpacket,
    tag: c_int,
    mdnid: c_int,
) -> c_int {
    let precompiled: &[u8] = match mdnid {
        NID_md2 => &OSSL_DER_OID_MD2_WITH_RSA_ENCRYPTION,
        NID_md5 => &OSSL_DER_OID_MD5_WITH_RSA_ENCRYPTION,
        NID_md4 => &OSSL_DER_OID_MD4_WITH_RSA_ENCRYPTION,
        NID_ripemd160 => &OSSL_DER_OID_RIPEMD160_WITH_RSA_ENCRYPTION,
        NID_mdc2 => &OSSL_DER_OID_MDC2_WITH_RSA_SIGNATURE,
        NID_sha1 => &OSSL_DER_OID_SHA1_WITH_RSA_ENCRYPTION,
        NID_sha224 => &OSSL_DER_OID_SHA224_WITH_RSA_ENCRYPTION,
        NID_sha256 => &OSSL_DER_OID_SHA256_WITH_RSA_ENCRYPTION,
        NID_sha384 => &OSSL_DER_OID_SHA384_WITH_RSA_ENCRYPTION,
        NID_sha512 => &OSSL_DER_OID_SHA512_WITH_RSA_ENCRYPTION,
        NID_sha512_224 => &OSSL_DER_OID_SHA512_224_WITH_RSA_ENCRYPTION,
        NID_sha512_256 => &OSSL_DER_OID_SHA512_256_WITH_RSA_ENCRYPTION,
        NID_sha3_224 => &OSSL_DER_OID_SHA3_224_WITH_RSA_ENCRYPTION,
        NID_sha3_256 => &OSSL_DER_OID_SHA3_256_WITH_RSA_ENCRYPTION,
        NID_sha3_384 => &OSSL_DER_OID_SHA3_384_WITH_RSA_ENCRYPTION,
        NID_sha3_512 => &OSSL_DER_OID_SHA3_512_WITH_RSA_ENCRYPTION,
        _ => return -1,
    };

    // SAFETY: `pkt` is live per the contract, and `precompiled` is a `'static` array whose length
    // is the fourth argument.
    unsafe {
        (ossl_DER_w_begin_sequence(pkt, tag) != 0
            && ossl_DER_w_null(pkt, -1) != 0
            && ossl_DER_w_precompiled(
                pkt,
                -1,
                precompiled.as_ptr().cast::<c_uchar>(),
                precompiled.len(),
            ) != 0
            && ossl_DER_w_end_sequence(pkt, tag) != 0) as c_int
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every OID the sixteen cases select is the authority's own generated bytes: `der_rsa.h`'s
    /// `DER_OID_V_*` macros, which are `DER_P_OBJECT` (`0x06`), a length, and the arc body. The
    /// check is against the authority's values rather than against a second transcription, because
    /// both sides agreeing on a wrong constant is invisible to a differential court.
    #[test]
    fn the_rsa_oids_are_the_authoritys_generated_bytes() {
        // `DER_OID_V_md2WithRSAEncryption DER_P_OBJECT, 9, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x02`.
        assert_eq!(
            OSSL_DER_OID_MD2_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x02]
        );
        assert_eq!(
            OSSL_DER_OID_MD5_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x04]
        );
        assert_eq!(
            OSSL_DER_OID_MD4_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x03]
        );
        // `DER_OID_V_ripemd160WithRSAEncryption DER_P_OBJECT, 6, 0x2B, 0x24, 0x03, 0x03, 0x01, 0x02`.
        assert_eq!(
            OSSL_DER_OID_RIPEMD160_WITH_RSA_ENCRYPTION,
            [0x06, 0x06, 0x2B, 0x24, 0x03, 0x03, 0x01, 0x02]
        );
        // `DER_OID_V_mdc2WithRSASignature DER_P_OBJECT, 5, 0x2B, 0x0E, 0x03, 0x02, 0x0E`.
        assert_eq!(
            OSSL_DER_OID_MDC2_WITH_RSA_SIGNATURE,
            [0x06, 0x05, 0x2B, 0x0E, 0x03, 0x02, 0x0E]
        );
        assert_eq!(
            OSSL_DER_OID_SHA1_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x05]
        );
        assert_eq!(
            OSSL_DER_OID_SHA224_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0E]
        );
        assert_eq!(
            OSSL_DER_OID_SHA256_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0B]
        );
        assert_eq!(
            OSSL_DER_OID_SHA384_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0C]
        );
        assert_eq!(
            OSSL_DER_OID_SHA512_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0D]
        );
        assert_eq!(
            OSSL_DER_OID_SHA512_224_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x0F]
        );
        assert_eq!(
            OSSL_DER_OID_SHA512_256_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x10]
        );
        // `DER_OID_V_id_rsassa_pkcs1_v1_5_with_sha3_224 DER_P_OBJECT, 9, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0D`.
        assert_eq!(
            OSSL_DER_OID_SHA3_224_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0D]
        );
        assert_eq!(
            OSSL_DER_OID_SHA3_256_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0E]
        );
        assert_eq!(
            OSSL_DER_OID_SHA3_384_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0F]
        );
        assert_eq!(
            OSSL_DER_OID_SHA3_512_WITH_RSA_ENCRYPTION,
            [0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x10]
        );
    }

    /// An `mdnid` outside the sixteen writes nothing and answers **-1**, which is `MD_with_RSA_CASE`'s
    /// `default` arm — not the 0 the DSA, ECDSA and EdDSA writers answer.
    #[test]
    fn an_unlisted_md_nid_answers_minus_one() {
        let mut pkt = core::mem::MaybeUninit::<Wpacket>::uninit();
        let mut buf = [0u8; 64];
        // SAFETY: `pkt` is a live local, `buf` is this call's own, and `mdnid` is `NID_undef`.
        unsafe {
            assert_eq!(
                crate::packet::WPACKET_init_der(pkt.as_mut_ptr(), buf.as_mut_ptr(), 64),
                1
            );
            let r = ossl_DER_w_algorithmIdentifier_MDWithRSAEncryption(
                pkt.as_mut_ptr(),
                -1,
                crate::runtime::obj::NID_undef,
            );
            assert_eq!(r, -1);
            crate::packet::WPACKET_cleanup(pkt.as_mut_ptr());
        }
    }
}
