//! Phase 8 — `providers/common/der/der_sm2_sig.c`: the SM2 `WITH MD` AlgorithmIdentifier writer,
//! and the one `sm2-with-SM3` OID it selects.
//!
//! This unit is `sm2_sig.c.in`'s one non-FIPS prerequisite — `src/sm2/sign.rs`'s
//! `ossl_sm2_compute_z_digest` and `src/ec/lib.rs`'s `ossl_ec_group_do_inverse_ord` being already
//! landed — exactly as `der_ec_sig.c` is `ecdsa_sig.c.in`'s. `sm2_sig.c.in`'s
//! `sm2sig_digest_signverify_init` builds the signature's AlgorithmIdentifier here, and like the DSA,
//! ECDSA and EdDSA writers it writes into a buffer it keeps on the context, because the identifier is
//! part of the signature's *parameter* contract rather than of the operation.
//!
//! ## There is one MD case, and its name is an alias
//!
//! `der_sm2_sig.c:19` defines `ossl_der_oid_id_sm2_with_sm3` as an alias of
//! `ossl_der_oid_sm2_with_SM3` "so we can have a uniform MD_CASE", and the macro pastes `NID_sm3`
//! onto the alias. SM2 permits no digest other than SM3, so the switch has exactly one case and a
//! `mdnid` outside it answers 0 without writing anything.
//!
//! ## The OID is a precompiled literal, transcribed rather than computed
//!
//! `providers/common/der/der_sm2_gen.c` is generated by `oids_to_c.pm` from
//! `providers/common/der/SM2.asn1`, and the entry is the DER encoding of one OID with no values to
//! derive: `sm2-with-SM3 OBJECT IDENTIFIER ::= { sm-scheme 501 }` is `06 08 2A 81 1C CF 55 01 83
//! 75`, ten bytes including the `06 08` header. The value below is read back from the authority's own
//! generated header (`der_sm2.h`'s `DER_OID_V_sm2_with_SM3`), not typed from the ASN.1 by hand.
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::{c_int, c_uchar};

use crate::der_writer::{
    ossl_DER_w_begin_sequence, ossl_DER_w_end_sequence, ossl_DER_w_precompiled,
};
use crate::ec::EcKey;
use crate::packet::Wpacket;
use crate::runtime::obj::NID_sm3;

/// `ossl_der_oid_sm2_with_SM3` — `der_sm2_gen.c`, generated from `SM2.asn1`'s
/// `sm2-with-SM3 OBJECT IDENTIFIER ::= { sm-scheme 501 }`. Ten bytes, the DER encoding including
/// its `06 08` header.
static OSSL_DER_OID_ID_SM2_WITH_SM3: [u8; 10] =
    [0x06, 0x08, 0x2A, 0x81, 0x1C, 0xCF, 0x55, 0x01, 0x83, 0x75];

/// `int ossl_DER_w_algorithmIdentifier_SM2_with_MD(WPACKET *pkt, int cont, EC_KEY *ec, int mdnid)`
/// — `der_sm2_sig.c:26-45`.
///
/// The `EC_KEY *ec` parameter is the authority's and is **unused**: the identifier for an
/// `sm2-with-SM3` algorithm carries no parameters, so the key contributes nothing. The single-case
/// switch is `MD_CASE`'s expansion, which is the file's macro rather than a convenience — the
/// generated `der_sm2.h` names the OID the macro names, and a `mdnid` other than `NID_sm3` answers 0
/// without writing anything.
///
/// # Safety
/// `pkt` live; `ec` is the caller's key and is not read.
#[allow(non_snake_case)] // the authority's name is the contract
#[allow(non_upper_case_globals)] // the `NID_sm3` constant is the authority's own spelling
pub(crate) unsafe fn ossl_DER_w_algorithmIdentifier_SM2_with_MD(
    pkt: *mut Wpacket,
    cont: c_int,
    _ec: *mut EcKey,
    mdnid: c_int,
) -> c_int {
    let precompiled: &[u8] = match mdnid {
        NID_sm3 => &OSSL_DER_OID_ID_SM2_WITH_SM3,
        _ => return 0,
    };

    // SAFETY: `pkt` is live per the contract, and `precompiled` is a `'static` array whose length
    // is the fourth argument.
    unsafe {
        (ossl_DER_w_begin_sequence(pkt, cont) != 0
            && ossl_DER_w_precompiled(
                pkt,
                -1,
                precompiled.as_ptr().cast::<c_uchar>(),
                precompiled.len(),
            ) != 0
            && ossl_DER_w_end_sequence(pkt, cont) != 0) as c_int
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The OID is the authority's own generated bytes: `der_sm2.h`'s
    /// `DER_OID_V_sm2_with_SM3 DER_P_OBJECT, 8, 0x2A, 0x81, 0x1C, 0xCF, 0x55, 0x01, 0x83, 0x75`.
    /// The check is against the authority's value rather than against a second transcription,
    /// because both sides agreeing on a wrong constant is invisible to a differential court.
    #[test]
    fn the_sm2_oid_is_the_authoritys_generated_bytes() {
        assert_eq!(
            OSSL_DER_OID_ID_SM2_WITH_SM3,
            [0x06, 0x08, 0x2A, 0x81, 0x1C, 0xCF, 0x55, 0x01, 0x83, 0x75]
        );
    }

    /// A `mdnid` other than `NID_sm3` writes nothing and answers 0, which is `MD_CASE`'s `default`
    /// arm.
    #[test]
    fn an_unapproved_md_nid_writes_nothing() {
        let mut pkt = core::mem::MaybeUninit::<Wpacket>::uninit();
        let mut buf = [0u8; 64];
        // SAFETY: `pkt` is a live local, `buf` is this call's own, and `mdnid` is `NID_undef`.
        unsafe {
            assert_eq!(
                crate::packet::WPACKET_init_der(pkt.as_mut_ptr(), buf.as_mut_ptr(), 64),
                1
            );
            let r = ossl_DER_w_algorithmIdentifier_SM2_with_MD(
                pkt.as_mut_ptr(),
                -1,
                core::ptr::null_mut(),
                crate::runtime::obj::NID_undef,
            );
            assert_eq!(r, 0);
            crate::packet::WPACKET_cleanup(pkt.as_mut_ptr());
        }
    }
}
