//! Phase 8 — `providers/common/der/der_ecx_key.c`: the four ECX `AlgorithmIdentifier` writers,
//! and the four OIDs they write.
//!
//! This unit is `eddsa_sig.c.in`'s one prerequisite. `eddsa_signverify_init` builds the signature's
//! AlgorithmIdentifier from it, selecting `ED25519` or `ED448` by the `ECX_KEY`'s own `type`, and
//! keeps the identifier on the context because it is part of the signature's *parameter* contract
//! rather than of the operation — the same shape as `der_dsa_sig.c` and `der_ec_sig.c`.
//!
//! ## The unit is transcribed whole, and two of its four writers are reached on this crate
//!
//! `der_ecx_key.c` defines **four** writers: `X25519`, `X448`, `ED25519` and `ED448`. Only the two
//! `ED*` ones are reached by `eddsa_sig.c.in`, but the unit is transcribed whole because the
//! unit — not the row — is the thing D327 transcribes, and the two `X*` writers share the file's one
//! `ossl_DER_w_begin_sequence`/`_precompiled`/`_end_sequence` shape. They are the AlgorithmIdentifier
//! the `X25519`/`X448` *key* encoders write, which land with their own unit.
//!
//! ## The OIDs are precompiled literals, and they are transcribed rather than computed
//!
//! `providers/common/der/der_ecx_gen.c` is generated by `oids_to_c.pm` from
//! `providers/common/der/ECX.asn1`, and every entry is the DER encoding of one OID with no values
//! to derive: `id-X25519` is `06 03 2B 65 6E` and its three siblings differ in the final arc. The
//! values below are read back from the authority's own generated header (`der_ecx.h`'s
//! `DER_OID_V_*` macros).
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::{c_int, c_uchar};

use crate::der_writer::{
    ossl_DER_w_begin_sequence, ossl_DER_w_end_sequence, ossl_DER_w_precompiled,
};
use crate::ec::ecx_key::EcxKey;
use crate::packet::Wpacket;

/// `ossl_der_oid_id_X25519` — `der_ecx_gen.c`, generated from `ECX.asn1`'s
/// `id-X25519 OBJECT IDENTIFIER ::= { 1 3 101 110 }`. Five bytes, the DER encoding including its
/// `06 03` header.
///
/// The two `X*` OIDs are the unit's other half: they are read by the `X25519`/`X448` *key* encoders,
/// which land with their own unit, so they are named here rather than dropped (D327's whole-unit
/// rule).
#[allow(dead_code)]
static OSSL_DER_OID_ID_X25519: [u8; 5] = [0x06, 0x03, 0x2B, 0x65, 0x6E];

/// `ossl_der_oid_id_X448` — `{ 1 3 101 111 }`.
#[allow(dead_code)]
static OSSL_DER_OID_ID_X448: [u8; 5] = [0x06, 0x03, 0x2B, 0x65, 0x6F];

/// `ossl_der_oid_id_Ed25519` — `{ 1 3 101 112 }`.
static OSSL_DER_OID_ID_ED25519: [u8; 5] = [0x06, 0x03, 0x2B, 0x65, 0x70];

/// `ossl_der_oid_id_Ed448` — `{ 1 3 101 113 }`.
static OSSL_DER_OID_ID_ED448: [u8; 5] = [0x06, 0x03, 0x2B, 0x65, 0x71];

/// The body the four writers share: a `SEQUENCE` around one precompiled OID and no parameters. The
/// `ECX_KEY *ec` argument is the authority's and is unused by all four.
///
/// # Safety
/// `pkt` is live.
#[allow(non_snake_case)] // the authority's `OSSL_DER_*` spelling is the contract
unsafe fn write_identifier(pkt: *mut Wpacket, cont: c_int, precompiled: &[u8]) -> c_int {
    // SAFETY: `pkt` is live per the contract, and `precompiled` is a `'static` array whose length
    // is the third argument.
    unsafe {
        (ossl_DER_w_begin_sequence(pkt, cont) != 0
            && ossl_DER_w_precompiled(
                pkt,
                -1,
                precompiled.as_ptr().cast::<c_uchar>(),
                precompiled.len(),
            ) != 0
            && ossl_DER_w_end_sequence(pkt, cont) != 0) as c_int
    }
}

/// `int ossl_DER_w_algorithmIdentifier_X25519(WPACKET *pkt, int cont, ECX_KEY *ec)` —
/// `der_ecx_key.c:14-21`. Reached by the `X25519` key encoder, not by this pass's rows.
///
/// # Safety
/// `pkt` live; `ec` is the caller's key and is not read.
#[allow(dead_code)] // reached by the `X25519` key encoder, which lands with its own unit
#[allow(non_snake_case)] // the authority's name is the contract
pub(crate) unsafe fn ossl_DER_w_algorithmIdentifier_X25519(
    pkt: *mut Wpacket,
    cont: c_int,
    _ec: *mut EcxKey,
) -> c_int {
    // SAFETY: the caller's contract.
    unsafe { write_identifier(pkt, cont, &OSSL_DER_OID_ID_X25519) }
}

/// `int ossl_DER_w_algorithmIdentifier_X448(WPACKET *pkt, int cont, ECX_KEY *ec)` —
/// `der_ecx_key.c:23-30`. Reached by the `X448` key encoder, not by this pass's rows.
///
/// # Safety
/// `pkt` live; `ec` is the caller's key and is not read.
#[allow(dead_code)] // reached by the `X448` key encoder, which lands with its own unit
#[allow(non_snake_case)] // the authority's name is the contract
pub(crate) unsafe fn ossl_DER_w_algorithmIdentifier_X448(
    pkt: *mut Wpacket,
    cont: c_int,
    _ec: *mut EcxKey,
) -> c_int {
    // SAFETY: the caller's contract.
    unsafe { write_identifier(pkt, cont, &OSSL_DER_OID_ID_X448) }
}

/// `int ossl_DER_w_algorithmIdentifier_ED25519(WPACKET *pkt, int cont, ECX_KEY *ec)` —
/// `der_ecx_key.c:32-39`.
///
/// # Safety
/// `pkt` live; `ec` is the caller's key and is not read.
#[allow(non_snake_case)] // the authority's name is the contract
pub(crate) unsafe fn ossl_DER_w_algorithmIdentifier_ED25519(
    pkt: *mut Wpacket,
    cont: c_int,
    _ec: *mut EcxKey,
) -> c_int {
    // SAFETY: the caller's contract.
    unsafe { write_identifier(pkt, cont, &OSSL_DER_OID_ID_ED25519) }
}

/// `int ossl_DER_w_algorithmIdentifier_ED448(WPACKET *pkt, int cont, ECX_KEY *ec)` —
/// `der_ecx_key.c:41-48`.
///
/// # Safety
/// `pkt` live; `ec` is the caller's key and is not read.
#[allow(non_snake_case)] // the authority's name is the contract
pub(crate) unsafe fn ossl_DER_w_algorithmIdentifier_ED448(
    pkt: *mut Wpacket,
    cont: c_int,
    _ec: *mut EcxKey,
) -> c_int {
    // SAFETY: the caller's contract.
    unsafe { write_identifier(pkt, cont, &OSSL_DER_OID_ID_ED448) }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The four OIDs are the authority's own generated bytes: `der_ecx.h`'s `DER_OID_V_*` macros,
    /// which are `DER_P_OBJECT` (`0x06`), a length, and the arc body. Checked against the
    /// authority's values rather than against a second transcription (D392).
    #[test]
    fn the_ecx_oids_are_the_authoritys_generated_bytes() {
        assert_eq!(OSSL_DER_OID_ID_X25519, [0x06, 0x03, 0x2B, 0x65, 0x6E]);
        assert_eq!(OSSL_DER_OID_ID_X448, [0x06, 0x03, 0x2B, 0x65, 0x6F]);
        assert_eq!(OSSL_DER_OID_ID_ED25519, [0x06, 0x03, 0x2B, 0x65, 0x70]);
        assert_eq!(OSSL_DER_OID_ID_ED448, [0x06, 0x03, 0x2B, 0x65, 0x71]);
    }

    /// Each writer is a `SEQUENCE` around one OID: the four encodings are seven bytes each
    /// (`30 05` header, then the five-byte OID) and differ only in the final arc.
    #[test]
    fn each_writer_emits_its_oid_in_a_sequence() {
        let mut buf = [0u8; 32];
        for (writer, tail) in [
            (
                ossl_DER_w_algorithmIdentifier_X25519
                    as unsafe fn(*mut Wpacket, c_int, *mut EcxKey) -> c_int,
                0x6Eu8,
            ),
            (
                ossl_DER_w_algorithmIdentifier_X448
                    as unsafe fn(*mut Wpacket, c_int, *mut EcxKey) -> c_int,
                0x6F,
            ),
            (
                ossl_DER_w_algorithmIdentifier_ED25519
                    as unsafe fn(*mut Wpacket, c_int, *mut EcxKey) -> c_int,
                0x70,
            ),
            (
                ossl_DER_w_algorithmIdentifier_ED448
                    as unsafe fn(*mut Wpacket, c_int, *mut EcxKey) -> c_int,
                0x71,
            ),
        ] {
            let mut pkt = core::mem::MaybeUninit::<Wpacket>::uninit();
            // SAFETY: `pkt` is a live local, `buf` is this call's own, and the writer is one of the
            // four above. `WPACKET_init_der` fills the buffer from its end, so the bytes are read
            // back through `WPACKET_get_curr` once the top-level `SEQUENCE` has closed.
            unsafe {
                assert_eq!(
                    crate::packet::WPACKET_init_der(pkt.as_mut_ptr(), buf.as_mut_ptr(), 32),
                    1
                );
                assert_eq!(writer(pkt.as_mut_ptr(), -1, core::ptr::null_mut()), 1);
                assert_eq!(crate::packet::WPACKET_finish(pkt.as_mut_ptr()), 1);
                let mut written: usize = 0;
                crate::packet::WPACKET_get_total_written(pkt.as_mut_ptr(), &raw mut written);
                assert_eq!(written, 7);
                let start = crate::packet::WPACKET_get_curr(pkt.as_mut_ptr());
                assert_eq!(
                    core::slice::from_raw_parts(start, 7),
                    &[0x30, 0x05, 0x06, 0x03, 0x2B, 0x65, tail]
                );
                crate::packet::WPACKET_cleanup(pkt.as_mut_ptr());
            }
        }
    }
}
