//! Phase 8 — `providers/common/der/der_ec_sig.c`: the ECDSA `WITH MD` AlgorithmIdentifier writer,
//! and the nine `ecdsa-with-*` OIDs it selects from.
//!
//! This unit is `ecdsa_sig.c.in`'s one non-FIPS prerequisite — `src/provider/digest_to_nid.rs`'s
//! `ossl_digest_get_approved_nid` being already landed — exactly as `der_dsa_sig.c` is `dsa_sig.c`'s.
//! `ecdsa_sig.c.in`'s `ecdsa_setup_md` builds the signature's AlgorithmIdentifier here, and like the
//! DSA and EdDSA writers it writes into a buffer it then keeps on the context, because the identifier
//! is part of the signature's *parameter* contract rather than of the operation.
//!
//! ## The OIDs are precompiled literals, and they are transcribed rather than computed
//!
//! `providers/common/der/der_ec_gen.c` is generated by `oids_to_c.pm` from
//! `providers/common/der/EC.asn1`, and every entry is the DER encoding of one OID with no values to
//! derive: `ecdsa-with-SHA1` is `06 07 2A 86 48 CE 3D 04 01` and its eight SHA-2/SHA-3 siblings
//! differ in the final arc. The values below are read back from the authority's own generated header
//! (`der_ec.h`'s `DER_OID_V_*` macros), not typed from the ASN.1 by hand.
//!
//! ## What is here, and what is not
//!
//! `der_ec_sig.c` defines exactly one function; the whole unit is transcribed. The other
//! `providers/common/der/` units (`der_ecx_key.c`, `der_rsa_sig.c`, `der_sm2_sig.c` and the key
//! encoders) are separate units and are not landed: each is named with its row in
//! `src/provider/signature.rs`.
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::{c_int, c_uchar};

use crate::der_writer::{
    ossl_DER_w_begin_sequence, ossl_DER_w_end_sequence, ossl_DER_w_precompiled,
};
use crate::ec::EcKey;
use crate::packet::Wpacket;
use crate::runtime::obj::{
    NID_sha1, NID_sha224, NID_sha256, NID_sha384, NID_sha3_224, NID_sha3_256, NID_sha3_384,
    NID_sha3_512, NID_sha512,
};

/// `ossl_der_oid_ecdsa_with_SHA1` — `der_ec_gen.c`, generated from `EC.asn1`'s
/// `ecdsa-with-SHA1 OBJECT IDENTIFIER ::= { iso(1) member-body(2) us(840) ansi-X9-62(10045)
/// signatures(4) 1 }`. Nine bytes, the DER encoding including its `06 07` header.
static OSSL_DER_OID_ECDSA_WITH_SHA1: [u8; 9] =
    [0x06, 0x07, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x01];

/// `ossl_der_oid_ecdsa_with_SHA224`.
static OSSL_DER_OID_ECDSA_WITH_SHA224: [u8; 10] =
    [0x06, 0x08, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x03, 0x01];

/// `ossl_der_oid_ecdsa_with_SHA256`.
static OSSL_DER_OID_ECDSA_WITH_SHA256: [u8; 10] =
    [0x06, 0x08, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x03, 0x02];

/// `ossl_der_oid_ecdsa_with_SHA384`.
static OSSL_DER_OID_ECDSA_WITH_SHA384: [u8; 10] =
    [0x06, 0x08, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x03, 0x03];

/// `ossl_der_oid_ecdsa_with_SHA512`.
static OSSL_DER_OID_ECDSA_WITH_SHA512: [u8; 10] =
    [0x06, 0x08, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x03, 0x04];

/// `ossl_der_oid_id_ecdsa_with_sha3_224`.
static OSSL_DER_OID_ID_ECDSA_WITH_SHA3_224: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x09,
];

/// `ossl_der_oid_id_ecdsa_with_sha3_256`.
static OSSL_DER_OID_ID_ECDSA_WITH_SHA3_256: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0A,
];

/// `ossl_der_oid_id_ecdsa_with_sha3_384`.
static OSSL_DER_OID_ID_ECDSA_WITH_SHA3_384: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0B,
];

/// `ossl_der_oid_id_ecdsa_with_sha3_512`.
static OSSL_DER_OID_ID_ECDSA_WITH_SHA3_512: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0C,
];

/// `int ossl_DER_w_algorithmIdentifier_ECDSA_with_MD(WPACKET *pkt, int cont, EC_KEY *ec, int mdnid)`
/// — `der_ec_sig.c:27-51`.
///
/// The `EC_KEY *ec` parameter is the authority's and is **unused**: the identifier for an
/// `ecdsa-with-*` algorithm carries no parameters, so the key contributes nothing. The nine-case
/// switch is `MD_CASE`'s expansion, which is the file's macro rather than a convenience — the
/// generated `der_ec.h` names the OIDs the macro pastes together, and a `mdnid` outside the nine
/// answers 0 without writing anything.
///
/// # Safety
/// `pkt` live; `ec` is the caller's key and is not read.
#[allow(non_snake_case)] // the authority's name is the contract
#[allow(non_upper_case_globals)] // the `NID_*` constants are the authority's own spellings
pub(crate) unsafe fn ossl_DER_w_algorithmIdentifier_ECDSA_with_MD(
    pkt: *mut Wpacket,
    cont: c_int,
    _ec: *mut EcKey,
    mdnid: c_int,
) -> c_int {
    let precompiled: &[u8] = match mdnid {
        NID_sha1 => &OSSL_DER_OID_ECDSA_WITH_SHA1,
        NID_sha224 => &OSSL_DER_OID_ECDSA_WITH_SHA224,
        NID_sha256 => &OSSL_DER_OID_ECDSA_WITH_SHA256,
        NID_sha384 => &OSSL_DER_OID_ECDSA_WITH_SHA384,
        NID_sha512 => &OSSL_DER_OID_ECDSA_WITH_SHA512,
        NID_sha3_224 => &OSSL_DER_OID_ID_ECDSA_WITH_SHA3_224,
        NID_sha3_256 => &OSSL_DER_OID_ID_ECDSA_WITH_SHA3_256,
        NID_sha3_384 => &OSSL_DER_OID_ID_ECDSA_WITH_SHA3_384,
        NID_sha3_512 => &OSSL_DER_OID_ID_ECDSA_WITH_SHA3_512,
        _ => return 0,
    };

    // SAFETY: `pkt` is live per the contract, and `precompiled` is a `'static` array whose length
    // is the fourth argument.
    unsafe {
        (ossl_DER_w_begin_sequence(pkt, cont) != 0
            && ossl_DER_w_precompiled(
                pkt,
                -1,
                precompiled.as_ptr().cast::<c_uchar>(),
                precompiled.len(),
            ) != 0
            && ossl_DER_w_end_sequence(pkt, cont) != 0) as c_int
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every OID the nine cases select is the authority's own generated bytes: `der_ec.h`'s
    /// `DER_OID_V_*` macros, which are `DER_P_OBJECT` (`0x06`), a length, and the arc body. The
    /// check is against the authority's values rather than against a second transcription, because
    /// both sides agreeing on a wrong constant is invisible to a differential court.
    #[test]
    fn the_ecdsa_oids_are_the_authoritys_generated_bytes() {
        // `DER_OID_V_ecdsa_with_SHA1 DER_P_OBJECT, 7, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x01`.
        assert_eq!(
            OSSL_DER_OID_ECDSA_WITH_SHA1,
            [0x06, 0x07, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x01]
        );
        // `DER_OID_V_ecdsa_with_SHA224 DER_P_OBJECT, 8, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x03, 0x01`.
        assert_eq!(
            OSSL_DER_OID_ECDSA_WITH_SHA224,
            [0x06, 0x08, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x03, 0x01]
        );
        assert_eq!(
            OSSL_DER_OID_ECDSA_WITH_SHA256,
            [0x06, 0x08, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x03, 0x02]
        );
        assert_eq!(
            OSSL_DER_OID_ECDSA_WITH_SHA384,
            [0x06, 0x08, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x03, 0x03]
        );
        assert_eq!(
            OSSL_DER_OID_ECDSA_WITH_SHA512,
            [0x06, 0x08, 0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x04, 0x03, 0x04]
        );
        // `DER_OID_V_id_ecdsa_with_sha3_224 DER_P_OBJECT, 9, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x09`.
        assert_eq!(
            OSSL_DER_OID_ID_ECDSA_WITH_SHA3_224,
            [0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x09]
        );
        assert_eq!(
            OSSL_DER_OID_ID_ECDSA_WITH_SHA3_256,
            [0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0A]
        );
        assert_eq!(
            OSSL_DER_OID_ID_ECDSA_WITH_SHA3_384,
            [0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0B]
        );
        assert_eq!(
            OSSL_DER_OID_ID_ECDSA_WITH_SHA3_512,
            [0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x0C]
        );
    }

    /// A `mdnid` outside the nine writes nothing and answers 0, which is `MD_CASE`'s `default` arm.
    #[test]
    fn an_unapproved_md_nid_writes_nothing() {
        let mut pkt = core::mem::MaybeUninit::<Wpacket>::uninit();
        let mut buf = [0u8; 64];
        // SAFETY: `pkt` is a live local, `buf` is this call's own, and `mdnid` is `NID_undef`.
        unsafe {
            assert_eq!(
                crate::packet::WPACKET_init_der(pkt.as_mut_ptr(), buf.as_mut_ptr(), 64),
                1
            );
            let r = ossl_DER_w_algorithmIdentifier_ECDSA_with_MD(
                pkt.as_mut_ptr(),
                -1,
                core::ptr::null_mut(),
                crate::runtime::obj::NID_undef,
            );
            assert_eq!(r, 0);
            crate::packet::WPACKET_cleanup(pkt.as_mut_ptr());
        }
    }
}
