//! Phase 8 — `providers/common/der/der_dsa_sig.c`: the DSA `WITH MD` AlgorithmIdentifier writer,
//! and the nine `id-dsa-with-*` OIDs it selects from.
//!
//! This unit is the DSA signature block's second prerequisite, beside
//! `src/provider/securitycheck.rs`'s `ossl_dsa_check_key`. `dsa_sig.c.in`'s `dsa_setup_md`
//! builds the signature's AlgorithmIdentifier here, and — like the EdDSA and ECDSA writers — it
//! writes into a buffer it then keeps on the context, because the identifier is part of the
//! signature's *parameter* contract rather than of the operation.
//!
//! ## The OIDs are precompiled literals, and they are transcribed rather than computed
//!
//! `providers/common/der/der_dsa_gen.c` is generated by `oids_to_c.pm` from
//! `providers/common/der/DSA.asn1`, and every entry is the DER encoding of one OID with no
//! values to derive: `id-dsa-with-sha1` is `06 07 2A 86 48 CE 38 04 03` and its eight SHA-2/SHA-3
//! siblings differ in the final arc. `src/provider/kdf.rs` transcribes the three
//! `der_wrap_gen.c` OIDs the same way, and for the same reason — there is nothing to compute and
//! a generator would be a second reader of the same `.asn1` file.
//!
//! ## What is here, and what is not
//!
//! `der_dsa_sig.c` defines exactly one function; the whole unit is transcribed. The other
//! `providers/common/der/` units (`der_ec_sig.c`, `der_ecx_key.c`, `der_rsa_sig.c`,
//! `der_sm2_sig.c` and the key encoders) are separate units and are not landed: each is named
//! with its row in `src/provider/signature.rs`.
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::{c_int, c_uchar};

use crate::der_writer::{
    ossl_DER_w_begin_sequence, ossl_DER_w_end_sequence, ossl_DER_w_precompiled,
};
use crate::dsa::Dsa;
use crate::packet::Wpacket;
use crate::runtime::obj::{
    NID_sha1, NID_sha224, NID_sha256, NID_sha384, NID_sha3_224, NID_sha3_256, NID_sha3_384,
    NID_sha3_512, NID_sha512,
};

/// `ossl_der_oid_id_dsa_with_sha1` — `der_dsa_gen.c`, generated from `DSA.asn1`'s
/// `id-dsa-with-sha1 OBJECT IDENTIFIER ::= { iso(1) member-body(2) us(840) x9-57(10040)
/// x9cm(4) 3 }`. Nine bytes, the DER encoding including its `06 07` header.
static OSSL_DER_OID_ID_DSA_WITH_SHA1: [u8; 9] =
    [0x06, 0x07, 0x2A, 0x86, 0x48, 0xCE, 0x38, 0x04, 0x03];

/// `ossl_der_oid_id_dsa_with_sha224`.
static OSSL_DER_OID_ID_DSA_WITH_SHA224: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x01,
];

/// `ossl_der_oid_id_dsa_with_sha256`.
static OSSL_DER_OID_ID_DSA_WITH_SHA256: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x02,
];

/// `ossl_der_oid_id_dsa_with_sha384`.
static OSSL_DER_OID_ID_DSA_WITH_SHA384: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x03,
];

/// `ossl_der_oid_id_dsa_with_sha512`.
static OSSL_DER_OID_ID_DSA_WITH_SHA512: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x04,
];

/// `ossl_der_oid_id_dsa_with_sha3_224`.
static OSSL_DER_OID_ID_DSA_WITH_SHA3_224: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x05,
];

/// `ossl_der_oid_id_dsa_with_sha3_256`.
static OSSL_DER_OID_ID_DSA_WITH_SHA3_256: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x06,
];

/// `ossl_der_oid_id_dsa_with_sha3_384`.
static OSSL_DER_OID_ID_DSA_WITH_SHA3_384: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x07,
];

/// `ossl_der_oid_id_dsa_with_sha3_512`.
static OSSL_DER_OID_ID_DSA_WITH_SHA3_512: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x08,
];

/// `int ossl_DER_w_algorithmIdentifier_DSA_with_MD(WPACKET *pkt, int tag, DSA *dsa, int mdnid)` —
/// `der_dsa_sig.c:26-50`.
///
/// The `DSA *dsa` parameter is the authority's and is **unused**: the identifier for a
/// `dsa-with-*` algorithm carries no parameters, so the key contributes nothing. The nine-case
/// switch is `MD_CASE`'s expansion, which is the file's macro rather than a convenience — the
/// generated `der_dsa.h` names the OIDs the macro pastes together, and a `mdnid` outside the nine
/// answers 0 without writing anything.
///
/// # Safety
/// `pkt` live; `dsa` is the caller's key and is not read.
#[allow(non_snake_case)] // the authority's name is the contract
#[allow(non_upper_case_globals)] // the `NID_*` constants are the authority's own spellings
pub(crate) unsafe fn ossl_DER_w_algorithmIdentifier_DSA_with_MD(
    pkt: *mut Wpacket,
    tag: c_int,
    _dsa: *mut Dsa,
    mdnid: c_int,
) -> c_int {
    let precompiled: &[u8] = match mdnid {
        NID_sha1 => &OSSL_DER_OID_ID_DSA_WITH_SHA1,
        NID_sha224 => &OSSL_DER_OID_ID_DSA_WITH_SHA224,
        NID_sha256 => &OSSL_DER_OID_ID_DSA_WITH_SHA256,
        NID_sha384 => &OSSL_DER_OID_ID_DSA_WITH_SHA384,
        NID_sha512 => &OSSL_DER_OID_ID_DSA_WITH_SHA512,
        NID_sha3_224 => &OSSL_DER_OID_ID_DSA_WITH_SHA3_224,
        NID_sha3_256 => &OSSL_DER_OID_ID_DSA_WITH_SHA3_256,
        NID_sha3_384 => &OSSL_DER_OID_ID_DSA_WITH_SHA3_384,
        NID_sha3_512 => &OSSL_DER_OID_ID_DSA_WITH_SHA3_512,
        _ => return 0,
    };

    // SAFETY: `pkt` is live per the contract, and `precompiled` is a `'static` array whose length
    // is the second argument.
    unsafe {
        (ossl_DER_w_begin_sequence(pkt, tag) != 0
            && ossl_DER_w_precompiled(
                pkt,
                -1,
                precompiled.as_ptr().cast::<c_uchar>(),
                precompiled.len(),
            ) != 0
            && ossl_DER_w_end_sequence(pkt, tag) != 0) as c_int
    }
}
