//! Phase 8 — `providers/common/der/der_slh_dsa_key.c` and the `id-slh-dsa-*` OID table
//! `der_slh_dsa_gen.c` generates from `SLH_DSA.asn1`.
//!
//! This unit is `slh_dsa_sig.c.in`'s one prerequisite: `slh_dsa_set_alg_id_buffer` builds the
//! signature's AlgorithmIdentifier through `ossl_DER_w_algorithmIdentifier_SLH_DSA`
//! (`slh_dsa_sig.c.in:140`), selecting the OID by the key's own NID, and keeps it on the context
//! because it is part of the signature's *parameter* contract rather than of the operation — the
//! same shape as `der_ecx_key.c`, `der_dsa_sig.c` and `der_ec_sig.c`.
//!
//! ## The OIDs are precompiled literals, and they are transcribed rather than computed
//!
//! `providers/common/der/der_slh_dsa_gen.c` is generated by `oids_to_c.pm` from
//! `providers/common/der/SLH_DSA.asn1`, and every entry is the DER encoding of one OID with no
//! values to derive. `id-slh-dsa-sha2-128s` is `{ 2 16 840 1 101 3 4 3 20 }`, whose body is eight
//! *seven-bit-shifted* arcs (`60 86 48 01 65 03 04 03`) followed by the one final arc, and the
//! twelve differ only in that final arc: `0x14`..`0x1F`. The values below are read back from the
//! authority's own generated header (`der_slh_dsa.h`'s `DER_OID_V_*` macros), not typed from the
//! ASN.1 by hand.
//!
//! ## The writer switches on the key's NID, and the twelve arms are the twelve parameter sets
//!
//! `ossl_slh_dsa_key_get_type` (`slh_dsa_key.c:463-466`) answers `params->type`, the `NID_SLH_DSA_*`
//! that `slh_params.c`'s table carries. The `default:` arm answers 0, so a key whose type is not
//! one of the twelve yields no AlgorithmIdentifier — the refusal `slh_dsa_set_alg_id_buffer`
//! silently tolerates, because an absent identifier still leaves the operation valid.
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::{c_int, c_uchar};

use crate::der_writer::{
    ossl_DER_w_begin_sequence, ossl_DER_w_end_sequence, ossl_DER_w_precompiled,
};
use crate::packet::Wpacket;
use crate::runtime::obj::{
    NID_SLH_DSA_SHA2_128f, NID_SLH_DSA_SHA2_128s, NID_SLH_DSA_SHA2_192f, NID_SLH_DSA_SHA2_192s,
    NID_SLH_DSA_SHA2_256f, NID_SLH_DSA_SHA2_256s, NID_SLH_DSA_SHAKE_128f, NID_SLH_DSA_SHAKE_128s,
    NID_SLH_DSA_SHAKE_192f, NID_SLH_DSA_SHAKE_192s, NID_SLH_DSA_SHAKE_256f, NID_SLH_DSA_SHAKE_256s,
};
use crate::slh_dsa::key::ossl_slh_dsa_key_get_type;
use crate::slh_dsa::SlhDsaKey;

/// `ossl_der_oid_id_slh_dsa_sha2_128s` — `der_slh_dsa_gen.c`, from `SLH_DSA.asn1`'s
/// `id-slh-dsa-sha2-128s OBJECT IDENTIFIER ::= { sigAlgs 20 }`. Eleven bytes: the `06 09` header
/// and the nine-arc body.
static OSSL_DER_OID_ID_SLH_DSA_SHA2_128S: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x14,
];
/// `ossl_der_oid_id_slh_dsa_sha2_128f` — `{ sigAlgs 21 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHA2_128F: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x15,
];
/// `ossl_der_oid_id_slh_dsa_sha2_192s` — `{ sigAlgs 22 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHA2_192S: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x16,
];
/// `ossl_der_oid_id_slh_dsa_sha2_192f` — `{ sigAlgs 23 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHA2_192F: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x17,
];
/// `ossl_der_oid_id_slh_dsa_sha2_256s` — `{ sigAlgs 24 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHA2_256S: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x18,
];
/// `ossl_der_oid_id_slh_dsa_sha2_256f` — `{ sigAlgs 25 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHA2_256F: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x19,
];
/// `ossl_der_oid_id_slh_dsa_shake_128s` — `{ sigAlgs 26 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHAKE_128S: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x1A,
];
/// `ossl_der_oid_id_slh_dsa_shake_128f` — `{ sigAlgs 27 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHAKE_128F: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x1B,
];
/// `ossl_der_oid_id_slh_dsa_shake_192s` — `{ sigAlgs 28 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHAKE_192S: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x1C,
];
/// `ossl_der_oid_id_slh_dsa_shake_192f` — `{ sigAlgs 29 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHAKE_192F: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x1D,
];
/// `ossl_der_oid_id_slh_dsa_shake_256s` — `{ sigAlgs 30 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHAKE_256S: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x1E,
];
/// `ossl_der_oid_id_slh_dsa_shake_256f` — `{ sigAlgs 31 }`.
static OSSL_DER_OID_ID_SLH_DSA_SHAKE_256F: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x1F,
];

/// `int ossl_DER_w_algorithmIdentifier_SLH_DSA(WPACKET *pkt, int tag, SLH_DSA_KEY *key)` —
/// `der_slh_dsa_key.c:24-47`.
///
/// # Safety
/// `pkt` live; `key` is the caller's live SLH-DSA key.
#[allow(non_snake_case)] // the authority's name is the contract
#[allow(non_upper_case_globals)] // the `NID_SLH_DSA_*` constants are the object table's own spelling
pub(crate) unsafe fn ossl_DER_w_algorithmIdentifier_SLH_DSA(
    pkt: *mut Wpacket,
    tag: c_int,
    key: *mut SlhDsaKey,
) -> c_int {
    // SAFETY: `key` is live per the contract; the two accessors take its own address.
    let nid = unsafe { ossl_slh_dsa_key_get_type(key) };
    let alg: &[u8] = match nid {
        NID_SLH_DSA_SHA2_128s => &OSSL_DER_OID_ID_SLH_DSA_SHA2_128S,
        NID_SLH_DSA_SHA2_128f => &OSSL_DER_OID_ID_SLH_DSA_SHA2_128F,
        NID_SLH_DSA_SHA2_192s => &OSSL_DER_OID_ID_SLH_DSA_SHA2_192S,
        NID_SLH_DSA_SHA2_192f => &OSSL_DER_OID_ID_SLH_DSA_SHA2_192F,
        NID_SLH_DSA_SHA2_256s => &OSSL_DER_OID_ID_SLH_DSA_SHA2_256S,
        NID_SLH_DSA_SHA2_256f => &OSSL_DER_OID_ID_SLH_DSA_SHA2_256F,
        NID_SLH_DSA_SHAKE_128s => &OSSL_DER_OID_ID_SLH_DSA_SHAKE_128S,
        NID_SLH_DSA_SHAKE_128f => &OSSL_DER_OID_ID_SLH_DSA_SHAKE_128F,
        NID_SLH_DSA_SHAKE_192s => &OSSL_DER_OID_ID_SLH_DSA_SHAKE_192S,
        NID_SLH_DSA_SHAKE_192f => &OSSL_DER_OID_ID_SLH_DSA_SHAKE_192F,
        NID_SLH_DSA_SHAKE_256s => &OSSL_DER_OID_ID_SLH_DSA_SHAKE_256S,
        NID_SLH_DSA_SHAKE_256f => &OSSL_DER_OID_ID_SLH_DSA_SHAKE_256F,
        _ => return 0,
    };
    // SAFETY: `pkt` is live per the contract, and `alg` is a `'static` array whose length is the
    // fourth argument.
    unsafe {
        (ossl_DER_w_begin_sequence(pkt, tag) != 0
            /* No parameters. */
            && ossl_DER_w_precompiled(pkt, -1, alg.as_ptr().cast::<c_uchar>(), alg.len()) != 0
            && ossl_DER_w_end_sequence(pkt, tag) != 0) as c_int
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The twelve OIDs are the authority's own generated bytes (`der_slh_dsa.h`'s `DER_OID_V_*`
    /// macros): `06 09`, the eight shifted arcs `60 86 48 01 65 03 04 03`, and a final arc running
    /// `0x14`..`0x1F` — FIPS 205's twelve `id-slh-dsa-*` OIDs, 2.16.840.1.101.3.4.3.20 through 31.
    #[test]
    fn the_oids_are_the_authoritys_generated_bytes() {
        let all: [[u8; 11]; 12] = [
            OSSL_DER_OID_ID_SLH_DSA_SHA2_128S,
            OSSL_DER_OID_ID_SLH_DSA_SHA2_128F,
            OSSL_DER_OID_ID_SLH_DSA_SHA2_192S,
            OSSL_DER_OID_ID_SLH_DSA_SHA2_192F,
            OSSL_DER_OID_ID_SLH_DSA_SHA2_256S,
            OSSL_DER_OID_ID_SLH_DSA_SHA2_256F,
            OSSL_DER_OID_ID_SLH_DSA_SHAKE_128S,
            OSSL_DER_OID_ID_SLH_DSA_SHAKE_128F,
            OSSL_DER_OID_ID_SLH_DSA_SHAKE_192S,
            OSSL_DER_OID_ID_SLH_DSA_SHAKE_192F,
            OSSL_DER_OID_ID_SLH_DSA_SHAKE_256S,
            OSSL_DER_OID_ID_SLH_DSA_SHAKE_256F,
        ];
        for (i, oid) in all.iter().enumerate() {
            assert_eq!(
                &oid[..10],
                &[0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03],
                "oid {i}: header and shifted arcs"
            );
            assert_eq!(oid[10], 0x14 + i as u8, "oid {i}: final arc");
        }
    }
}
