//! Phase 9 — `providers/common/der/der_ml_dsa_key.c` and the `id-ml-dsa-*` OID table
//! `der_ml_dsa_gen.c` generates from `ML_DSA.asn1`.
//!
//! This unit is `ml_dsa_sig.c.in`'s one prerequisite: `set_alg_id_buffer` builds the signature's
//! AlgorithmIdentifier through `ossl_DER_w_algorithmIdentifier_ML_DSA` (`ml_dsa_sig.c.in:156`),
//! selecting the OID by the key's own algorithm *name*, and keeps it on the context because it is
//! part of the signature's *parameter* contract rather than of the operation — the same shape as
//! `der_slh_dsa_key.c`, `der_ecx_key.c`, `der_dsa_sig.c` and `der_ec_sig.c`.
//!
//! ## The writer switches on the name, not the NID
//!
//! Unlike `der_slh_dsa_key.c`, which switches on `ossl_slh_dsa_key_get_type`'s NID, this writer
//! calls `ossl_ml_dsa_key_get_name` and compares the three `ML-DSA-*` names with
//! `OPENSSL_strcasecmp`. The `else` arm answers 0, so a key whose name is not one of the three
//! yields no AlgorithmIdentifier — the refusal `set_alg_id_buffer` silently tolerates, because an
//! absent identifier still leaves the operation valid.
//!
//! ## The OIDs are precompiled literals, transcribed rather than typed from memory
//!
//! `providers/common/der/der_ml_dsa_gen.c` is generated by `oids_to_c.pm` from
//! `providers/common/der/ML_DSA.asn1`, whose three leaves are
//! `id-ml-dsa-44 ::= { sigAlgs 17 }`, `id-ml-dsa-65 ::= { sigAlgs 18 }` and
//! `id-ml-dsa-87 ::= { sigAlgs 19 }`, with `sigAlgs ::= { 2 16 840 1 101 3 4 3 }`. Every entry is
//! the DER encoding of one OID with no values to derive: the `06 09` header, the eight
//! *seven-bit-shifted* arcs `60 86 48 01 65 03 04 03`, and the final arc — `0x11`, `0x12`, `0x13`.
//! The three arrays below are read back from the authority's own generated header
//! (`providers/common/include/prov/der_ml_dsa.h`'s `DER_OID_V_id_ml_dsa_*` macros), not typed from
//! the ASN.1 by hand.
//!
//! SPDX-License-Identifier: Apache-2.0

use core::ffi::c_int;

use crate::der_writer::{
    ossl_DER_w_begin_sequence, ossl_DER_w_end_sequence, ossl_DER_w_precompiled,
};
use crate::ml_dsa::key::ossl_ml_dsa_key_get_name;
use crate::ml_dsa::MlDsaKey;
use crate::packet::Wpacket;
use crate::runtime::str::OPENSSL_strcasecmp;

/// `ossl_der_oid_id_ml_dsa_44` — `der_ml_dsa_gen.c`, from `ML_DSA.asn1`'s
/// `id-ml-dsa-44 OBJECT IDENTIFIER ::= { sigAlgs 17 }`. Eleven bytes: the `06 09` header and the
/// nine-arc body.
static OSSL_DER_OID_ID_ML_DSA_44: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x11,
];
/// `ossl_der_oid_id_ml_dsa_65` — `{ sigAlgs 18 }`, differing only in the final arc.
static OSSL_DER_OID_ID_ML_DSA_65: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x12,
];
/// `ossl_der_oid_id_ml_dsa_87` — `{ sigAlgs 19 }`, differing only in the final arc.
static OSSL_DER_OID_ID_ML_DSA_87: [u8; 11] = [
    0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03, 0x13,
];

/// `int ossl_DER_w_algorithmIdentifier_ML_DSA(WPACKET *pkt, int tag, ML_DSA_KEY *key)` —
/// `der_ml_dsa_key.c:19-41`.
///
/// # Safety
/// `pkt` live; `key` is the caller's live ML-DSA key.
#[allow(non_snake_case)] // the authority's name is the contract
pub(crate) unsafe fn ossl_DER_w_algorithmIdentifier_ML_DSA(
    pkt: *mut Wpacket,
    tag: c_int,
    key: *mut MlDsaKey,
) -> c_int {
    // SAFETY: `key` is live per the contract; the accessor reads its own `params`.
    let name = unsafe { ossl_ml_dsa_key_get_name(key) };
    // SAFETY: `name` is NUL-terminated (a `params->alg` literal), and the three compared literals
    // are NUL-terminated by construction.
    let alg: &[u8] = unsafe {
        if OPENSSL_strcasecmp(name, c"ML-DSA-44".as_ptr()) == 0 {
            &OSSL_DER_OID_ID_ML_DSA_44
        } else if OPENSSL_strcasecmp(name, c"ML-DSA-65".as_ptr()) == 0 {
            &OSSL_DER_OID_ID_ML_DSA_65
        } else if OPENSSL_strcasecmp(name, c"ML-DSA-87".as_ptr()) == 0 {
            &OSSL_DER_OID_ID_ML_DSA_87
        } else {
            return 0;
        }
    };
    // SAFETY: `pkt` is live per the contract, and `alg` is a `'static` array whose length is the
    // fourth argument.
    unsafe {
        (ossl_DER_w_begin_sequence(pkt, tag) != 0
            /* No parameters. */
            && ossl_DER_w_precompiled(pkt, -1, alg.as_ptr(), alg.len()) != 0
            && ossl_DER_w_end_sequence(pkt, tag) != 0) as c_int
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The three OIDs are the authority's own generated bytes (`der_ml_dsa.h`'s `DER_OID_V_*`
    /// macros): `06 09`, the eight shifted arcs `60 86 48 01 65 03 04 03`, and a final arc running
    /// `0x11`..`0x13` — FIPS 204's three `id-ml-dsa-*` OIDs, 2.16.840.1.101.3.4.3.17 through 19.
    #[test]
    fn the_oids_are_the_authoritys_generated_bytes() {
        let all: [[u8; 11]; 3] = [
            OSSL_DER_OID_ID_ML_DSA_44,
            OSSL_DER_OID_ID_ML_DSA_65,
            OSSL_DER_OID_ID_ML_DSA_87,
        ];
        for (i, oid) in all.iter().enumerate() {
            assert_eq!(
                &oid[..10],
                &[0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x03],
                "oid {i}: header and shifted arcs"
            );
            assert_eq!(oid[10], 0x11 + i as u8, "oid {i}: final arc");
        }
    }
}
